---@diagnostic disable-next-line: unused-local
local __module_name__ = "dot.theme.hlgroup.basic.rosepine" ---@type string

---@class dot.theme.hlgroup.basic.rosepine
local M = {}

---@param context                       stl.t.theme.IContext
---@return dot.theme.hlgroup.basic.IModesColorMap
function M.gen_modes_color_map(context)
  local c = context.scheme.palette.rosepine ---@type stl.t.theme.IRosepinePalette
  return {
    command = c.gold,
    confirm = c.foam,
    insert = c.foam,
    normal = c.rose,
    nterminal = c.gold,
    replace = c.love,
    select = c.iris,
    terminal = c.pine,
    visual = c.iris,
  }
end

---@param context                       stl.t.theme.IContext
---@return table<string, stl.t.theme.IHlgroup>
function M.gen_hlgroup_map(context)
  local cs = stl.color
  local t = context.transparency ---@type boolean
  local c = context.scheme.palette.rosepine ---@type stl.t.theme.IRosepinePalette

  local bg = t and c.none or c.base ---@type string
  -- Iris keeps keywords legible when the terminal background replaces the native base.
  local keyword_fg = t and c.iris or c.pine ---@type string

  -- Tint diff fills from the native palette, independent of window transparency.
  local diff_add = cs.mix(c.base, c.pine, 15)
  local diff_del = cs.mix(c.base, c.love, 15)
  local diff_add_inline = cs.mix(c.base, c.pine, 30)
  local diff_del_inline = cs.mix(c.base, c.love, 30)

  ---@type table<string, stl.t.theme.IHlgroup>
  local hlgroup_map = {
    ---Completion
    ComplHint = { fg = c.muted, italic = true },
    ComplHintMore = { fg = c.gold, italic = true },

    Added = { fg = c.pine },
    Bold = { bold = true },
    Boolean = { fg = c.rose },
    Builtin = { fg = c.foam },
    Changed = { fg = c.gold },
    Character = { fg = c.gold },
    ColorColumn = { bg = c.highlightLow },
    Comment = { fg = c.subtle, italic = true },
    Conceal = { fg = c.muted },
    Conditional = { fg = keyword_fg },
    Constant = { fg = c.gold },
    CurSearch = { bg = c.love, fg = c.surface },
    Cursor = { fg = c.base, bg = c.text },
    CursorColumn = { bg = c.highlightLow },
    CursorLine = { bg = c.highlightLow },
    CursorLineNr = { fg = c.text, bold = true },
    Debug = { fg = c.rose },
    Define = { fg = c.iris },
    Delimiter = { fg = c.subtle },
    DevIconDefault = { fg = c.love },
    Diagnostic_ERROR = { fg = c.love },
    Diagnostic_HINT = { fg = c.iris },
    Diagnostic_INFO = { fg = c.foam },
    Diagnostic_WARN = { fg = c.gold },
    DiagnosticError = { fg = c.love },
    DiagnosticFloatingError = { fg = c.love },
    DiagnosticFloatingHint = { fg = c.iris },
    DiagnosticFloatingInfo = { fg = c.foam },
    DiagnosticFloatingOk = { fg = c.pine },
    DiagnosticFloatingWarn = { fg = c.gold },
    DiagnosticHint = { fg = c.iris },
    DiagnosticInfo = { fg = c.foam },
    DiagnosticOk = { fg = c.pine },
    DiagnosticSignError = { fg = c.love },
    DiagnosticSignHint = { fg = c.iris },
    DiagnosticSignInfo = { fg = c.foam },
    DiagnosticSignOk = { fg = c.pine },
    DiagnosticSignWarn = { fg = c.gold },
    DiagnosticUnderlineError = { undercurl = true, sp = c.love },
    DiagnosticUnderlineHint = { undercurl = true, sp = c.iris },
    DiagnosticUnderlineInfo = { undercurl = true, sp = c.foam },
    DiagnosticUnderlineWarn = { undercurl = true, sp = c.gold },
    DiagnosticVirtualTextError = { fg = c.love, bg = t and c.none or cs.mix(c.base, c.love, 12) },
    DiagnosticVirtualTextHint = { fg = c.iris, bg = t and c.none or cs.mix(c.base, c.iris, 12) },
    DiagnosticVirtualTextInfo = { fg = c.foam, bg = t and c.none or cs.mix(c.base, c.foam, 12) },
    DiagnosticVirtualTextWarn = { fg = c.gold, bg = t and c.none or cs.mix(c.base, c.gold, 12) },
    DiagnosticVirtualTextOk = { fg = c.pine, bg = t and c.none or cs.mix(c.base, c.pine, 12) },
    DiagnosticVirtualLinesError = { fg = c.love, bg = t and c.none or cs.mix(c.base, c.love, 12), italic = true },
    DiagnosticVirtualLinesHint = { fg = c.iris, bg = t and c.none or cs.mix(c.base, c.iris, 12), italic = true },
    DiagnosticVirtualLinesInfo = { fg = c.foam, bg = t and c.none or cs.mix(c.base, c.foam, 12), italic = true },
    DiagnosticVirtualLinesWarn = { fg = c.gold, bg = t and c.none or cs.mix(c.base, c.gold, 12), italic = true },
    DiagnosticVirtualLinesOk = { fg = c.pine, bg = t and c.none or cs.mix(c.base, c.pine, 12), italic = true },
    DiagnosticWarn = { fg = c.gold },
    DiffAdd = { bg = diff_add },
    DiffAddLeft = { bg = diff_del },
    DiffAddRight = { bg = diff_add },
    DiffAdded = { fg = c.pine },
    DiffChange = { bg = c.highlightLow },
    DiffChanged = { fg = c.rose },
    DiffDelLeft = { bg = diff_del },
    DiffDelRight = { bg = diff_del },
    DiffDelete = { bg = diff_del },
    DiffFile = { fg = c.rose },
    DiffIndexLine = { fg = c.foam },
    DiffLine = { fg = c.muted },
    DiffModLeft = { bg = diff_del },
    DiffModRight = { bg = diff_add },
    DiffNewFile = { fg = c.gold },
    DiffOldFile = { fg = c.gold },
    DiffRemoved = { fg = c.love },
    DiffText = { fg = c.text, bg = diff_add_inline },
    DiffWordLeft = { fg = c.text, bg = diff_del_inline },
    DiffWordRight = { fg = c.text, bg = diff_add_inline },
    Directory = { fg = c.foam, bold = true },
    Done = { fg = c.gold, bold = true, italic = true },
    EndOfBuffer = { fg = c.highlightMed },
    Error = { fg = c.love },
    ErrorMsg = { fg = c.love, bold = true, italic = true },
    Exception = { fg = keyword_fg },
    Float = { fg = c.gold },
    FloatActiveBorder = { link = t and "ms_b_bg0" or "ms_b_none" },
    FloatActiveTitle = { link = "ms_b_bg0" },
    FloatBorder = { fg = c.highlightHigh, bg = t and c.none or c.surface },
    FloatNormal = { fg = c.text, bg = t and c.none or c.surface },
    FloatTitle = { fg = c.rose, bg = t and c.none or c.surface },
    FoldColumn = { fg = c.muted },
    Folded = { fg = c.rose, bg = c.highlightMed },
    Function = { fg = c.rose },
    healthError = { fg = c.love },
    healthSuccess = { fg = c.foam },
    healthWarning = { fg = c.gold },
    iCursor = { link = "Cursor" },
    Identifier = { fg = c.text },
    IncSearch = { fg = c.base, bg = c.rose },
    Include = { fg = keyword_fg },
    Italic = { italic = true },
    Keyword = { fg = keyword_fg },
    Label = { fg = c.foam },
    lCursor = { link = "Cursor" },
    LineNr = { fg = c.muted },
    LspCodeLens = { fg = c.subtle },
    LspInlayHint = { fg = c.muted, bg = t and c.none or c.highlightLow },
    LspReferenceRead = { bg = c.highlightMed },
    LspReferenceText = { bg = c.highlightMed },
    LspReferenceWrite = { bg = c.highlightMed },
    LspSignatureActiveParameter = { bg = c.highlightLow, bold = true },
    Macro = { fg = c.iris },
    MatchParen = { fg = c.gold, bg = c.highlightMed, bold = true },
    MatchWord = { fg = c.text, bg = c.highlightMed },
    Member = { fg = c.foam },
    Method = { fg = c.rose },
    ModeMsg = { fg = c.text, bold = true },
    MoreMsg = { fg = c.rose },
    MsgArea = { link = "Normal" },
    NonText = { fg = cs.mix(bg, c.muted, 45), italic = true },
    Normal = { fg = c.text, bg = c.base, blend = t and 50 or 0 },
    NormalFloat = { link = "FloatNormal" },
    NormalNC = { fg = c.text, bg = c.surface, blend = t and 50 or 0 },
    Number = { fg = c.gold },
    NvimInternalError = { fg = c.love },
    Operator = { fg = c.subtle },
    Parameter = { fg = c.iris, italic = true },
    Pmenu = { fg = c.text, bg = c.surface },
    PmenuSbar = { bg = c.highlightLow },
    PmenuSel = { fg = c.text, bg = c.highlightMed },
    PmenuThumb = { bg = c.muted },
    PreCondit = { fg = c.iris },
    PreProc = { link = "PreCondit" },
    Question = { fg = c.rose },
    QuickFixLine = { bg = c.highlightMed, bold = true },
    Removed = { fg = c.love },
    RenamerBorder = { link = t and "ms_b_bg0" or "ms_b_none" },
    RenamerTitle = { link = t and "ms_b_bg0" or "ms_b_none" },
    Repeat = { fg = keyword_fg },
    Search = { fg = c.text, bg = c.highlightMed },
    SignColumn = { fg = c.highlightMed },
    Special = { fg = c.foam },
    SpecialChar = { link = "Special" },
    SpecialComment = { fg = c.iris },
    SpecialKey = { link = "NonText" },
    SpellBad = { undercurl = true, sp = c.love },
    SpellCap = { undercurl = true, sp = c.gold },
    SpellLocal = { undercurl = true, sp = c.rose },
    SpellRare = { undercurl = true, sp = c.pine },
    Statement = { fg = keyword_fg, bold = true },
    StatusColumnMark = { link = "DiagnosticHint", default = true },
    StatusLine = { fg = c.text, bg = c.surface, blend = t and 50 or 0 },
    StatusLineNC = { fg = c.highlightMed, bg = c.surface, blend = t and 50 or 0 },
    StorageClass = { fg = c.foam },
    String = { fg = c.gold },
    Structure = { fg = c.foam },
    Substitute = { bg = c.highlightMed, fg = c.iris },
    TabLine = { bg = c.base, fg = c.muted },
    TabLineFill = { bg = c.surface, blend = t and 50 or 0 },
    TabLineSel = { link = "Normal" },
    Tag = { fg = c.foam },
    Title = { fg = c.rose, bold = true },
    Todo = { fg = c.rose, bg = cs.mix(c.base, c.rose, 20) },
    TooLong = { fg = c.love },
    Type = { fg = c.foam },
    Typedef = { fg = c.foam },
    Variable = { fg = c.text },
    UnderLined = { fg = c.iris, underline = true },
    vCursor = { link = "Cursor" },
    Visual = { fg = c.text, bg = c.highlightMed },
    VisualNOS = { link = "Visual" },
    WarningMsg = { fg = c.gold },
    Whitespace = { fg = c.highlightMed },
    WildMenu = { bg = c.muted },
    WinBar = { fg = c.rose, bg = c.base },
    WinBarNC = { fg = c.rose, bg = c.surface },
    WinSeparator = { fg = t and c.highlightMed or c.base },
  }

  return hlgroup_map
end

return M
