---@class eve.constant.hlgroup.gruvbox.treesitter
local M = {}

---@param context                       dot.t.theme.IContext
---@return table<string, dot.t.theme.IHlgroup>
function M.gen_hlgroup_map(context)
  local c = context.scheme.palette.unified ---@type dot.t.theme.UnifiedPalette

  local heading_colors = {
    c.brightRed,
    c.brightOrange,
    c.brightYellow,
    c.brightGreen,
    c.brightBlue,
    c.brightPurple,
  }

  ---@type table<string, dot.t.theme.IHlgroup>
  local hlgroup_map = {
    ["@annotation"] = { fg = c.brightRed },
    ["@attribute"] = { fg = c.brightYellow },
    ["@boolean"] = { link = "Boolean" },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { link = "Comment" },
    ["@comment.danger"] = { fg = c.bg0, bg = c.red },
    ["@comment.error"] = { link = "ErrorMsg" },
    ["@comment.note"] = { fg = c.brightBlue, italic = true },
    ["@comment.todo"] = { link = "Todo" },
    ["@comment.warning"] = { link = "WarningMsg" },
    ["@conditional"] = { link = "Conditional" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "Constant" },
    ["@constant.macro"] = { link = "Macro" },
    ["@constructor"] = { link = "Special" },
    ["@debug"] = { link = "Debug" },
    ["@define"] = { link = "Define" },
    ["@diff.delta"] = { link = "DiffChange" },
    ["@diff.minus"] = { link = "DiffDelete" },
    ["@diff.plus"] = { link = "DiffAdd" },
    ["@error"] = { link = "Error" },
    ["@exception"] = { link = "Exception" },
    ["@field"] = { fg = c.brightBlue },
    ["@float"] = { link = "Float" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = c.brightPurple },
    ["@function.call"] = { link = "Function" },
    ["@function.macro"] = { link = "Macro" },
    ["@function.method"] = { link = "Function" },
    ["@function.method.call"] = { link = "Function" },
    ["@include"] = { link = "Include" },
    ["@keyword"] = { fg = c.purple, italic = true },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.conditional.ternary"] = { fg = c.brightOrange },
    ["@keyword.debug"] = { link = "Debug" },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.directive.define"] = { link = "Define" },
    ["@keyword.exception"] = { link = "Exception" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.operator"] = { fg = c.brightRed },
    ["@keyword.repeat"] = { link = "Repeat" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@keyword.storage"] = { link = "StorageClass" },
    ["@keyword.type"] = { link = "Type" },
    ["@label"] = { link = "Label" },
    ["@macro"] = { link = "Macro" },
    ["@markup"] = { fg = c.fg1 },
    ["@markup.environment"] = { link = "Macro" },
    ["@markup.environment.name"] = { link = "Type" },
    ["@markup.heading"] = { fg = c.brightYellow, bold = true },
    ["@markup.heading.1.markdown"] = { fg = heading_colors[1], bold = true },
    ["@markup.heading.2.markdown"] = { fg = heading_colors[2], bold = true },
    ["@markup.heading.3.markdown"] = { fg = heading_colors[3], bold = true },
    ["@markup.heading.4.markdown"] = { fg = heading_colors[4], bold = true },
    ["@markup.heading.5.markdown"] = { fg = heading_colors[5], bold = true },
    ["@markup.heading.6.markdown"] = { fg = heading_colors[6], bold = true },
    ["@markup.heading.1.marker.markdown"] = { link = "@markup.heading.1.markdown" },
    ["@markup.heading.2.marker.markdown"] = { link = "@markup.heading.2.markdown" },
    ["@markup.heading.3.marker.markdown"] = { link = "@markup.heading.3.markdown" },
    ["@markup.heading.4.marker.markdown"] = { link = "@markup.heading.4.markdown" },
    ["@markup.heading.5.marker.markdown"] = { link = "@markup.heading.5.markdown" },
    ["@markup.heading.6.marker.markdown"] = { link = "@markup.heading.6.markdown" },
    ["@markup.italic"] = { italic = true },
    ["@markup.link"] = { fg = c.brightBlue },
    ["@markup.link.label"] = { fg = c.brightOrange },
    ["@markup.link.url"] = { fg = c.brightBlue, underline = true },
    ["@markup.list"] = { fg = c.brightBlue },
    ["@markup.list.checked"] = { fg = c.brightGreen },
    ["@markup.list.unchecked"] = { fg = c.bg4 },
    ["@markup.math"] = { link = "Special" },
    ["@markup.quote"] = { fg = c.brightAqua },
    ["@markup.raw"] = { fg = c.brightGreen },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.underline"] = { underline = true },
    ["@method"] = { link = "Function" },
    ["@method.call"] = { link = "Function" },
    ["@module"] = { fg = c.brightYellow, italic = true },
    ["@namespace"] = { fg = c.brightYellow, italic = true },
    ["@none"] = { fg = c.none, bg = c.none },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@operator"] = { link = "Operator" },
    ["@parameter"] = { fg = c.brightBlue },
    ["@preproc"] = { link = "PreProc" },
    ["@property"] = { fg = c.brightBlue },
    ["@punctuation"] = { fg = c.bg4 },
    ["@punctuation.bracket"] = { fg = c.bg4 },
    ["@punctuation.delimiter"] = { fg = c.bg4 },
    ["@punctuation.special"] = { fg = c.bg4 },
    ["@repeat"] = { link = "Repeat" },
    ["@string"] = { link = "String" },
    ["@string.documentation"] = { link = "Comment" },
    ["@string.escape"] = { fg = c.brightRed },
    ["@string.regexp"] = { fg = c.brightRed },
    ["@string.special"] = { link = "SpecialChar" },
    ["@string.special.path"] = { fg = c.brightBlue, underline = true },
    ["@string.special.symbol"] = { fg = c.brightBlue },
    ["@string.special.url"] = { fg = c.brightBlue, underline = true },
    ["@symbol"] = { fg = c.brightBlue },
    ["@tag"] = { link = "Tag" },
    ["@tag.attribute"] = { fg = c.brightBlue },
    ["@tag.delimiter"] = { fg = c.aqua },
    ["@text"] = { fg = c.fg1 },
    ["@text.danger"] = { link = "ErrorMsg" },
    ["@text.danger.comment"] = { fg = c.bg0, bg = c.red },
    ["@text.diff.add"] = { link = "DiffAdd" },
    ["@text.diff.delete"] = { link = "DiffDelete" },
    ["@text.emphasis"] = { italic = true },
    ["@text.environment"] = { link = "Macro" },
    ["@text.environment.name"] = { link = "Type" },
    ["@text.literal"] = { link = "String" },
    ["@text.math"] = { link = "Special" },
    ["@text.note"] = { link = "SpecialComment" },
    ["@text.note.comment"] = { fg = c.brightBlue, italic = true },
    ["@text.reference"] = { link = "Constant" },
    ["@text.strike"] = { strikethrough = true },
    ["@text.strong"] = { bold = true },
    ["@text.title"] = { link = "Title" },
    ["@text.todo"] = { link = "Todo" },
    ["@text.todo.checked"] = { fg = c.brightGreen },
    ["@text.todo.unchecked"] = { fg = c.bg4 },
    ["@text.underline"] = { underline = true },
    ["@text.uri"] = { fg = c.brightBlue, underline = true },
    ["@text.warning"] = { link = "WarningMsg" },

    -- Compatibility
    ["@attribute.c_sharp"] = { fg = c.brightYellow },
    ["@character.printf"] = { link = "SpecialChar" },
    ["@character.special.html"] = { link = "@character.special" },
    ["@comment.hint"] = { fg = c.brightBlue, italic = true },
    ["@comment.info"] = { fg = c.brightBlue, italic = true },
    ["@comment.warning.gitcommit"] = { link = "WarningMsg" },
    ["@constant.java"] = { fg = c.brightYellow },
    ["@constructor.lua"] = { link = "@constructor" },
    ["@constructor.python"] = { link = "@constructor" },
    ["@constructor.tsx"] = { link = "@constructor" },
    ["@event"] = { fg = c.brightRed },
    ["@function.builtin.bash"] = { link = "@function.builtin" },
    ["@keyword.coroutine"] = { link = "Keyword" },
    ["@keyword.directive.css"] = { link = "@keyword.directive" },
    ["@keyword.import.c"] = { link = "@keyword.import" },
    ["@keyword.import.cpp"] = { link = "@keyword.import" },
    ["@keyword.modifier"] = { link = "Keyword" },
    ["@label.yaml"] = { link = "@label" },
    ["@markup.emphasis"] = { italic = true },
    ["@markup.heading.1"] = { fg = heading_colors[1], bold = true },
    ["@markup.heading.1.marker"] = { fg = heading_colors[1] },
    ["@markup.heading.2"] = { fg = heading_colors[2], bold = true },
    ["@markup.heading.2.marker"] = { fg = heading_colors[2] },
    ["@markup.heading.3"] = { fg = heading_colors[3], bold = true },
    ["@markup.heading.3.marker"] = { fg = heading_colors[3] },
    ["@markup.heading.4"] = { fg = heading_colors[4], bold = true },
    ["@markup.heading.4.marker"] = { fg = heading_colors[4] },
    ["@markup.heading.5"] = { fg = heading_colors[5], bold = true },
    ["@markup.heading.5.marker"] = { fg = heading_colors[5] },
    ["@markup.heading.6"] = { fg = heading_colors[6], bold = true },
    ["@markup.heading.6.marker"] = { fg = heading_colors[6] },
    ["@markup.link.label.html"] = { link = "@markup.link.label" },
    ["@markup.link.label.symbol"] = { link = "@markup.link.label" },
    ["@markup.list.markdown"] = { link = "@markup.list" },
    ["@markup.raw.markdown_inline"] = { link = "@markup.raw" },
    ["@modifier"] = { link = "Keyword" },
    ["@module.builtin"] = { fg = c.fg1 },
    ["@namespace.builtin"] = { fg = c.fg1 },
    ["@number.css"] = { link = "@number" },
    ["@property.class.css"] = { link = "@property" },
    ["@property.css"] = { link = "@property" },
    ["@property.id.css"] = { link = "@property" },
    ["@property.scss"] = { link = "@property" },
    ["@punctuation.special.markdown"] = { link = "@punctuation.special" },
    ["@reference"] = { fg = c.fg0 },
    ["@regexp"] = { fg = c.brightRed },
    ["@scope"] = {},
    ["@storageclass"] = { link = "StorageClass" },
    ["@string.plain.css"] = { link = "@string" },
    ["@string.regex"] = { link = "@string.regexp" },
    ["@string.special.url.html"] = { link = "@string.special.url" },
    ["@structure"] = { link = "Structure" },
    ["@tag.builtin"] = { link = "@tag" },
    ["@tag.delimiter.tsx"] = { link = "@tag.delimiter" },
    ["@tag.javascript"] = { link = "@tag" },
    ["@tag.tsx"] = { link = "@tag" },
    ["@type.css"] = { link = "@type" },
    ["@type.tag.css"] = { link = "@type" },
    ["@type.tsx"] = { link = "Variable" },
    ["@variable.jsx"] = { fg = c.brightBlue },
    ["@variable.parameter.bash"] = { link = "@variable.parameter" },
    ["@variable.parameter.builtin"] = { link = "@variable.parameter" },
    ["@variable.tsx"] = { fg = c.brightBlue },

    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { link = "Type" },
    ["@type.definition"] = { link = "Typedef" },
    ["@type.qualifier"] = { link = "Type" },
    ["@variable"] = { fg = c.fg1 },
    ["@variable.builtin"] = { fg = c.brightPurple },
    ["@variable.member"] = { fg = c.brightBlue },
    ["@variable.parameter"] = { fg = c.brightBlue },
    ["@variable.parameter.luadoc"] = { fg = c.brightBlue, italic = true },
  }

  return hlgroup_map
end

return M
