---@class eve.constant.hlgroup.gruvbox.treesitter
local M = {}

---@param context                       std.t.theme.IContext
---@return table<string, std.t.theme.IHlgroup>
function M.gen_hlgroup_map(context)
  local c = context.scheme.palette.unified ---@type std.t.theme.UnifiedPalette

  local heading_colors = {
    c.brightRed,
    c.brightOrange,
    c.brightYellow,
    c.brightGreen,
    c.brightBlue,
    c.brightPurple,
  }

  return {
    ["@annotation"] = { fg = c.brightRed },
    ["@attribute"] = { fg = c.brightYellow },
    ["@boolean"] = { link = "Boolean" },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { link = "Comment" },
    ["@comment.danger"] = { fg = c.bg0, bg = c.red },
    ["@comment.error"] = { link = "ErrorMsg" },
    ["@comment.note"] = { fg = c.brightBlue, italic = true },
    ["@comment.todo"] = { link = "Todo" },
    ["@comment.warning"] = { link = "WarningMsg" },
    ["@conditional"] = { link = "Conditional" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "Constant" },
    ["@constant.macro"] = { link = "Macro" },
    ["@constructor"] = { link = "Special" },
    ["@debug"] = { link = "Debug" },
    ["@define"] = { link = "Define" },
    ["@diff.delta"] = { link = "DiffChange" },
    ["@diff.minus"] = { link = "DiffDelete" },
    ["@diff.plus"] = { link = "DiffAdd" },
    ["@error"] = { link = "Error" },
    ["@exception"] = { link = "Exception" },
    ["@field"] = { fg = c.brightBlue },
    ["@float"] = { link = "Float" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = c.brightPurple },
    ["@function.call"] = { link = "Function" },
    ["@function.macro"] = { link = "Macro" },
    ["@function.method"] = { link = "Function" },
    ["@function.method.call"] = { link = "Function" },
    ["@include"] = { link = "Include" },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.conditional.ternary"] = { fg = c.brightOrange },
    ["@keyword.debug"] = { link = "Debug" },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.directive.define"] = { link = "Define" },
    ["@keyword.exception"] = { link = "Exception" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.operator"] = { fg = c.brightRed },
    ["@keyword.repeat"] = { link = "Repeat" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@keyword.storage"] = { link = "StorageClass" },
    ["@keyword.type"] = { link = "Type" },
    ["@label"] = { link = "Label" },
    ["@macro"] = { link = "Macro" },
    ["@markup"] = { fg = c.fg1 },
    ["@markup.environment"] = { link = "Macro" },
    ["@markup.environment.name"] = { link = "Type" },
    ["@markup.heading"] = { fg = c.brightYellow, bold = true },
    ["@markup.heading.1.markdown"] = { fg = heading_colors[1], bold = true },
    ["@markup.heading.2.markdown"] = { fg = heading_colors[2], bold = true },
    ["@markup.heading.3.markdown"] = { fg = heading_colors[3], bold = true },
    ["@markup.heading.4.markdown"] = { fg = heading_colors[4], bold = true },
    ["@markup.heading.5.markdown"] = { fg = heading_colors[5], bold = true },
    ["@markup.heading.6.markdown"] = { fg = heading_colors[6], bold = true },
    ["@markup.heading.1.marker.markdown"] = { link = "@markup.heading.1.markdown" },
    ["@markup.heading.2.marker.markdown"] = { link = "@markup.heading.2.markdown" },
    ["@markup.heading.3.marker.markdown"] = { link = "@markup.heading.3.markdown" },
    ["@markup.heading.4.marker.markdown"] = { link = "@markup.heading.4.markdown" },
    ["@markup.heading.5.marker.markdown"] = { link = "@markup.heading.5.markdown" },
    ["@markup.heading.6.marker.markdown"] = { link = "@markup.heading.6.markdown" },
    ["@markup.italic"] = { italic = true },
    ["@markup.link"] = { fg = c.brightBlue },
    ["@markup.link.label"] = { fg = c.brightOrange },
    ["@markup.link.url"] = { fg = c.brightBlue, underline = true },
    ["@markup.list"] = { fg = c.brightBlue },
    ["@markup.list.checked"] = { fg = c.brightGreen },
    ["@markup.list.unchecked"] = { fg = c.bg4 },
    ["@markup.math"] = { link = "Special" },
    ["@markup.quote"] = { fg = c.brightAqua },
    ["@markup.raw"] = { fg = c.brightGreen },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.underline"] = { underline = true },
    ["@method"] = { link = "Function" },
    ["@method.call"] = { link = "Function" },
    ["@module"] = { fg = c.brightYellow, italic = true },
    ["@namespace"] = { fg = c.brightYellow, italic = true },
    ["@none"] = { fg = c.none, bg = c.none },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@operator"] = { link = "Operator" },
    ["@parameter"] = { fg = c.brightBlue },
    ["@preproc"] = { link = "PreProc" },
    ["@property"] = { fg = c.brightBlue },
    ["@punctuation"] = { fg = c.bg4 },
    ["@punctuation.bracket"] = { fg = c.bg4 },
    ["@punctuation.delimiter"] = { fg = c.bg4 },
    ["@punctuation.special"] = { fg = c.bg4 },
    ["@repeat"] = { link = "Repeat" },
    ["@string"] = { link = "String" },
    ["@string.documentation"] = { link = "Comment" },
    ["@string.escape"] = { fg = c.brightRed },
    ["@string.regexp"] = { fg = c.brightRed },
    ["@string.special"] = { link = "SpecialChar" },
    ["@string.special.path"] = { fg = c.brightBlue, underline = true },
    ["@string.special.symbol"] = { fg = c.brightBlue },
    ["@string.special.url"] = { fg = c.brightBlue, underline = true },
    ["@symbol"] = { fg = c.brightBlue },
    ["@tag"] = { link = "Tag" },
    ["@tag.attribute"] = { fg = c.brightBlue },
    ["@tag.delimiter"] = { fg = c.aqua },
    ["@text"] = { fg = c.fg1 },
    ["@text.danger"] = { link = "ErrorMsg" },
    ["@text.danger.comment"] = { fg = c.bg0, bg = c.red },
    ["@text.diff.add"] = { link = "DiffAdd" },
    ["@text.diff.delete"] = { link = "DiffDelete" },
    ["@text.emphasis"] = { italic = true },
    ["@text.environment"] = { link = "Macro" },
    ["@text.environment.name"] = { link = "Type" },
    ["@text.literal"] = { link = "String" },
    ["@text.math"] = { link = "Special" },
    ["@text.note"] = { link = "SpecialComment" },
    ["@text.note.comment"] = { fg = c.brightBlue, italic = true },
    ["@text.reference"] = { link = "Constant" },
    ["@text.strike"] = { strikethrough = true },
    ["@text.strong"] = { bold = true },
    ["@text.title"] = { link = "Title" },
    ["@text.todo"] = { link = "Todo" },
    ["@text.todo.checked"] = { fg = c.brightGreen },
    ["@text.todo.unchecked"] = { fg = c.bg4 },
    ["@text.underline"] = { underline = true },
    ["@text.uri"] = { fg = c.brightBlue, underline = true },
    ["@text.warning"] = { link = "WarningMsg" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { link = "Type" },
    ["@type.definition"] = { link = "Typedef" },
    ["@type.qualifier"] = { link = "Type" },
    ["@variable"] = { fg = c.fg1 },
    ["@variable.builtin"] = { fg = c.brightPurple },
    ["@variable.member"] = { fg = c.brightBlue },
    ["@variable.parameter"] = { fg = c.brightBlue },
    ["@variable.parameter.luadoc"] = { fg = c.brightBlue, italic = true },
  }
end

return M
