---@class eve.constant.hlgroup.gruvbox.treesitter
local M = {}

---@param context                       std.t.theme.IContext
---@return table<string, std.t.theme.IHlgroup>
function M.gen_hlgroup_map(context)
  local c = context.scheme.palette.unified ---@type std.t.theme.UnifiedPalette

  return {
    ["@annotation"] = { fg = c.brightRed },
    ["@attribute"] = { fg = c.brightYellow },
    ["@boolean"] = { fg = c.brightPurple },
    ["@character"] = { fg = c.brightPurple },
    ["@character.special"] = { fg = c.brightRed },
    ["@comment"] = { fg = c.grey, italic = true },
    ["@comment.danger"] = { fg = c.bg1, bg = c.red },
    ["@comment.error"] = { fg = c.red, bold = true },
    ["@comment.note"] = { fg = c.purple, bold = true },
    ["@comment.todo"] = { fg = c.bg0, bg = c.yellow, bold = true, italic = true },
    ["@comment.warning"] = { fg = c.red, bold = true },
    ["@conditional"] = { fg = c.brightRed },
    ["@constant"] = { fg = c.brightPurple },
    ["@constant.builtin"] = { fg = c.brightPurple },
    ["@constant.macro"] = { fg = c.brightAqua },
    ["@constructor"] = { fg = c.brightYellow },
    ["@debug"] = { fg = c.red },
    ["@define"] = { fg = c.brightAqua },
    ["@diff.plus"] = { fg = c.green },
    ["@diff.minus"] = { fg = c.red },
    ["@diff.delta"] = { fg = c.yellow },
    ["@error"] = { fg = c.red },
    ["@event"] = { fg = c.red },
    ["@exception"] = { fg = c.red },
    ["@field"] = { fg = c.brightBlue },
    ["@float"] = { fg = c.brightPurple },
    ["@function"] = { fg = c.brightAqua },
    ["@function.builtin"] = { fg = c.brightPurple },
    ["@function.call"] = { fg = c.brightAqua },
    ["@function.lua"] = { fg = c.brightAqua },
    ["@function.macro"] = { fg = c.brightAqua },
    ["@function.method"] = { fg = c.brightBlue },
    ["@function.method.call"] = { fg = c.brightAqua },
    ["@include"] = { fg = c.brightRed },
    ["@keyword"] = { fg = c.brightRed, bold = true },
    ["@keyword.break"] = { fg = c.brightRed, bold = true },
    ["@keyword.conditional"] = { fg = c.brightRed, bold = true },
    ["@keyword.conditional.ternary"] = { fg = c.brightOrange, bold = true },
    ["@keyword.debug"] = { fg = c.red, bold = true },
    ["@keyword.directive"] = { fg = c.brightYellow, bold = true },
    ["@keyword.directive.define"] = { fg = c.brightAqua, bold = true },
    ["@keyword.exception"] = { fg = c.brightRed, bold = true },
    ["@keyword.function"] = { fg = c.brightRed, bold = true },
    ["@keyword.import"] = { fg = c.brightRed, bold = true },
    ["@keyword.import.git_config"] = { fg = c.pink, bold = true },
    ["@keyword.lua"] = { fg = c.brightRed, bold = true },
    ["@keyword.luadoc"] = { fg = c.brightBlue, bold = true },
    ["@keyword.operator"] = { fg = c.brightAqua, bold = true },
    ["@keyword.repeat"] = { fg = c.brightRed, bold = true },
    ["@keyword.return"] = { fg = c.brightRed, bold = true },
    ["@keyword.storage"] = { fg = c.brightOrange, bold = true },
    ["@label"] = { fg = c.brightRed },
    ["@macro"] = { fg = c.brightAqua },
    ["@markup"] = { fg = c.fg1 },
    ["@markup.environment"] = { fg = c.brightAqua },
    ["@markup.environment.name"] = { fg = c.brightYellow },
    ["@markup.heading.1.markdown"] = { fg = c.purple, bold = true },
    ["@markup.heading.2.markdown"] = { fg = c.aqua, bold = true },
    ["@markup.heading.3.markdown"] = { fg = c.orange, bold = true },
    ["@markup.heading.4.markdown"] = { fg = c.yellow, bold = true },
    ["@markup.heading.5.markdown"] = { fg = c.blue, bold = true },
    ["@markup.heading.6.markdown"] = { fg = c.green, bold = true },
    ["@markup.heading.1.marker.markdown"] = { link = "@markup.heading.1.markdown" },
    ["@markup.heading.2.marker.markdown"] = { link = "@markup.heading.2.markdown" },
    ["@markup.heading.3.marker.markdown"] = { link = "@markup.heading.3.markdown" },
    ["@markup.heading.4.marker.markdown"] = { link = "@markup.heading.4.markdown" },
    ["@markup.heading.5.marker.markdown"] = { link = "@markup.heading.5.markdown" },
    ["@markup.heading.6.marker.markdown"] = { link = "@markup.heading.6.markdown" },
    ["@markup.italic"] = { italic = true },
    ["@markup.link"] = { fg = c.blue, underline = true },
    ["@markup.link.label"] = { fg = c.brightRed },
    ["@markup.list"] = { fg = c.blue },
    ["@markup.list.checked"] = { fg = c.blue, blend = 10 },
    ["@markup.list.unchecked"] = { fg = c.fg4 },
    ["@markup.link.url"] = { fg = c.orange, underline = true },
    ["@markup.math"] = { fg = c.brightAqua },
    ["@markup.quote"] = { bg = c.bg1 },
    ["@markup.raw"] = { fg = c.brightGreen },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.underline"] = { underline = true },
    ["@method"] = { fg = c.brightBlue },
    ["@method.call"] = { fg = c.brightBlue },
    ["@modifier"] = { fg = c.red },
    ["@module"] = { fg = c.fg1 },
    ["@namespace"] = { fg = c.fg1 },
    ["@none"] = { fg = c.fg1 },
    ["@number"] = { fg = c.brightPurple },
    ["@number.float"] = { fg = c.brightPurple },
    ["@operator"] = { fg = c.brightRed },
    ["@operator.unary.not"] = { fg = c.brightRed },
    ["@operator.logical"] = { fg = c.brightAqua },
    ["@operator.assignment"] = { fg = c.brightAqua },
    ["@parameter"] = { fg = c.brightBlue },
    ["@preproc"] = { fg = c.brightYellow },
    ["@property"] = { fg = c.brightBlue },
    ["@punctuation"] = { fg = c.fg4 },
    ["@punctuation.delimiter"] = { fg = c.fg4 },
    ["@punctuation.bracket"] = { fg = c.fg4 },
    ["@punctuation.special"] = { fg = c.fg4 },
    ["@reference"] = { fg = c.fg0 },
    ["@regexp"] = { fg = c.brightRed },
    ["@repeat"] = { fg = c.brightRed },
    ["@scope"] = {},
    ["@string"] = { fg = c.brightGreen },
    ["@string.regex"] = { fg = c.brightRed },
    ["@string.regexp"] = { fg = c.brightRed },
    ["@string.escape"] = { fg = c.brightRed },
    ["@string.special"] = { fg = c.brightRed },
    ["@string.special.git_config"] = { fg = c.brightAqua, underline = true },
    ["@string.special.path"] = { fg = c.blue, underline = true },
    ["@string.special.path.git_config"] = { fg = c.brightBlue, italic = true },
    ["@string.special.symbol"] = { fg = c.brightBlue },
    ["@string.special.url"] = { fg = c.blue, underline = true },
    ["@storageclass"] = { fg = c.brightOrange },
    ["@structure"] = { fg = c.brightAqua },
    ["@symbol"] = { fg = c.brightBlue },
    ["@tag"] = { fg = c.yellow },
    ["@tag.attribute"] = { fg = c.brightBlue },
    ["@tag.delimiter"] = { fg = c.aqua },
    ["@tag.tsx"] = { fg = c.brightAqua },
    ["@text"] = { fg = c.fg1 },
    ["@text.strong"] = {},
    ["@text.emphasis"] = { italic = true },
    ["@text.underline"] = { underline = true },
    ["@text.strike"] = { strikethrough = true },
    ["@text.title"] = { fg = c.brightYellow },
    ["@text.literal"] = { fg = c.brightGreen },
    ["@text.uri"] = { fg = c.blue, underline = true },
    ["@text.math"] = { fg = c.brightAqua },
    ["@text.environment"] = { fg = c.brightAqua },
    ["@text.environment.name"] = { fg = c.brightYellow },
    ["@text.reference"] = { fg = c.brightPurple },
    ["@text.todo"] = { fg = c.bg0, bg = c.yellow, bold = true, italic = true },
    ["@text.todo.checked"] = { fg = c.green },
    ["@text.todo.unchecked"] = { fg = c.fg4 },
    ["@text.note"] = { fg = c.purple },
    ["@text.note.comment"] = { fg = c.brightPurple },
    ["@text.warning"] = { fg = c.red },
    ["@text.danger"] = { fg = c.red },
    ["@text.danger.comment"] = { fg = c.fg0, bg = c.red },
    ["@text.diff.add"] = { fg = c.green },
    ["@text.diff.delete"] = { fg = c.red },
    ["@type"] = { fg = c.brightYellow },
    ["@type.tsx"] = { fg = c.brightYellow },
    ["@type.builtin"] = { fg = c.brightYellow },
    ["@type.definition"] = { fg = c.brightYellow },
    ["@type.qualifier"] = { fg = c.brightYellow },
    ["@variable"] = { fg = c.fg2 },
    ["@variable.lua"] = { fg = c.fg2 },
    ["@variable.jsx"] = { fg = c.fg1 },
    ["@variable.tsx"] = { fg = c.brightBlue },
    ["@variable.builtin"] = { fg = c.brightPurple },
    ["@variable.member"] = { fg = c.brightBlue },
    ["@variable.member.lua"] = { fg = c.brightBlue },
    ["@variable.parameter"] = { fg = c.brightBlue },
    ["@variable.parameter.luadoc"] = { fg = c.brightBlue, italic = true },
  }
end

return M
