# gruvbox-light

[delta "customized-theme"]
syntax-theme      = 'gruvbox-light'

plus-style        = 'syntax #E8E6B0'
plus-emph-style   = 'syntax #D3D192 bold'
minus-style       = 'syntax #FCC19F'
minus-emph-style  = 'syntax #EB9D82 bold'
true-color        = always

