---@class std.t.theme.CatppuccinPalette
---@field public base                   string
---@field public blue                   string
---@field public crust                  string
---@field public flamingo               string
---@field public green                  string
---@field public lavender               string
---@field public mantle                 string
---@field public maroon                 string
---@field public mauve                  string
---@field public overlay0               string
---@field public overlay1               string
---@field public overlay2               string
---@field public peach                  string
---@field public pink                   string
---@field public red                    string
---@field public rosewater              string
---@field public sapphire               string
---@field public sky                    string
---@field public subtext0               string
---@field public subtext1               string
---@field public surface0               string
---@field public surface1               string
---@field public surface2               string
---@field public teal                   string
---@field public text                   string
---@field public yellow                 string

---@class std.t.theme.GruvboxPalette
---@field public aqua                   string
---@field public bg                     string
---@field public bg0                    string
---@field public bg0_h                  string
---@field public bg0_s                  string
---@field public bg1                    string
---@field public bg2                    string
---@field public bg3                    string
---@field public bg4                    string
---@field public blue                   string
---@field public dark_aqua              string
---@field public dark_blue              string
---@field public dark_gray              string
---@field public dark_green             string
---@field public dark_orange            string
---@field public dark_purple            string
---@field public dark_red               string
---@field public dark_yellow            string
---@field public fg                     string
---@field public fg0                    string
---@field public fg0_h                  string
---@field public fg0_s                  string
---@field public fg1                    string
---@field public fg2                    string
---@field public fg3                    string
---@field public fg4                    string
---@field public gray                   string
---@field public green                  string
---@field public light_gray             string
---@field public orange                 string
---@field public purple                 string
---@field public red                    string
---@field public yellow                 string

---@class std.t.theme.NordPalette
---@field public nord0                  string
---@field public nord1                  string
---@field public nord2                  string
---@field public nord3                  string
---@field public nord4                  string
---@field public nord5                  string
---@field public nord6                  string
---@field public nord7                  string
---@field public nord8                  string
---@field public nord9                  string
---@field public nord10                 string
---@field public nord11                 string
---@field public nord12                 string
---@field public nord13                 string
---@field public nord14                 string
---@field public nord15                 string
---@field public polarNight0            string
---@field public polarNight1            string
---@field public polarNight2            string
---@field public polarNight3            string
---@field public snowStorm0             string
---@field public snowStorm1             string
---@field public snowStorm2             string
---@field public frost0                 string
---@field public frost1                 string
---@field public frost2                 string
---@field public frost3                 string
---@field public aurora0                string
---@field public aurora1                string
---@field public aurora2                string
---@field public aurora3                string
---@field public aurora4                string

---@class std.t.theme.OnehalfPalette
---@field public background             string
---@field public black                  string
---@field public blue                   string
---@field public comment                string
---@field public cyan                   string
---@field public foreground             string
---@field public green                  string
---@field public gutter                 string
---@field public guide                  string
---@field public orange                 string
---@field public purple                 string
---@field public red                    string
---@field public selection              string
---@field public white                  string
---@field public yellow                 string

---@class std.t.theme.RosepinePalette
---@field public base                   string
---@field public foam                   string
---@field public gold                   string
---@field public highlightHigh          string
---@field public highlightLow           string
---@field public highlightMed           string
---@field public iris                   string
---@field public love                   string
---@field public muted                  string
---@field public overlay                string
---@field public pine                   string
---@field public rose                   string
---@field public subtle                 string
---@field public surface                string
---@field public text                   string

---@class std.t.theme.IUnifiedPalette
---@field public none                   string
---
---@field public bg0                    string
---@field public bg1                    string
---@field public bg2                    string
---@field public bg3                    string
---@field public bg4                    string
---
---@field public fg0                    string
---@field public fg1                    string
---@field public fg2                    string
---@field public fg3                    string
---@field public fg4                    string
---
---@field public red                    string
---@field public green                  string
---@field public yellow                 string
---@field public blue                   string
---@field public purple                 string
---@field public aqua                   string
---@field public orange                 string
---
---@field public brightRed              string
---@field public brightGreen            string
---@field public brightYellow           string
---@field public brightBlue             string
---@field public brightPurple           string
---@field public brightAqua             string
---@field public brightOrange           string
---
---@field public grey                   string
---@field public pink                   string
---
---@field public diffDel                string
---@field public diffDelInline          string
---@field public diffAdd                string
---@field public diffAddInline          string

---@class std.t.theme.IPalette
---@field public unified                std.t.theme.IUnifiedPalette
---@field public catppuccin             std.t.theme.CatppuccinPalette|nil
---@field public gruvbox                std.t.theme.GruvboxPalette|nil
---@field public nord                   std.t.theme.NordPalette|nil
---@field public onehalf                std.t.theme.OnehalfPalette|nil
---@field public rosepine               std.t.theme.RosepinePalette|nil

---@class std.t.theme.IScheme
---@field public theme                  std.e.ThemeFamily
---@field public variant                std.e.ThemeVariant|nil
---@field public opposite               std.e.ThemeVariant|nil
---@field public darken                 boolean
---@field public palette                std.t.theme.IPalette

---@class std.t.theme.IContext
---@field public theme                  string
---@field public variant                string|nil
---@field public scheme                 std.t.theme.IScheme
---@field public transparency           boolean

---@class std.t.theme.IHlgroup : vim.api.keyset.highlight
