---@class std.t.ux.IRawWidget
---@field public name                   string|nil
---@field public close                  fun(widget: std.t.ux.IWidget): nil
---@field public focus                  fun(widget: std.t.ux.IWidget): nil
---@field public hide                   fun(widget: std.t.ux.IWidget): nil
---@field public isdisposed             fun(self: std.t.ux.IWidget): boolean
---@field public isfocused              fun(self: std.t.ux.IWidget): boolean
---@field public isvisible              fun(self: std.t.ux.IWidget): boolean
---@field public resize                 fun(widget: std.t.ux.IWidget): nil

---@class std.t.ux.IWidget
---@field public name                   string|nil
---@field public close                  fun(self: std.t.ux.IWidget): nil
---@field public focus                  fun(self: std.t.ux.IWidget): nil
---@field public hide                   fun(self: std.t.ux.IWidget): nil
---@field public isdisposed             fun(self: std.t.ux.IWidget): boolean
---@field public isfocused              fun(self: std.t.ux.IWidget): boolean
---@field public isvisible              fun(self: std.t.ux.IWidget): boolean
---@field public resize                 fun(self: std.t.ux.IWidget): nil
