---@class guanghechen.types.ICircularQueue
---@field public size fun(self: guanghechen.types.ICircularQueue): number
---@field public at fun(self: guanghechen.types.ICircularQueue, index: number): guanghechen.types.T|nil
---@field public front fun(self: guanghechen.types.ICircularQueue): guanghechen.types.T|nil
---@field public back fun(self: guanghechen.types.ICircularQueue): guanghechen.types.T|nil
---@field public collect fun():guanghechen.types.T[]
---@field public enqueue fun(self: guanghechen.types.ICircularQueue, element:guanghechen.types.T):nil
---@field public dequeue fun(self: guanghechen.types.ICircularQueue):guanghechen.types.T|nil
---@field public dequeue_back fun(self: guanghechen.types.ICircularQueue):guanghechen.types.T|nil
---@field public iterator fun(self: guanghechen.types.ICircularQueue):fun():guanghechen.types.T|nil
---@field public iterator_reverse fun(self: guanghechen.types.ICircularQueue):fun():guanghechen.types.T|nil
