---@class guanghechen.types.ICircularQueue
---@field public size fun(): number
---@field public front fun(): guanghechen.types.T|nil
---@field public back fun(): guanghechen.types.T|nil
---@field public enqueue fun(element:guanghechen.types.T):nil
---@field public dequeue fun():guanghechen.types.T|nil
---@field public iterator fun():fun():guanghechen.types.T|nil
