---@class dot.theme.hlgroup.catppuccin.treesitter
local M = {}

---@param context                       dot.t.theme.IContext
---@return table<string, ark.t.theme.IHlgroup>
function M.gen_hlgroup_map(context)
  local t = context.transparency ---@type boolean
  local c = context.scheme.palette.catppuccin ---@type dot.t.theme.CatppuccinPalette

  ---@type table<string, ark.t.theme.IHlgroup>
  local hlgroup_map = {
    -- Comments
    ["@comment"] = { fg = c.overlay2, italic = true },
    ["@comment.documentation"] = { fg = c.overlay2, italic = true },
    ["@comment.error"] = { fg = c.base, bg = t and c.none or c.red },
    ["@comment.hint"] = { fg = c.base, bg = t and c.none or c.blue },
    ["@comment.note"] = { fg = c.base, bg = t and c.none or c.rosewater },
    ["@comment.todo"] = { fg = c.base, bg = t and c.none or c.flamingo },
    ["@comment.warning"] = { fg = c.base, bg = t and c.none or c.yellow },

    -- Identifiers
    ["@annotation"] = { fg = c.red },
    ["@attribute"] = { fg = c.peach },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = c.peach },
    ["@constant.macro"] = { link = "Macro" },
    ["@constructor"] = { fg = c.yellow },
    ["@diff.delta"] = { link = "DiffChange" },
    ["@diff.minus"] = { link = "DiffDelete" },
    ["@diff.plus"] = { link = "DiffAdd" },
    ["@error"] = { link = "Error" },
    ["@field"] = { fg = c.lavender },
    ["@module"] = { fg = c.yellow, italic = true },
    ["@namespace"] = { fg = c.yellow, italic = true },
    ["@parameter"] = { fg = c.maroon },
    ["@property"] = { fg = c.lavender },
    ["@symbol"] = { fg = c.flamingo },
    ["@variable"] = { fg = c.text },
    ["@variable.builtin"] = { fg = c.red, italic = true },
    ["@variable.member"] = { fg = c.lavender },
    ["@variable.parameter"] = { fg = c.maroon },
    ["@variable.parameter.luadoc"] = { fg = c.yellow, italic = true },

    -- Literals
    ["@boolean"] = { link = "Boolean" },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@float"] = { link = "Float" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@string"] = { link = "String" },
    ["@string.documentation"] = { fg = c.teal },
    ["@string.escape"] = { fg = c.pink },
    ["@string.regexp"] = { fg = c.pink },
    ["@string.special"] = { link = "Special" },
    ["@string.special.path"] = { fg = c.blue, underline = true },
    ["@string.special.symbol"] = { fg = c.flamingo },
    ["@string.special.url"] = { fg = c.blue, underline = true, italic = true },

    -- Functions
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = c.peach },
    ["@function.call"] = { link = "Function" },
    ["@function.macro"] = { fg = c.pink },
    ["@function.method"] = { link = "Function" },
    ["@function.method.call"] = { link = "Function" },
    ["@method"] = { link = "Function" },
    ["@method.call"] = { link = "Function" },
    ["@operator"] = { link = "Operator" },

    -- Keywords
    ["@keyword"] = { fg = c.mauve, italic = true },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.conditional.ternary"] = { fg = c.sky },
    ["@keyword.coroutine"] = { link = "Keyword" },
    ["@keyword.debug"] = { link = "Exception" },
    ["@keyword.directive"] = { fg = c.pink },
    ["@keyword.directive.define"] = { fg = c.pink },
    ["@keyword.exception"] = { link = "Exception" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.modifier"] = { link = "Keyword" },
    ["@keyword.operator"] = { fg = c.mauve },
    ["@keyword.repeat"] = { link = "Repeat" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@keyword.storage"] = { link = "StorageClass" },
    ["@keyword.type"] = { link = "Keyword" },
    ["@label"] = { link = "Label" },

    -- Types
    ["@markup.environment"] = { fg = c.pink },
    ["@markup.environment.name"] = { fg = c.blue },
    ["@markup.heading"] = { fg = c.blue, bold = true },
    ["@markup.heading.1.markdown"] = { fg = c.red, bold = true },
    ["@markup.heading.1.marker.markdown"] = { fg = c.red },
    ["@markup.heading.2.markdown"] = { fg = c.peach, bold = true },
    ["@markup.heading.2.marker.markdown"] = { fg = c.peach },
    ["@markup.heading.3.markdown"] = { fg = c.yellow, bold = true },
    ["@markup.heading.3.marker.markdown"] = { fg = c.yellow },
    ["@markup.heading.4.markdown"] = { fg = c.green, bold = true },
    ["@markup.heading.4.marker.markdown"] = { fg = c.green },
    ["@markup.heading.5.markdown"] = { fg = c.sapphire, bold = true },
    ["@markup.heading.5.marker.markdown"] = { fg = c.sapphire },
    ["@markup.heading.6.markdown"] = { fg = c.lavender, bold = true },
    ["@markup.heading.6.marker.markdown"] = { fg = c.lavender },
    ["@markup.italic"] = { fg = c.red, italic = true },
    ["@markup.link"] = { fg = c.lavender },
    ["@markup.link.label"] = { fg = c.lavender },
    ["@markup.link.url"] = { fg = c.blue, underline = true, italic = true },
    ["@markup.list"] = { fg = c.teal },
    ["@markup.list.checked"] = { fg = c.green },
    ["@markup.list.unchecked"] = { fg = c.overlay1 },
    ["@markup.math"] = { fg = c.blue },
    ["@markup.quote"] = { fg = c.pink },
    ["@markup.raw"] = { fg = c.green },
    ["@markup.strikethrough"] = { fg = c.text, strikethrough = true },
    ["@markup.strong"] = { fg = c.red, bold = true },
    ["@markup.underline"] = { underline = true },

    -- Tags
    ["@tag"] = { fg = c.blue },
    ["@tag.attribute"] = { fg = c.yellow, italic = true },
    ["@tag.builtin"] = { fg = c.blue },
    ["@tag.delimiter"] = { fg = c.teal },

    -- Text (legacy)
    ["@text"] = { fg = c.text },
    ["@text.danger"] = { fg = c.base, bg = t and c.none or c.red },
    ["@text.diff.add"] = { link = "DiffAdd" },
    ["@text.diff.delete"] = { link = "DiffDelete" },
    ["@text.emphasis"] = { fg = c.red, italic = true },
    ["@text.environment"] = { fg = c.pink },
    ["@text.environment.name"] = { fg = c.blue },
    ["@text.literal"] = { fg = c.green },
    ["@text.math"] = { fg = c.blue },
    ["@text.note"] = { fg = c.base, bg = t and c.none or c.rosewater },
    ["@text.reference"] = { fg = c.lavender },
    ["@text.strike"] = { fg = c.text, strikethrough = true },
    ["@text.strong"] = { fg = c.red, bold = true },
    ["@text.title"] = { fg = c.blue, bold = true },
    ["@text.todo"] = { fg = c.base, bg = t and c.none or c.flamingo },
    ["@text.todo.checked"] = { fg = c.green },
    ["@text.todo.unchecked"] = { fg = c.overlay1 },
    ["@text.underline"] = { underline = true },
    ["@text.uri"] = { fg = c.blue, underline = true, italic = true },
    ["@text.warning"] = { fg = c.base, bg = t and c.none or c.yellow },

    -- Compatibility
    ["@character.printf"] = { link = "SpecialChar" },
    ["@comment.danger"] = { fg = c.base, bg = t and c.none or c.red },
    ["@comment.info"] = { fg = c.base, bg = t and c.none or c.sky },
    ["@conditional"] = { link = "Conditional" },
    ["@constructor.tsx"] = { link = "@constructor" },
    ["@debug"] = { link = "Debug" },
    ["@define"] = { link = "PreProc" },
    ["@event"] = { link = "Keyword" },
    ["@exception"] = { link = "Exception" },
    ["@include"] = { link = "Include" },
    ["@macro"] = { link = "Macro" },
    ["@markup"] = { fg = c.text },
    ["@markup.emphasis"] = { fg = c.red, italic = true },
    ["@markup.heading.1"] = { fg = c.red, bold = true },
    ["@markup.heading.1.marker"] = { fg = c.red },
    ["@markup.heading.2"] = { fg = c.peach, bold = true },
    ["@markup.heading.2.marker"] = { fg = c.peach },
    ["@markup.heading.3"] = { fg = c.yellow, bold = true },
    ["@markup.heading.3.marker"] = { fg = c.yellow },
    ["@markup.heading.4"] = { fg = c.green, bold = true },
    ["@markup.heading.4.marker"] = { fg = c.green },
    ["@markup.heading.5"] = { fg = c.sapphire, bold = true },
    ["@markup.heading.5.marker"] = { fg = c.sapphire },
    ["@markup.heading.6"] = { fg = c.lavender, bold = true },
    ["@markup.heading.6.marker"] = { fg = c.lavender },
    ["@markup.link.label.symbol"] = { link = "@markup.link.label" },
    ["@markup.list.markdown"] = { link = "@markup.list" },
    ["@markup.raw.markdown_inline"] = { link = "@markup.raw" },
    ["@modifier"] = { link = "Keyword" },
    ["@module.builtin"] = { fg = c.yellow, italic = true },
    ["@namespace.builtin"] = { fg = c.yellow, italic = true },
    ["@none"] = { fg = c.text },
    ["@preproc"] = { link = "PreProc" },
    ["@punctuation"] = { link = "Delimiter" },
    ["@punctuation.special.markdown"] = { link = "@punctuation.delimiter" },
    ["@reference"] = { fg = c.lavender },
    ["@regexp"] = { fg = c.pink },
    ["@repeat"] = { link = "Repeat" },
    ["@scope"] = {},
    ["@storageclass"] = { link = "StorageClass" },
    ["@string.regex"] = { link = "@string.regexp" },
    ["@structure"] = { link = "Structure" },
    ["@tag.delimiter.tsx"] = { link = "@tag.delimiter" },
    ["@tag.javascript"] = { link = "@tag" },
    ["@tag.tsx"] = { link = "@tag" },
    ["@text.danger.comment"] = { fg = c.base, bg = t and c.none or c.red },
    ["@text.note.comment"] = { fg = c.base, bg = t and c.none or c.rosewater },
    ["@type.tsx"] = { link = "@type" },
    ["@variable.jsx"] = { fg = c.text },
    ["@variable.parameter.builtin"] = { link = "@variable.parameter" },
    ["@variable.tsx"] = { fg = c.text },

    -- Types
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = c.mauve, italic = true },
    ["@type.definition"] = { link = "Type" },
    ["@type.qualifier"] = { fg = c.yellow },

    -- Punctuation
    ["@punctuation.bracket"] = { fg = c.overlay2 },
    ["@punctuation.delimiter"] = { fg = c.overlay2 },
    ["@punctuation.special"] = { fg = c.pink },

    -- Language specific
    ["@function.builtin.bash"] = { fg = c.red, italic = true },
    ["@variable.parameter.bash"] = { fg = c.green },
    ["@markup.link.label.html"] = { fg = c.text },
    ["@string.special.url.html"] = { fg = c.green },
    ["@character.special.html"] = { fg = c.red },
    ["@constructor.lua"] = { link = "@punctuation.bracket" },
    ["@constructor.python"] = { fg = c.sky },
    ["@constant.java"] = { fg = c.teal },
    ["@property.css"] = { fg = c.blue },
    ["@property.scss"] = { fg = c.blue },
    ["@property.id.css"] = { fg = c.yellow },
    ["@property.class.css"] = { fg = c.yellow },
    ["@type.css"] = { fg = c.lavender },
    ["@type.tag.css"] = { fg = c.blue },
    ["@string.plain.css"] = { fg = c.text },
    ["@number.css"] = { fg = c.peach },
    ["@keyword.directive.css"] = { link = "Keyword" },
    ["@keyword.import.c"] = { fg = c.yellow },
    ["@keyword.import.cpp"] = { fg = c.yellow },
    ["@attribute.c_sharp"] = { fg = c.yellow },
    ["@label.yaml"] = { fg = c.yellow },
    ["@comment.warning.gitcommit"] = { fg = c.yellow },
  }

  return hlgroup_map
end

return M
