#_tmux_widget_app_name="ps -o comm= -t '#{pane_tty}' | rg -o '[\\w-]+' | tail -1"
_tmux_widget_app_name="bash $HOME/.config/tmux/script/app_name.sh #{pane_tty}"
_tmux_widget_app_pid="ps -o pid= -t '#{pane_tty}' | rg -o '\\d+' | tail -1"

set -g status-left "\
#[fg=#{@GHC_SL_COLOR_BG},               bg=#{@GHC_SL_COLOR_BG}]\
#[fg=#{@GHC_SL_COLOR_FG_SESSION_TEXT},  bg=#{@GHC_SL_COLOR_BG_SESSION_TEXT}, bold] #S \
#[fg=#{@GHC_SL_COLOR_FG_SESSION_SYM},   bg=#{@GHC_SL_COLOR_BG_SESSION_SYM}, bold] #{@GHC_SL_SYM_SESSION} \
#[fg=#{@GHC_SL_COLOR_BG_SESSION_SYM},   bg=#{@GHC_SL_COLOR_BG}]#{@GHC_SL_SEP_RIGHT}\
#[fg=#{@GHC_SL_COLOR_BG},               bg=#{@GHC_SL_COLOR_BG}] \
"

set -g status-right "\
#[fg=#{@GHC_SL_COLOR_BG},               bg=#{@GHC_SL_COLOR_BG}] \
#[fg=#{@GHC_SL_COLOR_BG_TIME_SYM},      bg=#{@GHC_SL_COLOR_BG}]#{@GHC_SL_SEP_LEFT}\
#[fg=#{@GHC_SL_COLOR_FG_TIME_SYM},      bg=#{@GHC_SL_COLOR_BG_TIME_SYM}]#{@GHC_SL_SYM_TIME} \
#[fg=#{@GHC_SL_COLOR_FG_TIME_TEXT},     bg=#{@GHC_SL_COLOR_BG_TIME_TEXT}, bold] %H:%M:%S \
\
#[fg=#{@GHC_SL_COLOR_BG_DATE_SYM},      bg=#{@GHC_SL_COLOR_BG_TIME_TEXT}]#{@GHC_SL_SEP_LEFT}\
#[fg=#{@GHC_SL_COLOR_FG_DATE_SYM},      bg=#{@GHC_SL_COLOR_BG_DATE_SYM}]#{@GHC_SL_SYM_DATE} \
#[fg=#{@GHC_SL_COLOR_FG_DATE_TEXT},     bg=#{@GHC_SL_COLOR_BG_DATE_TEXT}, bold] %a %b %d, %Y \
"

