---@meta

---@class dot.t.IRawWidget
---@field public name                   string|nil
---@field public close                  fun(widget: dot.t.IWidget): nil
---@field public focus                  fun(widget: dot.t.IWidget): nil
---@field public hide                   fun(widget: dot.t.IWidget): nil
---@field public isdisposed             fun(self: dot.t.IWidget): boolean
---@field public isfocused              fun(self: dot.t.IWidget): boolean
---@field public isvisible              fun(self: dot.t.IWidget): boolean
---@field public resize                 fun(widget: dot.t.IWidget): nil

---@class dot.t.IWidget
---@field public name                   string|nil
---@field public close                  fun(self: dot.t.IWidget): nil
---@field public focus                  fun(self: dot.t.IWidget): nil
---@field public hide                   fun(self: dot.t.IWidget): nil
---@field public isdisposed             fun(self: dot.t.IWidget): boolean
---@field public isfocused              fun(self: dot.t.IWidget): boolean
---@field public isvisible              fun(self: dot.t.IWidget): boolean
---@field public resize                 fun(self: dot.t.IWidget): nil
