mod cpu;
mod date;
mod duration;
mod fullscreen;
mod host;
mod memory;
mod network;
mod pill;
mod prefix_indicator;
mod session_list;
mod time;
mod window_id;

pub use cpu::CpuWidget;
pub use date::DateWidget;
pub use duration::DurationWidget;
pub use fullscreen::FullscreenWidget;
pub use host::HostWidget;
pub use memory::MemoryWidget;
pub use network::NetworkWidget;
pub use prefix_indicator::PrefixIndicatorWidget;
pub use session_list::SessionListWidget;
pub use time::TimeWidget;
pub use window_id::WindowIdWidget;
