---@alias kyokuya.theme.palette.IColorKey
---| "white"
---| "darker_black"
---| "black"
---| "black2"
---| "one_bg"
---| "one_bg2"
---| "one_bg3"
---| "grey"
---| "grey_fg"
---| "grey_fg2"
---| "light_grey"
---| "red"
---| "baby_pink"
---| "pink"
---| "line"
---| "green"
---| "vibrant_green"
---| "nord_blue"
---| "blue"
---| "yellow"
---| "sun"
---| "purple"
---| "dark_purple"
---| "teal"
---| "orange"
---| "cyan"
---| "statusline_bg"
---| "lightbg"
---| "pmenu_bg"
---| "folder_bg"
---| "diff_delete"
---| "diff_add"
---| "diff_delete_hl"
---| "diff_add_hl"

---@class kyokuya.theme.palette.IColors
---@field public  white           string
---@field public  darker_black    string
---@field public  black           string
---@field public  black2          string
---@field public  one_bg          string
---@field public  one_bg2         string
---@field public  one_bg3         string
---@field public  grey            string
---@field public  grey_fg         string
---@field public  grey_fg2        string
---@field public  light_grey      string
---@field public  red             string
---@field public  baby_pink       string
---@field public  pink            string
---@field public  line            string
---@field public  green           string
---@field public  vibrant_green   string
---@field public  nord_blue       string
---@field public  blue            string
---@field public  yellow          string
---@field public  sun             string
---@field public  purple          string
---@field public  dark_purple     string
---@field public  teal            string
---@field public  orange          string
---@field public  cyan            string
---@field public  statusline_bg   string
---@field public  lightbg         string
---@field public  pmenu_bg        string
---@field public  folder_bg       string
---@field public  diff_delete     string
---@field public  diff_add        string
---@field public  diff_delete_hl  string
---@field public  diff_add_hl     string

---@alias kyokuya.theme.palette.IPaletteScheme
---| "lighten"
---| "darken"

---@class kyokuya.theme.palette.IPalette
---@field public scheme kyokuya.theme.palette.IPaletteScheme
---@field public colors kyokuya.theme.palette.IColors

---@class kyokuya.theme.IHighlightGroup
---@field public fg             ?kyokuya.theme.palette.IColorKey|"none"
---@field public bg             ?kyokuya.theme.palette.IColorKey|"none"
---@field public sp             ?kyokuya.theme.palette.IColorKey|"none"
---@field public blend          ?integer  0-100 [0, 100]
---@field public bold           ?boolean
---@field public standout       ?boolean
---@field public underline      ?boolean
---@field public undercurl      ?boolean
---@field public underdouble    ?boolean
---@field public underdotted    ?boolean
---@field public underdashed    ?boolean
---@field public strikethrough  ?boolean
---@field public italic         ?boolean
---@field public reverse        ?boolean
---@field public nocombine      ?boolean
---@field public link           ?string

---@class kyokuya.theme.INvimHighlightGroup : vim.api.keyset.highlight
---@field public fg             ?string
---@field public bg             ?string
---@field public sp             ?string
---@field public blend          ?integer  0-100 [0, 100]
---@field public bold           ?boolean
---@field public standout       ?boolean
---@field public underline      ?boolean
---@field public undercurl      ?boolean
---@field public underdouble    ?boolean
---@field public underdotted    ?boolean
---@field public underdashed    ?boolean
---@field public strikethrough  ?boolean
---@field public italic         ?boolean
---@field public reverse        ?boolean
---@field public nocombine      ?boolean
---@field public link           ?string
