import fs from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'

import { gen_full_theme_name, render_template } from '#cli/theme/util'

const global_settings_header = '// Generated by the theme CLI. Put personal settings in settings.json.\n'

/**
 * Match Zed's platform paths, independently of where this dotfiles repo lives.
 * @param {string} [platform]
 * @param {NodeJS.ProcessEnv} [environment]
 * @param {string} [home]
 */
export function resolve_zed_config_dir(platform = process.platform, environment = process.env, home = os.homedir()) {
  if (platform === 'win32') {
    return path.win32.join(environment.APPDATA || path.win32.join(home, 'AppData', 'Roaming'), 'Zed')
  }
  if (platform === 'darwin') return path.join(home, '.config', 'zed')
  const config = environment.FLATPAK_XDG_CONFIG_HOME || environment.XDG_CONFIG_HOME
  return path.join(config && path.isAbsolute(config) ? config : path.join(home, '.config'), 'zed')
}

/**
 * @param {string} filepath
 * @param {string} content
 * @param {string} temporaryRoot
 */
async function write_atomic(filepath, content, temporaryRoot) {
  let mode
  try {
    const current = await fs.readFile(filepath, 'utf8')
    if (current === content) return
    mode = (await fs.stat(filepath)).mode & 0o777
  } catch (error) {
    if (error.code !== 'ENOENT') throw error
  }
  const temporary = await fs.mkdtemp(path.join(temporaryRoot, '.tmp-zed-theme-'))
  try {
    const staged = path.join(temporary, 'content')
    await fs.writeFile(staged, content, { mode: mode ?? 0o644 })
    // Creation applies umask; restore an existing file's exact permission bits.
    if (mode !== undefined) await fs.chmod(staged, mode)
    await fs.rename(staged, filepath)
  } finally {
    await fs.rm(temporary, { recursive: true, force: true })
  }
}

/** @param {string} filepath */
async function validate_global_settings(filepath) {
  let content
  try {
    content = await fs.readFile(filepath, 'utf8')
  } catch (error) {
    if (error.code === 'ENOENT') return
    throw error
  }
  if (!content.startsWith(global_settings_header)) {
    throw new Error(`Refusing to replace unmanaged Zed settings: ${filepath}. Move personal settings to settings.json first.`)
  }
}

export default {
  location: resolve_zed_config_dir(),
  active: { file: 'settings.json' },
  themes: 'themes/',
  extname: '.json',
  local: 'global_settings.json',
  on_render: async function (_app, template, scheme) {
    const content = await render_template(template, scheme)
    if (content.includes('{{')) throw new Error('Unresolved expression in Zed theme')
    const theme = JSON.parse(content)
    const name = gen_full_theme_name(scheme.theme, scheme.variant)
    if (theme.themes?.length !== 1 || theme.themes[0].name !== name ||
      theme.themes[0].appearance !== (scheme.darken ? 'dark' : 'light')) {
      throw new Error(`Invalid Zed theme identity: ${name}`)
    }
    // Zed 1.19 uses transparent AccentContent values, unlike the older hosted schema.
    const accents = theme.themes[0].style?.accents
    if (accents !== undefined && (!Array.isArray(accents) || accents.some(color =>
      typeof color !== 'string' || !/^#[\da-f]{6}(?:[\da-f]{2})?$/i.test(color)))) {
      throw new Error(`Invalid Zed theme accents: expected color strings in ${name}`)
    }
    return content
  },
  on_prepare: async function (app) {
    await validate_global_settings(path.join(app.home, app.local))
  },
  on_apply: async function (app, content, scheme) {
    const settingsPath = path.join(app.home, app.local)
    await validate_global_settings(settingsPath)
    const name = gen_full_theme_name(scheme.theme, scheme.variant)
    const themesPath = path.join(app.home, app.themes)
    await fs.mkdir(themesPath, { recursive: true })
    // Publish the theme before selecting it; failure leaves the selection intact.
    await write_atomic(path.join(themesPath, `${name}.json`), content, app.home)
    // Zed merges this CLI-owned layer below settings.json and watches it for changes.
    // Never read/modify/write the user settings: external saves cannot be lost.
    const settings = global_settings_header + JSON.stringify({ theme: name }, null, 2) + '\n'
    await write_atomic(settingsPath, settings, app.home)
  },
}
