---@class dot.theme.hlgroup.tokyonight.basic
local M = {}

---@param context                       stl.t.theme.IContext
---@return dot.theme.hlgroup.common.modes_color_map
function M.gen_modes_color_map(context)
  local c = context.scheme.palette.unified ---@type stl.t.theme.IUnifiedPalette
  local mc = {
    command = c.brightBlue,
    confirm = c.brightAqua,
    insert = c.brightPurple,
    normal = c.brightAqua,
    nterminal = c.yellow,
    replace = c.brightYellow,
    select = c.brightOrange,
    terminal = c.brightBlue,
    visual = c.brightOrange,
  }
  return mc
end

---@param context                       stl.t.theme.IContext
---@return table<string, stl.t.theme.IHlgroup>
function M.gen_hlgroup_map(context)
  local cs = stl.color
  local t = context.transparency ---@type boolean
  local u = context.scheme.palette.unified ---@type stl.t.theme.IUnifiedPalette

  local bg = t and u.none or u.bg0 ---@type string

  ---@type table<string, stl.t.theme.IHlgroup>
  local hlgroup_map = {
    ---Completion
    ComplHint = { fg = u.fg3 },
    ComplHintMore = { fg = u.orange, italic = true },

    Added = { fg = u.green },
    Bold = { bold = true, fg = u.fg1 },
    Boolean = { fg = u.orange },
    Builtin = { fg = u.brightBlue },
    Changed = { fg = u.yellow },
    Character = { fg = u.green },
    ColorColumn = { bg = u.bg2 },
    Comment = { fg = u.grey, italic = true },
    Conceal = { fg = u.fg3 },
    Conditional = { fg = u.purple },
    Constant = { fg = u.orange },
    CurSearch = { bg = u.red, fg = u.bg0 },
    Cursor = { fg = u.bg0, bg = u.purple },
    CursorColumn = { bg = u.bg2 },
    CursorLine = { bg = u.bg2 },
    CursorLineNr = { fg = u.orange, bold = true },
    Debug = { fg = u.orange },
    Define = { fg = u.aqua },
    Delimiter = { fg = u.aqua },
    DevIconDefault = { fg = u.red },
    Diagnostic_ERROR = { fg = u.red },
    Diagnostic_HINT = { fg = u.brightAqua },
    Diagnostic_INFO = { fg = u.brightBlue },
    Diagnostic_WARN = { fg = u.yellow },
    DiagnosticError = { fg = u.red },
    DiagnosticFloatingError = { fg = u.red },
    DiagnosticFloatingHint = { fg = u.brightAqua },
    DiagnosticFloatingInfo = { fg = u.brightBlue },
    DiagnosticFloatingOk = { fg = u.green },
    DiagnosticFloatingWarn = { fg = u.yellow },
    DiagnosticHint = { fg = u.brightAqua },
    DiagnosticInfo = { fg = u.brightBlue },
    DiagnosticOk = { fg = u.green },
    DiagnosticSignError = { fg = u.red },
    DiagnosticSignHint = { fg = u.brightAqua },
    DiagnosticSignInfo = { fg = u.brightBlue },
    DiagnosticSignOk = { fg = u.green },
    DiagnosticSignWarn = { fg = u.yellow },
    DiagnosticUnderlineError = { undercurl = true, sp = u.red },
    DiagnosticUnderlineHint = { undercurl = true, sp = u.brightAqua },
    DiagnosticUnderlineInfo = { undercurl = true, sp = u.brightBlue },
    DiagnosticUnderlineWarn = { undercurl = true, sp = u.yellow },
    DiagnosticVirtualTextError = { fg = u.red, bg = t and u.none or cs.mix(u.bg0, u.red, 12) },
    DiagnosticVirtualTextHint = { fg = u.brightAqua, bg = t and u.none or cs.mix(u.bg0, u.brightAqua, 12) },
    DiagnosticVirtualTextInfo = { fg = u.brightBlue, bg = t and u.none or cs.mix(u.bg0, u.brightBlue, 12) },
    DiagnosticVirtualTextWarn = { fg = u.yellow, bg = t and u.none or cs.mix(u.bg0, u.yellow, 12) },
    DiagnosticVirtualTextOk = { fg = u.green, bg = t and u.none or cs.mix(u.bg0, u.green, 12) },
    DiagnosticVirtualLinesError = { fg = u.red, bg = t and u.none or cs.mix(u.bg0, u.red, 12), italic = true },
    DiagnosticVirtualLinesHint = {
      fg = u.brightAqua,
      bg = t and u.none or cs.mix(u.bg0, u.brightAqua, 12),
      italic = true,
    },
    DiagnosticVirtualLinesInfo = {
      fg = u.brightBlue,
      bg = t and u.none or cs.mix(u.bg0, u.brightBlue, 12),
      italic = true,
    },
    DiagnosticVirtualLinesWarn = { fg = u.yellow, bg = t and u.none or cs.mix(u.bg0, u.yellow, 12), italic = true },
    DiagnosticVirtualLinesOk = { fg = u.green, bg = t and u.none or cs.mix(u.bg0, u.green, 12), italic = true },
    DiagnosticWarn = { fg = u.yellow },
    DiffAdd = { bg = u.diffAdd },
    DiffAddLeft = { bg = u.diffDel },
    DiffAddRight = { bg = u.diffAdd },
    DiffAdded = { fg = u.green },
    DiffChange = { bg = u.bg2 },
    DiffChanged = { fg = u.blue },
    DiffDelLeft = { bg = u.diffDel },
    DiffDelRight = { bg = u.diffDel },
    DiffDelete = { bg = u.diffDel },
    DiffFile = { fg = u.blue },
    DiffIndexLine = { fg = u.purple },
    DiffLine = { fg = u.fg2 },
    DiffModLeft = { bg = u.diffDel },
    DiffModRight = { bg = u.diffAdd },
    DiffNewFile = { fg = u.brightBlue },
    DiffOldFile = { fg = u.brightBlue },
    DiffRemoved = { fg = u.red },
    DiffText = { fg = u.fg1, bg = u.diffAddInline },
    DiffWordLeft = { fg = u.fg1, bg = u.diffDelInline },
    DiffWordRight = { fg = u.fg1, bg = u.diffAddInline },
    Directory = { fg = u.blue, bold = true },
    Done = { fg = u.orange, bold = true, italic = true },
    EndOfBuffer = { fg = u.bg0 },
    Error = { fg = u.red },
    ErrorMsg = { fg = u.red, bold = true, italic = true },
    Exception = { fg = u.purple },
    Float = { fg = u.orange },
    FloatActiveBorder = { link = t and "ms_b_bg0" or "ms_b_none" },
    FloatActiveTitle = { link = "ms_b_bg0" },
    FloatBorder = { fg = u.blue, bg = t and u.bg1 or u.none, blend = t and 50 or 0 },
    FloatNormal = { fg = u.fg1, bg = t and u.bg1 or u.none },
    FloatTitle = { fg = u.blue, bg = t and u.bg1 or u.none },
    FoldColumn = { fg = u.grey },
    Folded = { fg = u.fg2, bg = u.bg2 },
    Function = { fg = u.blue },
    healthError = { fg = u.red },
    healthSuccess = { fg = u.brightGreen },
    healthWarning = { fg = u.yellow },
    iCursor = { fg = u.bg0, bg = u.purple },
    Identifier = { fg = u.purple },
    IncSearch = { bg = u.orange, fg = u.bg0 },
    Include = { fg = u.purple },
    Italic = { italic = true, fg = u.fg1 },
    Keyword = { fg = u.aqua },
    Label = { fg = u.blue },
    lCursor = { fg = u.bg0, bg = u.purple },
    LineNr = { fg = u.fg3 },
    LspCodeLens = { fg = u.grey },
    LspInlayHint = { fg = u.fg3, bg = u.bg1, blend = t and 50 or 0 },
    LspReferenceRead = { bg = u.bg3, bold = true, underline = true },
    LspReferenceText = { bg = u.bg3, bold = true, underline = true },
    LspReferenceWrite = { bg = u.bg3, bold = true, underline = true },
    LspSignatureActiveParameter = { fg = u.fg1, bg = u.bg3, bold = true },
    Macro = { fg = u.aqua },
    MatchParen = { fg = u.orange, bg = u.bg3, bold = true },
    MatchWord = { fg = u.fg1, bg = u.bg3 },
    Member = { fg = u.blue },
    Method = { fg = u.blue },
    ModeMsg = { fg = u.fg2, bold = true },
    MoreMsg = { fg = u.blue },
    MsgArea = { link = "Normal" },
    NonText = { fg = cs.mix(bg, u.fg4, 45), italic = true },
    Normal = { fg = u.fg1, bg = u.bg0, blend = t and 50 or 0 },
    NormalFloat = { fg = u.fg1, bg = u.bg1 },
    NormalNC = { fg = u.fg1, bg = u.bg1, blend = t and 50 or 0 },
    Number = { fg = u.orange },
    NvimInternalError = { fg = u.red },
    Operator = { fg = u.aqua },
    Parameter = { fg = u.blue },
    Pmenu = { fg = u.fg1, bg = u.bg1 },
    PmenuSbar = { bg = u.bg2 },
    PmenuSel = { fg = u.fg1, bg = u.bg3, bold = true },
    PmenuThumb = { bg = u.bg4 },
    PreCondit = { fg = u.aqua },
    PreProc = { fg = u.aqua },
    Question = { fg = u.blue },
    QuickFixLine = { fg = u.fg1, bg = u.bg3, bold = true },
    Removed = { fg = u.red },
    RenamerBorder = { link = t and "ms_b_bg0" or "ms_b_none" },
    RenamerTitle = { link = t and "ms_b_bg0" or "ms_b_none" },
    Repeat = { fg = u.purple },
    Search = { bg = u.yellow, fg = u.bg0 },
    SignColumn = { fg = u.fg3 },
    Special = { fg = u.brightBlue },
    SpecialChar = { fg = u.brightBlue },
    SpecialKey = { link = "NonText" },
    SpellBad = { undercurl = true, sp = u.red },
    SpellCap = { undercurl = true, sp = u.yellow },
    SpellLocal = { undercurl = true, sp = u.brightBlue },
    SpellRare = { undercurl = true, sp = u.brightAqua },
    Statement = { fg = u.purple },
    StatusColumnMark = { link = "DiagnosticHint", default = true },
    StatusLine = { fg = u.fg2, bg = u.bg1, blend = t and 50 or 0 },
    StatusLineNC = { fg = u.fg3, bg = u.bg1, blend = t and 50 or 0 },
    StorageClass = { fg = u.aqua },
    String = { fg = u.green },
    Structure = { fg = u.brightBlue },
    Substitute = { bg = u.red, fg = u.bg0 },
    TabLine = { bg = u.bg1, fg = u.fg2 },
    TabLineFill = { bg = u.bg2, blend = t and 50 or 0 },
    TabLineSel = { link = "Normal" },
    Tag = { fg = u.blue, bold = true },
    Title = { fg = u.blue, bold = true },
    Todo = { fg = u.bg0, bg = u.yellow, bold = true },
    TooLong = { fg = u.red },
    Type = { fg = u.brightBlue },
    Typedef = { fg = u.brightBlue },
    Variable = { fg = u.fg1 },
    UnderLined = { underline = true },
    vCursor = { fg = u.bg0, bg = u.purple },
    Visual = { fg = u.fg1, bg = u.bg3, bold = true },
    VisualNOS = { fg = u.fg1, bg = u.bg3, bold = true },
    WarningMsg = { fg = u.yellow },
    Whitespace = { fg = u.bg4 },
    WildMenu = { fg = u.fg1, bg = u.bg3 },
    WinBar = { fg = u.fg1, bg = u.bg0 },
    WinBarNC = { fg = u.fg1, bg = u.bg1 },
    WinSeparator = { fg = u.bg4, blend = t and 50 or 0 },
  }

  return hlgroup_map
end

return M
