---@class dot.theme.hlgroup.tokyonight.basic
local M = {}

---@param context                       stl.t.theme.IContext
---@return dot.theme.hlgroup.common.modes_color_map
function M.gen_modes_color_map(context)
  local c = context.scheme.palette.unified ---@type stl.t.theme.IUnifiedPalette
  local mc = {
    command = c.brightBlue,
    confirm = c.brightAqua,
    insert = c.brightPurple,
    normal = c.brightAqua,
    nterminal = c.yellow,
    replace = c.brightYellow,
    select = c.brightOrange,
    terminal = c.brightBlue,
    visual = c.brightOrange,
  }
  return mc
end

---@param context                       stl.t.theme.IContext
---@return table<string, stl.t.theme.IHlgroup>
function M.gen_hlgroup_map(context)
  local cs = stl.color
  local t = context.transparency ---@type boolean
  local c = context.scheme.palette.tokyonight ---@type stl.t.theme.ITokyonightPalette
  local u = context.scheme.palette.unified ---@type stl.t.theme.IUnifiedPalette

  local bg = t and c.none or c.bg ---@type string

  ---@type table<string, stl.t.theme.IHlgroup>
  local hlgroup_map = {
    ---Completion
    ComplHint = { fg = c.terminal_black },
    ComplHintMore = { fg = c.orange, italic = true },

    Added = { fg = c.green },
    Bold = { bold = true, fg = c.fg },
    Boolean = { fg = c.orange },
    Builtin = { fg = c.blue1 },
    Changed = { fg = c.yellow },
    Character = { fg = c.green },
    ColorColumn = { bg = c.black },
    Comment = { fg = c.comment, italic = true },
    Conceal = { fg = c.dark5 },
    Conditional = { fg = c.magenta },
    Constant = { fg = c.orange },
    CurSearch = { bg = c.red, fg = c.bg_dark },
    Cursor = { fg = c.bg, bg = c.fg },
    CursorColumn = { bg = c.bg_highlight },
    CursorLine = { bg = c.bg_highlight },
    CursorLineNr = { fg = c.orange, bold = true },
    Debug = { fg = c.orange },
    Define = { fg = c.cyan },
    Delimiter = { fg = c.blue5 },
    DevIconDefault = { fg = c.red },
    Diagnostic_ERROR = { fg = c.red },
    Diagnostic_HINT = { fg = c.hint },
    Diagnostic_INFO = { fg = c.info },
    Diagnostic_WARN = { fg = c.warning },
    DiagnosticError = { fg = c.red },
    DiagnosticFloatingError = { fg = c.red },
    DiagnosticFloatingHint = { fg = c.hint },
    DiagnosticFloatingInfo = { fg = c.info },
    DiagnosticFloatingOk = { fg = c.green },
    DiagnosticFloatingWarn = { fg = c.warning },
    DiagnosticHint = { fg = c.hint },
    DiagnosticInfo = { fg = c.info },
    DiagnosticOk = { fg = c.green },
    DiagnosticSignError = { fg = c.red },
    DiagnosticSignHint = { fg = c.hint },
    DiagnosticSignInfo = { fg = c.info },
    DiagnosticSignOk = { fg = c.green },
    DiagnosticSignWarn = { fg = c.warning },
    DiagnosticUnderlineError = { undercurl = true, sp = c.red },
    DiagnosticUnderlineHint = { undercurl = true, sp = c.hint },
    DiagnosticUnderlineInfo = { undercurl = true, sp = c.info },
    DiagnosticUnderlineWarn = { undercurl = true, sp = c.warning },
    DiagnosticVirtualTextError = { fg = c.red, bg = t and c.none or cs.mix(c.bg, c.red, 12) },
    DiagnosticVirtualTextHint = { fg = c.hint, bg = t and c.none or cs.mix(c.bg, c.hint, 12) },
    DiagnosticVirtualTextInfo = { fg = c.info, bg = t and c.none or cs.mix(c.bg, c.info, 12) },
    DiagnosticVirtualTextWarn = { fg = c.warning, bg = t and c.none or cs.mix(c.bg, c.warning, 12) },
    DiagnosticVirtualTextOk = { fg = c.green, bg = t and c.none or cs.mix(c.bg, c.green, 12) },
    DiagnosticVirtualLinesError = { fg = c.red, bg = t and c.none or cs.mix(c.bg, c.red, 12), italic = true },
    DiagnosticVirtualLinesHint = { fg = c.hint, bg = t and c.none or cs.mix(c.bg, c.hint, 12), italic = true },
    DiagnosticVirtualLinesInfo = { fg = c.info, bg = t and c.none or cs.mix(c.bg, c.info, 12), italic = true },
    DiagnosticVirtualLinesWarn = { fg = c.warning, bg = t and c.none or cs.mix(c.bg, c.warning, 12), italic = true },
    DiagnosticVirtualLinesOk = { fg = c.green, bg = t and c.none or cs.mix(c.bg, c.green, 12), italic = true },
    DiagnosticWarn = { fg = c.warning },
    DiffAdd = { bg = cs.mix(bg, c.green, 18) },
    DiffAddLeft = { bg = cs.mix(bg, c.red, 30) },
    DiffAddRight = { bg = cs.mix(bg, c.green, 30) },
    DiffAdded = { fg = c.green },
    DiffChange = { bg = cs.mix(bg, c.blue, 7) },
    DiffChanged = { fg = c.blue },
    DiffDelLeft = { bg = cs.mix(bg, c.red, 30) },
    DiffDelRight = { bg = cs.mix(bg, c.red, 30) },
    DiffDelete = { bg = cs.mix(bg, c.red, 18) },
    DiffFile = { fg = c.blue },
    DiffIndexLine = { fg = c.magenta },
    DiffLine = { fg = c.comment },
    DiffModLeft = { bg = cs.mix(bg, c.red, 30) },
    DiffModRight = { bg = cs.mix(bg, c.green, 30) },
    DiffNewFile = { fg = c.blue1 },
    DiffOldFile = { fg = c.blue1 },
    DiffRemoved = { fg = c.red },
    DiffText = { bg = cs.mix(bg, c.blue, 30) },
    DiffWordLeft = { bg = cs.mix(bg, c.red, 60) },
    DiffWordRight = { bg = cs.mix(bg, c.green, 60) },
    Directory = { fg = c.blue, bold = true },
    Done = { fg = c.orange, bold = true, italic = true },
    EndOfBuffer = { fg = c.bg },
    Error = { fg = c.red },
    ErrorMsg = { fg = c.red, bold = true, italic = true },
    Exception = { fg = c.magenta },
    Float = { fg = c.orange },
    FloatActiveBorder = { link = t and "ms_b_bg0" or "ms_b_none" },
    FloatActiveTitle = { link = "ms_b_bg0" },
    FloatBorder = { fg = c.border_highlight, bg = t and c.bg_dark or c.none, blend = t and 50 or 0 },
    FloatNormal = { fg = c.fg, bg = t and c.bg_dark or c.none },
    FloatTitle = { fg = c.border_highlight, bg = t and c.bg_dark or c.none },
    FoldColumn = { fg = c.comment },
    Folded = { fg = c.blue, bg = c.fg_gutter },
    Function = { fg = c.blue },
    healthError = { fg = c.red },
    healthSuccess = { fg = c.green1 },
    healthWarning = { fg = c.warning },
    iCursor = { fg = c.bg, bg = c.fg },
    Identifier = { fg = c.magenta },
    IncSearch = { bg = c.orange, fg = c.black },
    Include = { fg = c.magenta },
    Italic = { italic = true, fg = c.fg },
    Keyword = { fg = c.cyan },
    Label = { fg = c.blue },
    lCursor = { fg = c.bg, bg = c.fg },
    LineNr = { fg = c.fg_gutter },
    LspCodeLens = { fg = c.comment },
    LspInlayHint = { fg = c.dark3, bg = cs.mix(c.bg, c.blue7, 10), blend = t and 50 or 0 },
    LspReferenceRead = { bg = c.fg_gutter, bold = true, underline = true },
    LspReferenceText = { bg = c.fg_gutter, bold = true, underline = true },
    LspReferenceWrite = { bg = c.fg_gutter, bold = true, underline = true },
    LspSignatureActiveParameter = { bg = c.bg_visual, bold = true },
    Macro = { fg = c.cyan },
    MatchParen = { fg = c.orange, bg = c.fg_gutter, bold = true },
    MatchWord = { fg = c.fg, bg = c.fg_gutter },
    Member = { fg = c.blue },
    Method = { fg = c.blue },
    ModeMsg = { fg = c.fg_dark, bold = true },
    MoreMsg = { fg = c.blue },
    MsgArea = { link = "Normal" },
    NonText = { fg = cs.mix(bg, c.dark3, 45), italic = true },
    Normal = { fg = c.fg, bg = u.bg0, blend = t and 50 or 0 },
    NormalFloat = { fg = c.fg, bg = c.bg_dark },
    NormalNC = { fg = c.fg, bg = u.bg1, blend = t and 50 or 0 },
    Number = { fg = c.orange },
    NvimInternalError = { fg = c.red },
    Operator = { fg = c.blue5 },
    Parameter = { fg = c.blue },
    Pmenu = { fg = c.fg, bg = c.bg_dark },
    PmenuMatch = { fg = c.blue1 },
    PmenuMatchSel = { fg = c.yellow, bold = true },
    PmenuSbar = { bg = cs.mix(c.bg_dark, c.fg_gutter, 5) },
    PmenuSel = { bg = cs.mix(c.bg_dark, c.fg_gutter, 80), bold = true },
    PmenuThumb = { bg = c.fg_gutter },
    PreCondit = { fg = c.cyan },
    PreProc = { fg = c.cyan },
    Question = { fg = c.blue },
    QuickFixLine = { bg = c.bg_visual, bold = true },
    Removed = { fg = c.red },
    RenamerBorder = { link = t and "ms_b_bg0" or "ms_b_none" },
    RenamerTitle = { link = t and "ms_b_bg0" or "ms_b_none" },
    Repeat = { fg = c.magenta },
    Search = { bg = cs.change_hex_lightness(c.blue2, -30), fg = c.fg },
    SignColumn = { fg = c.fg_gutter },
    Special = { fg = c.blue1 },
    SpecialChar = { fg = c.blue1 },
    SpecialKey = { link = "NonText" },
    SpellBad = { undercurl = true, sp = c.red },
    SpellCap = { undercurl = true, sp = c.warning },
    SpellLocal = { undercurl = true, sp = c.info },
    SpellRare = { undercurl = true, sp = c.hint },
    Statement = { fg = c.magenta },
    StatusColumnMark = { link = "DiagnosticHint", default = true },
    StatusLine = { fg = c.fg_sidebar, bg = c.bg_dark, blend = t and 50 or 0 },
    StatusLineNC = { fg = c.fg_gutter, bg = c.bg_dark, blend = t and 50 or 0 },
    StorageClass = { fg = c.cyan },
    String = { fg = c.green },
    Structure = { fg = c.blue1 },
    Substitute = { bg = c.red, fg = c.black },
    TabLine = { bg = c.bg_dark, fg = c.fg_gutter },
    TabLineFill = { bg = c.black, blend = t and 50 or 0 },
    TabLineSel = { link = "Normal" },
    Tag = { fg = c.blue, bold = true },
    Title = { fg = c.blue, bold = true },
    Todo = { fg = c.bg, bg = c.yellow, bold = true },
    TooLong = { fg = c.red },
    Type = { fg = c.blue1 },
    Typedef = { fg = c.blue1 },
    Variable = { fg = c.fg },
    UnderLined = { underline = true },
    vCursor = { fg = c.bg, bg = c.fg },
    Visual = { bg = c.bg_visual, bold = true },
    VisualNOS = { bg = c.bg_visual, bold = true },
    WarningMsg = { fg = c.warning },
    Whitespace = { fg = c.fg_gutter },
    WildMenu = { bg = c.bg_visual },
    WinBar = { fg = c.fg, bg = u.bg0 },
    WinBarNC = { fg = c.fg, bg = u.bg1 },
    WinSeparator = { fg = c.fg_gutter, blend = t and 50 or 0 },
  }

  return hlgroup_map
end

return M
