# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# gruvbox-light

[delta]
hunk-header-style             = raw
hunk-header-decoration-style  = ul
hyperlinks                    = true
hyperlinks-file-link-format   = file://{path}:{line}
detect-dark-light             = auto
line-numbers                  = true
navigate                      = true    # use n and N to move between diff sections
paging                        = never
side-by-side                  = true

light                         = true
syntax-theme                  = gruvbox-light
plus-style                    = syntax "#E8E6B0"
plus-emph-style               = syntax "#D3D192" bold
plus-non-emph-style           = syntax auto
minus-style                   = syntax "#FCC19F"
minus-emph-style              = syntax "#EB9D82" bold
minus-non-emph-style          = syntax auto
true-color                    = always

