git:
  commit:
    signOff: false
  log:
    order: topo-order
    showGraph: "always"
    showWholeGraph: false
  mainBranches:
    - main
    - master
  paging:
    # cargo install git-delta
    colorArg: always
    useConfig: false
    pager: delta --paging=never
  autoFetch: false
  autoRefresh: true
  fetchAll: false
  ignoreWhitespaceInDiffView: false
  parseEmoji: true
  skipHookPrefix: WIP
gui:
  authorColors:
    guanghechen: blue
    "*": white
  branchColors:
    main: blue
  spiner:
    frames:
      - ⣾
      - ⣽
      - ⣻
      - ⢿
      - ⡿
      - ⣟
      - ⣯
      - ⣷
  theme:
    defaultFgColor:
      - default
    activeBorderColor:
      - magenta
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - yellow
    selectedLineBgColor:
      - white
    cherryPickedCommitFgColor:
      - blue
    cherryPickedCommitBgColor:
      - cyan
    markedBaseCommitFgColor:
      - green
    markedBaseCommitBgColor:
      - magenta
    searchingActiveBorderColor:
      - blue
    unstagedChangesColor:
      - red
  border: "rounded"
  expandFocusedSidePanel: false
  language: 'en'
  mainPanelSplitMode: flexible
  mouseEvents: true
  nerdFontsVersion: "3"
  showBottomLine: false
  showCommandLog: true
  showFileTree: true
  showIcons: true
  showRandomTip: true
  skipAmendWarning: false
  skipDiscardChangeWarning: false
  skipStashWarning: false
  skipNoStagedFilesWarning: false
  skipRewordInEditorWarning: false
  splitDiff: auto
  tabWidth: 2
  useHunkModeInStagingView: true
  wrapLinesInStagingView: false
notARepository: skip
os:
  edit: "nvim"
  editAtLine: "nvim --line={{line}} {{filename}}"
  editAtLineAndWait: "nvim --block --line={{line}} {{filename}}"
  editInTerminal: true
  editPreset: "nvim-remote"
  openDirInEditor: "nvim {{dir}}"
keybinding:
  universal:
    nextBlock-alt2: <disabled>
    prevBlock-alt2: <disabled>
    nextScreenMode: <tab>
    prevScreenMode: <backtab>
  main:
    toggleSelectHunk: '`'
promptToReturnFromSubprocess: false
