# font
font_size                     15
font_family                   family="Maple Mono NF CN" style="Light"
bold_font                     family="Maple Mono NF CN" style="Bold" 
italic_font                   family="Maple Mono NF CN" style="Italic"
bold_italic_font              family="Maple Mono NF CN" style="Bold Italic"

font_features                 MapleMono-NF-CN-Light         +cv01 +ss02 +ss04 +ss05 +zero
font_features                 MapleMono-NF-CN-Bold          +cv01 +ss02 +ss04 +ss05 +zero
font_features                 MapleMono-NF-CN-MediumItalic  +cv01 +ss02 +ss04 +ss05 +zero
font_features                 MapleMono-NF-CN-BoldItalic    +cv01 +ss02 +ss04 +ss05 +zero

border_style                  normal
disable_ligatures             cursor
modify_font                   cell_width  100%
modify_font                   cell_height 101%
symbol_map                    U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A3,U+E0B0-U+E0C8,U+E0CA,U+E0CC-U+E0D2,U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E634,U+E700-U+E7C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F32F,U+F400-U+F4A9,U+F500-U+F8FF Symbols Nerd Font Mono
text_composition_strategy     platform
