[font]
size = 14

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font."bold_italic"]
family = "RobotoMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "RobotoMono Nerd Font"
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

# Offset is the extra space around each character.
# `offset.y` can be thought of as modifying the line spacing, and `offset.x` as modifying the letter spacing.
[font.offset]
x = 0
y = 0

# Glyph offset determines the locations of the glyphs within their cells with the default being at the bottom.
# Increasing `x` moves the glyph to the right, increasing `y` moves the glyph upwards.
[font.glyph_offset]
x = 0
y = 0
