[font]
builtin_box_drawing = false
size = 15
glyph_offset = { x = 0, y = 0 }
offset = { x = 0, y = 1 }

[font.bold]
family = "Maple Mono NF CN"
style = "Bold"

[font.bold_italic]
family = "Maple Mono NF CN"
style = "Bold Italic"

[font.italic]
family = "Maple Mono NF CN"
style = "Italic"

[font.normal]
family = "Maple Mono NF CN"
style = "Light"

