[delta]
  feature = customized-theme
  hunk-header-style = raw
  hunk-header-decoration-style = ul
  hyperlinks = true
  hyperlinks-file-link-format = file://{path}:{line}
  detect-dark-light = auto
  line-numbers = true
  navigate = true    # use n and N to move between diff sections
  paging = never
  side-by-side = true

[include]
  path = ~/.config/git-delta/local/theme.conf

