_G.eve = require("eve")
eve.setup_patches()
eve.setup_workspace()
require("eve.option")
require("eve.keymap")
require("integration.neovim.autocmd")

eve.setup_state({ editor = eve.get_default_storage().editor })
require("integration.neovim.keymap")

eve.setup_theme()

require("fml.command")
require("fml.dressing.hipairs")
require("fml.dressing.commentstring")
require("fml.dressing.illumniate")
require("fml.dressing.im")
require("fml.dressing.input")
require("fml.dressing.notifier")
require("fml.dressing.nvimbar.statusline")
require("fml.dressing.nvimbar.tabline")
require("fml.dressing.nvimbar.winline")
require("fml.dressing.python_venv")
require("fml.dressing.select")
require("fml.dressing.winsep")

require("ghc.command")
