_G.eve = require("eve")
eve.setup_patches()
eve.setup_workspace()
require("eve.option")
require("eve.keymap")
require("integration.neovim.autocmd")

eve.setup_state({ editor = eve.get_default_storage().editor })
require("integration.neovim.keymap")

require("fml.dressing.notifier")
require("fml.dressing.ui_attach")
require("fml.dressing.nvimbar.statusline")
require("fml.dressing.nvimbar.tabline")
require("fml.dressing.nvimbar.winline")
eve.setup_theme()

require("fml.command")
require("ghc.command")

vim.schedule(function()
  require("fml.dressing.clipboard")
  require("fml.dressing.commentstring")
  require("fml.dressing.foldexpr")
  require("fml.dressing.hipairs")
  require("fml.dressing.illumniate")
  require("fml.dressing.im")
  require("fml.dressing.indentline")
  require("fml.dressing.input")
  require("fml.dressing.python_venv")
  require("fml.dressing.select")
  require("fml.dressing.winsep")
end)
