# Key bindings
# A list with all available `key` names can be found here:
# https://docs.rs/glutin/*/glutin/enum.VirtualKeyCode.html#variants
#
# Run "xxd -psd" to find hex codes of keys.
#
# Alacritty + Tmux key integratio
#   `\u0002` is `C-b` as tmux prefix
#   `\u001b` is `Esc`

[mouse]
bindings = [
  { mouse = "Left",     mods = "Control",                   action = "Open" },
]

[keyboard]
bindings = [
  # ----- Unbind keys ----
  { key = "F1",                                             action = "None" },
  { key = "F2",                                             action = "None" },
  { key = "F3",                                             action = "None" },
  { key = "F4",                                             action = "None" },
  { key = "F5",                                             action = "None" },
  { key = "F6",                                             action = "None" },
  { key = "F7",                                             action = "None" },
  { key = "F8",                                             action = "None" },
  { key = "F9",                                             action = "None" },
  { key = "F10",                                            action = "None" },
  { key = "F11",                                            action = "None" },
  { key = "F12",                                            action = "None" },
  { key = "F1",         mods = "Shift",                     action = "None" },
  { key = "F2",         mods = "Shift",                     action = "None" },
  { key = "F3",         mods = "Shift",                     action = "None" },
  { key = "F4",         mods = "Shift",                     action = "None" },
  { key = "F5",         mods = "Shift",                     action = "None" },
  { key = "F6",         mods = "Shift",                     action = "None" },
  { key = "F7",         mods = "Shift",                     action = "None" },
  { key = "F8",         mods = "Shift",                     action = "None" },
  { key = "F9",         mods = "Shift",                     action = "None" },
  { key = "F10",        mods = "Shift",                     action = "None" },
  { key = "F11",        mods = "Shift",                     action = "None" },
  { key = "F12",        mods = "Shift",                     action = "None" },
  { key = "A",          mods = "Command",                   action = "None" },
  { key = "B",          mods = "Command",                   action = "None" },
  { key = "C",          mods = "Command",                   action = "None" },
  { key = "D",          mods = "Command",                   action = "None" },
  { key = "E",          mods = "Command",                   action = "None" },
  { key = "F",          mods = "Command",                   action = "None" },
  { key = "G",          mods = "Command",                   action = "None" },
  { key = "H",          mods = "Command",                   action = "None" },
  { key = "I",          mods = "Command",                   action = "None" },
  { key = "J",          mods = "Command",                   action = "None" },
  { key = "K",          mods = "Command",                   action = "None" },
  { key = "L",          mods = "Command",                   action = "None" },
  { key = "M",          mods = "Command",                   action = "None" },
  { key = "N",          mods = "Command",                   action = "None" },
  { key = "O",          mods = "Command",                   action = "None" },
  { key = "P",          mods = "Command",                   action = "None" },
  { key = "Q",          mods = "Command",                   action = "None" },
  { key = "R",          mods = "Command",                   action = "None" },
  { key = "S",          mods = "Command",                   action = "None" },
  { key = "T",          mods = "Command",                   action = "None" },
  { key = "U",          mods = "Command",                   action = "None" },
  { key = "V",          mods = "Command",                   action = "None" },
  { key = "W",          mods = "Command",                   action = "None" },
  { key = "X",          mods = "Command",                   action = "None" },
  { key = "Y",          mods = "Command",                   action = "None" },
  { key = "Z",          mods = "Command",                   action = "None" },
  { key = "A",          mods = "Command|Shift",             action = "None" },
  { key = "B",          mods = "Command|Shift",             action = "None" },
  { key = "C",          mods = "Command|Shift",             action = "None" },
  { key = "D",          mods = "Command|Shift",             action = "None" },
  { key = "E",          mods = "Command|Shift",             action = "None" },
  { key = "F",          mods = "Command|Shift",             action = "None" },
  { key = "G",          mods = "Command|Shift",             action = "None" },
  { key = "H",          mods = "Command|Shift",             action = "None" },
  { key = "I",          mods = "Command|Shift",             action = "None" },
  { key = "J",          mods = "Command|Shift",             action = "None" },
  { key = "K",          mods = "Command|Shift",             action = "None" },
  { key = "L",          mods = "Command|Shift",             action = "None" },
  { key = "M",          mods = "Command|Shift",             action = "None" },
  { key = "N",          mods = "Command|Shift",             action = "None" },
  { key = "O",          mods = "Command|Shift",             action = "None" },
  { key = "P",          mods = "Command|Shift",             action = "None" },
  { key = "Q",          mods = "Command|Shift",             action = "None" },
  { key = "R",          mods = "Command|Shift",             action = "None" },
  { key = "S",          mods = "Command|Shift",             action = "None" },
  { key = "T",          mods = "Command|Shift",             action = "None" },
  { key = "U",          mods = "Command|Shift",             action = "None" },
  { key = "V",          mods = "Command|Shift",             action = "None" },
  { key = "W",          mods = "Command|Shift",             action = "None" },
  { key = "X",          mods = "Command|Shift",             action = "None" },
  { key = "Y",          mods = "Command|Shift",             action = "None" },
  { key = "Z",          mods = "Command|Shift",             action = "None" },

  # ----- Alacritty keys ----
  { key = "V",          mods = "Command",                   action = "Paste"       },
  { key = "Insert",     mods = "Control",                   action = "Copy"        },
  { key = "Insert",     mods = "Shift",                     action = "Paste"       },
  { key = "F",          mods = "Command|Control|Shift",     action = "ToggleFullscreen" },
  { key = "N",          mods = "Command|Control|Shift",     action = "CreateNewWindow" },
  { key = "V",          mods = "Command|Control|Shift",     action = "ToggleViMode" },
  { key = "W",          mods = "Command|Control|Shift",     action = "Quit" },
  { key = "Z",          mods = "Command|Control|Shift",     action = "ToggleSimpleFullscreen" },
  { key = ")",          mods = "Command|Control|Shift",     action = "ResetFontSize" },
  { key = "Plus",       mods = "Command|Control|Shift",     action = "IncreaseFontSize" },
  { key = "_",          mods = "Command|Control|Shift",     action = "DecreaseFontSize" },

  # ----- tmux -----
  { key = "R",          mods = "Command",                   chars = "\u0002\u0072" },       # <Ctrl-b>r
  { key = "S",          mods = "Command",                   chars = "\u0002\u0072" },       # <Ctrl-b>s
  { key = "D",          mods = "Command|Shift",             chars = "\u0002\u0044" },       # <Ctrl-b>D
  { key = "S",          mods = "Command|Shift",             chars = "\u0002\u0053" },       # <Ctrl-b>S

  ## ---- Create ----
  { key = "N",          mods = "Command|Control",           chars = "\u0002\u000e" },       # <Ctrl-b><Ctrl-n>
  { key = "J",          mods = "Command|Control",           chars = "\u0002\u000a" },       # <Ctrl-b><Ctrl-j>
  { key = "L",          mods = "Command|Control",           chars = "\u0002\u000c" },       # <Ctrl-b><Ctrl-l>

  ## ---- Join ----
  { key = "B",          mods = "Command|Control",           chars = "\u0002\u0002" },       # <Ctrl-b><Ctrl-b>

  ## ---- Kill ----
  { key = "O",          mods = "Command|Control",           chars = "\u0002\u000f" },       # <Ctrl-b><Ctrl-o>
  { key = "W",          mods = "Command|Control",           chars = "\u0002\u0017" },       # <Ctrl-b><Ctrl-w>
  { key = "P",          mods = "Command|Control",           chars = "\u0002\u0010" },       # <Ctrl-b><Ctrl-p>

  ## ---- Resize ----
  { key = "Up",         mods = "Command|Control",           chars = "\u0002\u001b[1;5A" },  # <Ctrl-b><Ctrl-Up>
  { key = "Right",      mods = "Command|Control",           chars = "\u0002\u001b[1;5C" },  # <Ctrl-b><Ctrl-Right>
  { key = "Down",       mods = "Command|Control",           chars = "\u0002\u001b[1;5B" },  # <Ctrl-b><Ctrl-Down> 
  { key = "Left",       mods = "Command|Control",           chars = "\u0002\u001b[1;5D" },  # <Ctrl-b><Ctrl-Left>
  { key = "Z",          mods = "Command|Control",           chars = "\u0002\u001a" },       # <Ctrl-b><Ctrl-z>

  ## ---- Swap ----
  { key = "K",          mods = "Command|Shift",             chars = "\u0002\u004b" },       # <Ctrl-b>K
  { key = "L",          mods = "Command|Shift",             chars = "\u0002\u004C" },       # <Ctrl-b>L
  { key = "J",          mods = "Command|Shift",             chars = "\u0002\u004a" },       # <Ctrl-b>J
  { key = "H",          mods = "Command|Shift",             chars = "\u0002\u0048" },       # <Ctrl-b>H
  { key = "T",          mods = "Command|Shift",             chars = "\u0002\u0054" },       # <Ctrl-b>T
  { key = "{",          mods = "Command|Shift",             chars = "\u0002\u007b" },       # <Ctrl-b>{
  { key = "}",          mods = "Command|Shift",             chars = "\u0002\u007d" },       # <Ctrl-b>}
  { key = "<",          mods = "Command|Shift",             chars = "\u0002\u003c" },       # <Ctrl-b><
  { key = ">",          mods = "Command|Shift",             chars = "\u0002\u003e" },       # <Ctrl-b>>

  ## ---- Focus ----
  { key = "Key1",       mods = "Command",                   chars = "\u0002\u0031" },       # <Ctrl-b>1
  { key = "Key2",       mods = "Command",                   chars = "\u0002\u0032" },       # <Ctrl-b>2
  { key = "Key3",       mods = "Command",                   chars = "\u0002\u0033" },       # <Ctrl-b>3
  { key = "Key4",       mods = "Command",                   chars = "\u0002\u0034" },       # <Ctrl-b>4
  { key = "Key5",       mods = "Command",                   chars = "\u0002\u0035" },       # <Ctrl-b>5
  { key = "Key6",       mods = "Command",                   chars = "\u0002\u0036" },       # <Ctrl-b>6
  { key = "Key7",       mods = "Command",                   chars = "\u0002\u0037" },       # <Ctrl-b>7
  { key = "Key8",       mods = "Command",                   chars = "\u0002\u0038" },       # <Ctrl-b>8
  { key = "Key9",       mods = "Command",                   chars = "\u0002\u0039" },       # <Ctrl-b>9
  { key = "Key0",       mods = "Command",                   chars = "\u0002\u0030" },       # <Ctrl-b>0
  { key = "[",          mods = "Command",                   chars = "\u0002\u005b" },       # <Ctrl-b>[
  { key = "]",          mods = "Command",                   chars = "\u0002\u005d" },       # <Ctrl-b>]
  { key = "K",          mods = "Command",                   chars = "\u0002\u006b" },       # <Ctrl-b>k
  { key = "L",          mods = "Command",                   chars = "\u0002\u006c" },       # <Ctrl-b>l
  { key = "J",          mods = "Command",                   chars = "\u0002\u006a" },       # <Ctrl-b>j
  { key = "H",          mods = "Command",                   chars = "\u0002\u0068" },       # <Ctrl-b>h

  ## ---- Misc ----
  { key = "Enter",      mods = "Command",                   chars = "\u001b\u000d" },       # <alt-cr>
  { key = "A",          mods = "Command",                   chars = "\u0002\u0061" },       # <Ctrl-b>a
  { key = "C",          mods = "Command",                   chars = "\u0002\u0063" },       # <Ctrl-b>c
  { key = "G",          mods = "Command",                   chars = "\u0002\u0067" },       # <Ctrl-b>g
  { key = "I",          mods = "Command",                   chars = "\u0002\u0069" },       # <Ctrl-b>i
  { key = "O",          mods = "Command",                   chars = "\u0002\u006f" },       # <Ctrl-b>o
  { key = "T",          mods = "Command",                   chars = "\u0002\u0074" },       # <Ctrl-b>t
  { key = ":",          mods = "Command|Shift",             chars = "\u0002\u003a" },       # <Ctrl-b>:

  ## ---- Preserved ----
  { key = "Key1",       mods = "Command|Control",           chars = "\u0002\u001b[49;5u" }, # <Ctrl-b><Ctrl-1>
  { key = "Key2",       mods = "Command|Control",           chars = "\u0002\u001b[50;5u" }, # <Ctrl-b><Ctrl-2>
  { key = "Key3",       mods = "Command|Control",           chars = "\u0002\u001b[51;5u" }, # <Ctrl-b><Ctrl-3>
  { key = "Key4",       mods = "Command|Control",           chars = "\u0002\u001b[52;5u" }, # <Ctrl-b><Ctrl-4>
  { key = "Key5",       mods = "Command|Control",           chars = "\u0002\u001b[53;5u" }, # <Ctrl-b><Ctrl-5>
  { key = "Key6",       mods = "Command|Control",           chars = "\u0002\u001b[54;5u" }, # <Ctrl-b><Ctrl-6>
  { key = "Key7",       mods = "Command|Control",           chars = "\u0002\u001b[55;5u" }, # <Ctrl-b><Ctrl-7>
  { key = "Key8",       mods = "Command|Control",           chars = "\u0002\u001b[56;5u" }, # <Ctrl-b><Ctrl-8>
  { key = "Key9",       mods = "Command|Control",           chars = "\u0002\u001b[57;5u" }, # <Ctrl-b><Ctrl-9>
  { key = "Key0",       mods = "Command|Control",           chars = "\u0002\u001b[48;5u" }, # <Ctrl-b><Ctrl-0>
  { key = "Up",         mods = "Command",                   chars = "\u0002\u001b[A" },     # <Ctrl-b><Up>
  { key = "Right",      mods = "Command",                   chars = "\u0002\u001b[C" },     # <Ctrl-b><Right>
  { key = "Down",       mods = "Command",                   chars = "\u0002\u001b[B" },     # <Ctrl-b><Down>
  { key = "Left",       mods = "Command",                   chars = "\u0002\u001b[D" },     # <Ctrl-b><Left>
]

