#:schema https://yazi-rs.github.io/schemas/keymap.json

[mgr]
prepend_keymap = [
  { on = ["c", "m"], run = "plugin chmod", desc = "Change permissions" },
  { on = ["g", "?"], run = "help", desc = "Open help" },
  { on = ["g", "i"], run = "cd --interactive", desc = "Jump interactively" },

  { on = "R", run = "bulk_rename", desc = "Bulk rename selected files" },

  { on = "<C-k>", run = "seek -1", desc = "Seek preview up" },
  { on = "<C-j>", run = "seek 1", desc = "Seek preview down" },
  { on = "K", run = "spot", desc = "Spot hovered file" },

  { on = ["s", "f"], run = "search --via=fd", desc = "Search files by name" },
  { on = ["s", "s"], run = "search --via=rg", desc = "Search files by content" },

  { on = "!", run = 'shell "$SHELL" --block', desc = "Open shell here" },

  { on = ["t", "d"], run = "tab_close", desc = "Close current tab" },
  { on = ["t", "1"], run = "tab_switch 0", desc = "Switch to tab 1" },
  { on = ["t", "2"], run = "tab_switch 1", desc = "Switch to tab 2" },
  { on = ["t", "3"], run = "tab_switch 2", desc = "Switch to tab 3" },
  { on = ["t", "4"], run = "tab_switch 3", desc = "Switch to tab 4" },
  { on = ["t", "5"], run = "tab_switch 4", desc = "Switch to tab 5" },
  { on = ["t", "6"], run = "tab_switch 5", desc = "Switch to tab 6" },
  { on = ["t", "7"], run = "tab_switch 6", desc = "Switch to tab 7" },
  { on = ["t", "8"], run = "tab_switch 7", desc = "Switch to tab 8" },
  { on = ["t", "9"], run = "tab_switch 8", desc = "Switch to tab 9" },
  { on = ["t", "0"], run = "tab_switch 9", desc = "Switch to tab 10" },
  { on = ["t", ","], run = "tab_switch -1 --relative", desc = "Switch to previous tab" },
  { on = ["t", "."], run = "tab_switch 1 --relative", desc = "Switch to next tab" },
  { on = ["t", "<"], run = "tab_swap -1", desc = "Swap tab left" },
  { on = ["t", ">"], run = "tab_swap 1", desc = "Swap tab right" },
  { on = ["t", "["], run = "tab_switch -1 --relative", desc = "Switch to previous tab" },
  { on = ["t", "]"], run = "tab_switch 1 --relative", desc = "Switch to next tab" },
  { on = ["t", "{"], run = "tab_swap -1", desc = "Swap tab left" },
  { on = ["t", "}"], run = "tab_swap 1", desc = "Swap tab right" },

  { on = "z", run = "plugin zoxide", desc = "Jump to a directory via zoxide" },
  { on = "Z", run = "plugin fzf", desc = "Jump via fzf" },
]

[help]
prepend_keymap = [
  { on = ["g", "g"], run = "arrow top", desc = "Go to top" },
  { on = "G", run = "arrow bot", desc = "Go to bottom" },
]
