# Includes
include keymap.conf
include font.conf
include local/theme.conf

# General
allow_remote_control          no
click_interval                -1.0
copy_on_select                yes
detect_urls                   yes
enable_audio_bell             no
sync_to_monitor               no

# Background
background_blur               32
background_image_layout       scaled
background_image_linear       no
background_opacity            1.0
background_tint               1.0
dynamic_background_opacity    no

# Cursor
cursor_trail                  20
cursor_trail_start_threshold  10
cursor_trail_decay            0.0 0.3
cursor_blink_interval         0
mouse_hide_wait               0.5
# cursor none  # Uncomment this if you want no cursor

# Scroll
scrollback_lines              10000
touch_scroll_multiplier       2.0

# Tabline
tab_bar_align                 left
tab_bar_edge                  top
tab_bar_min_tabs              2
tab_bar_style                 powerline
tab_powerline_style           slanted
tab_separator                 " "
tab_title_template            "{title} | {index}"


# Window
enabled_layouts               splits,stack
hide_window_decorations       titlebar-only
initial_window_height         1000
initial_window_width          1600
placement_strategy            top-left
remember_window_size          yes
window_padding_width          0

