include local/theme.conf
include keymap.conf

# font
font_size 15
font_family "RobotoMono Nerd Font"
bold_font "RobotoMono Nerd Font Bold"
bold_italic_font "RobotoMono Nerd Font BoldItalic"
italic_font "RobotoMono Nerd Font Italic"

# Letter and line spacing
letter_spacing 0.0
line_spacing 0.0

# window
background_opacity 0.8
background_blur 30
hide_window_decorations titlebar-only
remember_window_size yes
window_padding_width 0
