# Includes
include keymap.conf
include font.conf
include local/theme.conf

# General
sync_to_monitor               no
detect_urls                   yes
copy_on_select                yes
enable_audio_bell             no

# Background
background_blur               0
background_image_layout       scaled
background_image_linear       no
background_opacity            1.0
background_tint               1.0
dynamic_background_opacity    no

# Cursor
cursor_blink_interval         0
cursor_trail                  3
cursor_trail_decay            0.1 0.4
# cursor none  # Uncomment this if you want no cursor

# Scroll
scrollback_lines              10000
touch_scroll_multiplier       2.0

# Tabline
tab_bar_edge                  top
tab_bar_style                 powerline
tab_powerline_style           slanted
tab_separator                 " "

# Window
hide_window_decorations       titlebar-only
initial_window_height         1000
initial_window_width          1600
remember_window_size          yes
window_padding_width          0

