# Shader

## cursor
custom-shader = shaders/cursor.glsl
custom-shader-animation = true

## background (dark)
# custom-shader = shaders/dark/cubes.glsl
# custom-shader = shaders/dark/fireworks-rockets.glsl
# custom-shader = shaders/dark/gears-and-belts.glsl
# custom-shader = shaders/dark/inside-the-matrix.glsl
# custom-shader = shaders/dark/matrix-hallway.glsl
# custom-shader = shaders/dark/mnoise.glsl
# custom-shader = shaders/dark/neuro-noise.glsl
# custom-shader = shaders/dark/sparks-from-fire.glsl
# custom-shader = shaders/dark/starfield.glsl

## background (light)
# custom-shader = shaders/light/cubes.glsl
# custom-shader = shaders/light/fireworks-rockets.glsl
# custom-shader = shaders/light/gears-and-belts.glsl
# custom-shader = shaders/light/inside-the-matrix.glsl
# custom-shader = shaders/light/matrix-hallway.glsl
# custom-shader = shaders/light/mnoise.glsl
# custom-shader = shaders/light/neuro-noise.glsl
# custom-shader = shaders/light/sparks-from-fire.glsl
# custom-shader = shaders/light/starfield.glsl
