# Shader

## cursor
custom-shader = shaders/cursor.glsl
custom-shader-animation = true

## background (dark)
# custom-shader = shaders/cubes.glsl
# custom-shader = shaders/fireworks-rockets.glsl
# custom-shader = shaders/gears-and-belts.glsl
# custom-shader = shaders/inside-the-matrix.glsl
# custom-shader = shaders/matrix-hallway.glsl
# custom-shader = shaders/mnoise.glsl
# custom-shader = shaders/sparks-from-fire.glsl
# custom-shader = shaders/starfield.glsl

## background (light)
# custom-shader = shaders/cubes-light.glsl
# custom-shader = shaders/inside-the-matrix-light.glsl
