## General
set     -g  default-command             "$SHELL -l"
set     -g  default-terminal            'tmux-256color'
set     -g  extended-keys-format        csi-u
set     -sg extended-keys               on
set     -sa terminal-features           ',*:RGB'
set     -sa terminal-overrides          ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set     -sa terminal-overrides          ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colors - needs tmux-3.0

set     -g  mode-keys                   vi
set     -g  status-keys                 vi

set     -g  mouse                       on      # Enable Mouse mode (scrolling, etc).
set     -g  set-clipboard               on

setw    -g  xterm-keys                  on
set     -sg repeat-time                 600     # Increase repeat timeout.
set     -s  focus-events                on
set     -sg exit-empty                  on

set -q  -g  utf8                        on      # Expect UTF-8.
set     -g  history-limit               10000   # Boost history.

## Apperance
setw    -g  automatic-rename            off     # Rename window to reflect current program.
set     -g  renumber-windows            on      # Renumber windows when a window is closed.

set     -g  set-titles                  off     # Set terminal title.
set     -g  set-titles-string           '#T'

set     -g  display-panes-time          2000    # Slightly longer pane indicators display time.
set     -g  display-time                3000    # Slightly longer status messages display time.
set     -sg escape-time                 0       # Faster command sequences.

## Activity
set     -g  monitor-activity            on
set     -g  visual-activity             off

## Bell
set     -g  bell-action                 none    # Disable visual bell in Tmux
set     -g  visual-bell                 on      # Disable flashing screen for bell

## For yazi
set     -g  allow-passthrough           on
set     -ga update-environment          TERM
set     -ga update-environment          TERM_PROGRAM

source $HOME/.config/tmux/conf/variable.tmux.conf           ## Variables
source $HOME/.config/tmux/conf/keymap-unbind.tmux.conf      ## Unbind default keymaps
source $HOME/.config/tmux/conf/keymap.tmux.conf             ## Customized keymaps

run-shell "bash $HOME/.config/tmux/script/status-load.sh"
if-shell "[ -f $HOME/.config/tmux/local/theme.tmux.conf ]" 'source $HOME/.config/tmux/local/theme.tmux.conf'
source $HOME/.config/tmux/conf/theme.tmux.conf              ## Theme

## Hooks
set-hook -g session-created "run-shell 'bash $HOME/.config/tmux/hook/session-created.sh #{session_name}'"

## Plugins
set     -g  @tpm_plugins ''
set     -ga @tpm_plugins ' tmux-plugins/tpm'
set     -ga @tpm_plugins ' tmux-plugins/tmux-resurrect'
run 'if [ "$(uname)" != "Darwin" ]; then tmux set -ga @tpm_plugins " tmux-plugins/tmux-yank"; fi'
run "$HOME/.config/tmux/plugins/tpm/tpm"

