#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config \
  active_window_opacity 1.0 \
  auto_balance off \
  bottom_padding 4 \
  display_arrangement_order default \
  external_bar off:40:0 \
  focus_follows_mouse off \
  insert_feedback_color 0xffd75f5f \
  layout bsp \
  left_padding 4 \
  menubar_opacity 1.0 \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap \
  mouse_follows_focus off \
  mouse_modifier fn \
  normal_window_opacity 0.90 \
  right_padding 4 \
  split_ratio 0.50 \
  split_type auto \
  top_padding 4 \
  window_animation_duration 0.0 \
  window_animation_easing ease_out_circ \
  window_gap 8 \
  window_insertion_point focused \
  window_opacity off \
  window_opacity_duration 0.0 \
  window_origin_display default \
  window_placement second_child \
  window_shadow on \
  window_zoom_persist on

yabai -m rule --add app="^(System Settings)" manage=off sub-layer=normal

borders active_color=0xFFF4BAE3 inactive_color=0XFF494D64 width=6.0 &

echo "yabai configuration loaded.."
