#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
linemode      = "permissions"
ratio         = [1, 3, 4]
show_hidden   = true
sort_by       = "natural"

[input]
cursor_blink = true

[open]
prepend_rules = [
  { url = "*.{pptx,ppt,docx,doc,xlsx,xls,pdf}", use = "open" },
  { mime = "video/*", use = "open" },
  { mime = "application/vnd.openxmlformats-officedocument.*", use = "open" },
  { mime = "application/vnd.ms-*", use = "open" },
  { mime = "application/msword", use = "open" },
  { mime = "application/pdf", use = "open" },
]

[opener]
edit = [
  { run = "nvim %s", desc = "nvim", for = "unix", block = true },
  { run = "nvim %s", desc = "nvim", for = "windows", block = true },
]

[plugin]
prepend_fetchers = [
  { url = "*", run = "git", prio = "normal", group = "git" },
  { url = "*/", run = "git", prio = "normal", group = "git" },
]
