require("ghc.command.buf.close")
require("ghc.command.buf.create")
require("ghc.command.buf.focus")
require("ghc.command.buf.pin")
require("ghc.command.buf.save")
require("ghc.command.buf.swap")

require("ghc.command.tab.close")
require("ghc.command.tab.create")
require("ghc.command.tab.focus")

require("ghc.command.win.close")
require("ghc.command.win.create")
require("ghc.command.win.focus")
require("ghc.command.win.history")
require("ghc.command.win.resize")

require("ghc.command.find.buffers")
require("ghc.command.find.explorer")
require("ghc.command.find.files")
require("ghc.command.find.git")
require("ghc.command.find.highlights")
require("ghc.command.find.pinned_files")
require("ghc.command.find.vim_options")

require("ghc.command.lsp.diagnostic")
require("ghc.command.lsp.reference")

require("ghc.command.search.files")

require("ghc.command.toggle.flag")
require("ghc.command.toggle.flight")
require("ghc.command.toggle.main")
require("ghc.command.toggle.theme")

require("ghc.command.copy")
require("ghc.command.debug")
require("ghc.command.lazygit")
require("ghc.command.refresh")
require("ghc.command.resume")
require("ghc.command.run")
require("ghc.command.scroll")
require("ghc.command.session")
require("ghc.command.term")
