---@class fml.t.ux.ISetting
---@field public bufnr                  integer|nil
---@field public winnr                  integer|nil
---@field public open                   fun(self: fml.t.ux.ISetting, params: fml.t.ux.setting.IOpenParams): nil
---@field public close                  fun(self: fml.t.ux.ISetting): nil

---@class fml.t.ux.setting.IOpenParams
---@field public initial_value          eve.t.T
---@field public row                    ?number
---@field public col                    ?number
---@field public width                  ?number
---@field public height                 ?number
---@field public win_cursor_row         ?integer
---@field public win_cursor_col         ?integer
