print(eve.path.is_absolute("/a/b/c"))
print(vim.inspect(eve.path.split("/a/b/c")))
print(eve.path.relative("/a/b/c", "/a/b/c/d/e.txt", true))
print(eve.path.relative("/a/b/c", "/a/b/c/e.txt", true))
print(eve.path.relative("/a/b/c", "/a/b/e.txt", true))
print(eve.path.relative("/a/b/c", "e.txt", true))
print(eve.path.relative("a/b/c", "/a/b/c/e.txt", true))
print(eve.path.normalize("a/b/c"))
print(eve.path.normalize("a/b/..//c"))
print(eve.path.normalize("/../a/../../../b/d/e/..//c"))
