vim.keymap.set("n", "<leader>1", ":BufferLineGoToBuffer 1<CR>", { noremap = true, silent = true, desc = "bufferline: Goto buffer 1" })
vim.keymap.set("n", "<leader>2", ":BufferLineGoToBuffer 2<CR>", { noremap = true, silent = true, desc = "bufferline: Goto buffer 2" })
vim.keymap.set("n", "<leader>3", ":BufferLineGoToBuffer 3<CR>", { noremap = true, silent = true, desc = "bufferline: Goto buffer 3" })
vim.keymap.set("n", "<leader>4", ":BufferLineGoToBuffer 4<CR>", { noremap = true, silent = true, desc = "bufferline: Goto buffer 4" })
vim.keymap.set("n", "<leader>5", ":BufferLineGoToBuffer 5<CR>", { noremap = true, silent = true, desc = "bufferline: Goto buffer 5" })
vim.keymap.set("n", "<leader>6", ":BufferLineGoToBuffer 6<CR>", { noremap = true, silent = true, desc = "bufferline: Goto buffer 6" })
vim.keymap.set("n", "<leader>7", ":BufferLineGoToBuffer 7<CR>", { noremap = true, silent = true, desc = "bufferline: Goto buffer 7" })
vim.keymap.set("n", "<leader>8", ":BufferLineGoToBuffer 8<CR>", { noremap = true, silent = true, desc = "bufferline: Goto buffer 8" })
vim.keymap.set("n", "<leader>9", ":BufferLineGoToBuffer 9<CR>", { noremap = true, silent = true, desc = "bufferline: Goto buffer 9" })
vim.keymap.set("n", "<leader>0", ":BufferLineGoToBuffer 10<CR>", { noremap = true, silent = true, desc = "bufferline: Goto buffer 10" })
vim.keymap.set("n", "<leader>b1", ":BufferLineGoToBuffer 1<CR>", { noremap = true, silent = true, desc = "bufferline: Goto buffer 1" })
vim.keymap.set("n", "<leader>b2", ":BufferLineGoToBuffer 2<CR>", { noremap = true, silent = true, desc = "bufferline: Goto buffer 2" })
vim.keymap.set("n", "<leader>b3", ":BufferLineGoToBuffer 3<CR>", { noremap = true, silent = true, desc = "bufferline: Goto buffer 3" })
vim.keymap.set("n", "<leader>b4", ":BufferLineGoToBuffer 4<CR>", { noremap = true, silent = true, desc = "bufferline: Goto buffer 4" })
vim.keymap.set("n", "<leader>b5", ":BufferLineGoToBuffer 5<CR>", { noremap = true, silent = true, desc = "bufferline: Goto buffer 5" })
vim.keymap.set("n", "<leader>b6", ":BufferLineGoToBuffer 6<CR>", { noremap = true, silent = true, desc = "bufferline: Goto buffer 6" })
vim.keymap.set("n", "<leader>b7", ":BufferLineGoToBuffer 7<CR>", { noremap = true, silent = true, desc = "bufferline: Goto buffer 7" })
vim.keymap.set("n", "<leader>b8", ":BufferLineGoToBuffer 8<CR>", { noremap = true, silent = true, desc = "bufferline: Goto buffer 8" })
vim.keymap.set("n", "<leader>b9", ":BufferLineGoToBuffer 9<CR>", { noremap = true, silent = true, desc = "bufferline: Goto buffer 9" })
vim.keymap.set("n", "<leader>b0", ":BufferLineGoToBuffer 10<CR>", { noremap = true, silent = true, desc = "bufferline: Goto buffer 10" })
vim.keymap.set("n", "<leader>bl", ":BufferLineCyclePrev<CR>", { noremap = true, silent = true, desc = "bufferline: Switch to prev" })
vim.keymap.set("n", "<leader>br", ":BufferLineCycleNext<CR>", { noremap = true, silent = true, desc = "bufferline: Switch to next" })
vim.keymap.set("n", "<leader>bL", "<Cmd>BufferLineCloseLeft<CR>", { noremap = true, silent = true, desc = "bufferline: Delete buffers to the left" })
vim.keymap.set("n", "<leader>bH", "<Cmd>BufferLineCloseRight<CR>", { noremap = true, silent = true, desc = "bufferline: Delete buffers to the right" })
vim.keymap.set("n", "<leader>bO", "<Cmd>BufferLineCloseOthers<CR>", { noremap = true, silent = true, desc = "bufferline: Delete other buffers" })
