---@class t.eve.context.data
---@field public theme                  t.eve.context.data.theme
---
---@field public bookmark               t.eve.context.data.bookmark
---@field public find                   t.eve.context.data.find
---@field public flight                 t.eve.context.data.flight
---@field public search                 t.eve.context.data.search
---
---@field public bufs                   t.eve.context.data.buf.IItem[]
---@field public tabs                   t.eve.context.data.tab.IItem[]
---@field public wins                   t.eve.context.data.win.IItem[]
---@field public frecency               t.eve.context.data.frecency
---@field public input_history          t.eve.context.data.input_history
---@field public tab_history            t.eve.collection.history.ISerializedData

---@class t.eve.context.state
---@field public theme                  t.eve.context.state.theme
---
---@field public bookmark               t.eve.context.state.bookmark
---@field public find                   t.eve.context.state.find
---@field public flight                 t.eve.context.state.flight
---@field public search                 t.eve.context.state.search
---
---@field public bufs                   table<integer, t.eve.context.state.buf.IItem>
---@field public tabs                   table<integer, t.eve.context.state.tab.IItem>
---@field public wins                   table<integer, t.eve.context.state.win.IItem>
---@field public status                 t.eve.context.state.status
---@field public frecency               t.eve.context.state.frecency
---@field public input_history          t.eve.context.state.input_history
---@field public tab_history            t.eve.collection.IAdvanceHistory
---@field public winline_dirty_nr       t.eve.collection.IObservable
---
---@field public client_has_changed     t.eve.collection.ITicker
---@field public session_has_changed    t.eve.collection.ITicker

---@class t.eve.context.storage
---@field public client                 ?string
---@field public session                ?string
---@field public workspace              ?string
---@field public nvim_session           ?string
---@field public nvim_session_autosaved ?string

---@class t.eve.context.IWatchChangeParams
---@field public on_theme_changed       ?fun(): nil

---@class t.eve.context
---@field public state                  t.eve.context.state
---@field public storage                t.eve.context.storage
---@field public dump                   fun(): t.eve.context.data
---@field public load                   fun(storage: t.eve.context.storage): nil
---@field public save                   fun(storage: t.eve.context.storage): nil
---@field public set_storage            fun(storage: t.eve.context.storage): nil
---@field public watch_changes          fun(): nil
