---@class fml.types.ui.file_select.IRawItem
---@field public filepath               string
---@field public lnum                   ?integer
---@field public col                    ?integer

---@class fml.types.ui.file_select.IItem
---@field public group                  string|nil
---@field public uuid                   string
---@field public filepath               string
---@field public filename               string
---@field public icon                   string
---@field public icon_hl                string
---@field public lnum                   ?integer
---@field public col                    ?integer

---@class fml.types.ui.IFileSelect
---@field public state                  fml.types.ui.search.IState
---@field public get_winnr_input        fun(self: fml.types.ui.IFileSelect): integer|nil
---@field public get_winnr_main         fun(self: fml.types.ui.IFileSelect): integer|nil
---@field public get_winnr_preview      fun(self: fml.types.ui.IFileSelect): integer|nil
---@field public change_input_title     fun(self: fml.types.ui.IFileSelect, title: string): nil
---@field public change_preview_title   fun(self: fml.types.ui.IFileSelect, title: string): nil
---@field public update_data            fun(self: fml.types.ui.IFileSelect, cwd: string, items: fml.types.ui.file_select.IRawItem[]): nil
---@field public close                  fun(self: fml.types.ui.IFileSelect): nil
---@field public focus                  fun(self: fml.types.ui.IFileSelect): nil
---@field public open                   fun(self: fml.types.ui.IFileSelect): nil
---@field public resume                 fun(self: fml.types.ui.IFileSelect): nil
---@field public toggle                 fun(self: fml.types.ui.IFileSelect): nil
