---@class fml.types.ui.ITextarea
---@field public bufnr                  integer|nil
---@field public winnr                  integer|nil
---@field public on_close               fun(): nil
---@field public on_confirm             fun(): nil
---@field public open                   fun(self: fml.types.ui.ITextarea, params: fml.types.ui.textarea.IOpenParams): nil
---@field public close                  fun(self: fml.types.ui.ITextarea): nil

---@class fml.types.ui.textarea.IOpenParams
---@field public initial_lines          string[]
---@field public row                    ?number
---@field public col                    ?number
---@field public text_cursor_row        ?integer
---@field public text_cursor_col        ?integer
---@field public win_cursor_row         ?integer
---@field public win_cursor_col         ?integer
