---@class fml.types.ui.theme.IPalette
---@field public black                  string
---@field public blue                   string
---@field public cyan                   string
---@field public green                  string
---@field public grey                   string
---@field public lavender               string
---@field public pink                   string
---@field public purple                 string
---@field public red                    string
---@field public white                  string
---@field public yellow                 string
---@field public dark_black             string
---@field public dark_blue              string
---@field public dark_cyan              string
---@field public dark_green             string
---@field public dark_pink              string
---@field public dark_purple            string
---@field public dark_red               string
---@field public dark_white             string
---@field public dark_yellow            string
---
---@field public bg0                    string
---@field public bg1                    string
---@field public bg2                    string
---@field public bg3                    string
---@field public bg_blue                string
---@field public bg_cyan                string
---@field public bg_pink                string
---@field public bg_yellow              string
---@field public fg0                    string
---@field public fg1                    string
---@field public fg2                    string
---@field public fg3                    string
---
---@field public diff_add               string
---@field public diff_add_word          string
---@field public diff_del               string
---@field public diff_del_word          string

---@class fml.types.ui.theme.IScheme
---@field public name                   string
---@field public mode                   fml.enums.theme.Mode
---@field public palette                fml.types.ui.theme.IPalette

---@class fml.types.ui.theme.IHlgroup : vim.api.keyset.highlight

---@class fml.types.ui.theme.IApplyParams
---@field public scheme                 fml.types.ui.theme.IScheme
---@field public nsnr                   integer

---@class fml.types.ui.theme.ICompileParams
---@field public scheme                 fml.types.ui.theme.IScheme
---@field public filepath               string
---@field public nsnr                   integer

---@class fml.types.ui.ITheme
---@field public apply                  fun(self: fml.types.ui.ITheme, params: fml.types.ui.theme.IApplyParams): nil
---@field public compile                fun(self: fml.types.ui.ITheme, params: fml.types.ui.theme.ICompileParams): nil
---@field public register               fun(self: fml.types.ui.ITheme, hlname: string, hlgroup: fml.types.ui.theme.IHlgroup): fml.types.ui.ITheme
---@field public registers              fun(self: fml.types.ui.ITheme, hlgroup_map: table<string, fml.types.ui.theme.IHlgroup | nil>): fml.types.ui.ITheme
