---@diagnostic disable-next-line: unused-local
local __module_name__ = "dot.theme.hlgroup.lsp.rosepine" ---@type string

-- Official syntax defaults: rose-pine/neovim@ff483051a47e.
---@class dot.theme.hlgroup.lsp.rosepine
local M = {}

---@param context                       stl.t.theme.IContext
---@return table<string, stl.t.theme.IHlgroup>
function M.gen_hlgroup_map(context)
  local c = context.scheme.palette.rosepine ---@type stl.t.theme.IRosepinePalette

  return {
    ["@lsp.mod.deprecated"] = { link = "DiagnosticDeprecated" },
    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.comment"] = {},
    ["@lsp.type.decorator"] = { link = "@attribute" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.event"] = { link = "@type" },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.interface"] = { link = "@type" },
    ["@lsp.type.keyword"] = { link = "@keyword" },
    ["@lsp.type.macro"] = { link = "@constant.macro" },
    ["@lsp.type.method"] = { link = "@function.method" },
    ["@lsp.type.modifier"] = { link = "@type.qualifier" },
    -- Keep namespaces on their official color when Include adapts to transparency.
    ["@lsp.type.namespace"] = { fg = c.pine },
    ["@lsp.type.number"] = { link = "@number" },
    ["@lsp.type.operator"] = { link = "@operator" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.regexp"] = { link = "@string.regexp" },
    ["@lsp.type.string"] = { link = "@string" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type.definition" },
    ["@lsp.type.variable"] = {},
    ["@lsp.type.comment.c"] = { link = "@comment" },
    ["@lsp.type.comment.cpp"] = { link = "@comment" },
    ["@lsp.type.namespace.python"] = { link = "@variable" },
    ["@lsp.type.variable.svelte"] = { link = "@variable" },
    ["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.operator.injected"] = { link = "@operator" },
    ["@lsp.typemod.string.injected"] = { link = "@string" },
    ["@lsp.typemod.variable.constant"] = { link = "@constant" },
    ["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
    ["@lsp.typemod.variable.injected"] = { link = "@variable" },

    -- Restore native fallback behavior for captures overridden by other local themes.
    ["@lsp.mod.declaration"] = {},
    ["@lsp.mod.definition"] = {},
    ["@lsp.mod.documentation"] = {},
    ["@lsp.mod.modification"] = {},
    ["@lsp.mod.readonly"] = {},
    ["@lsp.mod.static"] = {},
    ["@lsp.type.boolean"] = {},
    ["@lsp.type.builtin"] = {},
    ["@lsp.type.builtinType"] = {},
    ["@lsp.type.class.lua"] = { link = "@lsp.type.class" },
    ["@lsp.type.deriveHelper"] = {},
    ["@lsp.type.escapeSequence"] = {},
    ["@lsp.type.formatSpecifier"] = {},
    ["@lsp.type.generic"] = {},
    ["@lsp.type.keyword.lua"] = { link = "@lsp.type.keyword" },
    ["@lsp.type.label"] = {},
    ["@lsp.type.lifetime"] = {},
    ["@lsp.type.namespace.typescriptreact"] = { link = "@lsp.type.namespace" },
    ["@lsp.type.parameter.lua"] = { link = "@lsp.type.parameter" },
    ["@lsp.type.primitive"] = {},
    ["@lsp.type.selfKeyword"] = {},
    ["@lsp.type.selfTypeKeyword"] = {},
    ["@lsp.type.typeAlias"] = {},
    ["@lsp.type.unresolvedReference"] = {},
    ["@lsp.typemod.class.declaration"] = {},
    ["@lsp.typemod.class.declaration.lua"] = {},
    ["@lsp.typemod.class.defaultLibrary"] = {},
    ["@lsp.typemod.comment.documentation"] = {},
    ["@lsp.typemod.enum.declaration"] = {},
    ["@lsp.typemod.enum.defaultLibrary"] = {},
    ["@lsp.typemod.enumMember.declaration"] = {},
    ["@lsp.typemod.enumMember.defaultLibrary"] = {},
    ["@lsp.typemod.function.builtin"] = {},
    ["@lsp.typemod.function.declaration"] = {},
    ["@lsp.typemod.function.definition"] = {},
    ["@lsp.typemod.interface.declaration"] = {},
    ["@lsp.typemod.keyword.async"] = {},
    ["@lsp.typemod.keyword.documentation.lua"] = {},
    ["@lsp.typemod.keyword.injected"] = {},
    ["@lsp.typemod.macro.defaultLibrary"] = {},
    ["@lsp.typemod.method.builtin"] = {},
    ["@lsp.typemod.method.declaration"] = {},
    ["@lsp.typemod.method.defaultLibrary"] = {},
    ["@lsp.typemod.method.definition"] = {},
    ["@lsp.typemod.parameter.documentation"] = {},
    ["@lsp.typemod.property.readonly"] = {},
    ["@lsp.typemod.struct.declaration"] = {},
    ["@lsp.typemod.struct.defaultLibrary"] = {},
    ["@lsp.typemod.type.declaration"] = {},
    ["@lsp.typemod.type.defaultLibrary"] = {},
    ["@lsp.typemod.typeAlias.defaultLibrary"] = {},
    ["@lsp.typemod.variable.callable"] = {},
    ["@lsp.typemod.variable.declaration"] = {},
    ["@lsp.typemod.variable.readonly"] = {},
    ["@lsp.typemod.variable.readonly.typescriptreact"] = {},
    ["@lsp.typemod.variable.static"] = {},
  }
end

return M
