require("guanghechen.command.buf.close")
require("guanghechen.command.buf.create")
require("guanghechen.command.buf.focus")
require("guanghechen.command.buf.pin")
require("guanghechen.command.buf.save")

require("guanghechen.command.tab.close")
require("guanghechen.command.tab.create")
require("guanghechen.command.tab.focus")

require("guanghechen.command.win.close")
require("guanghechen.command.win.create")
require("guanghechen.command.win.focus")
require("guanghechen.command.win.history")
require("guanghechen.command.win.resize")

require("guanghechen.command.find.buffers")
require("guanghechen.command.find.explorer")
require("guanghechen.command.find.files")
require("guanghechen.command.find.git")
require("guanghechen.command.find.highlights")
require("guanghechen.command.find.pinned_files")
require("guanghechen.command.find.vim_options")

require("guanghechen.command.plugin.diffview")
require("guanghechen.command.plugin.nvim-notify")
require("guanghechen.command.plugin.nvim-window-picker")

require("guanghechen.command.search.files")

require("guanghechen.command.toggle.flag")
require("guanghechen.command.toggle.flight")
require("guanghechen.command.toggle.main")
require("guanghechen.command.toggle.theme")

require("guanghechen.command.copy")
require("guanghechen.command.debug")
require("guanghechen.command.lazygit")
require("guanghechen.command.refresh")
require("guanghechen.command.resume")
require("guanghechen.command.run")
require("guanghechen.command.scroll")
require("guanghechen.command.session")
require("guanghechen.command.term")
