---@param params                        ghc.types.ui.theme.IGenHlgroupMapParams
---@return table<string, fml.types.ui.theme.IHlgroup|nil>
local function gen_hlgroup(params)
  local c = params.scheme.colors ---@type fml.types.ui.theme.IColors
  local t = params.transparency ---@type boolean

  return {
    ---common
    f_transparent = { bg = "none" },

    ---statusline
    f_sl_bg = { fg = t and "none" or c.statusline_bg, bg = t and "none" or c.statusline_bg },
    f_sl_copilot_InProgress = { fg = c.cyan, bg = t and "none" or c.statusline_bg },
    f_sl_copilot_Normal = { fg = c.blue, bg = t and "none" or c.statusline_bg },
    f_sl_copilot_Warning = { fg = c.yellow, bg = t and "none" or c.statusline_bg },
    f_sl_diagnostics_error = { fg = c.red, bg = t and "none" or c.statusline_bg },
    f_sl_diagnostics_hint = { fg = c.purple, bg = t and "none" or c.statusline_bg },
    f_sl_diagnostics_info = { fg = c.green, bg = t and "none" or c.statusline_bg },
    f_sl_diagnostics_warn = { fg = c.yellow, bg = t and "none" or c.statusline_bg },
    f_sl_flag = { fg = c.white, bg = t and "none" or c.grey },
    f_sl_flag_enabled = { fg = c.black, bg = c.nord_blue },
    f_sl_flag_scope = { fg = c.black, bg = c.baby_pink },
    f_sl_noice_command = { fg = c.white, bg = t and "none" or c.statusline_bg },
    f_sl_noice_mode = { fg = c.yellow, bg = t and "none" or c.statusline_bg },
    f_sl_readonly = { fg = c.orange, bg = t and "none" or c.statusline_bg },
    f_sl_text = { fg = c.white, bg = t and "none" or c.statusline_bg },
    f_sl_text_command = { fg = c.vibrant_green, bg = t and "none" or c.statusline_bg, bold = true },
    f_sl_text_confirm = { fg = c.teal, bg = t and "none" or c.statusline_bg, bold = true },
    f_sl_text_insert = { fg = c.dark_purple, bg = t and "none" or c.statusline_bg, bold = true },
    f_sl_text_normal = { fg = c.nord_blue, bg = t and "none" or c.statusline_bg, bold = true },
    f_sl_text_nterminal = { fg = c.yellow, bg = t and "none" or c.statusline_bg, bold = true },
    f_sl_text_replace = { fg = c.orange, bg = t and "none" or c.statusline_bg, bold = true },
    f_sl_text_select = { fg = c.blue, bg = t and "none" or c.statusline_bg, bold = true },
    f_sl_text_terminal = { fg = c.green, bg = t and "none" or c.statusline_bg, bold = true },
    f_sl_text_visual = { fg = c.cyan, bg = t and "none" or c.statusline_bg },
    f_sl_username = { fg = c.black, bg = c.cyan },

    ---tabline
    f_tl_bg = { fg = t and "none" or c.statusline_bg, bg = t and "none" or c.statusline_bg },
    f_tl_buf_item = { fg = c.light_grey, bg = t and "none" or c.black2 },
    f_tl_buf_item_cur = { fg = c.white, bg = t and "none" or c.black },
    f_tl_buf_mod = { fg = c.red, bg = t and "none" or c.black2 },
    f_tl_buf_mod_cur = { fg = c.green, bg = t and "none" or c.black },
    f_tl_buf_title = { fg = c.light_grey, bg = t and "none" or c.black2 },
    f_tl_buf_title_cur = { fg = c.white, bg = t and "none" or c.black },
    f_tl_neotree_blank = { fg = c.white, bg = t and "none" or c.black2 },
    f_tl_neotree_text = { fg = c.white, bg = t and "none" or c.black2 },
    f_tl_tab_add = { fg = c.white, bg = c.one_bg2 },
    f_tl_tab_item = { fg = c.white, bg = c.black2 },
    f_tl_tab_item_cur = { fg = c.red },
    f_tl_tab_toggle = { fg = c.black, bg = c.blue },

    ---diff
    ghc_DiffAdd_left = { bg = "#FFE0E0", fg = "none" },
    ghc_DiffDelete_left = { bg = "#FFE0E0", fg = "none" },
    ghc_DiffChange_left = { bg = "#FFE0E0", fg = "none" },
    ghc_DiffText_left = { bg = "#FFC0C0", fg = "none" },
    ghc_DiffAdd_right = { bg = "#D0FFD0", fg = "none" },
    ghc_DiffDelete_right = { bg = "#FFE0E0", fg = "none" },
    ghc_DiffChange_right = { bg = "#D0FFD0", fg = "none" },
    ghc_DiffText_right = { bg = "#A0EFA0", fg = "none" },

    ---lazy_nvim
    --LazyButton = { bg = c.one_bg, fg = fml.color.change_hex_lightness("light_grey", vim.o.bg == c.dark and 10 or -20) },
    LazyCommit = { fg = c.green },
    LazyCommitIssue = { fg = c.pink },
    LazyDir = { fg = c.base05 },
    LazyH1 = { bg = c.green, fg = c.black },
    LazyH2 = { fg = c.red, bold = true, underline = true },
    LazyNoCond = { fg = c.red },
    LazyOperator = { fg = c.white },
    LazyProgressDone = { fg = c.green },
    LazyReasonCmd = { fg = c.sun },
    LazyReasonEvent = { fg = c.yellow },
    LazyReasonFt = { fg = c.purple },
    LazyReasonImport = { fg = c.white },
    LazyReasonKeys = { fg = c.teal },
    LazyReasonPlugin = { fg = c.red },
    LazyReasonRuntime = { fg = c.nord_blue },
    LazyReasonSource = { fg = c.cyan },
    LazyReasonStart = { fg = c.white },
    LazySpecial = { fg = c.blue },
    LazyTaskOutput = { fg = c.white },
    LazyUrl = { fg = c.base05 },
    LazyValue = { fg = c.teal },

    ---misc
    Added = { fg = c.green },
    Bold = { bold = true },
    Changed = { fg = c.yellow },
    ColorColumn = { bg = c.black2 },
    Comment = { fg = c.grey_fg },
    Conceal = { bg = "none" },
    Cursor = { fg = c.base00, bg = c.base05 },
    CursorColumn = { bg = c.base01, sp = "none" },
    CursorLine = { bg = c.one_bg2 },
    CursorLineNr = { fg = c.white },
    Debug = { fg = c.base08 },
    DevIconDefault = { fg = c.red },
    Directory = { fg = c.base0D },
    Error = { fg = c.base00, bg = c.base08 },
    ErrorMsg = { fg = c.base08, bg = c.base00 },
    Exception = { fg = c.base08 },
    FloatBorder = { fg = c.blue },
    Folded = { fg = c.light_grey, bg = c.black2 },
    FoldColumn = { fg = c.base0C, bg = c.base01 },
    IncSearch = { fg = c.base01, bg = c.base09 },
    Italic = { italic = true },
    LineNr = { fg = c.grey },
    Macro = { fg = c.base08 },
    MatchParen = { link = "MatchWord" },
    MatchWord = { bg = c.grey, fg = c.white },
    ModeMsg = { fg = c.base0B },
    MoreMsg = { fg = c.base0B },
    NonText = { fg = c.base03 },
    Normal = { fg = c.base05, bg = c.base00 },
    NormalFloat = { bg = c.darker_black },
    NvimInternalError = { fg = c.red },
    Pmenu = { bg = c.one_bg },
    PmenuSbar = { bg = c.one_bg },
    PmenuSel = { bg = c.pmenu_bg, fg = c.black },
    Question = { fg = c.base0D },
    QuickFixLine = { bg = c.base01, sp = "none" },
    PmenuThumb = { bg = c.grey },
    Removed = { fg = c.red },
    Search = { fg = c.base01, bg = c.base0A },
    SignColumn = { fg = c.base03, sp = "none" },
    SpecialKey = { fg = c.base03 },
    Substitute = { fg = c.base01, bg = c.base0A, sp = "none" },
    Title = { fg = c.base0D, sp = "none" },
    TooLong = { fg = c.base08 },
    UnderLined = { underline = true },
    Visual = { bg = c.light_grey },
    VisualNOS = { fg = c.base08 },
    WarningMsg = { fg = c.base08 },
    WinSeparator = { fg = c.line },
    WildMenu = { fg = c.base08, bg = c.base0A },

    ---replace
    GhcReplaceFilepath = { fg = c.blue, bg = "none" },
    GhcReplaceFlag = { fg = c.white, bg = c.grey },
    GhcReplaceFlagEnabled = { fg = c.black, bg = c.baby_pink },
    GhcReplaceFence = { fg = c.grey, bg = "none" },
    GhcReplaceInvisible = { fg = "none", bg = "none" },
    GhcReplaceOptName = { fg = c.blue, bg = "none", bold = true },
    GhcReplaceOptReplacePattern = { fg = c.diff_add_hl, bg = "none" },
    GhcReplaceOptSearchPattern = { fg = c.diff_delete_hl, bg = "none" },
    GhcReplaceOptValue = { fg = c.yellow, bg = "none" },
    GhcReplaceTextAdded = { fg = c.diff_add_hl, bg = "none" },
    GhcReplaceTextDeleted = { fg = c.diff_delete_hl, strikethrough = true },
    GhcReplaceUsage = { fg = c.grey_fg2, bg = "none" },

    ---spell
    healthSuccess = { bg = c.green, fg = c.black },
    SpellBad = { undercurl = true, sp = c.base08 },
    SpellCap = { undercurl = true, sp = c.base0D },
    SpellLocal = { undercurl = true, sp = c.base0C },
    SpellRare = { undercurl = true, sp = c.base0E },
  }
end

return gen_hlgroup
