---@param params                        ghc.types.ui.theme.IGenHlgroupMapParams
---@return table<string, fml.types.ui.theme.IHlgroup|nil>
local function gen_hlgroup(params)
  local c = params.scheme.colors ---@type fml.types.ui.theme.IColors

  return {
    ["@annotation"] = { fg = c.base0F },
    ["@attribute"] = { fg = c.base0A },
    ["@character"] = { fg = c.base08 },
    ["@character.special"] = { fg = c.base08 },
    ["@comment.danger"] = { fg = c.black2, bg = c.red },
    ["@comment.note"] = { fg = c.black2, bg = c.white },
    ["@comment.todo"] = { fg = c.grey, bg = c.white },
    ["@comment.warning"] = { fg = c.black2, bg = c.base09 },
    ["@comment"] = { fg = c.grey_fg },
    ["@constant.builtin"] = { fg = c.base09 },
    ["@constant.macro"] = { fg = c.base08 },
    ["@constant"] = { fg = c.base08 },
    ["@constructor"] = { fg = c.base0C },
    ["@definition"] = { sp = c.base04, underline = true },
    ["@diff.delta"] = { fg = c.light_grey },
    ["@diff.minus"] = { fg = c.red },
    ["@diff.plus"] = { fg = c.green },
    ["@error"] = { fg = c.base08 },
    ["@function.builtin"] = { fg = c.base0D },
    ["@function.call"] = { fg = c.base0D },
    ["@function.macro"] = { fg = c.base08 },
    ["@function.method.call"] = { fg = c.base0D },
    ["@function.method"] = { fg = c.base0D },
    ["@function"] = { fg = c.base0D },
    ["@keyword.conditional.ternary"] = { fg = c.base0E },
    ["@keyword.conditional"] = { fg = c.base0E },
    ["@keyword.directive.define"] = { fg = c.base0E },
    ["@keyword.directive"] = { fg = c.base0A },
    ["@keyword.exception"] = { fg = c.base08 },
    ["@keyword.function"] = { fg = c.base0E },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.operator"] = { fg = c.base0E },
    ["@keyword.repeat"] = { fg = c.base0A },
    ["@keyword.return"] = { fg = c.base0E },
    ["@keyword.storage"] = { fg = c.base0A },
    ["@keyword"] = { fg = c.base0E },
    ["@markup.heading"] = { fg = c.base0D },
    ["@markup.italic"] = { italic = true },
    ["@markup.link.label"] = { fg = c.base0C },
    ["@markup.link.url"] = { fg = c.base09, underline = true },
    ["@markup.link"] = { fg = c.base08 },
    ["@markup.list"] = { fg = c.base08 },
    ["@markup.quote"] = { bg = c.black2 },
    ["@markup.raw"] = { fg = c.base09 },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.underline"] = { underline = true },
    ["@module"] = { fg = c.base08 },
    ["@module.builtin"] = { fg = c.base08 },
    ["@number.float"] = { fg = c.base09 },
    ["@number"] = { fg = c.base09 },
    ["@operator"] = { fg = c.base05 },
    ["@property"] = { fg = c.base08 },
    ["@punctuation.bracket"] = { fg = c.base0F },
    ["@punctuation.delimiter"] = { fg = c.base0F },
    ["@reference"] = { fg = c.base05 },
    ["@scope"] = { bold = true },
    ["@string.escape"] = { fg = c.base0C },
    ["@string.regex"] = { fg = c.base0C },
    ["@string"] = { fg = c.base0B },
    ["@symbol"] = { fg = c.base0B },
    ["@tag.attribute"] = { fg = c.base08 },
    ["@tag.delimiter"] = { fg = c.base0F },
    ["@tag"] = { fg = c.base0A },
    ["@text.emphasis"] = { fg = c.base09 },
    ["@text.strike"] = { fg = c.base0F, strikethrough = true },
    ["@text"] = { fg = c.base05 },
    ["@type.builtin"] = { fg = c.base0A },
    ["@variable.builtin"] = { fg = c.base09 },
    ["@variable.member.key"] = { fg = c.base08 },
    ["@variable.member"] = { fg = c.base08 },
    ["@variable.parameter"] = { fg = c.base08 },
    ["@variable"] = { fg = c.base05 },
  }
end

return gen_hlgroup
