---@param params                        ghc.types.ui.theme.IGenHlgroupMapParams
---@return table<string, fml.types.ui.theme.IHlgroup>
local function gen_hlgroup_map(params)
  local c = params.scheme.palette ---@type fml.types.ui.theme.IPalette

  return {
    ["@annotation"] = { fg = c.dark_red },
    ["@attribute"] = { fg = c.yellow },
    ["@character"] = { fg = c.red },
    ["@character.special"] = { fg = c.red },
    ["@comment.danger"] = { fg = c.black, bg = c.red },
    ["@comment.note"] = { fg = c.black, bg = c.white },
    ["@comment.todo"] = { fg = c.grey, bg = c.white },
    ["@comment.warning"] = { fg = c.black, bg = c.dark_yellow },
    ["@comment"] = { fg = c.grey },
    ["@constant.builtin"] = { fg = c.dark_yellow },
    ["@constant.macro"] = { fg = c.red },
    ["@constant"] = { fg = c.red },
    ["@constructor"] = { fg = c.purple },
    ["@definition"] = { sp = c.grey, underline = true },
    ["@diff.delta"] = { fg = c.grey },
    ["@diff.minus"] = { fg = c.red },
    ["@diff.plus"] = { fg = c.green },
    ["@error"] = { fg = c.red },
    ["@function.builtin"] = { fg = c.blue },
    ["@function.call"] = { fg = c.blue },
    ["@function.macro"] = { fg = c.red },
    ["@function.method.call"] = { fg = c.blue },
    ["@function.method"] = { fg = c.blue },
    ["@function"] = { fg = c.blue },
    ["@keyword.conditional.ternary"] = { fg = c.purple },
    ["@keyword.conditional"] = { fg = c.purple },
    ["@keyword.directive.define"] = { fg = c.purple },
    ["@keyword.directive"] = { fg = c.yellow },
    ["@keyword.exception"] = { fg = c.red },
    ["@keyword.function"] = { fg = c.purple },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.operator"] = { fg = c.purple },
    ["@keyword.repeat"] = { fg = c.yellow },
    ["@keyword.return"] = { fg = c.purple },
    ["@keyword.storage"] = { fg = c.yellow },
    ["@keyword"] = { fg = c.purple },
    ["@markup.heading"] = { fg = c.blue },
    ["@markup.italic"] = { italic = true },
    ["@markup.link.label"] = { fg = c.cyan },
    ["@markup.link.url"] = { fg = c.dark_yellow, underline = true },
    ["@markup.link"] = { fg = c.red },
    ["@markup.list"] = { fg = c.red },
    ["@markup.quote"] = { bg = c.bg1 },
    ["@markup.raw"] = { fg = c.dark_yellow },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.underline"] = { underline = true },
    ["@module"] = { fg = c.red },
    ["@module.builtin"] = { fg = c.red },
    ["@number.float"] = { fg = c.dark_yellow },
    ["@number"] = { fg = c.dark_yellow },
    ["@operator"] = { fg = c.fg0 },
    ["@property"] = { fg = c.red },
    ["@punctuation.bracket"] = { fg = c.purple },
    ["@punctuation.delimiter"] = { fg = c.dark_red },
    ["@reference"] = { fg = c.fg0 },
    ["@scope"] = { bold = true },
    ["@string.escape"] = { fg = c.cyan },
    ["@string.regex"] = { fg = c.cyan },
    ["@string"] = { fg = c.green },
    ["@symbol"] = { fg = c.green },
    ["@tag.attribute"] = { fg = c.red },
    ["@tag.delimiter"] = { fg = c.dark_red },
    ["@tag"] = { fg = c.yellow },
    ["@text.emphasis"] = { fg = c.dark_yellow },
    ["@text.strike"] = { fg = c.dark_red, strikethrough = true },
    ["@text"] = { fg = c.fg0 },
    ["@text.diff.add"] = { link = "DiffAdded", default = true },
    ["@text.diff.delete"] = { link = "DiffRemoved", default = true },
    ["@type.builtin"] = { fg = c.yellow },
    ["@variable"] = { fg = c.red },
    ["@variable.builtin"] = { fg = c.dark_yellow },
    ["@variable.member.key"] = { fg = c.red },
    ["@variable.member"] = { fg = c.fg1 },
    ["@variable.parameter"] = { fg = c.red },
  }
end

return gen_hlgroup_map
