---@class fml.types.IKeymapOverridable
---@field public bufnr                  ?integer
---@field public nowait                 ?boolean
---@field public noremap                ?boolean
---@field public silent                 ?boolean

---@class fml.types.IKeymap : fml.types.IKeymapOverridable
---@field public modes                  eve.enums.VimMode[]
---@field public key                    string
---@field public callback               fun(): nil
---@field public desc                   string|nil
