---@class dot.hlgroup.tokyonight.treesitter
local M = {}

---@param context                       dot.t.theme.IContext
---@return table<string, dot.t.theme.IHlgroup>
function M.gen_hlgroup_map(context)
  local cs = std.color
  local t = context.transparency ---@type boolean
  local c = context.scheme.palette.tokyonight ---@type dot.t.theme.TokyonightPalette

  ---@type table<string, dot.t.theme.IHlgroup>
  local hlgroup_map = {
    ["@annotation"] = { link = "PreProc" },
    ["@attribute"] = { link = "PreProc" },
    ["@boolean"] = { link = "Boolean" },
    ["@character"] = { link = "Character" },
    ["@character.printf"] = { link = "SpecialChar" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@comment"] = { link = "Comment" },
    ["@comment.error"] = { fg = c.red },
    ["@comment.hint"] = { fg = c.hint },
    ["@comment.info"] = { fg = c.info },
    ["@comment.note"] = { fg = c.hint },
    ["@comment.todo"] = { fg = c.todo },
    ["@comment.warning"] = { fg = c.warning },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "Special" },
    ["@constant.macro"] = { link = "Define" },
    ["@constructor"] = { fg = c.magenta },
    ["@constructor.tsx"] = { fg = c.blue1 },
    ["@diff.delta"] = { link = "DiffChange" },
    ["@diff.minus"] = { link = "DiffDelete" },
    ["@diff.plus"] = { link = "DiffAdd" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { link = "Special" },
    ["@function.call"] = { link = "@function" },
    ["@function.macro"] = { link = "Macro" },
    ["@function.method"] = { link = "Function" },
    ["@function.method.call"] = { link = "@function.method" },
    ["@keyword"] = { fg = c.purple, italic = true },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.coroutine"] = { link = "@keyword" },
    ["@keyword.debug"] = { link = "Debug" },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.directive.define"] = { link = "Define" },
    ["@keyword.exception"] = { link = "Exception" },
    ["@keyword.function"] = { fg = c.magenta },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.operator"] = { link = "@operator" },
    ["@keyword.repeat"] = { link = "Repeat" },
    ["@keyword.return"] = { link = "@keyword" },
    ["@keyword.storage"] = { link = "StorageClass" },
    ["@label"] = { fg = c.blue },
    ["@markup"] = { link = "@none" },
    ["@markup.emphasis"] = { italic = true },
    ["@markup.environment"] = { link = "Macro" },
    ["@markup.environment.name"] = { link = "Type" },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.italic"] = { italic = true },
    ["@markup.link"] = { fg = c.teal },
    ["@markup.link.label"] = { link = "SpecialChar" },
    ["@markup.link.label.symbol"] = { link = "Identifier" },
    ["@markup.link.url"] = { link = "Underlined" },
    ["@markup.list"] = { fg = c.blue5 },
    ["@markup.list.checked"] = { fg = c.green1 },
    ["@markup.list.markdown"] = { fg = c.orange, bold = true },
    ["@markup.list.unchecked"] = { fg = c.blue },
    ["@markup.math"] = { link = "Special" },
    ["@markup.raw"] = { link = "String" },
    ["@markup.raw.markdown_inline"] = { bg = c.terminal_black, fg = c.blue },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.underline"] = { underline = true },
    ["@module"] = { link = "Include" },
    ["@module.builtin"] = { fg = c.red },
    ["@namespace.builtin"] = { link = "@variable.builtin" },
    ["@none"] = {},
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@operator"] = { fg = c.blue5 },
    ["@property"] = { fg = c.green1 },
    ["@punctuation.bracket"] = { fg = c.fg_dark },
    ["@punctuation.delimiter"] = { fg = c.blue5 },
    ["@punctuation.special"] = { fg = c.blue5 },
    ["@punctuation.special.markdown"] = { fg = c.orange },
    ["@string"] = { link = "String" },
    ["@string.documentation"] = { fg = c.yellow },
    ["@string.escape"] = { fg = c.magenta },
    ["@string.regexp"] = { fg = c.blue6 },
    ["@tag"] = { link = "Label" },
    ["@tag.attribute"] = { link = "@property" },
    ["@tag.delimiter"] = { link = "Delimiter" },
    ["@tag.delimiter.tsx"] = { fg = cs.mix(c.blue, c.bg, 70) },
    ["@tag.tsx"] = { fg = c.red },
    ["@tag.javascript"] = { fg = c.red },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = cs.mix(c.blue1, c.bg, 20) },
    ["@type.definition"] = { link = "Typedef" },
    ["@type.qualifier"] = { link = "@keyword" },
    ["@variable"] = { fg = c.fg },
    ["@variable.builtin"] = { fg = c.red },
    ["@variable.member"] = { fg = c.green1 },
    ["@variable.parameter"] = { fg = c.yellow },
    ["@variable.parameter.builtin"] = { fg = cs.mix(c.yellow, c.fg, 80) },

    -- Compatibility
    ["@attribute.c_sharp"] = { link = "@attribute" },
    ["@character.special.html"] = { link = "@character.special" },
    ["@comment.danger"] = { fg = c.bg_dark, bg = t and c.none or c.red },
    ["@comment.documentation"] = { link = "@comment" },
    ["@comment.warning.gitcommit"] = { fg = c.warning },
    ["@conditional"] = { link = "Conditional" },
    ["@constant.java"] = { link = "Constant" },
    ["@constructor.lua"] = { link = "@constructor" },
    ["@constructor.python"] = { link = "@constructor" },
    ["@debug"] = { link = "Debug" },
    ["@define"] = { link = "Define" },
    ["@error"] = { link = "Error" },
    ["@event"] = { link = "Keyword" },
    ["@exception"] = { link = "Exception" },
    ["@field"] = { fg = c.green1 },
    ["@float"] = { link = "Float" },
    ["@function.builtin.bash"] = { link = "@function.builtin" },
    ["@include"] = { link = "Include" },
    ["@keyword.conditional.ternary"] = { link = "@keyword" },
    ["@keyword.directive.css"] = { link = "@keyword.directive" },
    ["@keyword.import.c"] = { link = "@keyword.import" },
    ["@keyword.import.cpp"] = { link = "@keyword.import" },
    ["@keyword.modifier"] = { link = "@keyword" },
    ["@keyword.type"] = { link = "Type" },
    ["@label.yaml"] = { link = "@label" },
    ["@macro"] = { link = "Macro" },
    ["@markup.heading.1"] = { fg = c.blue, bold = true },
    ["@markup.heading.1.markdown"] = { fg = c.blue, bold = true, bg = cs.mix(c.bg, c.blue, 10) },
    ["@markup.heading.1.marker"] = { fg = c.blue },
    ["@markup.heading.1.marker.markdown"] = { fg = c.blue },
    ["@markup.heading.2"] = { fg = c.yellow, bold = true },
    ["@markup.heading.2.markdown"] = { fg = c.yellow, bold = true, bg = cs.mix(c.bg, c.yellow, 10) },
    ["@markup.heading.2.marker"] = { fg = c.yellow },
    ["@markup.heading.2.marker.markdown"] = { fg = c.yellow },
    ["@markup.heading.3"] = { fg = c.green, bold = true },
    ["@markup.heading.3.markdown"] = { fg = c.green, bold = true, bg = cs.mix(c.bg, c.green, 10) },
    ["@markup.heading.3.marker"] = { fg = c.green },
    ["@markup.heading.3.marker.markdown"] = { fg = c.green },
    ["@markup.heading.4"] = { fg = c.teal, bold = true },
    ["@markup.heading.4.markdown"] = { fg = c.teal, bold = true, bg = cs.mix(c.bg, c.teal, 10) },
    ["@markup.heading.4.marker"] = { fg = c.teal },
    ["@markup.heading.4.marker.markdown"] = { fg = c.teal },
    ["@markup.heading.5"] = { fg = c.cyan, bold = true },
    ["@markup.heading.5.markdown"] = { fg = c.cyan, bold = true, bg = cs.mix(c.bg, c.cyan, 10) },
    ["@markup.heading.5.marker"] = { fg = c.cyan },
    ["@markup.heading.5.marker.markdown"] = { fg = c.cyan },
    ["@markup.heading.6"] = { fg = c.magenta, bold = true },
    ["@markup.heading.6.markdown"] = { fg = c.magenta, bold = true, bg = cs.mix(c.bg, c.magenta, 10) },
    ["@markup.heading.6.marker"] = { fg = c.magenta },
    ["@markup.heading.6.marker.markdown"] = { fg = c.magenta },
    ["@markup.link.label.html"] = { link = "@markup.link.label" },
    ["@markup.quote"] = { fg = c.fg, bg = t and c.none or c.bg_dark },
    ["@method"] = { link = "Function" },
    ["@method.call"] = { link = "@method" },
    ["@modifier"] = { link = "@keyword" },
    ["@namespace"] = { link = "@module" },
    ["@number.css"] = { link = "@number" },
    ["@parameter"] = { link = "@variable.parameter" },
    ["@preproc"] = { link = "PreProc" },
    ["@property.class.css"] = { link = "@property" },
    ["@property.css"] = { link = "@property" },
    ["@property.id.css"] = { link = "@property" },
    ["@property.scss"] = { link = "@property" },
    ["@punctuation"] = { link = "Delimiter" },
    ["@reference"] = { link = "Constant" },
    ["@regexp"] = { link = "@string.regexp" },
    ["@repeat"] = { link = "Repeat" },
    ["@scope"] = {},
    ["@storageclass"] = { link = "StorageClass" },
    ["@string.plain.css"] = { link = "@string" },
    ["@string.regex"] = { link = "@string.regexp" },
    ["@string.special"] = { link = "Special" },
    ["@string.special.path"] = { link = "Underlined" },
    ["@string.special.symbol"] = { link = "Identifier" },
    ["@string.special.url"] = { link = "Underlined" },
    ["@string.special.url.html"] = { link = "@string.special.url" },
    ["@structure"] = { link = "Structure" },
    ["@symbol"] = { link = "Identifier" },
    ["@tag.builtin"] = { link = "@tag" },
    ["@text"] = { fg = c.fg },
    ["@text.danger"] = { link = "ErrorMsg" },
    ["@text.danger.comment"] = { fg = c.bg_dark, bg = t and c.none or c.red },
    ["@text.diff.add"] = { link = "DiffAdd" },
    ["@text.diff.delete"] = { link = "DiffDelete" },
    ["@text.emphasis"] = { italic = true },
    ["@text.environment"] = { link = "Macro" },
    ["@text.environment.name"] = { link = "Type" },
    ["@text.literal"] = { link = "String" },
    ["@text.math"] = { link = "Special" },
    ["@text.note"] = { link = "SpecialComment" },
    ["@text.note.comment"] = { fg = c.purple },
    ["@text.reference"] = { link = "Constant" },
    ["@text.strike"] = { strikethrough = true },
    ["@text.strong"] = { bold = true },
    ["@text.title"] = { link = "Title" },
    ["@text.todo"] = { link = "Todo" },
    ["@text.todo.checked"] = { fg = c.green1 },
    ["@text.todo.unchecked"] = { fg = c.fg_gutter },
    ["@text.underline"] = { underline = true },
    ["@text.uri"] = { link = "Underlined" },
    ["@text.warning"] = { link = "WarningMsg" },
    ["@type.css"] = { link = "@type" },
    ["@type.tag.css"] = { link = "@type" },
    ["@type.tsx"] = { link = "Variable" },
    ["@variable.jsx"] = { fg = c.blue1 },
    ["@variable.parameter.bash"] = { link = "@variable.parameter" },
    ["@variable.parameter.luadoc"] = { link = "@variable.parameter" },
    ["@variable.tsx"] = { fg = c.blue1 },
  }

  return hlgroup_map
end

return M
