---@param context                       eve.t.theme.IContext
---@return eve.constant.hlgroup.nvimbar
local function gen_hlgroup_map(context)
  local c = context.scheme.palette ---@type eve.t.theme.IPalette
  local t = context.transparency ---@type boolean
  local bg_bufc = t and "none" or c.bg0 ---@type string
  local bg_pos = t and c.bg0 or c.bg2 ---@type string
  local bg_username = c.bg0 ---@type string

  local mc = {
    command = c.green,
    confirm = c.brightAqua,
    insert = c.purple,
    normal = c.aqua,
    nterminal = c.yellow,
    replace = c.brightYellow,
    select = c.orange,
    terminal = c.green,
    visual = c.orange,
  }

  local bgs = {
    f_sl = t and "none" or c.bg1,
    f_tl = t and "none" or c.bg1,
    f_wl = "none",
  }

  ---@type table<string, eve.t.theme.IHlgroup>
  local hlgroup_map = {
    bg = { fg = "bg_bar", bg = "bg_bar" },
    ai_text = { fg = c.fg2, bg = "bg_bar" },
    ai_status_InProgress = { fg = c.aqua, bg = "bg_bar" },
    ai_status_Inactive = { fg = c.red, bg = "bg_bar" },
    ai_status_Normal = { fg = c.fg1, bg = "bg_bar" },
    ai_status_Warning = { fg = c.yellow, bg = "bg_bar" },
    buf = { fg = c.bg4, bg = "bg_bar" },
    buf_indicator = { fg = c.purple, bg = bg_bufc, bold = true, underline = true, sp = c.purple },
    buf_mod = { fg = c.fg4, bg = "bg_bar" },
    buf_omitter = { fg = c.blue, bg = "bg_bar" },
    buf_omitter_sep = { fg = c.bg4, bg = "bg_bar" },
    buf_pinned = { fg = c.fg4, bg = "bg_bar" },
    buf_order = { fg = c.fg4, bg = "bg_bar" },
    buf_sep = { fg = c.fg4, bg = "bg_bar" },
    buf_text = { fg = c.fg4, bg = "bg_bar" },
    bufc = { fg = c.fg2, bg = bg_bufc, underline = true, sp = c.purple },
    bufc_mod = { fg = c.green, bg = bg_bufc, underline = true, sp = c.purple },
    bufc_pinned = { fg = c.fg0, bg = bg_bufc, underline = true, sp = c.purple },
    bufc_order = { fg = c.fg0, bg = bg_bufc, underline = true, sp = c.purple },
    bufc_text = { fg = c.fg2, bg = bg_bufc, bold = true, italic = true, underline = true, sp = c.purple },
    bufc_error = { fg = c.red, bg = bg_bufc, bold = true, italic = true, underline = true, sp = c.purple },
    bufc_warn = { fg = c.yellow, bg = bg_bufc, bold = true, italic = true, underline = true, sp = c.purple },
    bufc_hint = { fg = c.purple, bg = bg_bufc, bold = true, italic = true, underline = true, sp = c.purple },
    bufc_info = { fg = c.green, bg = bg_bufc, bold = true, italic = true, underline = true, sp = c.purple },
    copilot_InProgress = { fg = c.aqua, bg = "bg_bar" },
    copilot_Inactive = { fg = c.red, bg = "bg_bar" },
    copilot_Normal = { fg = c.fg1, bg = "bg_bar" },
    copilot_Warning = { fg = c.yellow, bg = "bg_bar" },
    cwd_sep_command = { fg = mc.command, bg = "bg_bar", bold = true },
    cwd_sep_confirm = { fg = mc.confirm, bg = "bg_bar", bold = true },
    cwd_sep_insert = { fg = mc.insert, bg = "bg_bar", bold = true },
    cwd_sep_normal = { fg = mc.normal, bg = "bg_bar", bold = true },
    cwd_sep_nterminal = { fg = mc.nterminal, bg = "bg_bar", bold = true },
    cwd_sep_replace = { fg = mc.replace, bg = "bg_bar", bold = true },
    cwd_sep_select = { fg = mc.select, bg = "bg_bar", bold = true },
    cwd_sep_terminal = { fg = mc.terminal, bg = "bg_bar", bold = true },
    cwd_sep_visual = { fg = mc.visual, bg = "bg_bar", bold = true },
    cwd_text_command = { fg = c.bg1, bg = mc.command, bold = true },
    cwd_text_confirm = { fg = c.bg1, bg = mc.confirm, bold = true },
    cwd_text_insert = { fg = c.bg1, bg = mc.insert, bold = true },
    cwd_text_normal = { fg = c.bg1, bg = mc.normal, bold = true },
    cwd_text_nterminal = { fg = c.bg1, bg = mc.nterminal, bold = true },
    cwd_text_replace = { fg = c.bg1, bg = mc.replace, bold = true },
    cwd_text_select = { fg = c.bg1, bg = mc.select, bold = true },
    cwd_text_terminal = { fg = c.bg1, bg = mc.terminal, bold = true },
    cwd_text_visual = { fg = c.bg1, bg = mc.visual, bold = true },
    debug_render_count_text = { fg = c.bg0, bg = c.orange, bold = true },
    debug_render_count_sep = { fg = c.orange, bg = c.bg1, bold = true },
    devmode = { fg = c.bg0, bg = c.yellow, bold = true },
    diagnostics_error = { fg = c.red, bg = "bg_bar" },
    diagnostics_warn = { fg = c.yellow, bg = "bg_bar" },
    diagnostics_hint = { fg = c.purple, bg = "bg_bar" },
    diagnostics_info = { fg = c.green, bg = "bg_bar" },
    dirpath_icon = { fg = c.blue, bg = "bg_bar" },
    dirpath_sep = { fg = c.fg1, bg = "bg_bar" },
    dirpath_text = { fg = c.blue, bg = "bg_bar" },
    dirpath_prominent_icon = { fg = c.bg0, bg = c.pink, bold = true },
    dirpath_prominent_text = { fg = c.bg0, bg = c.pink, bold = true },
    filename = { fg = c.fg1, bg = "bg_bar" },
    filename_text = { fg = c.fg3, bg = "bg_bar" },
    filename_text_cur = { fg = c.fg2, bg = "bg_bar", bold = true, italic = true },
    flag = { fg = c.fg1, bg = t and c.bg2 or c.bg3 },
    flag_sep = { fg = c.bg4, bg = t and c.bg2 or c.bg3 },
    flag_enabled = { fg = c.bg1, bg = c.blue },
    flag_enabled_sep = { fg = c.bg4, bg = c.blue },
    flag_scope = { fg = c.bg1, bg = c.blue },
    flag_scope_sep = { fg = c.bg4, bg = c.blue },
    flag_popup = { fg = c.bg1, bg = c.purple },
    flag_popup_sep = { fg = c.bg1, bg = c.purple },
    git_text = { fg = c.fg1, bg = "bg_bar" },
    indicator = { fg = c.orange, bg = "bg_bar" },
    lsp_icon = { fg = c.brightPurple, bg = "bg_bar" },
    lsp_icon_Array = { fg = c.blue, bg = "bg_bar" },
    lsp_icon_Boolean = { fg = c.orange, bg = "bg_bar" },
    lsp_icon_Class = { fg = c.brightAqua, bg = "bg_bar" },
    lsp_icon_Color = { fg = c.fg1, bg = "bg_bar" },
    lsp_icon_Constant = { fg = c.orange, bg = "bg_bar" },
    lsp_icon_Constructor = { fg = c.blue, bg = "bg_bar" },
    lsp_icon_Enum = { fg = c.blue, bg = "bg_bar" },
    lsp_icon_EnumMember = { fg = c.brightPurple, bg = "bg_bar" },
    lsp_icon_Event = { fg = c.yellow, bg = "bg_bar" },
    lsp_icon_Field = { fg = c.red, bg = "bg_bar" },
    lsp_icon_File = { fg = c.fg1, bg = "bg_bar" },
    lsp_icon_Folder = { fg = c.fg1, bg = "bg_bar" },
    lsp_icon_Function = { fg = c.blue, bg = "bg_bar" },
    lsp_icon_Identifier = { fg = c.red, bg = "bg_bar" },
    lsp_icon_Interface = { fg = c.green, bg = "bg_bar" },
    lsp_icon_Key = { fg = c.red, bg = "bg_bar" },
    lsp_icon_Keyword = { fg = c.fg1, bg = "bg_bar" },
    lsp_icon_Method = { fg = c.blue, bg = "bg_bar" },
    lsp_icon_Module = { fg = c.yellow, bg = "bg_bar" },
    lsp_icon_Namespace = { fg = c.brightAqua, bg = "bg_bar" },
    lsp_icon_Null = { fg = c.aqua, bg = "bg_bar" },
    lsp_icon_Number = { fg = c.orange, bg = "bg_bar" },
    lsp_icon_Object = { fg = c.brightPurple, bg = "bg_bar" },
    lsp_icon_Operator = { fg = c.fg1, bg = "bg_bar" },
    lsp_icon_Package = { fg = c.green, bg = "bg_bar" },
    lsp_icon_Property = { fg = c.red, bg = "bg_bar" },
    lsp_icon_Reference = { fg = c.fg1, bg = "bg_bar" },
    lsp_icon_Snippet = { fg = c.red, bg = "bg_bar" },
    lsp_icon_String = { fg = c.green, bg = "bg_bar" },
    lsp_icon_Struct = { fg = c.brightPurple, bg = "bg_bar" },
    lsp_icon_Structure = { fg = c.brightPurple, bg = "bg_bar" },
    lsp_icon_Text = { fg = c.green, bg = "bg_bar" },
    lsp_icon_Type = { fg = c.yellow, bg = "bg_bar" },
    lsp_icon_TypeParameter = { fg = c.red, bg = "bg_bar" },
    lsp_icon_Unit = { fg = c.brightPurple, bg = "bg_bar" },
    lsp_icon_Value = { fg = c.aqua, bg = "bg_bar" },
    lsp_icon_Variable = { fg = c.brightPurple, bg = "bg_bar" },
    lsp_sep = { fg = c.fg3, bg = "bg_bar" },
    lsp_text = { fg = c.fg3, bg = "bg_bar" },
    mode_sep_command = { fg = mc.command, bg = bg_pos, bold = true },
    mode_sep_confirm = { fg = mc.confirm, bg = bg_pos, bold = true },
    mode_sep_insert = { fg = mc.insert, bg = bg_pos, bold = true },
    mode_sep_normal = { fg = mc.normal, bg = bg_pos, bold = true },
    mode_sep_nterminal = { fg = mc.nterminal, bg = bg_pos, bold = true },
    mode_sep_replace = { fg = mc.replace, bg = bg_pos, bold = true },
    mode_sep_select = { fg = mc.select, bg = bg_pos, bold = true },
    mode_sep_terminal = { fg = mc.terminal, bg = bg_pos, bold = true },
    mode_sep_visual = { fg = mc.visual, bg = bg_pos, bold = true },
    mode_text_command = { fg = c.bg1, bg = mc.command, bold = true },
    mode_text_confirm = { fg = c.bg1, bg = mc.confirm, bold = true },
    mode_text_insert = { fg = c.bg1, bg = mc.insert, bold = true },
    mode_text_normal = { fg = c.bg1, bg = mc.normal, bold = true },
    mode_text_nterminal = { fg = c.bg1, bg = mc.nterminal, bold = true },
    mode_text_replace = { fg = c.bg1, bg = mc.replace, bold = true },
    mode_text_select = { fg = c.bg1, bg = mc.select, bold = true },
    mode_text_terminal = { fg = c.bg1, bg = mc.terminal, bold = true },
    mode_text_visual = { fg = c.bg1, bg = mc.visual, bold = true },
    noice_command = { fg = c.fg2, bg = "bg_bar" },
    noice_mode = { fg = c.yellow, bg = "bg_bar" },
    pos_sep = { fg = bg_pos, bg = "bg_bar" },
    pos_text_anchor = { fg = c.fg2, bg = "bg_bar" },
    pos_text_percentage = { fg = c.fg2, bg = bg_pos, bold = true },
    python_env = { fg = c.fg3, bg = "bg_bar" },
    readonly = { fg = c.orange, bg = "bg_bar" },
    sidebar_blank = { fg = c.fg1, bg = "bg_bar" },
    sidebar_split = { fg = c.bg4, bg = "bg_bar" },
    sidebar_sep_command = { fg = mc.command, bg = "bg_bar", bold = true },
    sidebar_sep_confirm = { fg = mc.confirm, bg = "bg_bar", bold = true },
    sidebar_sep_insert = { fg = mc.insert, bg = "bg_bar", bold = true },
    sidebar_sep_normal = { fg = mc.normal, bg = "bg_bar", bold = true },
    sidebar_sep_nterminal = { fg = mc.nterminal, bg = "bg_bar", bold = true },
    sidebar_sep_replace = { fg = mc.replace, bg = "bg_bar", bold = true },
    sidebar_sep_select = { fg = mc.select, bg = "bg_bar", bold = true },
    sidebar_sep_terminal = { fg = mc.terminal, bg = "bg_bar", bold = true },
    sidebar_sep_visual = { fg = mc.visual, bg = "bg_bar", bold = true },
    sidebar_text_command = { fg = c.bg1, bg = mc.command, bold = true },
    sidebar_text_confirm = { fg = c.bg1, bg = mc.confirm, bold = true },
    sidebar_text_insert = { fg = c.bg1, bg = mc.insert, bold = true },
    sidebar_text_normal = { fg = c.bg1, bg = mc.normal, bold = true },
    sidebar_text_nterminal = { fg = c.bg1, bg = mc.nterminal, bold = true },
    sidebar_text_replace = { fg = c.bg1, bg = mc.replace, bold = true },
    sidebar_text_select = { fg = c.bg1, bg = mc.select, bold = true },
    sidebar_text_terminal = { fg = c.bg1, bg = mc.terminal, bold = true },
    sidebar_text_visual = { fg = c.bg1, bg = mc.visual, bold = true },
    tab_add = { fg = c.fg1, bg = c.bg3 },
    tab_item = { fg = c.fg1, bg = "bg_bar" },
    tab_item_cur = { fg = c.red, bg = bg_bufc },
    tab_toggle = { fg = c.bg1, bg = c.green },
    text = { fg = c.fg2, bg = "bg_bar" },
    username_text_command = { fg = mc.command, bg = bg_username, bold = true },
    username_text_confirm = { fg = mc.confirm, bg = bg_username, bold = true },
    username_text_insert = { fg = mc.insert, bg = bg_username, bold = true },
    username_text_normal = { fg = mc.normal, bg = bg_username, bold = true },
    username_text_nterminal = { fg = mc.nterminal, bg = bg_username, bold = true },
    username_text_replace = { fg = mc.replace, bg = bg_username, bold = true },
    username_text_select = { fg = mc.select, bg = bg_username, bold = true },
    username_text_terminal = { fg = mc.terminal, bg = bg_username, bold = true },
    username_text_visual = { fg = mc.visual, bg = bg_username, bold = true },
    username_sep_command = { fg = bg_username, bg = mc.command, bold = true },
    username_sep_confirm = { fg = bg_username, bg = mc.confirm, bold = true },
    username_sep_insert = { fg = bg_username, bg = mc.insert, bold = true },
    username_sep_normal = { fg = bg_username, bg = mc.normal, bold = true },
    username_sep_nterminal = { fg = bg_username, bg = mc.nterminal, bold = true },
    username_sep_replace = { fg = bg_username, bg = mc.replace, bold = true },
    username_sep_select = { fg = bg_username, bg = mc.select, bold = true },
    username_sep_terminal = { fg = bg_username, bg = mc.terminal, bold = true },
    username_sep_visual = { fg = bg_username, bg = mc.visual, bold = true },
    win_indicator_sep_command = { fg = mc.command, bg = c.bg1, bold = true },
    win_indicator_sep_confirm = { fg = mc.confirm, bg = c.bg1, bold = true },
    win_indicator_sep_insert = { fg = mc.insert, bg = c.bg1, bold = true },
    win_indicator_sep_normal = { fg = mc.normal, bg = c.bg1, bold = true },
    win_indicator_sep_nterminal = { fg = mc.nterminal, bg = c.bg1, bold = true },
    win_indicator_sep_replace = { fg = mc.replace, bg = c.bg1, bold = true },
    win_indicator_sep_select = { fg = mc.select, bg = c.bg1, bold = true },
    win_indicator_sep_terminal = { fg = mc.terminal, bg = c.bg1, bold = true },
    win_indicator_sep_visual = { fg = mc.visual, bg = c.bg1, bold = true },
    win_indicator_text_command = { fg = c.bg1, bg = mc.command, bold = true },
    win_indicator_text_confirm = { fg = c.bg1, bg = mc.confirm, bold = true },
    win_indicator_text_insert = { fg = c.bg1, bg = mc.insert, bold = true },
    win_indicator_text_normal = { fg = c.bg1, bg = mc.normal, bold = true },
    win_indicator_text_nterminal = { fg = c.bg1, bg = mc.nterminal, bold = true },
    win_indicator_text_replace = { fg = c.bg1, bg = mc.replace, bold = true },
    win_indicator_text_select = { fg = c.bg1, bg = mc.select, bold = true },
    win_indicator_text_terminal = { fg = c.bg1, bg = mc.terminal, bold = true },
    win_indicator_text_visual = { fg = c.bg1, bg = mc.visual, bold = true },
  }

  local positions = { "f_sl", "f_tl", "f_wl" } ---@type fml.ux.nvimbar.Position[]

  ---@class eve.constant.hlgroup.nvimbar : table<string, eve.t.theme.IHlgroup>
  ---@field public f_sl_bg              { bg: string, sp?: string }
  ---@field public f_tl_bg              { bg: string, sp?: string }
  ---@field public f_wl_bg              { bg: string, sp?: string }
  ---@field public f_sl_buf             { bg: string, sp?: string }
  ---@field public f_tl_buf             { bg: string, sp?: string }
  ---@field public f_wl_buf             { bg: string, sp?: string }
  ---@field public f_sl_bufc            { bg: string, sp?: string }
  ---@field public f_tl_bufc            { bg: string, sp?: string }
  ---@field public f_wl_bufc            { bg: string, sp?: string }
  ---@field public f_sl_filename        { bg: string, sp?: string }
  ---@field public f_tl_filename        { bg: string, sp?: string }
  ---@field public f_wl_filename        { bg: string, sp?: string }
  local results = {}
  for _, position in ipairs(positions) do
    for hlname, hlgroup in pairs(hlgroup_map) do
      results[position .. "_" .. hlname] = {
        fg = hlgroup.fg == "bg_bar" and bgs[position] or hlgroup.fg,
        bg = hlgroup.bg == "bg_bar" and bgs[position] or hlgroup.bg,
        sp = hlgroup.sp,
        bold = hlgroup.bold,
        italic = hlgroup.italic,
        link = hlgroup.link,
        reverse = hlgroup.reverse,
        strikethrough = hlgroup.strikethrough,
        undercurl = hlgroup.undercurl,
        underline = hlgroup.underline,
      }
    end
  end
  return results
end

return gen_hlgroup_map
