---@param context                       eve.t.theme.IContext
---@return table<string, eve.t.theme.IHlgroup>
local function gen_hlgroup_map(context)
  local cs = eve.std.color
  local c = context.scheme.palette ---@type eve.t.theme.IPalette
  local t = context.transparency ---@type boolean

  ---@type string
  local item_kind_bg = t and "none" or c.bg0

  return {
    ---! aerial.nvim
    AerialGuide = { fg = c.bg2 },
    AerialGuide1 = { fg = cs.mix(c.bg2, c.purple, 60) },
    AerialGuide2 = { fg = cs.mix(c.bg2, c.blue, 60) },
    AerialGuide3 = { fg = cs.mix(c.bg2, c.aqua, 60) },
    AerialGuide4 = { fg = cs.mix(c.bg2, c.green, 60) },
    AerialGuide5 = { fg = cs.mix(c.bg2, c.yellow, 60) },
    AerialGuide6 = { fg = cs.mix(c.bg2, c.orange, 60) },
    AerialGuide7 = { fg = cs.mix(c.bg2, c.red, 60) },
    AerialLine = { fg = c.yellow },
    AerialNormal = { bg = t and "none" or c.bg1 },
    AerialNormalNC = { link = "AerialNormal" },
    AerialCursorLine = { bg = c.bg2 },
    AerialCursorLineNr = { link = "AerialCursorLine" },

    AerialArrayIcon = { link = "f_sl_lsp_icon_Array" },
    AerialBooleanIcon = { link = "f_sl_lsp_icon_Boolean" },
    AerialClassIcon = { link = "f_sl_lsp_icon_Class" },
    AerialConstantIcon = { link = "f_sl_lsp_icon_Constant" },
    AerialConstructorIcon = { link = "f_sl_lsp_icon_Constructor" },
    AerialEnumIcon = { link = "f_sl_lsp_icon_Enum" },
    AerialEnumMemberIcon = { link = "f_sl_lsp_icon_EnumMember" },
    AerialEventIcon = { link = "f_sl_lsp_icon_Event" },
    AerialFieldIcon = { link = "f_sl_lsp_icon_Field" },
    AerialFileIcon = { link = "f_sl_lsp_icon_File" },
    AerialFunctionIcon = { link = "f_sl_lsp_icon_Function" },
    AerialInterfaceIcon = { link = "f_sl_lsp_icon_" },
    AerialKeyIcon = { link = "f_sl_lsp_icon_Key" },
    AerialMethodIcon = { link = "f_sl_lsp_icon_Method" },
    AerialModuleIcon = { link = "f_sl_lsp_icon_Module" },
    AerialNamespaceIcon = { link = "f_sl_lsp_icon_Namespace" },
    AerialNullIcon = { link = "f_sl_lsp_icon_Null" },
    AerialNumberIcon = { link = "f_sl_lsp_icon_Number" },
    AerialObjectIcon = { link = "f_sl_lsp_icon_Object" },
    AerialOperatorIcon = { link = "f_sl_lsp_icon_Operator" },
    AerialPackageIcon = { link = "f_sl_lsp_icon_Package" },
    AerialPropertyIcon = { link = "f_sl_lsp_icon_Property" },
    AerialStringIcon = { link = "f_sl_lsp_icon_String" },
    AerialStructIcon = { link = "f_sl_lsp_icon_Struct" },
    AerialTypeParameterIcon = { link = "f_sl_lsp_icon_TypeParameter" },
    AerialVariableIcon = { link = "f_sl_lsp_icon_Variable" },

    ---! avante.nvim
    AvanteConflictCurrent = { bg = c.diffDel, bold = true },
    AvanteConflictCurrentLabel = { bg = cs.mix(c.bg0, c.diffDel, 40) },
    AvanteConflictIncoming = { bg = c.diffAdd, bold = true },
    AvanteConflictIncomingLabel = { bg = cs.mix(c.bg0, c.diffAdd, 40) },
    AvanteInlineHint = { fg = c.pink, bg = "none", bold = true, italic = true },
    AvantePromptInput = { fg = c.fg1, bg = c.bg0 },
    AvantePromptInputBorder = { link = "FloatActiveBorder" },
    AvanteReversedSubtitle = { fg = c.yellow },
    AvanteReversedThirdTitle = { fg = c.blue },
    AvanteReversedTitle = { fg = c.aqua },
    AvantePopupHint = { fg = c.aqua, bg = "none", bold = true },
    AvanteSidebarWinSeparator = { fg = c.bg2 },
    AvanteSidebarWinHorizontalSeparator = { fg = c.blue },
    AvanteSubtitle = { fg = c.bg0, bg = c.yellow, bold = true },
    AvanteThirdTitle = { fg = c.bg0, bg = c.blue, bold = true },
    AvanteTitle = { fg = c.bg0, bg = c.aqua, bold = true },
    AvanteToBeDeleted = { bg = c.diffDelInline, strikethrough = true },
    AvanteToBeDeletedWOStrikethrough = { bg = c.diffDel },

    ---! cmp
    BlinkCmpDoc = { bg = t and "none" or c.bg0 },
    BlinkCmpDocBorder = { link = "FloatBorder" },
    BlinkCmpDocSeparator = { fg = c.bg4, bg = "none" },
    BlinkCmpGhostText = { link = "Comment", default = true },
    BlinkCmpKindClass = { fg = c.aqua, bg = item_kind_bg },
    BlinkCmpKindCodeium = { fg = c.green, bg = item_kind_bg },
    BlinkCmpKindColor = { fg = c.fg1, bg = item_kind_bg },
    BlinkCmpKindConstant = { fg = c.orange, bg = item_kind_bg },
    BlinkCmpKindConstructor = { fg = c.blue, bg = item_kind_bg },
    BlinkCmpKindCopilot = { fg = c.green, bg = item_kind_bg },
    BlinkCmpKindEnum = { fg = c.blue, bg = item_kind_bg },
    BlinkCmpKindEnumMember = { fg = c.purple, bg = item_kind_bg },
    BlinkCmpKindEvent = { fg = c.yellow, bg = item_kind_bg },
    BlinkCmpKindField = { fg = c.red, bg = item_kind_bg },
    BlinkCmpKindFile = { fg = c.fg1, bg = item_kind_bg },
    BlinkCmpKindFolder = { fg = c.fg1, bg = item_kind_bg },
    BlinkCmpKindFunction = { fg = c.blue, bg = item_kind_bg },
    BlinkCmpKindIdentifier = { fg = c.red, bg = item_kind_bg },
    BlinkCmpKindInterface = { fg = c.green, bg = item_kind_bg },
    BlinkCmpKindKeyword = { fg = c.fg1, bg = item_kind_bg },
    BlinkCmpKindMethod = { fg = c.blue, bg = item_kind_bg },
    BlinkCmpKindModule = { fg = c.yellow, bg = item_kind_bg },
    BlinkCmpKindOperator = { fg = c.fg1, bg = item_kind_bg },
    BlinkCmpKindProperty = { fg = c.red, bg = item_kind_bg },
    BlinkCmpKindReference = { fg = c.fg1, bg = item_kind_bg },
    BlinkCmpKindSnippet = { fg = c.red, bg = item_kind_bg },
    BlinkCmpKindStruct = { fg = c.purple, bg = item_kind_bg },
    BlinkCmpKindStructure = { fg = c.purple, bg = item_kind_bg },
    BlinkCmpKindTabNine = { fg = c.orange, bg = item_kind_bg },
    BlinkCmpKindText = { fg = c.green, bg = item_kind_bg },
    BlinkCmpKindType = { fg = c.yellow, bg = item_kind_bg },
    BlinkCmpKindTypeParameter = { fg = c.red, bg = item_kind_bg },
    BlinkCmpKindUnit = { fg = c.purple, bg = item_kind_bg },
    BlinkCmpKindValue = { fg = c.aqua, bg = item_kind_bg },
    BlinkCmpKindVariable = { fg = c.purple, bg = item_kind_bg },
    BlinkCmpLabel = { fg = c.fg4, italic = true, bg = item_kind_bg },
    BlinkCmpMenu = { fg = c.fg4, italic = true },
    BlinkCmpMenuBorder = { link = "FloatBorder" },
    BlinkCmpSignatureHelp = { bg = t and "none" or c.bg0 },
    BlinkCmpSignatureHelpActiveParameter = {},
    BlinkCmpSignatureHelpBorder = { link = "FloatBorder" },
    BlinkCmpSource = { fg = c.fg3, bg = item_kind_bg },

    ---! diffview.nvim
    DiffviewFilePanelDeletions = { fg = c.red, bold = true },
    DiffviewFilePanelInsertions = { fg = c.green, bold = true },
    DiffviewStatusModified = { fg = c.green, bold = true },

    ---! flash.nvim
    FlashBackdrop = { fg = c.bg4, bg = "none" },
    FlashCurrent = { fg = c.orange, bg = t and "none" or c.bg2, italic = true },
    FlashLabel = { fg = c.blue, bg = t and "none" or c.bg0, bold = true },
    FlashMatch = { fg = c.yellow, bg = t and "none" or c.bg1, italic = true },
    FlashPrompt = { fg = c.yellow, bg = c.bg2 },
    FlashPromptIcon = { fg = c.orange, bg = t and "none" or c.bg2 },

    ---! gitsigns.nvim
    GitSignsAdd = { fg = c.green },
    GitSignsAddNr = { link = "GitSignsAdd" },
    GitSignsChange = { fg = c.blue },
    GitSignsChangeNr = { link = "GitSignsChange" },
    GitSignsDelete = { fg = c.red },
    GitSignsDeleteNr = { link = "GitSignsDelete" },
    GitSignsTopdelete = { fg = c.red },
    GitSignsTopdeleteNr = { link = "GitSignsTopdelete" },
    GitSignsUntracked = { fg = c.grey },
    GitSignsUntrackedNr = { link = "GitSignsUntracked" },
    GitSignsStagedAdd = { fg = cs.mix(c.bg0, c.green, 50) },
    GitSignsStagedAddNr = { link = "GitSignsStagedAdd" },
    GitSignsStagedChange = { fg = cs.mix(c.bg0, c.blue, 50) },
    GitSignsStagedChangeNr = { link = "GitSignsStagedChange" },
    GitSignsStagedDelete = { fg = cs.mix(c.bg0, c.red, 50) },
    GitSignsStagedDeleteNr = { link = "GitSignsStagedDelete" },
    GitSignsStagedTopdelete = { fg = cs.mix(c.bg0, c.red, 50) },
    GitSignsStagedTopdeleteNr = { link = "GitSignsStagedTopdelete" },
    GitSignsStagedUntracked = { fg = cs.mix(c.bg0, c.grey, 50) },
    GitSignsStagedUntrackedNr = { link = "GitSignsStagedUntracked" },

    GitSignsCurrentLineBlame = { fg = c.bg4, italic = true },

    ---! indent-blankline.nvim
    IblChar = { fg = c.bg1 },
    IblScopeChar = { fg = c.grey },
    ["@ibl.scope.underline.0"] = { link = "IblChar" },
    ["@ibl.scope.underline.1"] = { fg = cs.mix(c.bg0, c.red, 32) },
    ["@ibl.scope.underline.2"] = { fg = cs.mix(c.bg0, c.green, 32) },
    ["@ibl.scope.underline.3"] = { fg = cs.mix(c.bg0, c.yellow, 32) },
    ["@ibl.scope.underline.4"] = { fg = cs.mix(c.bg0, c.blue, 32) },
    ["@ibl.scope.underline.5"] = { fg = cs.mix(c.bg0, c.purple, 32) },
    ["@ibl.scope.underline.6"] = { fg = cs.mix(c.bg0, c.aqua, 32) },
    ["@ibl.scope.underline.7"] = { fg = cs.mix(c.bg0, c.orange, 32) },

    ---! lazy.nvim
    LazyButton = { fg = c.fg2, bg = "none" },
    LazyButtonActive = { fg = c.bg1, bg = c.green, bold = true },
    LazyCommit = { fg = c.green },
    LazyCommitIssue = { fg = c.orange },
    LazyDir = { fg = c.fg1 },
    LazyH1 = { fg = c.bg1, bg = c.green, bold = true },
    LazyH2 = { fg = c.fg1, bold = true, underline = true },
    LazyNoCond = { fg = c.red },
    LazyOperator = { fg = c.fg1 },
    LazyProgressDone = { fg = c.green },
    LazyReasonCmd = { fg = c.yellow },
    LazyReasonEvent = { fg = c.yellow },
    LazyReasonFt = { fg = c.purple },
    LazyReasonImport = { fg = c.fg1 },
    LazyReasonKeys = { fg = c.brightAqua },
    LazyReasonPlugin = { fg = c.red },
    LazyReasonRuntime = { fg = c.purple },
    LazyReasonSource = { fg = c.aqua },
    LazyReasonStart = { fg = c.fg1 },
    LazySpecial = { fg = c.blue },
    LazyTaskOutput = { fg = c.fg1 },
    LazyUrl = { fg = c.fg1 },
    LazyValue = { fg = c.brightAqua },

    ---! mason.nvim
    MasonHeader = { fg = c.bg0, bg = c.red },
    MasonHighlight = { fg = c.blue },
    MasonHighlightBlock = { fg = c.bg0, bg = c.green },
    MasonHighlightBlockBold = { link = "MasonHighlightBlock" },
    MasonHeaderSecondary = { link = "MasonHighlightBlock" },
    MasonMuted = { fg = c.fg4 },
    MasonMutedBlock = { fg = c.bg4, bg = c.bg1 },

    ---! mini.hipatterns
    MiniHipatternsFixme = { fg = c.bg0, bg = c.red, bold = true, italic = true, underline = true },
    MiniHipatternsHack = { fg = c.bg0, bg = c.yellow, bold = true, italic = true, underline = true },
    MiniHipatternsTodo = { fg = c.bg0, bg = c.aqua, bold = true, italic = true, underline = true },
    MiniHipatternsNote = { fg = c.bg0, bg = c.purple, bold = true, italic = true, underline = true },

    ---! mini.icons
    MiniIconsAzure = { fg = c.blue },
    MiniIconsBlue = { fg = c.blue },
    MiniIconsCyan = { fg = c.aqua },
    MiniIconsGreen = { fg = c.green },
    MiniIconsGrey = { fg = c.fg2 },
    MiniIconsOrange = { fg = c.orange },
    MiniIconsPurple = { fg = c.purple },
    MiniIconsRed = { fg = c.red },
    MiniIconsYellow = { fg = c.yellow },

    ---! mini.indentscope
    MiniIndentscopeSymbol = { fg = c.pink },
    MiniIndentscopeSymbolOff = { fg = c.yellow },

    ---! neo-tree.nvim
    NeoTreeCursorLine = { bg = c.bg2 },
    NeoTreeDirectoryIcon = { link = "Directory" },
    NeoTreeDirectoryName = { fg = c.blue },
    NeoTreeExpander = { fg = c.fg4 },
    NeoTreeFileName = { fg = c.fg2 },
    NeoTreeFloatBorder = { link = "FloatBorder" },
    NeoTreeFloatTitle = { link = "FloatTitle" },
    NeoTreeGitIgnored = { fg = c.fg4 },
    NeoTreeGitModified = { fg = c.yellow },
    NeoTreeGitUntracked = { fg = c.orange },
    NeoTreeHiddenByName = { fg = c.fg4 },
    NeoTreeIndentMarker = { fg = c.bg2 },
    NeoTreeMessage = { fg = c.grey },
    NeoTreeNormal = { link = "Normal" },
    NeoTreeNormalNC = { link = "NormalNC" },
    NeoTreeRootName = { fg = c.fg1, bold = true },
    NeoTreeTab = { fg = c.fg4, bg = c.bg0, bold = true },
    NeoTreeTabActive = { fg = c.bg1, bg = c.aqua, bold = true },
    NeoTreeTabSeparator = { fg = c.bg0, bg = "none" },
    NeoTreeTabSeparatorActive = { fg = c.aqua, bg = "none" },
    NeoTreeTitleBar = { fg = c.fg4 },
    NeoTreeWinbar = { fg = "none", bg = "none" },

    ---! noice.nvim
    NoiceCmdlineIcon = { fg = c.green, bg = "none" },
    NoiceCmdlinePopup = { bg = c.bg0 },
    NoiceCmdlinePopupBorder = { fg = c.green, bg = c.bg0 },
    NoiceCompletionItemKindClass = { fg = c.aqua, bg = item_kind_bg },
    NoiceCompletionItemKindCodeium = { fg = c.green, bg = item_kind_bg },
    NoiceCompletionItemKindColor = { fg = c.fg1, bg = item_kind_bg },
    NoiceCompletionItemKindConstant = { fg = c.orange, bg = item_kind_bg },
    NoiceCompletionItemKindConstructor = { fg = c.blue, bg = item_kind_bg },
    NoiceCompletionItemKindCopilot = { fg = c.green, bg = item_kind_bg },
    NoiceCompletionItemKindEnum = { fg = c.blue, bg = item_kind_bg },
    NoiceCompletionItemKindEnumMember = { fg = c.purple, bg = item_kind_bg },
    NoiceCompletionItemKindEvent = { fg = c.yellow, bg = item_kind_bg },
    NoiceCompletionItemKindField = { fg = c.red, bg = item_kind_bg },
    NoiceCompletionItemKindFile = { fg = c.fg1, bg = item_kind_bg },
    NoiceCompletionItemKindFolder = { fg = c.fg1, bg = item_kind_bg },
    NoiceCompletionItemKindFunction = { fg = c.blue, bg = item_kind_bg },
    NoiceCompletionItemKindIdentifier = { fg = c.red, bg = item_kind_bg },
    NoiceCompletionItemKindInterface = { fg = c.green, bg = item_kind_bg },
    NoiceCompletionItemKindKeyword = { fg = c.fg1, bg = item_kind_bg },
    NoiceCompletionItemKindMethod = { fg = c.blue, bg = item_kind_bg },
    NoiceCompletionItemKindModule = { fg = c.yellow, bg = item_kind_bg },
    NoiceCompletionItemKindOperator = { fg = c.fg1, bg = item_kind_bg },
    NoiceCompletionItemKindProperty = { fg = c.red, bg = item_kind_bg },
    NoiceCompletionItemKindReference = { fg = c.fg1, bg = item_kind_bg },
    NoiceCompletionItemKindSnippet = { fg = c.red, bg = item_kind_bg },
    NoiceCompletionItemKindStruct = { fg = c.purple, bg = item_kind_bg },
    NoiceCompletionItemKindStructure = { fg = c.purple, bg = item_kind_bg },
    NoiceCompletionItemKindTabNine = { fg = c.orange, bg = item_kind_bg },
    NoiceCompletionItemKindText = { fg = c.green, bg = item_kind_bg },
    NoiceCompletionItemKindType = { fg = c.yellow, bg = item_kind_bg },
    NoiceCompletionItemKindTypeParameter = { fg = c.red, bg = item_kind_bg },
    NoiceCompletionItemKindUnit = { fg = c.purple, bg = item_kind_bg },
    NoiceCompletionItemKindValue = { fg = c.aqua, bg = item_kind_bg },
    NoiceCompletionItemKindVariable = { fg = c.purple, bg = item_kind_bg },

    ---! nvim-dap
    DapBreakpoint = { fg = c.red },
    DapBreakpointCondition = { fg = c.yellow },
    DapBreakpointRejected = { fg = c.fg4 },
    DapLogPoint = { fg = c.aqua },
    DapStopped = { fg = c.orange },
    DapStoppedLine = { bg = cs.mix(c.bg0, c.yellow, 40), blend = 50, reverse = false },

    ---! nvim-dap-ui
    DapUIBreakpointsCurrentLine = { fg = c.green, bold = true },
    DapUIBreakpointsDisabledLine = { fg = c.fg4 },
    DapUIBreakpointsInfo = { fg = c.green },
    DapUIBreakpointsLine = { fg = c.aqua },
    DapUIBreakpointsPath = { fg = c.aqua },
    DapUICurrentFrameName = { fg = c.green, bold = true },
    DapUIDecoration = { fg = c.aqua },
    DapUIEndofBuffer = { link = "EndofBuffer" },
    DapUIFloatBorder = { link = "FloatBorder" },
    DapUIFloatNormal = { link = "NormalFloat" },
    DapUIFrameName = { link = "Normal" },
    DapUILineNumber = { fg = c.aqua },
    DapUIModifiedValue = { fg = c.orange },
    DapUINormal = { link = "Normal" },
    DapUIPlayPause = { fg = c.green },
    DapUIPlayPauseNC = { fg = c.green },
    DapUIRestart = { fg = c.green },
    DapUIRestartNC = { fg = c.green },
    DapUIScope = { fg = c.aqua },
    DapUISource = { fg = c.purple },
    DapUIStepBack = { fg = c.aqua },
    DapUIStepBackNC = { fg = c.blue },
    DapUIStepInto = { fg = c.aqua },
    DapUIStepIntoNC = { fg = c.blue },
    DapUIStepOut = { fg = c.aqua },
    DapUIStepOutNC = { fg = c.blue },
    DapUIStepOver = { fg = c.aqua },
    DapUIStepOverNC = { fg = c.blue },
    DapUIStop = { fg = c.red },
    DapUIStopNC = { fg = c.red },
    DapUIStoppedThread = { fg = c.aqua },
    DapUIThread = { fg = c.green },
    DapUIType = { fg = c.purple },
    DapUIUnavailable = { fg = c.fg4 },
    DapUIUnavailableNC = { fg = c.fg4 },
    DapUIValue = { fg = c.aqua },
    DapUIVariable = { fg = c.fg1 },
    DapUIWatchesEmpty = { fg = c.red },
    DapUIWatchesError = { fg = c.red },
    DapUIWatchesValue = { fg = c.green },
    DapUIWinSelect = { fg = c.aqua, bold = true },

    ---! nvim-dap-virtual-text
    NvimDapVirtualText = { fg = c.fg2, bg = cs.mix(c.bg0, c.orange, 30), italic = true },
    NvimDapVirtualTextChanged = { fg = c.fg0, bg = cs.mix(c.bg0, c.orange, 30), italic = true },

    ---! nvim-notify
    NotifyERRORBorder = { fg = c.red, bg = t and c.bg0 or "none" },
    NotifyWARNBorder = { fg = c.yellow, bg = t and c.bg0 or "none" },
    NotifyINFOBorder = { fg = c.green, bg = t and c.bg0 or "none" },
    NotifyDEBUGBorder = { fg = c.orange, bg = t and c.bg0 or "none" },
    NotifyTRACEBorder = { fg = c.bg4, bg = t and c.bg0 or "none" },

    NotifyERRORBody = { fg = c.fg1, bg = c.bg0 },
    NotifyWARNBody = { fg = c.fg1, bg = c.bg0 },
    NotifyINFOBody = { fg = c.fg1, bg = c.bg0 },
    NotifyDEBUGBody = { fg = c.fg1, bg = c.bg0 },
    NotifyTRACEBody = { fg = c.fg1, bg = c.bg0 },

    NotifyERRORIcon = { fg = c.red },
    NotifyWARNIcon = { fg = c.yellow },
    NotifyINFOIcon = { fg = c.green },
    NotifyDEBUGIcon = { fg = c.orange },
    NotifyTRACEIcon = { fg = c.bg4 },

    NotifyERRORTitle = { link = "NotifyERRORIcon" },
    NotifyWARNTitle = { link = "NotifyWARNIcon" },
    NotifyINFOTitle = { link = "NotifyINFOIcon" },
    NotifyDEBUGTitle = { link = "NotifyDEBUGIcon" },
    NotifyTRACETitle = { link = "NotifyTRACEIcon" },

    ---! nvim-treesitter-context
    TreesitterContext = { fg = c.fg1, bg = c.bg2 },
    TreesitterContextBottom = {},
    TreesitterContextLineNumber = { fg = c.orange },
    TreesitterContextLineNumberBottom = { underline = true },

    ---! render-markdown.nvim
    RenderMarkdownCode = { bg = c.bg2 },
    RenderMarkdownCodeInline = { fg = c.orange, bg = c.bg4 },
    RenderMarkdownCodeBorder = { fg = c.aqua, bg = c.bg2 },
    RenderMarkdownH1Bg = { bg = "none" },
    RenderMarkdownH2Bg = { bg = "none" },
    RenderMarkdownH3Bg = { bg = "none" },
    RenderMarkdownH4Bg = { bg = "none" },
    RenderMarkdownH5Bg = { bg = "none" },
    RenderMarkdownH6Bg = { bg = "none" },
    RenderMarkdownQuote = { fg = c.fg1, bg = c.bg2 },
    RenderMarkdownList = { fg = c.blue, bold = true },
    RenderMarkdownListMarker = { fg = c.orange },
    RenderMarkdownLink = { fg = c.aqua, underline = true },
    RenderMarkdownLinkText = { fg = c.blue },
    RenderMarkdownCheckboxChecked = { fg = c.green, bold = true },
    RenderMarkdownCheckboxUnchecked = { fg = c.red },

    ---! trouble.nvim
    TroubleCode = { fg = c.fg1 },
    TroubleCount = { fg = c.purple },
    TroubleError = { fg = c.red },
    TroubleFile = { fg = c.yellow },
    TroubleFoldIcon = { link = "Folded" },
    TroubleHint = { fg = c.orange },
    TroubleIndent = { link = "Comment" },
    TroubleInformation = { fg = c.fg1 },
    TroubleLocation = { fg = c.red },
    TroubleNormal = { fg = c.fg1 },
    TroublePreview = { fg = c.red },
    TroubleSignError = { link = "DiagnosticError" },
    TroubleSignHint = { link = "DiagnosticHint" },
    TroubleSignInformation = { fg = c.fg1 },
    TroubleSignOther = { link = "DiagnosticNormal" },
    TroubleSignWarning = { link = "DiagnosticWarn" },
    TroubleSource = { fg = c.aqua },
    TroubleText = { fg = c.fg1 },
    TroubleTextError = { fg = c.fg1 },
    TroubleTextHint = { fg = c.fg1 },
    TroubleTextInformation = { fg = c.fg1 },
    TroubleTextWarning = { fg = c.fg1 },
    TroubleWarning = { fg = c.orange },

    ---! which-key.nvim
    WhichKey = { fg = c.blue },
    WhichKeyDesc = { fg = c.fg3 },
    WhichKeyGroup = { fg = c.blue },
    WhichKeyIconAzure = { fg = c.blue },
    WhichKeyIconBlue = { fg = c.blue },
    WhichKeyIconCyan = { fg = c.aqua },
    WhichKeyIconGreen = { fg = c.green },
    WhichKeyIconGrey = { fg = c.bg4 },
    WhichKeyIconOrange = { fg = c.orange },
    WhichKeyIconPurple = { fg = c.purple },
    WhichKeyIconRed = { fg = c.red },
    WhichKeyIconYellow = { fg = c.yellow },
    WhichKeySeparator = { fg = c.bg4 },
    WhichKeyValue = { fg = c.green },
  }
end

return gen_hlgroup_map
