---@class eve.constant.hlgroup.plugin
local M = {}

---@param context                       std.t.theme.IContext
---@return table<string, std.t.theme.IHlgroup>
function M.gen_hlgroup_map(context)
  local cs = std.color
  local c = context.scheme.palette ---@type std.t.theme.IPalette
  local t = context.transparency ---@type boolean

  ---@type string
  local item_kind_bg = t and c.none or c.bg0

  ---@type table<string, std.t.theme.IHlgroup>
  return {
    ---! avante.nvim
    AvanteAnnotation = { link = "Comment" },
    AvanteButtonDanger = { fg = c.bg0, bg = c.fg2 },
    AvanteButtonDangerHover = { fg = c.bg0, bg = c.red },
    AvanteButtonDefault = { fg = c.bg0, bg = c.fg2 },
    AvanteButtonDefaultHover = { fg = c.bg0, bg = c.green },
    AvanteButtonPrimary = { fg = c.bg0, bg = c.fg2 },
    AvanteButtonPrimaryHover = { fg = c.bg0, bg = c.blue },
    AvanteCommentFg = { fg = c.fg4 },
    AvanteConfirmTitle = { fg = c.bg0, bg = c.red, bold = true },
    AvanteConflictCurrent = { bg = c.diffDel, bold = true },
    AvanteConflictCurrentLabel = { bg = cs.mix(c.bg0, c.diffDel, 40) },
    AvanteConflictIncoming = { bg = c.diffAdd, bold = true },
    AvanteConflictIncomingLabel = { bg = cs.mix(c.bg0, c.diffAdd, 40) },
    AvanteInlineHint = { fg = c.pink, bg = c.none, bold = true, italic = true },
    AvantePromptInput = { fg = c.fg1, bg = c.bg0 },
    AvantePromptInputBorder = { link = "FloatActiveBorder" },
    AvanteReversedNormal = { fg = c.bg0, bg = c.fg1 },
    AvanteReversedSubtitle = { fg = c.yellow },
    AvanteReversedThirdTitle = { link = t and "ms_b_none" or "ms_b_bg0" },
    AvanteReversedTitle = { link = t and "ms_b_none" or "ms_b_bg0" },
    AvantePopupHint = { link = t and "ms_b_none" or "ms_b_bg0" },
    AvanteSidebarNormal = { bg = t and c.none or c.bg0 },
    AvanteSidebarWinSeparator = { fg = c.bg2 },
    AvanteSidebarWinHorizontalSeparator = { fg = c.blue },
    AvanteStateSpinnerCompacting = { fg = c.bg0, bg = c.purple, bold = true, italic = true },
    AvanteStateSpinnerFailed = { fg = c.bg0, bg = c.red, bold = true, italic = true },
    AvanteStateSpinnerGenerating = { fg = c.bg0, bg = c.purple, bold = true, italic = true },
    AvanteStateSpinnerSearching = { fg = c.bg0, bg = c.purple, bold = true, italic = true },
    AvanteStateSpinnerSucceeded = { fg = c.bg0, bg = c.green, bold = true, italic = true },
    AvanteStateSpinnerThinking = { fg = c.bg0, bg = c.purple, bold = true, italic = true },
    AvanteStateSpinnerToolCalling = { fg = c.bg0, bg = c.blue, bold = true, italic = true },
    AvanteSubtitle = { fg = c.bg1, bg = c.yellow, bold = true },
    AvanteSuggestion = { link = "Comment" },
    AvanteTaskCompleted = { fg = c.green, bg = c.bg0, bold = true },
    AvanteThinking = { fg = c.purple, bold = true },
    AvanteThirdTitle = { link = "mf_b_bg0" },
    AvanteTitle = { link = "mf_b_bg0" },
    AvanteToBeDeleted = { bg = c.diffDelInline, strikethrough = true },
    AvanteToBeDeletedWOStrikethrough = { bg = c.diffDel },

    ---! cmp
    BlinkCmpDoc = { bg = t and c.none or c.bg0 },
    BlinkCmpDocBorder = { link = "FloatBorder" },
    BlinkCmpDocSeparator = { fg = c.bg4, bg = c.none },
    BlinkCmpGhostText = { link = "Comment", default = true },
    BlinkCmpItemIdx = { fg = c.fg3, bg = item_kind_bg },
    BlinkCmpKindClass = { fg = c.aqua, bg = item_kind_bg },
    BlinkCmpKindCodeium = { fg = c.green, bg = item_kind_bg },
    BlinkCmpKindColor = { fg = c.fg1, bg = item_kind_bg },
    BlinkCmpKindConstant = { fg = c.orange, bg = item_kind_bg },
    BlinkCmpKindConstructor = { fg = c.blue, bg = item_kind_bg },
    BlinkCmpKindCopilot = { fg = c.green, bg = item_kind_bg },
    BlinkCmpKindEnum = { fg = c.blue, bg = item_kind_bg },
    BlinkCmpKindEnumMember = { fg = c.purple, bg = item_kind_bg },
    BlinkCmpKindEvent = { fg = c.yellow, bg = item_kind_bg },
    BlinkCmpKindField = { fg = c.red, bg = item_kind_bg },
    BlinkCmpKindFile = { fg = c.fg1, bg = item_kind_bg },
    BlinkCmpKindFolder = { fg = c.fg1, bg = item_kind_bg },
    BlinkCmpKindFunction = { fg = c.blue, bg = item_kind_bg },
    BlinkCmpKindIdentifier = { fg = c.red, bg = item_kind_bg },
    BlinkCmpKindInterface = { fg = c.green, bg = item_kind_bg },
    BlinkCmpKindKeyword = { fg = c.fg1, bg = item_kind_bg },
    BlinkCmpKindMethod = { fg = c.blue, bg = item_kind_bg },
    BlinkCmpKindModule = { fg = c.yellow, bg = item_kind_bg },
    BlinkCmpKindOperator = { fg = c.fg1, bg = item_kind_bg },
    BlinkCmpKindProperty = { fg = c.red, bg = item_kind_bg },
    BlinkCmpKindReference = { fg = c.fg1, bg = item_kind_bg },
    BlinkCmpKindSnippet = { fg = c.red, bg = item_kind_bg },
    BlinkCmpKindStruct = { fg = c.purple, bg = item_kind_bg },
    BlinkCmpKindStructure = { fg = c.purple, bg = item_kind_bg },
    BlinkCmpKindTabNine = { fg = c.orange, bg = item_kind_bg },
    BlinkCmpKindText = { fg = c.green, bg = item_kind_bg },
    BlinkCmpKindType = { fg = c.yellow, bg = item_kind_bg },
    BlinkCmpKindTypeParameter = { fg = c.red, bg = item_kind_bg },
    BlinkCmpKindUnit = { fg = c.purple, bg = item_kind_bg },
    BlinkCmpKindValue = { fg = c.aqua, bg = item_kind_bg },
    BlinkCmpKindVariable = { fg = c.purple, bg = item_kind_bg },
    BlinkCmpLabel = { fg = c.fg4, italic = true, bg = item_kind_bg },
    BlinkCmpMenu = { fg = c.fg4, italic = true },
    BlinkCmpMenuBorder = { link = "FloatBorder" },
    BlinkCmpSignatureHelp = { bg = t and c.none or c.bg0 },
    BlinkCmpSignatureHelpActiveParameter = { link = "LspSignatureActiveParameter" },
    BlinkCmpSignatureHelpBorder = { link = "FloatBorder" },
    BlinkCmpSource = { fg = c.fg3, bg = item_kind_bg },

    ---! diffview.nvim
    DiffviewFilePanelDeletions = { fg = c.red, bold = true },
    DiffviewFilePanelInsertions = { fg = c.green, bold = true },
    DiffviewStatusModified = { fg = c.green, bold = true },

    ---! flash.nvim
    FlashBackdrop = { fg = c.bg4, bg = c.none },
    FlashCurrent = { fg = c.orange, bg = t and c.none or c.bg2, italic = true },
    FlashLabel = { fg = c.blue, bg = t and c.none or c.bg0, bold = true },
    FlashMatch = { fg = c.yellow, bg = t and c.none or c.bg1, italic = true },
    FlashPrompt = { fg = c.yellow, bg = c.bg2 },
    FlashPromptIcon = { fg = c.orange, bg = t and c.none or c.bg2 },

    ---! gitsigns.nvim
    GitSignsAdd = { fg = c.green },
    GitSignsAddNr = { link = "GitSignsAdd" },
    GitSignsChange = { fg = c.blue },
    GitSignsChangeNr = { link = "GitSignsChange" },
    GitSignsDelete = { fg = c.red },
    GitSignsDeleteNr = { link = "GitSignsDelete" },
    GitSignsTopdelete = { fg = c.red },
    GitSignsTopdeleteNr = { link = "GitSignsTopdelete" },
    GitSignsUntracked = { fg = c.grey },
    GitSignsUntrackedNr = { link = "GitSignsUntracked" },
    GitSignsStagedAdd = { fg = cs.mix(c.bg0, c.green, 50) },
    GitSignsStagedAddNr = { link = "GitSignsStagedAdd" },
    GitSignsStagedChange = { fg = cs.mix(c.bg0, c.blue, 50) },
    GitSignsStagedChangeNr = { link = "GitSignsStagedChange" },
    GitSignsStagedDelete = { fg = cs.mix(c.bg0, c.red, 50) },
    GitSignsStagedDeleteNr = { link = "GitSignsStagedDelete" },
    GitSignsStagedTopdelete = { fg = cs.mix(c.bg0, c.red, 50) },
    GitSignsStagedTopdeleteNr = { link = "GitSignsStagedTopdelete" },
    GitSignsStagedUntracked = { fg = cs.mix(c.bg0, c.grey, 50) },
    GitSignsStagedUntrackedNr = { link = "GitSignsStagedUntracked" },
    GitSignsCurrentLineBlame = { fg = c.bg4, italic = true },

    ---! lazy.nvim
    LazyButton = { fg = c.fg2, bg = c.none },
    LazyButtonActive = { fg = c.bg1, bg = c.orange, bold = true },
    LazyCommit = { fg = c.green },
    LazyCommitIssue = { fg = c.orange },
    LazyDir = { fg = c.fg1 },
    LazyH1 = { fg = c.bg2, bg = c.orange, bold = true },
    LazyH2 = { fg = c.fg2, bold = true, underline = true },
    LazyNoCond = { fg = c.red },
    LazyNormal = { bg = cs.mix(c.bg0, c.bg1, 80), blend = 50 },
    LazyOperator = { fg = c.fg1 },
    LazyProgressDone = { fg = c.green },
    LazyReasonCmd = { fg = c.yellow },
    LazyReasonEvent = { fg = c.yellow },
    LazyReasonFt = { fg = c.purple },
    LazyReasonImport = { fg = c.fg1 },
    LazyReasonKeys = { fg = c.brightAqua },
    LazyReasonPlugin = { fg = c.red },
    LazyReasonRuntime = { fg = c.purple },
    LazyReasonSource = { fg = c.aqua },
    LazyReasonStart = { fg = c.fg1 },
    LazySpecial = { fg = c.blue },
    LazyTaskOutput = { fg = c.fg1 },
    LazyUrl = { fg = c.fg1 },
    LazyValue = { fg = c.brightAqua },

    ---! mason.nvim
    MasonHeader = { fg = c.bg0, bg = c.red },
    MasonHighlight = { fg = c.blue },
    MasonHighlightBlock = { fg = c.bg0, bg = c.green },
    MasonHighlightBlockBold = { link = "MasonHighlightBlock" },
    MasonHeaderSecondary = { link = "MasonHighlightBlock" },
    MasonMuted = { fg = c.fg4 },
    MasonMutedBlock = { fg = c.bg4, bg = c.bg1 },
    MasonNormal = { bg = cs.mix(c.bg0, c.bg1, 80), blend = 50 },

    ---! mini.hipatterns
    MiniHipatternsFixme = { fg = c.bg0, bg = c.red, bold = true, italic = true, underline = true },
    MiniHipatternsHack = { fg = c.bg0, bg = c.yellow, bold = true, italic = true, underline = true },
    MiniHipatternsTodo = { fg = c.bg0, bg = c.aqua, bold = true, italic = true, underline = true },
    MiniHipatternsNote = { fg = c.bg0, bg = c.purple, bold = true, italic = true, underline = true },

    ---! mini.icons
    MiniIconsAzure = { fg = c.blue },
    MiniIconsBlue = { fg = c.blue },
    MiniIconsCyan = { fg = c.aqua },
    MiniIconsGreen = { fg = c.green },
    MiniIconsGrey = { fg = c.fg2 },
    MiniIconsOrange = { fg = c.orange },
    MiniIconsPurple = { fg = c.purple },
    MiniIconsRed = { fg = c.red },
    MiniIconsYellow = { fg = c.yellow },

    ---! mini.indentscope
    MiniIndentscopeSymbol = { fg = c.pink },
    MiniIndentscopeSymbolOff = { fg = c.yellow },

    ---! neo-tree.nvim
    NeoTreeCursorLine = { bg = c.bg2 },
    NeoTreeDirectoryIcon = { link = "Directory" },
    NeoTreeDirectoryName = { fg = c.blue },
    NeoTreeExpander = { fg = c.fg4 },
    NeoTreeFileName = { fg = c.fg2 },
    NeoTreeFloatBorder = { link = "FloatBorder" },
    NeoTreeFloatTitle = { link = "FloatTitle" },
    NeoTreeGitIgnored = { fg = c.fg4 },
    NeoTreeGitModified = { fg = c.yellow },
    NeoTreeGitUntracked = { fg = c.orange },
    NeoTreeHiddenByName = { fg = c.fg4 },
    NeoTreeIndentMarker = { fg = c.bg2 },
    NeoTreeMessage = { fg = c.grey },
    NeoTreeNormal = { link = "Normal" },
    NeoTreeNormalNC = { link = "NormalNC" },
    NeoTreeRootName = { fg = c.fg1, bold = true },
    NeoTreeTab = { fg = c.fg4, bg = c.bg0, bold = true },
    NeoTreeTabActive = { fg = c.bg1, bg = c.aqua, bold = true },
    NeoTreeTabSeparator = { fg = c.bg0, bg = c.none },
    NeoTreeTabSeparatorActive = { fg = c.aqua, bg = c.none },
    NeoTreeTitleBar = { fg = c.fg4 },
    NeoTreeWinbar = { fg = c.none, bg = c.none },

    ---! nvim-dap
    DapBreakpoint = { fg = c.red },
    DapBreakpointCondition = { fg = c.yellow },
    DapBreakpointRejected = { fg = c.fg4 },
    DapLogPoint = { fg = c.aqua },
    DapStopped = { fg = c.orange },
    DapStoppedLine = { bg = cs.mix(c.bg0, c.yellow, 40), blend = 50, reverse = false },

    ---! nvim-dap-ui
    DapUIBreakpointsCurrentLine = { fg = c.green, bold = true },
    DapUIBreakpointsDisabledLine = { fg = c.fg4 },
    DapUIBreakpointsInfo = { fg = c.green },
    DapUIBreakpointsLine = { fg = c.aqua },
    DapUIBreakpointsPath = { fg = c.aqua },
    DapUICurrentFrameName = { fg = c.green, bold = true },
    DapUIDecoration = { fg = c.aqua },
    DapUIEndofBuffer = { link = "EndofBuffer" },
    DapUIFloatBorder = { link = "FloatBorder" },
    DapUIFloatNormal = { link = "NormalFloat" },
    DapUIFrameName = { link = "Normal" },
    DapUILineNumber = { fg = c.aqua },
    DapUIModifiedValue = { fg = c.orange },
    DapUINormal = { link = "Normal" },
    DapUIPlayPause = { fg = c.green },
    DapUIPlayPauseNC = { fg = c.green },
    DapUIRestart = { fg = c.green },
    DapUIRestartNC = { fg = c.green },
    DapUIScope = { fg = c.aqua },
    DapUISource = { fg = c.purple },
    DapUIStepBack = { fg = c.aqua },
    DapUIStepBackNC = { fg = c.blue },
    DapUIStepInto = { fg = c.aqua },
    DapUIStepIntoNC = { fg = c.blue },
    DapUIStepOut = { fg = c.aqua },
    DapUIStepOutNC = { fg = c.blue },
    DapUIStepOver = { fg = c.aqua },
    DapUIStepOverNC = { fg = c.blue },
    DapUIStop = { fg = c.red },
    DapUIStopNC = { fg = c.red },
    DapUIStoppedThread = { fg = c.aqua },
    DapUIThread = { fg = c.green },
    DapUIType = { fg = c.purple },
    DapUIUnavailable = { fg = c.fg4 },
    DapUIUnavailableNC = { fg = c.fg4 },
    DapUIValue = { fg = c.aqua },
    DapUIVariable = { fg = c.fg1 },
    DapUIWatchesEmpty = { fg = c.red },
    DapUIWatchesError = { fg = c.red },
    DapUIWatchesValue = { fg = c.green },
    DapUIWinSelect = { fg = c.aqua, bold = true },

    ---! nvim-dap-virtual-text
    NvimDapVirtualText = { fg = c.fg2, bg = cs.mix(c.bg0, c.orange, 30), italic = true },
    NvimDapVirtualTextChanged = { fg = c.fg0, bg = cs.mix(c.bg0, c.orange, 30), italic = true },

    NotifyERRORIcon = { fg = c.red },
    NotifyWARNIcon = { fg = c.yellow },
    NotifyINFOIcon = { fg = c.green },
    NotifyDEBUGIcon = { fg = c.orange },
    NotifyTRACEIcon = { fg = c.bg4 },

    NotifyERRORTitle = { link = "NotifyERRORIcon" },
    NotifyWARNTitle = { link = "NotifyWARNIcon" },
    NotifyINFOTitle = { link = "NotifyINFOIcon" },
    NotifyDEBUGTitle = { link = "NotifyDEBUGIcon" },
    NotifyTRACETitle = { link = "NotifyTRACEIcon" },

    ---! nvim-treesitter-context
    TreesitterContext = { fg = c.fg1, bg = c.bg2 },
    TreesitterContextBottom = {},
    TreesitterContextLineNumber = { fg = c.orange },
    TreesitterContextLineNumberBottom = { underline = true },

    ---! render-markdown.nvim
    RenderMarkdownBullet = { fg = c.fg4 },
    RenderMarkdownCode = { bg = c.bg2 },
    RenderMarkdownCodeInline = { fg = c.orange, bg = c.bg4 },
    RenderMarkdownCodeBorder = { fg = c.aqua, bg = c.bg2 },
    RenderMarkdownH1Bg = { bg = c.none },
    RenderMarkdownH2Bg = { bg = c.none },
    RenderMarkdownH3Bg = { bg = c.none },
    RenderMarkdownH4Bg = { bg = c.none },
    RenderMarkdownH5Bg = { bg = c.none },
    RenderMarkdownH6Bg = { bg = c.none },
    RenderMarkdownQuote = { fg = c.fg1, bg = c.bg2 },
    RenderMarkdownList = { fg = c.blue, bold = true },
    RenderMarkdownListMarker = { fg = c.orange },
    RenderMarkdownLink = { fg = c.aqua, underline = true },
    RenderMarkdownLinkText = { fg = c.blue },
    RenderMarkdownCheckboxChecked = { fg = c.green, bold = true },
    RenderMarkdownCheckboxUnchecked = { fg = c.red },

    ---! which-key.nvim
    WhichKey = { fg = c.blue },
    WhichKeyDesc = { fg = c.fg3 },
    WhichKeyGroup = { fg = c.blue },
    WhichKeyIconAzure = { fg = c.blue },
    WhichKeyIconBlue = { fg = c.blue },
    WhichKeyIconCyan = { fg = c.aqua },
    WhichKeyIconGreen = { fg = c.green },
    WhichKeyIconGrey = { fg = c.bg4 },
    WhichKeyIconOrange = { fg = c.orange },
    WhichKeyIconPurple = { fg = c.purple },
    WhichKeyIconRed = { fg = c.red },
    WhichKeyIconYellow = { fg = c.yellow },
    WhichKeySeparator = { fg = c.bg4 },
    WhichKeyValue = { fg = c.green },
  }
end

return M
