## Unbind digits
bind 1  send-keys C-a 1
bind 2  send-keys C-a 2
bind 3  send-keys C-a 3
bind 4  send-keys C-a 4
bind 5  send-keys C-a 5
bind 6  send-keys C-a 6
bind 7  send-keys C-a 7
bind 8  send-keys C-a 8
bind 9  send-keys C-a 9
bind 0  send-keys C-a 0

## Unbind lowercase letters
bind a  send-keys C-a a
bind b  send-keys C-a b
bind c  send-keys C-a c
bind d  send-keys C-a d
bind e  send-keys C-a e
bind f  send-keys C-a f
bind g  send-keys C-a g
bind h  send-keys C-a h
bind i  send-keys C-a i
bind j  send-keys C-a j
bind k  send-keys C-a k
bind l  send-keys C-a l
bind m  send-keys C-a m
bind n  send-keys C-a n
bind o  send-keys C-a o
bind p  send-keys C-a p
bind q  send-keys C-a q
bind r  send-keys C-a r
bind s  send-keys C-a s
bind t  send-keys C-a t
bind u  send-keys C-a u
bind v  send-keys C-a v
bind w  send-keys C-a w
bind x  send-keys C-a x
bind y  send-keys C-a y
bind z  send-keys C-a z

## Unbind uppercase letters
bind A  send-keys C-a A
bind B  send-keys C-a B
bind C  send-keys C-a C
bind D  send-keys C-a D
bind E  send-keys C-a E
bind F  send-keys C-a F
bind G  send-keys C-a G
bind H  send-keys C-a H
bind I  send-keys C-a I
bind J  send-keys C-a J
bind K  send-keys C-a K
bind L  send-keys C-a L
bind M  send-keys C-a M
bind N  send-keys C-a N
bind O  send-keys C-a O
bind P  send-keys C-a P
bind Q  send-keys C-a Q
bind R  send-keys C-a R
bind S  send-keys C-a S
bind T  send-keys C-a T
bind U  send-keys C-a U
bind V  send-keys C-a V
bind W  send-keys C-a W
bind X  send-keys C-a X
bind Y  send-keys C-a Y
bind Z  send-keys C-a Z

## Unbind function keys
unbind F1
unbind F2
unbind F3
unbind F4
unbind F5
unbind F6
unbind F7
unbind F8
unbind F9
unbind F10
unbind F11
unbind F12
unbind S-F1
unbind S-F2
unbind S-F3
unbind S-F4
unbind S-F5
unbind S-F6
unbind S-F7
unbind S-F8
unbind S-F9
unbind S-F10
unbind S-F11
unbind S-F12

## Unbind control-letters
unbind C-a
unbind C-b
unbind C-c
unbind C-d
unbind C-e
unbind C-f
unbind C-g
unbind C-h
unbind C-i
unbind C-j
unbind C-k
unbind C-l
unbind C-m
unbind C-n
unbind C-o
unbind C-p
unbind C-q
unbind C-r
unbind C-s
unbind C-t
unbind C-u
unbind C-v
unbind C-w
unbind C-x
unbind C-y
unbind C-z

## Unbind arrow keys
unbind Up
unbind Down
unbind Left
unbind Right
unbind C-Up
unbind C-Down
unbind C-Left
unbind C-Right
unbind M-Up
unbind M-Down
unbind M-Left
unbind M-Right
unbind S-Up
unbind S-Down
unbind S-Left
unbind S-Right
unbind C-M-Up
unbind C-M-Down
unbind C-M-Left
unbind C-M-Right
unbind C-S-Up
unbind C-S-Down
unbind C-S-Left
unbind C-S-Right

## Unbind symbols
unbind '!'
unbind '@'
unbind '#'
unbind '$'
unbind '%'
unbind '^'
unbind '&'
unbind '*'
unbind '('
unbind ')'
unbind '-'
unbind '_'
unbind '+'
unbind '='
unbind '['
unbind ']'
unbind '{'
unbind '}'
unbind \\
unbind '|'
unbind ';'
unbind ':'
unbind \'
unbind \"
unbind ','
unbind '<'
unbind '.'
unbind '>'
unbind '/'
unbind '?'

## Copy mode
unbind -T copy-mode y
unbind -T copy-mode-vi y
