## Unbind digits
unbind 1
unbind 2
unbind 3
unbind 4
unbind 5
unbind 6
unbind 7
unbind 8
unbind 9
unbind 0

## Unbind lowercase letters
unbind a
unbind b
unbind c
unbind d
unbind e
unbind f
unbind g
unbind h
unbind i
unbind j
unbind k
unbind l
unbind m
unbind n
unbind o
unbind p
unbind q
unbind r
unbind s
unbind t
unbind u
unbind v
unbind w
unbind x
unbind y
unbind z

## Unbind uppercase letters
unbind A
unbind B
unbind C
unbind D
unbind E
unbind F
unbind G
unbind H
unbind I
unbind J
unbind K
unbind L
unbind M
unbind N
unbind O
unbind P
unbind Q
unbind R
unbind S
unbind T
unbind U
unbind V
unbind W
unbind X
unbind Y
unbind Z

## Unbind function keys
unbind F1
unbind F2
unbind F3
unbind F4
unbind F5
unbind F6
unbind F7
unbind F8
unbind F9
unbind F10
unbind F11
unbind F12
unbind S-F1
unbind S-F2
unbind S-F3
unbind S-F4
unbind S-F5
unbind S-F6
unbind S-F7
unbind S-F8
unbind S-F9
unbind S-F10
unbind S-F11
unbind S-F12

## Unbind control-letters
unbind C-a
unbind C-b
unbind C-c
unbind C-d
unbind C-e
unbind C-f
unbind C-g
unbind C-h
unbind C-i
unbind C-j
unbind C-k
unbind C-l
unbind C-m
unbind C-n
unbind C-o
unbind C-p
unbind C-q
unbind C-r
unbind C-s
unbind C-t
unbind C-u
unbind C-v
unbind C-w
unbind C-x
unbind C-y
unbind C-z

## Unbind arrow keys
unbind Up
unbind Down
unbind Left
unbind Right
unbind C-Up
unbind C-Down
unbind C-Left
unbind C-Right
unbind M-Up
unbind M-Down
unbind M-Left
unbind M-Right
unbind S-Up
unbind S-Down
unbind S-Left
unbind S-Right
unbind C-M-Up
unbind C-M-Down
unbind C-M-Left
unbind C-M-Right
unbind C-S-Up
unbind C-S-Down
unbind C-S-Left
unbind C-S-Right

## Unbind symbols
unbind '!'
unbind '@'
unbind '#'
unbind '$'
unbind '%'
unbind '^'
unbind '&'
unbind '*'
unbind '('
unbind ')'
unbind '-'
unbind '_'
unbind '+'
unbind '='
unbind '['
unbind ']'
unbind '{'
unbind '}'
unbind \\
unbind '|'
unbind ';'
unbind ':'
unbind \'
unbind \"
unbind ','
unbind '<'
unbind '.'
unbind '>'
unbind '/'
unbind '?'

