#_tmux_widget_app_name="ps -o comm= -t '#{pane_tty}' | rg -o '[\\w-]+' | tail -1"
_tmux_widget_app_name="bash $HOME/.config/tmux/script/app_name.sh #{pane_tty}"
_tmux_widget_app_pid="ps -o pid= -t '#{pane_tty}' | rg -o '\\d+' | tail -1"

# Popup
set -g @popup-bg                        "colour0"
set -g @popup-fg                        "colour255"
set -g popup-border-style               "fg=#{@GHC_SL_COLOR_BORDER_CUR},bg=default"
set -g popup-border-lines               "single"

# Basic
setw  -g window-status-activity-style   "none"
setw  -g window-status-separator        " "
set   -g message-style                  "fg=#{@GHC_SL_COLOR_FG_MESSAGE},bg=#{@GHC_SL_COLOR_BG_MESSAGE}"
set   -g pane-border-style              "fg=#{@GHC_SL_COLOR_BORDER}"
set   -g pane-active-border-style       "fg=#{@GHC_SL_COLOR_BORDER_CUR}"
set   -g status-justify                 "centre"
set   -g status-style                   "none,bg=#{@GHC_SL_COLOR_BG}"
set   -g status-left-style              "bold"
set   -g status-right-style             "none"
set   -g status-left-length             32
set   -g status-right-length            64

set -g status-left "\
#[fg=#{@GHC_SL_COLOR_FG_SESSION},       bg=#{@GHC_SL_COLOR_BG_SESSION}, bold] #{@GHC_SL_SYM_SESSION} #S \
#[fg=#{@GHC_SL_COLOR_BG},               bg=#{@GHC_SL_COLOR_BG}] \
"

set -g status-right "\
#[fg=#{@GHC_SL_COLOR_BG},               bg=#{@GHC_SL_COLOR_BG}]  \
#[fg=#{@GHC_SL_COLOR_BG_TIME_SYM},      bg=#{@GHC_SL_COLOR_BG}]#{@GHC_SL_SEP_RIGHT}\
#[fg=#{@GHC_SL_COLOR_FG_TIME_SYM},      bg=#{@GHC_SL_COLOR_BG_TIME_SYM}]#{@GHC_SL_SYM_TIME} \
#[fg=#{@GHC_SL_COLOR_FG_TIME_TEXT},     bg=#{@GHC_SL_COLOR_BG_TIME_TEXT}, bold] %H:%M:%S \
\
#[fg=#{@GHC_SL_COLOR_BG_DATE_SYM},      bg=#{@GHC_SL_COLOR_BG_TIME_TEXT}]#{@GHC_SL_SEP_RIGHT}\
#[fg=#{@GHC_SL_COLOR_FG_DATE_SYM},      bg=#{@GHC_SL_COLOR_BG_DATE_SYM}]#{@GHC_SL_SYM_DATE} \
#[fg=#{@GHC_SL_COLOR_FG_DATE_TEXT},     bg=#{@GHC_SL_COLOR_BG_DATE_TEXT}, bold] %a %b %d, %Y \
"

# window
setw -g window-status-format "\
#[fg=#{@GHC_SL_COLOR_BG},               bg=#{@GHC_SL_COLOR_BG}]\
#[fg=#{@GHC_SL_COLOR_BG_WIN_NAME},      bg=#{@GHC_SL_COLOR_BG}]\
#[fg=#{@GHC_SL_COLOR_FG_WIN_NAME},      bg=#{@GHC_SL_COLOR_BG_WIN_NAME}]#W \
#[fg=#{@GHC_SL_COLOR_FG_WIN_NUM},       bg=#{@GHC_SL_COLOR_BG_WIN_NUM}, bold] #I\
#[fg=#{@GHC_SL_COLOR_BG_WIN_NUM},       bg=#{@GHC_SL_COLOR_BG}]\
#[fg=#{@GHC_SL_COLOR_BG},               bg=#{@GHC_SL_COLOR_BG}]\
"

# active window
setw -g window-status-current-format "\
#[fg=#{@GHC_SL_COLOR_BG},               bg=#{@GHC_SL_COLOR_BG}]\
#[fg=#{@GHC_SL_COLOR_BG_WIN_CUR_NAME},  bg=#{@GHC_SL_COLOR_BG}]\
#[fg=#{@GHC_SL_COLOR_FG_WIN_CUR_NAME},  bg=#{@GHC_SL_COLOR_BG_WIN_CUR_NAME}, bold]#W \
#[fg=#{@GHC_SL_COLOR_FG_WIN_CUR_NUM},   bg=#{@GHC_SL_COLOR_BG_WIN_CUR_NUM}, bold] #I\
#[fg=#{@GHC_SL_COLOR_BG_WIN_CUR_NUM},   bg=#{@GHC_SL_COLOR_BG}]\
#[fg=#{@GHC_SL_COLOR_BG},               bg=#{@GHC_SL_COLOR_BG}]\
"
