## Message
set   -g message-style                  "fg=#{@GHC_SL_FG_MESSAGE},bg=#{@GHC_SL_BG_MESSAGE}"

## Pane
setw  -g pane-base-index                1 # Make pane numbering consistent with windows.
set   -g pane-border-status             top
set   -g pane-border-style              "fg=#{@GHC_PSL_FG_BORDER}"
set   -g pane-active-border-style       "fg=#{@GHC_PSL_FG_BORDER_CUR},bold"

## Popup
set   -g @popup-bg                      "colour0"
set   -g @popup-fg                      "colour255"
set   -g popup-border-style             "fg=default,bg=default"
set   -g popup-border-lines             "single"

## Statusline
set   -g base-index                     1       # Start windows numbering at 1.
set   -g status                         on
set   -g status-interval                15      # Redraw status line every 10 seconds.
set   -g status-position                bottom  # Put the status line position to top.
set   -g status-justify                 "centre"
set   -g status-style                   "none,bg=#{@GHC_SL_BG}"
set   -g status-left-style              "bold"
set   -g status-right-style             "none"
set   -g status-left-length             64
set   -g status-right-length            64

### window
setw  -g window-status-activity-style   "none"
setw  -g window-status-current-style    "none"
setw  -g window-status-separator        " "
setw  -g window-status-style            "none,bg=#{@GHC_SL_BG}"

setw -g window-status-format "\
#[default]\
#[fg=#{@GHC_SL_BG_WIN_NAME},  bg=#{@GHC_SL_BG}]#{@GHC_SEP_LEFT}\
#[fg=#{@GHC_SL_FG_WIN_NAME},  bg=#{@GHC_SL_BG_WIN_NAME}]#W \
#[fg=#{@GHC_SL_FG_WIN_NUM},   bg=#{@GHC_SL_BG_WIN_NUM}] #I\
#[fg=#{@GHC_SL_BG_WIN_NUM},   bg=#{@GHC_SL_BG}]#{@GHC_SEP_RIGHT}\
#[default]\
"

### window (active)
setw -g window-status-current-format "\
#[default]\
#[fg=#{@GHC_SL_BG_WIN_NAME_ACTIVE},   bg=#{@GHC_SL_FG_WIN_NAME_ACTIVE}]#{@GHC_SEP_LEFT}\
#[fg=#{@GHC_SL_FG_WIN_NAME_ACTIVE},   bg=#{@GHC_SL_BG_WIN_NAME_ACTIVE}, bold]#W | #I\
#[fg=#{@GHC_SL_BG_WIN_NAME_ACTIVE},   bg=#{@GHC_SL_FG_WIN_NAME_ACTIVE}]#{@GHC_SEP_RIGHT}\
#[default]\
"

