## Message
set   -g message-style                  "fg=#{@GHC_SL_COLOR_FG_MESSAGE},bg=#{@GHC_SL_COLOR_BG_MESSAGE}"

## Pane
set   -g pane-border-style              "fg=#{@GHC_SL_COLOR_BORDER}"
set   -g pane-border-status             top
set   -g pane-active-border-style       "fg=#{@GHC_SL_COLOR_BORDER_CUR},bold"

## Popup
set -g @popup-bg                        "colour0"
set -g @popup-fg                        "colour255"
set -g popup-border-style               "fg=#{@GHC_SL_COLOR_BORDER_CUR},bg=default"
set -g popup-border-lines               "single"

## Statusline
set   -g status-justify                 "centre"
set   -g status-style                   "none,bg=#{@GHC_SL_COLOR_BG}"
set   -g status-left-style              "bold"
set   -g status-right-style             "none"
set   -g status-left-length             64
set   -g status-right-length            64
setw  -g window-status-activity-style   "none"
setw  -g window-status-separator        " "

### window
setw -g window-status-format "\
#[fg=#{@GHC_SL_COLOR_BG},               bg=#{@GHC_SL_COLOR_BG}]\
#[fg=#{@GHC_SL_COLOR_BG_WIN_NAME},      bg=#{@GHC_SL_COLOR_BG}]#{@GHC_SL_SEP_LEFT}\
#[fg=#{@GHC_SL_COLOR_FG_WIN_NAME},      bg=#{@GHC_SL_COLOR_BG_WIN_NAME}]#W \
#[fg=#{@GHC_SL_COLOR_FG_WIN_NUM},       bg=#{@GHC_SL_COLOR_BG_WIN_NUM}] #I\
#[fg=#{@GHC_SL_COLOR_BG_WIN_NUM},       bg=#{@GHC_SL_COLOR_BG}]#{@GHC_SL_SEP_RIGHT}\
#[fg=#{@GHC_SL_COLOR_BG},               bg=#{@GHC_SL_COLOR_BG}]\
"

### window (active)
setw -g window-status-current-format "\
#[fg=#{@GHC_SL_COLOR_BG},               bg=#{@GHC_SL_COLOR_BG}]\
#[fg=#{@GHC_SL_COLOR_BG_WIN_CUR_NAME},  bg=#{@GHC_SL_COLOR_BG}]#{@GHC_SL_SEP_LEFT}\
#[fg=#{@GHC_SL_COLOR_FG_WIN_CUR_NAME},  bg=#{@GHC_SL_COLOR_BG_WIN_CUR_NAME}, bold]#W | #I\
#[fg=#{@GHC_SL_COLOR_BG_WIN_CUR_NAME},  bg=#{@GHC_SL_COLOR_BG}]#{@GHC_SL_SEP_RIGHT}\
#[fg=#{@GHC_SL_COLOR_BG},               bg=#{@GHC_SL_COLOR_BG}]\
"

