_tmux_is_os_linux="uname -s | grep -iqE '^Linux$'"
_tmux_is_os_macos="uname -s | grep -iqE '^Darwin$'"
_tmux_is_os_windows="uname -s | grep -iqE '^Windows_NT$'"

# Define custom_os_icon based on the OS
set -g @GHC_SYM_OS ""
if-shell "$_tmux_is_os_macos"           'set -g @GHC_SYM_OS ""'
if-shell "$_tmux_is_os_linux"           'set -g @GHC_SYM_OS ""'
if-shell "$_tmux_is_os_windows"         'set -g @GHC_SYM_OS ""'

# Symbols
set -g @GHC_SEP_LEFT                    ''
set -g @GHC_SEP_RIGHT                   ''
set -g @GHC_SYM_SESSION                 ''
set -g @GHC_SYM_APP                     ''
set -g @GHC_SYM_CPU                     ''
set -g @GHC_SYM_DATE                    ''
set -g @GHC_SYM_NET                     '󰛳'
set -g @GHC_SYM_PID                     ''
set -g @GHC_SYM_TIME                    ''
set -g @GHC_SYM_USER                    ""
set -g @GHC_SYM_WIN                     ''
set -g @GHC_SYM_INDEX                   '#'
set -g @GHC_SYM_TREE_SESSION            ''
set -g @GHC_SYM_TREE_WINDOW             '󰕰'
set -g @GHC_SYM_TREE_ATTACHED           '󰌘'
set -g @GHC_SYM_TREE_SEPARATOR          ''

# Choose-tree format
set -g @GHC_TREE_FORMAT "\
#{?session_format,\
#{?session_attached,\
#[fg=cyan#,bold]#{@GHC_SYM_TREE_ATTACHED} \
#[fg=cyan#,bold]#S\
#[default]\
,\
#[fg=grey]#{@GHC_SYM_TREE_SESSION} \
#[fg=white#,bold]#S\
#[default]\
},\
#{?window_format,\
#{?window_active,\
#[fg=cyan#,bold]#{@GHC_SYM_TREE_WINDOW} \
#[fg=cyan#,bold]#W\
#[default]\
,\
#[fg=grey]#{@GHC_SYM_TREE_WINDOW} \
#[fg=white#,bold]#W\
#[default]\
},\
#{?pane_active,\
#[fg=cyan]#{@GHC_SYM_OS} \
#[fg=cyan]#(ps -o user= -t #{pane_tty}) \
#[fg=cyan]#{@GHC_SYM_PID} \
#[fg=cyan]#{pane_pid} \
#[fg=cyan]#{@GHC_SYM_APP} \
#[fg=cyan]#{@GHC_SYM_INDEX}#{pane_index} #{pane_title}\
#[default]\
,\
#[fg=grey]#{@GHC_SYM_OS} \
#[fg=grey]#(ps -o user= -t #{pane_tty}) \
#[fg=grey]#{@GHC_SYM_PID} \
#[fg=grey]#{pane_pid} \
#[fg=grey]#{@GHC_SYM_APP} \
#[fg=grey]#{@GHC_SYM_INDEX}#{pane_index} #{pane_title}\
#[default]\
}\
}\
}"

# Plugin options
set -g  @resurrect-save                 'F10'             # Save the sessions
set -g  @resurrect-restore              'S-F10'           # Restore the sessions
