_tmux_is_os_linux="uname -s | grep -iqE '^Linux$'"
_tmux_is_os_macos="uname -s | grep -iqE '^Darwin$'"
_tmux_is_os_windows="uname -s | grep -iqE '^Windows_NT$'"

# Define custom_os_icon based on the OS
set -g @GHC_SL_SYM_OS ""
if-shell "$_tmux_is_os_macos"           'set -g @GHC_SL_SYM_OS ""'
if-shell "$_tmux_is_os_linux"           'set -g @GHC_SL_SYM_OS ""'
if-shell "$_tmux_is_os_windows"         'set -g @GHC_SL_SYM_OS ""'

# Symbols
set -g @GHC_SL_SEP_LEFT                 ''
set -g @GHC_SL_SEP_RIGHT                ''
set -g @GHC_SL_SYM_SESSION              ''
set -g @GHC_SL_SYM_APP                  ''
set -g @GHC_SL_SYM_CPU                  ''
set -g @GHC_SL_SYM_DATE                 ''
set -g @GHC_SL_SYM_NET                  '󰛳'
set -g @GHC_SL_SYM_PID                  ''
set -g @GHC_SL_SYM_TIME                 ''
set -g @GHC_SL_SYM_USER                 ""
set -g @GHC_SL_SYM_WIN                  ''

# Theme scheme
run-shell "bash $HOME/.config/tmux/script/status-load.sh"
if-shell "[ -f $HOME/.config/tmux/local/theme.tmux.conf ]" 'source $HOME/.config/tmux/local/theme.tmux.conf'

# Plugin options
set -g  @resurrect-save                 'F10'             # Save the sessions
set -g  @resurrect-restore              'S-F10'           # Restore the sessions
