_tmux_is_os_linux="uname -s | grep -iqE '^Linux$'"
_tmux_is_os_macos="uname -s | grep -iqE '^Darwin$'"
_tmux_is_os_windows="uname -s | grep -iqE '^Windows_NT$'"

# decide whether we're in a Vim process
# See: https://github.com/christoomey/vim-tmux-navigator/blob/a26954a585b02a2ac02f87145e204f8798a7cbc2/vim-tmux-navigator.tmux#L1
_tmux_is_zen_mode="(tmux display-message -p '#{window_panes}' | grep -iqE 1) || (tmux display-message -p '#{window_zoomed_flag}' | grep -iqE 1)"
_tmux_is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?(\\.exe)?$'"
_tmux_is_vim_pane="#{m:*vim*,#{pane_current_command}}"

# Define custom_os_icon based on the OS
set -g @GHC_SYM_OS ""
if-shell "$_tmux_is_os_macos"           'set -g @GHC_SYM_OS ""'
if-shell "$_tmux_is_os_linux"           'set -g @GHC_SYM_OS ""'
if-shell "$_tmux_is_os_windows"         'set -g @GHC_SYM_OS ""'

# Symbols
set -g @GHC_SEP_LEFT                    ''
set -g @GHC_SEP_RIGHT                   ''
set -g @GHC_SYM_SESSION                 ''
set -g @GHC_SYM_APP                     ''
set -g @GHC_SYM_CPU                     ''
set -g @GHC_SYM_DATE                    ''
set -g @GHC_SEP_ROUND_LEFT              ''
set -g @GHC_SEP_ROUND_RIGHT             ''
set -g @GHC_SYM_NET                     '󰛳'
set -g @GHC_SYM_PID                     ''
set -g @GHC_SYM_TIME                    ''
set -g @GHC_SYM_USER                    ""
set -g @GHC_SYM_WIN                     ''
set -g @GHC_SYM_WIN_BELL                '󰂚'
set -g @GHC_SYM_WIN_LAST                ''
set -g @GHC_SYM_WIN_ZOOM                '󰊓'
set -g @GHC_SYM_ALERT                   '󰂚'
set -g @GHC_SYM_PREFIX                  '󰌌'
set -g @GHC_SYM_COPY_MODE               '󰆏'
set -g @GHC_SYM_COPY_MODE_SEARCH        '󰍉'
set -g @GHC_SYM_COPY_MODE_SELECT        '󰒅'
set -g @GHC_SYM_DURATION                '󱦟'
set -g @GHC_SYM_INDEX                   '#'
set -g @GHC_SYM_TREE_SESSION            ''
set -g @GHC_SYM_TREE_WINDOW             '󰕰'
set -g @GHC_SYM_TREE_ATTACHED           '󰌘'
set -g @GHC_SYM_TREE_SEPARATOR          ''

# Choose-tree format
set -g @GHC_TREE_FORMAT "\
#{?session_format,\
#{?session_attached,\
#[fg=cyan#,bold]#{@GHC_SYM_TREE_ATTACHED} \
#[fg=cyan#,bold]#S\
#[default]\
,\
#[fg=grey]#{@GHC_SYM_TREE_SESSION} \
#[fg=white#,bold]#S\
#[default]\
},\
#{?window_format,\
#{?window_active,\
#[fg=cyan#,bold]#{@GHC_SYM_TREE_WINDOW} \
#[fg=cyan#,bold]#W\
#[default]\
,\
#[fg=grey]#{@GHC_SYM_TREE_WINDOW} \
#[fg=white#,bold]#W\
#[default]\
},\
#{?pane_active,\
#[fg=cyan]#{@GHC_SYM_OS} \
#[fg=cyan]#(ps -o user= -t #{pane_tty}) \
#[fg=cyan]#{@GHC_SYM_PID} \
#[fg=cyan]#{pane_pid} \
#[fg=cyan]#{@GHC_SYM_APP} \
#[fg=cyan]#{@GHC_SYM_INDEX}#{pane_index} #{pane_title}\
#[default]\
,\
#[fg=grey]#{@GHC_SYM_OS} \
#[fg=grey]#(ps -o user= -t #{pane_tty}) \
#[fg=grey]#{@GHC_SYM_PID} \
#[fg=grey]#{pane_pid} \
#[fg=grey]#{@GHC_SYM_APP} \
#[fg=grey]#{@GHC_SYM_INDEX}#{pane_index} #{pane_title}\
#[default]\
}\
}\
}"

# Plugin options
set -g  @resurrect-save                 'F10'             # Save the sessions
set -g  @resurrect-restore              'S-F10'           # Restore the sessions
