[General]
auto_backup=false
first_run=false
language=en
read_tips=4
startup_fix=2

[Hotkey]
custom_snip=
hide=
paste=
snip="335544385, 335544320"
snip_and_copy=
switch=

[Interface]
color_values=HEX
tray_color=@Variant(\0\0\0\x43\x1\0\0\xff\xff\xff\xff\xff\xff\0\0)
uppercase_hex=true

## need replace the '~' to the real user home.
[Output]
auto_save_path=~/.local/state/snipaste/autosave/$yyyy-MM-dd$/$HH-mm-ss$.png
copy_as_windows_bitmap_for_paste=true
file_name_pattern=$yyyy-MM-dd_HH-mm-ss$.png
quick_save_path=~/.local/state/snipaste/quicksave/$yyyy-MM-dd$/$HH-mm-ss$.png

[Paste]
text_to_image=false

[Paste2]
ignore_text_format=true

[Snip]
ask_for_confirm_on_esc=false
auto_cross_lines=true
capture_cursor=true
middle_click_output=4

