--- tokyonight-moon

---@type dot.t.theme.IScheme
local M = {
  theme = "tokyonight",
  variant = "moon",
  opposite = "day",
  darken = true,
  -- stylua: ignore start
  palette = {
    unified = {
      none          = "none",

      bg0           = "#222436",
      bg1           = "#1e2030",
      bg2           = "#191b29",
      bg3           = "#2f334d",
      bg4           = "#2d3f76",

      fg0           = "#c8d3f5",
      fg1           = "#b6c1e7",
      fg2           = "#a5afd9",
      fg3           = "#909bca",
      fg4           = "#7c86ba",

      red           = "#ff757f",
      green         = "#c3e88d",
      yellow        = "#ffc777",
      blue          = "#82aaff",
      purple        = "#fca7ea",
      aqua          = "#86e1fc",
      orange        = "#ff966c",

      brightRed     = "#c53b53",
      brightGreen   = "#4fd6be",
      brightYellow  = "#ffc777",
      brightBlue    = "#65bcff",
      brightPurple  = "#c099ff",
      brightAqua    = "#4fd6be",
      brightOrange  = "#ff966c",

      grey          = "#636da6",
      pink          = "#c099ff",

      diffDel       = "#4b2a3d",
      diffDelInline = "#e26a75",
      diffAdd       = "#2a4556",
      diffAddInline = "#b8db87",
    },
    tokyonight = {
      none          = "none",

      bg            = "#222436",
      bg_dark       = "#1e2030",
      bg_dark1      = "#191B29",
      bg_highlight  = "#2f334d",
      bg_visual     = "#2d3f76",
      fg            = "#c8d3f5",
      fg_dark       = "#828bb8",
      fg_gutter     = "#3b4261",
      fg_sidebar    = "#828bb8",
      comment       = "#636da6",
      dark3         = "#545c7e",
      dark5         = "#737aa2",
      blue          = "#82aaff",
      blue0         = "#3e68d7",
      blue1         = "#65bcff",
      blue2         = "#0db9d7",
      blue5         = "#89ddff",
      blue6         = "#b4f9f8",
      blue7         = "#394b70",
      cyan          = "#86e1fc",
      green         = "#c3e88d",
      green1        = "#4fd6be",
      green2        = "#41a6b5",
      magenta       = "#c099ff",
      magenta2      = "#ff007c",
      orange        = "#ff966c",
      purple        = "#fca7ea",
      red           = "#ff757f",
      red1          = "#c53b53",
      teal          = "#4fd6be",
      yellow        = "#ffc777",
      terminal_black = "#444a73",
      black         = "#1b1d2b",
      border        = "#1b1d2b",
      border_highlight = "#589ed7",
      git_add       = "#b8db87",
      git_change    = "#7ca1f2",
      git_delete    = "#e26a75",
      diff_add      = "#2a4556",
      diff_change   = "#252a3f",
      diff_delete   = "#4b2a3d",
      diff_text     = "#394b70",
      hint          = "#4fd6be",
      info          = "#0db9d7",
      todo          = "#82aaff",
      warning       = "#ffc777",
    },
  },
  -- stylua: ignore end
}

return M
