---@class eve.constant.hlgroup.catppuccin.treesitter
local M = {}

---@param context                       std.t.theme.IContext
---@return table<string, std.t.theme.IHlgroup>
function M.gen_hlgroup_map(context)
  local t = context.transparency ---@type boolean
  local c = context.scheme.palette.catppuccin ---@type std.t.theme.CatppuccinPalette

  return {
    ["@annotation"] = { fg = c.red },
    ["@attribute"] = { fg = c.peach },
    ["@boolean"] = { fg = c.peach },
    ["@character"] = { fg = c.teal },
    ["@character.special"] = { fg = c.pink },
    ["@comment"] = { fg = c.overlay2 },
    ["@comment.danger"] = { fg = c.base, bg = t and c.none or c.red },
    ["@comment.error"] = { fg = c.base, bg = t and c.none or c.red },
    ["@comment.note"] = { fg = c.base, bg = t and c.none or c.rosewater },
    ["@comment.todo"] = { fg = c.base, bg = t and c.none or c.flamingo },
    ["@comment.warning"] = { fg = c.base, bg = t and c.none or c.yellow },
    ["@conditional"] = { fg = c.mauve },
    ["@constant"] = { fg = c.peach },
    ["@constant.builtin"] = { fg = c.peach },
    ["@constant.macro"] = { fg = c.mauve },
    ["@constructor"] = { fg = c.yellow },
    ["@debug"] = { fg = c.red },
    ["@define"] = { fg = c.pink },
    ["@diff.plus"] = { fg = c.green },
    ["@diff.minus"] = { fg = c.red },
    ["@diff.delta"] = { fg = c.blue },
    ["@error"] = { fg = c.red },
    ["@event"] = { fg = c.red },
    ["@exception"] = { fg = c.mauve },
    ["@field"] = { fg = c.text },
    ["@float"] = { fg = c.peach },
    ["@function"] = { fg = c.blue },
    ["@function.builtin"] = { fg = c.peach },
    ["@function.call"] = { fg = c.blue },
    ["@function.lua"] = { fg = c.blue },
    ["@function.macro"] = { fg = c.pink },
    ["@function.method"] = { fg = c.blue },
    ["@function.method.call"] = { fg = c.blue },
    ["@include"] = { fg = c.mauve },
    ["@keyword"] = { fg = c.mauve },
    ["@keyword.break"] = { fg = c.mauve },
    ["@keyword.conditional"] = { fg = c.mauve },
    ["@keyword.conditional.ternary"] = { fg = c.sky },
    ["@keyword.debug"] = { fg = c.mauve },
    ["@keyword.directive"] = { fg = c.pink },
    ["@keyword.directive.define"] = { fg = c.pink },
    ["@keyword.exception"] = { fg = c.mauve },
    ["@keyword.function"] = { fg = c.mauve },
    ["@keyword.import"] = { fg = c.mauve },
    ["@keyword.lua"] = { fg = c.mauve },
    ["@keyword.luadoc"] = { fg = c.blue },
    ["@keyword.operator"] = { fg = c.mauve },
    ["@keyword.repeat"] = { fg = c.mauve },
    ["@keyword.return"] = { fg = c.mauve },
    ["@keyword.storage"] = { fg = c.yellow },
    ["@label"] = { fg = c.sapphire },
    ["@macro"] = { fg = c.mauve },
    ["@markup"] = { fg = c.text },
    ["@markup.environment"] = { fg = c.pink },
    ["@markup.environment.name"] = { fg = c.blue },
    ["@markup.heading.1.markdown"] = { fg = c.red },
    ["@markup.heading.2.markdown"] = { fg = c.peach },
    ["@markup.heading.3.markdown"] = { fg = c.yellow },
    ["@markup.heading.4.markdown"] = { fg = c.green },
    ["@markup.heading.5.markdown"] = { fg = c.sapphire },
    ["@markup.heading.6.markdown"] = { fg = c.lavender },
    ["@markup.heading.1.marker.markdown"] = { fg = c.red },
    ["@markup.heading.2.marker.markdown"] = { fg = c.peach },
    ["@markup.heading.3.marker.markdown"] = { fg = c.yellow },
    ["@markup.heading.4.marker.markdown"] = { fg = c.green },
    ["@markup.heading.5.marker.markdown"] = { fg = c.sapphire },
    ["@markup.heading.6.marker.markdown"] = { fg = c.lavender },
    ["@markup.italic"] = { fg = c.red, italic = true },
    ["@markup.link"] = { fg = c.lavender },
    ["@markup.link.label"] = { fg = c.lavender },
    ["@markup.list"] = { fg = c.teal },
    ["@markup.list.checked"] = { fg = c.green },
    ["@markup.list.unchecked"] = { fg = c.overlay1 },
    ["@markup.link.url"] = { fg = c.blue, underline = true },
    ["@markup.math"] = { fg = c.blue },
    ["@markup.quote"] = { fg = c.pink },
    ["@markup.raw"] = { fg = c.green },
    ["@markup.strikethrough"] = { fg = c.text, strikethrough = true },
    ["@markup.strong"] = { fg = c.red, bold = true },
    ["@markup.underline"] = { underline = true },
    ["@method"] = { fg = c.blue },
    ["@method.call"] = { fg = c.blue },
    ["@modifier"] = { fg = c.red },
    ["@module"] = { fg = c.yellow },
    ["@namespace"] = { fg = c.yellow },
    ["@none"] = {},
    ["@number"] = { fg = c.peach },
    ["@number.float"] = { fg = c.peach },
    ["@operator"] = { fg = c.sky },
    ["@operator.unary.not"] = { fg = c.red },
    ["@parameter"] = { fg = c.maroon },
    ["@preproc"] = { fg = c.pink },
    ["@property"] = { fg = c.text },
    ["@punctuation"] = { fg = c.overlay2 },
    ["@punctuation.delimiter"] = { fg = c.overlay2 },
    ["@punctuation.bracket"] = { fg = c.overlay2 },
    ["@punctuation.special"] = { fg = c.pink },
    ["@reference"] = { fg = c.text },
    ["@regexp"] = { fg = c.pink },
    ["@repeat"] = { fg = c.mauve },
    ["@scope"] = { bold = true },
    ["@string"] = { fg = c.green },
    ["@string.regex"] = { fg = c.pink },
    ["@string.regexp"] = { fg = c.pink },
    ["@string.escape"] = { fg = c.pink },
    ["@string.special"] = { fg = c.pink },
    ["@string.special.path"] = { fg = c.blue, underline = true },
    ["@string.special.symbol"] = { fg = c.flamingo },
    ["@string.special.url"] = { fg = c.blue, underline = true },
    ["@storageclass"] = { fg = c.yellow },
    ["@structure"] = { fg = c.yellow },
    ["@symbol"] = { fg = c.flamingo },
    ["@tag"] = { fg = c.blue },
    ["@tag.attribute"] = { fg = c.yellow },
    ["@tag.delimiter"] = { fg = c.teal },
    ["@text"] = { fg = c.text },
    ["@text.strong"] = { fg = c.red, bold = true },
    ["@text.emphasis"] = { fg = c.red, italic = true },
    ["@text.underline"] = { underline = true },
    ["@text.strike"] = { fg = c.text, strikethrough = true },
    ["@text.title"] = { fg = c.blue, bold = true },
    ["@text.literal"] = { fg = c.green },
    ["@text.uri"] = { fg = c.blue, underline = true },
    ["@text.math"] = { fg = c.blue },
    ["@text.environment"] = { fg = c.pink },
    ["@text.environment.name"] = { fg = c.blue },
    ["@text.reference"] = { fg = c.lavender },
    ["@text.todo"] = { fg = c.base, bg = t and c.none or c.flamingo },
    ["@text.todo.checked"] = { fg = c.green },
    ["@text.todo.unchecked"] = { fg = c.overlay1 },
    ["@text.note"] = { fg = c.base, bg = t and c.none or c.rosewater },
    ["@text.note.comment"] = { fg = c.mauve, bold = true },
    ["@text.warning"] = { fg = c.base, bg = t and c.none or c.yellow },
    ["@text.danger"] = { fg = c.base, bg = t and c.none or c.red },
    ["@text.danger.comment"] = { fg = c.text, bg = t and c.none or c.red, bold = true },
    ["@text.diff.add"] = { fg = c.green },
    ["@text.diff.delete"] = { fg = c.red },
    ["@type"] = { fg = c.yellow },
    ["@type.tsx"] = { fg = c.yellow, italic = true, bold = true },
    ["@type.builtin"] = { fg = c.mauve },
    ["@type.definition"] = { fg = c.yellow },
    ["@type.qualifier"] = { fg = c.yellow },
    ["@variable"] = { fg = c.text },
    ["@variable.lua"] = { fg = c.text },
    ["@variable.jsx"] = { fg = c.text },
    ["@variable.tsx"] = { fg = c.text },
    ["@variable.builtin"] = { fg = c.red },
    ["@variable.member"] = { fg = c.text },
    ["@variable.member.lua"] = { fg = c.text },
    ["@variable.parameter"] = { fg = c.maroon },
    ["@variable.parameter.luadoc"] = { fg = c.yellow, italic = true },

    -----

    ["@lsp.type.class"] = { fg = c.yellow },
    ["@lsp.type.comment"] = { fg = c.overlay2 },
    ["@lsp.type.decorator"] = { fg = c.mauve },
    ["@lsp.type.enum"] = { fg = c.yellow },
    ["@lsp.type.enumMember"] = { fg = c.peach },
    ["@lsp.type.function"] = { fg = c.blue },
    ["@lsp.type.interface"] = { fg = c.yellow },
    ["@lsp.type.macro"] = { fg = c.mauve },
    ["@lsp.type.method"] = { fg = c.blue },
    ["@lsp.type.namespace"] = { fg = c.yellow },
    ["@lsp.type.parameter"] = { fg = c.maroon },
    ["@lsp.type.property"] = { fg = c.text },
    ["@lsp.type.struct"] = { fg = c.yellow },
    ["@lsp.type.type"] = { fg = c.yellow },
    ["@lsp.type.typeParameter"] = { fg = c.yellow },
    ["@lsp.type.variable"] = { fg = c.text },
  }
end

return M
