---@class eve.constant.hlgroup.vsc.basic
local M = {}

---@param context                       std.t.theme.IContext
---@return eve.constant.hlgroup.common.modes_color_map
function M.gen_modes_color_map(context)
  local c = context.scheme.palette.vsc ---@type std.t.theme.IVscPalette
  return {
    command = c.accentBlue,
    confirm = c.accentAqua,
    insert = c.accentPurple,
    normal = c.accentAqua,
    nterminal = c.accentYellow,
    replace = c.brightYellow,
    select = c.accentOrange,
    terminal = c.accentBlue,
    visual = c.accentOrange,
  }
end

---@param context                       std.t.theme.IContext
---@return table<string, std.t.theme.IHlgroup>
function M.gen_hlgroup_map(context)
  local cs = std.color
  local t = context.transparency ---@type boolean
  local c = context.scheme.palette.vsc ---@type std.t.theme.IVscPalette

  local function diag_bg(color)
    if t then
      return c.none
    end
    return cs.mix(c.editor_background, color, 18)
  end

  ---@type table<string, std.t.theme.IHlgroup>
  local hlgroup_map = {
    ComplHint = { fg = c.muted, italic = true },
    ComplHintMore = { fg = c.descriptionForeground, italic = true },
    Added = { fg = c.success },
    Changed = { fg = c.accentYellow },
    Bold = { fg = c.editor_foreground, bold = true },
    Boolean = { fg = c.tokenConstantLanguage },
    Builtin = { fg = c.tokenThisSelf, italic = true },
    Character = { fg = c.semanticStringLiteral },
    ColorColumn = { bg = c.editorWidget_background },
    Comment = { fg = c.tokenComment, italic = true },
    Conceal = { fg = c.muted },
    Conditional = { fg = c.tokenKeyword },
    Constant = { fg = c.tokenConstantsAndEnums },
    CurSearch = { fg = c.none, bg = c.editor_findMatchBackground, bold = true },
    Cursor = { fg = c.editor_background, bg = c.accentOrange },
    CursorColumn = { bg = c.editor_inactiveSelectionBackground },
    CursorLine = { bg = c.editor_selectionHighlightBackground },
    CursorLineNr = {
      fg = c.editorLineNumber_activeForeground,
      bg = c.editor_selectionHighlightBackground,
      bold = true,
    },
    iCursor = { link = "Cursor" },
    lCursor = { link = "Cursor" },
    vCursor = { link = "Cursor" },
    Debug = { fg = c.warning },
    Define = { fg = c.tokenKeyword },
    Delimiter = { fg = c.semanticNewOperator },
    Diagnostic_ERROR = { fg = c.errorForeground },
    Diagnostic_HINT = { fg = c.accentAqua },
    Diagnostic_INFO = { fg = c.accentBlue },
    Diagnostic_WARN = { fg = c.warning },
    DiagnosticError = { fg = c.errorForeground },
    DiagnosticFloatingError = { fg = c.errorForeground },
    DiagnosticFloatingHint = { fg = c.accentAqua },
    DiagnosticFloatingInfo = { fg = c.accentBlue },
    DiagnosticFloatingOk = { fg = c.success },
    DiagnosticFloatingWarn = { fg = c.warning },
    DiagnosticHint = { fg = c.accentAqua },
    DiagnosticInfo = { fg = c.accentBlue },
    DiagnosticWarn = { fg = c.warning },
    DiagnosticOk = { fg = c.success },
    DiagnosticSignError = { fg = c.errorForeground },
    DiagnosticSignHint = { fg = c.accentAqua },
    DiagnosticSignInfo = { fg = c.accentBlue },
    DiagnosticSignOk = { fg = c.success },
    DiagnosticSignWarn = { fg = c.warning },
    DiagnosticUnderlineError = { undercurl = true, sp = c.errorForeground },
    DiagnosticUnderlineHint = { undercurl = true, sp = c.accentAqua },
    DiagnosticUnderlineInfo = { undercurl = true, sp = c.accentBlue },
    DiagnosticUnderlineWarn = { undercurl = true, sp = c.warning },
    DiagnosticVirtualTextError = { fg = c.errorForeground, bg = diag_bg(c.errorForeground) },
    DiagnosticVirtualTextHint = { fg = c.accentAqua, bg = diag_bg(c.accentAqua) },
    DiagnosticVirtualTextInfo = { fg = c.accentBlue, bg = diag_bg(c.accentBlue) },
    DiagnosticVirtualTextWarn = { fg = c.warning, bg = diag_bg(c.warning) },
    DiagnosticVirtualTextOk = { fg = c.success, bg = diag_bg(c.success) },
    DiffAddLeft = { bg = cs.mix(c.editor_background, c.editorGutter_addedBackground, 30) },
    DiffAddRight = { bg = cs.mix(c.editor_background, c.editorGutter_addedBackground, 30) },
    DiffAdd = { bg = cs.mix(c.editor_background, c.editorGutter_addedBackground, 22) },
    DiffAdded = { link = "DiffAdd" },
    DiffChange = { bg = cs.mix(c.editor_background, c.editorGutter_modifiedBackground, 18) },
    DiffChanged = { link = "DiffChange" },
    DiffDelete = { bg = cs.mix(c.editor_background, c.editorGutter_deletedBackground, 20) },
    DiffDelLeft = { bg = cs.mix(c.editor_background, c.editorGutter_deletedBackground, 30) },
    DiffDelRight = { bg = cs.mix(c.editor_background, c.editorGutter_deletedBackground, 30) },
    DiffFile = { fg = c.tokenMarkupHeading },
    DiffIndexLine = { link = "diffChanged" },
    DiffLine = { fg = c.editorGutter_modifiedBackground },
    DiffModLeft = { bg = cs.mix(c.editor_background, c.editorGutter_modifiedBackground, 30) },
    DiffModRight = { bg = cs.mix(c.editor_background, c.editorGutter_modifiedBackground, 30) },
    DiffNewFile = { fg = c.editorGutter_addedBackground },
    DiffOldFile = { fg = c.editorGutter_deletedBackground },
    DiffRemoved = { link = "DiffDelete" },
    DiffText = { bg = cs.mix(c.editor_background, c.editorGutter_modifiedBackground, 24) },
    DiffWordLeft = { bg = cs.mix(c.editor_background, c.editorGutter_deletedBackground, 60) },
    DiffWordRight = { bg = cs.mix(c.editor_background, c.editorGutter_addedBackground, 60) },
    DevIconDefault = { fg = c.icon_foreground },
    Directory = { fg = c.sideBarTitle_foreground, bold = true },
    Done = { fg = c.success, bold = true, italic = true },
    EndOfBuffer = { fg = c.editor_background },
    Error = { fg = c.errorForeground },
    ErrorMsg = { fg = c.errorForeground, bg = c.statusBar_background, bold = true },
    Exception = { fg = c.accentPurple },
    Float = { fg = c.semanticStringLiteral },
    FloatActiveBorder = { link = t and "ms_b_bg0" or "ms_b_none" },
    FloatBorder = { fg = c.dropdown_border, bg = c.dropdown_background, blend = t and 50 or 0 },
    FloatNormal = { fg = c.dropdown_foreground, bg = c.dropdown_background, blend = t and 50 or 0 },
    FloatActiveTitle = { link = "ms_b_bg0" },
    FloatTitle = { fg = c.notificationCenterHeader_foreground, bg = c.notificationCenterHeader_background, bold = true },
    FoldColumn = { fg = c.editorLineNumber_foreground },
    Folded = { fg = c.descriptionForeground, bg = c.editorWidget_background },
    Function = { fg = c.tokenFunctionDeclarations },
    Identifier = { fg = c.tokenVariableAndParameterName },
    Include = { fg = c.tokenKeyword },
    IncSearch = { fg = c.none, bg = c.editor_findMatchBackground, bold = true },
    Italic = { fg = c.editor_foreground, italic = true },
    Keyword = { fg = c.tokenKeyword },
    Label = { fg = c.tokenMarkupHeading },
    Macro = { fg = c.accentAqua },
    Member = { fg = c.accentAqua },
    Method = { fg = c.tokenFunctionDeclarations },
    LineNr = { fg = c.editorLineNumber_foreground },
    LspCodeLens = { fg = c.muted, italic = true },
    LspInlayHint = { fg = c.descriptionForeground, bg = t and c.none or c.editorWidget_background, italic = true },
    LspReferenceRead = { bg = cs.mix(c.editor_background, c.selection, 40) },
    LspReferenceText = { bg = cs.mix(c.editor_background, c.selection, 40) },
    LspReferenceWrite = { bg = cs.mix(c.editor_background, c.accentOrange, 35) },
    LspSignatureActiveParameter = {
      fg = c.tokenFunctionDeclarations,
      bg = cs.mix(c.editor_background, c.selection, 45),
      bold = true,
    },
    RenamerBorder = { link = t and "ms_b_bg0" or "ms_b_none" },
    RenamerTitle = { link = t and "ms_b_bg0" or "ms_b_none" },
    MatchParen = { fg = c.accentOrange, bg = cs.mix(c.editor_background, c.selection, 55), bold = true },
    MatchWord = { fg = c.editor_foreground, bg = c.editor_selectionHighlightBackground },
    MiniIndentscopeSymbol = { fg = c.editorIndentGuide_activeBackground1 },
    ModeMsg = { fg = c.statusBar_foreground, bg = c.statusBar_background, bold = true },
    MoreMsg = { fg = c.success, bg = c.statusBar_background, bold = true },
    MsgArea = { fg = c.statusBar_foreground, bg = c.statusBar_background, blend = t and 50 or 0 },
    NonText = {
      fg = cs.mix(c.editor_background, c.editorLineNumber_foreground, 45),
      italic = true,
    },
    Normal = { fg = c.editor_foreground, bg = c.editor_background, blend = t and 50 or 0 },
    NormalFloat = { fg = c.dropdown_foreground, bg = c.dropdown_background },
    NormalNC = { fg = c.editor_foreground, bg = c.editor_background, blend = t and 50 or 0 },
    NvimInternalError = { fg = c.errorForeground },
    Number = { fg = c.semanticNumberLiteral },
    Operator = { fg = c.semanticNewOperator },
    Parameter = { fg = c.tokenVariableAndParameterName },
    Pmenu = { fg = c.menu_foreground, bg = c.menu_background, blend = t and 50 or 0 },
    PmenuSbar = { bg = c.menu_separatorBackground },
    PmenuSel = { fg = c.menu_foreground, bg = c.menu_selectionBackground, bold = true },
    PmenuThumb = { bg = c.menu_border },
    PreCondit = { fg = c.tokenKeyword },
    PreProc = { fg = c.tokenKeyword },
    Repeat = { fg = c.tokenKeyword },
    Question = { fg = c.success },
    QuickFixLine = { fg = c.quickInput_foreground, bg = c.list_dropBackground, bold = true },
    Removed = { fg = c.accentRed },
    Search = { fg = c.none, bg = c.editor_findMatchBackground },
    SignColumn = { fg = c.editorLineNumber_foreground, bg = c.editor_background },
    Special = { fg = c.tokenMarkupInlineRaw },
    SpecialChar = { fg = c.tokenString },
    SpecialKey = { fg = c.editorLineNumber_foreground },
    healthError = { fg = c.errorForeground },
    healthSuccess = { fg = c.editor_background, bg = c.success },
    healthWarning = { fg = c.warning },
    SpellBad = { undercurl = true, sp = c.errorForeground },
    SpellCap = { undercurl = true, sp = c.accentBlue },
    SpellLocal = { undercurl = true, sp = c.accentGreen },
    SpellRare = { undercurl = true, sp = c.accentPurple },
    Statement = { fg = c.tokenKeyword },
    StatusColumnMark = { link = "DiagnosticHint", default = true },
    StatusLine = { fg = c.statusBar_foreground, bg = c.statusBar_background, blend = t and 50 or 0 },
    StatusLineNC = { fg = c.descriptionForeground, bg = c.statusBar_noFolderBackground, blend = t and 50 or 0 },
    StorageClass = { fg = c.tokenKeyword },
    String = { fg = c.semanticStringLiteral },
    Structure = { fg = c.tokenTypesDeclarationAndReferences },
    Substitute = { fg = c.editor_background, bg = c.accentRed },
    TabLine = { fg = c.tab_inactiveForeground, bg = c.tab_inactiveBackground, blend = t and 50 or 0 },
    TabLineFill = { fg = c.tab_inactiveForeground, bg = c.editorGroupHeader_tabsBackground, blend = t and 50 or 0 },
    TabLineSel = { fg = c.tab_activeForeground, bg = c.tab_activeBackground, bold = true, blend = t and 50 or 0 },
    Tag = { fg = c.tokenEntityNameTag, bold = true },
    Title = { fg = c.accentBlue, bold = true },
    Todo = { fg = c.editor_background, bg = c.accentOrange, bold = true, italic = true },
    TooLong = { fg = c.errorForeground },
    Type = { fg = c.tokenTypesDeclarationAndReferences },
    Typedef = { fg = c.tokenTypesDeclarationAndReferences },
    UnderLined = { underline = true },
    Variable = { fg = c.tokenVariableAndParameterName },
    Visual = { bg = c.selection, fg = c.editor_foreground },
    VisualNOS = { link = "Visual" },
    WarningMsg = { fg = c.warning, bg = c.statusBar_background, bold = true },
    Whitespace = { fg = c.editorIndentGuide_background1 },
    WildMenu = { fg = c.menu_foreground, bg = c.menu_selectionBackground, bold = true },
    WinBar = { fg = c.titleBar_activeForeground, bg = c.titleBar_activeBackground, blend = t and 50 or 0 },
    WinBarNC = { fg = c.titleBar_inactiveForeground, bg = c.titleBar_inactiveBackground, blend = t and 50 or 0 },
    VertSplit = { fg = c.editorGroupHeader_tabsBorder },
    VertSplitActive = { fg = c.tab_activeBorder },
    WinSeparator = { fg = c.editorGroup_border },
  }

  return hlgroup_map
end

return M
