---@class eve.constant.hlgroup.vsc.lsp
local M = {}

---@param context                       std.t.theme.IContext
---@return table<string, std.t.theme.IHlgroup>
function M.gen_hlgroup_map(context)
  local c = context.scheme.palette.vsc ---@type std.t.theme.IVscPalette

  return {
    ["@lsp.mod.declaration"] = {},
    ["@lsp.mod.definition"] = {},
    ["@lsp.mod.deprecated"] = { fg = c.tokenInvalid, strikethrough = true },
    ["@lsp.mod.documentation"] = { italic = true },
    ["@lsp.mod.modification"] = { underline = true },
    ["@lsp.mod.readonly"] = { italic = true },
    ["@lsp.mod.static"] = { italic = true },
    ["@lsp.type.boolean"] = { link = "@boolean" },
    ["@lsp.type.builtin"] = { link = "@type.builtin" },
    ["@lsp.type.builtinType"] = { link = "@type.builtin" },
    ["@lsp.type.class"] = { fg = c.tokenTypesDeclarationAndReferences },
    ["@lsp.type.class.lua"] = { fg = c.tokenTypesDeclarationAndReferences },
    ["@lsp.type.comment"] = { link = "@comment" },
    ["@lsp.type.decorator"] = { fg = c.tokenTypesDeclarationAndReferences },
    ["@lsp.type.deriveHelper"] = { fg = c.tokenFunctionDeclarations },
    ["@lsp.type.enum"] = { fg = c.tokenTypesDeclarationAndReferences },
    ["@lsp.type.enumMember"] = { fg = c.tokenConstantsAndEnums },
    ["@lsp.type.escapeSequence"] = { link = "@string.escape" },
    ["@lsp.type.event"] = { fg = c.tokenVariableAndParameterName },
    ["@lsp.type.formatSpecifier"] = { link = "@string.special" },
    ["@lsp.type.function"] = { fg = c.tokenFunctionDeclarations },
    ["@lsp.type.generic"] = { fg = c.tokenTypesDeclarationAndReferences },
    ["@lsp.type.interface"] = { fg = c.tokenTypesDeclarationAndReferences },
    ["@lsp.type.keyword"] = { fg = c.tokenKeyword },
    ["@lsp.type.keyword.lua"] = { fg = c.tokenKeyword },
    ["@lsp.type.label"] = { fg = c.tokenEntityNameLabel },
    ["@lsp.type.lifetime"] = { fg = c.tokenControlFlowSpecialKeywords },
    ["@lsp.type.macro"] = { fg = c.tokenMetaPreprocessor },
    ["@lsp.type.method"] = { fg = c.tokenFunctionDeclarations },
    ["@lsp.type.modifier"] = { fg = c.tokenKeyword },
    ["@lsp.type.namespace"] = { fg = c.tokenTypesDeclarationAndReferences },
    ["@lsp.type.namespace.python"] = { fg = c.tokenTypesDeclarationAndReferences },
    ["@lsp.type.namespace.typescriptreact"] = { fg = c.tokenTypesDeclarationAndReferences },
    ["@lsp.type.number"] = { fg = c.semanticNumberLiteral },
    ["@lsp.type.operator"] = { fg = c.semanticNewOperator },
    ["@lsp.type.parameter"] = { fg = c.tokenVariableAndParameterName },
    ["@lsp.type.parameter.lua"] = { fg = c.tokenVariableAndParameterName },
    ["@lsp.type.primitive"] = { link = "@type.builtin" },
    ["@lsp.type.property"] = { fg = c.tokenVariableAndParameterName },
    ["@lsp.type.regexp"] = { fg = c.tokenStringRegexp },
    ["@lsp.type.selfKeyword"] = { fg = c.tokenThisSelf },
    ["@lsp.type.selfTypeKeyword"] = { link = "@type.builtin" },
    ["@lsp.type.string"] = { fg = c.semanticStringLiteral },
    ["@lsp.type.struct"] = { fg = c.tokenTypesDeclarationAndReferences },
    ["@lsp.type.type"] = { fg = c.tokenTypesDeclarationAndReferences },
    ["@lsp.type.typeAlias"] = { fg = c.tokenTypesDeclarationAndReferences },
    ["@lsp.type.typeParameter"] = { fg = c.tokenTypesDeclarationAndReferences },
    ["@lsp.type.unresolvedReference"] = { undercurl = true, sp = c.tokenInvalid },
    ["@lsp.type.variable"] = { fg = c.tokenVariableAndParameterName },
    ["@lsp.typemod.class.declaration"] = { fg = c.tokenTypesDeclarationAndReferences },
    ["@lsp.typemod.class.declaration.lua"] = { fg = c.descriptionForeground, italic = true },
    ["@lsp.typemod.class.defaultLibrary"] = { fg = c.tokenTypesDeclarationAndReferences },
    ["@lsp.typemod.enum.declaration"] = { fg = c.tokenTypesDeclarationAndReferences },
    ["@lsp.typemod.enum.defaultLibrary"] = { fg = c.tokenTypesDeclarationAndReferences },
    ["@lsp.typemod.enumMember.declaration"] = { fg = c.tokenConstantsAndEnums },
    ["@lsp.typemod.enumMember.defaultLibrary"] = { fg = c.tokenConstantsAndEnums },
    ["@lsp.typemod.function.builtin"] = { fg = c.tokenFunctionDeclarations },
    ["@lsp.typemod.function.declaration"] = { fg = c.tokenFunctionDeclarations },
    ["@lsp.typemod.function.defaultLibrary"] = { fg = c.tokenFunctionDeclarations },
    ["@lsp.typemod.interface.declaration"] = { fg = c.tokenTypesDeclarationAndReferences },
    ["@lsp.typemod.keyword.async"] = { fg = c.tokenControlFlowSpecialKeywords },
    ["@lsp.typemod.keyword.documentation.lua"] = { fg = c.accentBlue, italic = true },
    ["@lsp.typemod.keyword.injected"] = { fg = c.tokenKeyword },
    ["@lsp.typemod.macro.defaultLibrary"] = { fg = c.tokenMetaPreprocessor },
    ["@lsp.typemod.method.builtin"] = { fg = c.tokenFunctionDeclarations },
    ["@lsp.typemod.method.declaration"] = { fg = c.tokenFunctionDeclarations },
    ["@lsp.typemod.method.defaultLibrary"] = { fg = c.tokenFunctionDeclarations },
    ["@lsp.typemod.operator.injected"] = { fg = c.semanticNewOperator },
    ["@lsp.typemod.parameter.documentation"] = { fg = c.accentBlue, italic = true },
    ["@lsp.typemod.property.readonly"] = { fg = c.tokenConstantsAndEnums, italic = true },
    ["@lsp.typemod.string.injected"] = { fg = c.semanticStringLiteral },
    ["@lsp.typemod.struct.declaration"] = { fg = c.tokenTypesDeclarationAndReferences },
    ["@lsp.typemod.struct.defaultLibrary"] = { fg = c.tokenTypesDeclarationAndReferences },
    ["@lsp.typemod.type.declaration"] = { fg = c.tokenTypesDeclarationAndReferences },
    ["@lsp.typemod.type.defaultLibrary"] = { fg = c.tokenTypesDeclarationAndReferences },
    ["@lsp.typemod.typeAlias.defaultLibrary"] = { fg = c.tokenTypesDeclarationAndReferences },
    ["@lsp.typemod.variable.callable"] = { fg = c.tokenFunctionDeclarations },
    ["@lsp.typemod.variable.declaration"] = { fg = c.tokenVariableAndParameterName },
    ["@lsp.typemod.variable.defaultLibrary"] = { fg = c.tokenThisSelf },
    ["@lsp.typemod.variable.injected"] = { fg = c.tokenVariableAndParameterName },
    ["@lsp.typemod.variable.readonly"] = { fg = c.tokenConstantsAndEnums, italic = true },
    ["@lsp.typemod.variable.readonly.typescriptreact"] = { fg = c.tokenConstantsAndEnums, italic = true },
    ["@lsp.typemod.variable.static"] = { fg = c.tokenVariableAndParameterName, italic = true },
  }
end

return M
