---@class eve.constant.hlgroup.vsc.plugin
local M = {}

---@param context                       dot.t.theme.IContext
---@return table<string, dot.t.theme.IHlgroup>
function M.gen_hlgroup_map(context)
  local cs = std.color
  local t = context.transparency ---@type boolean
  local c = context.scheme.palette.vsc ---@type dot.t.theme.IVscPalette
  local u = context.scheme.palette.unified ---@type dot.t.theme.UnifiedPalette
  local cmp_panel_bg = cs.mix(c.overlay, c.base, 70) ---@type string
  local treesitter_context_bg = t and c.none or cs.mix(c.base, c.accentBlue, 70) ---@type string
  local lazy_badge_fg = u.bg1 ---@type string
  local lazy_panel_bg = cs.mix(t and c.none or c.base, t and c.none or c.overlay, 60) ---@type string

  ---@type table<string, dot.t.theme.IHlgroup>
  return {
    ---! blink.cmp
    BlinkCmpDoc = { fg = c.text, bg = cmp_panel_bg },
    BlinkCmpDocBorder = { fg = c.border, bg = cmp_panel_bg },
    BlinkCmpDocSeparator = { fg = c.textMuted, bg = cmp_panel_bg },
    BlinkCmpGhostText = { fg = c.textMuted, default = true },
    BlinkCmpItemIdx = { fg = c.textDim, bg = c.none },
    BlinkCmpKindClass = { fg = c.tokenTypesDeclarationAndReferences, bg = c.none },
    BlinkCmpKindCodeium = { fg = c.success, bg = c.none },
    BlinkCmpKindColor = { fg = c.tokenCssPropertyValue, bg = c.none },
    BlinkCmpKindConstant = { fg = c.tokenConstantsAndEnums, bg = c.none },
    BlinkCmpKindConstructor = { fg = c.tokenFunctionDeclarations, bg = c.none },
    BlinkCmpKindCopilot = { fg = c.success, bg = c.none },
    BlinkCmpKindDefault = { fg = c.textDim, bg = c.none },
    BlinkCmpKindEnum = { fg = c.tokenConstantsAndEnums, bg = c.none },
    BlinkCmpKindEnumMember = { fg = c.tokenConstantsAndEnums, bg = c.none },
    BlinkCmpKindEvent = { fg = c.warning, bg = c.none },
    BlinkCmpKindField = { fg = c.tokenVariableAndParameterName, bg = c.none },
    BlinkCmpKindFile = { fg = c.text, bg = c.none },
    BlinkCmpKindFolder = { fg = c.accentBlue, bg = c.none },
    BlinkCmpKindFunction = { fg = c.tokenFunctionDeclarations, bg = c.none },
    BlinkCmpKindIdentifier = { fg = c.tokenVariableAndParameterName, bg = c.none },
    BlinkCmpKindInterface = { fg = c.tokenTypesDeclarationAndReferences, bg = c.none },
    BlinkCmpKindKeyword = { fg = c.tokenKeyword, bg = c.none },
    BlinkCmpKindMethod = { fg = c.tokenFunctionDeclarations, bg = c.none },
    BlinkCmpKindModule = { fg = c.tokenKeyword, bg = c.none },
    BlinkCmpKindOperator = { fg = c.semanticNewOperator, bg = c.none },
    BlinkCmpKindProperty = { fg = c.tokenObjectKeysTsGrammarSpecific, bg = c.none },
    BlinkCmpKindReference = { fg = c.tokenMarkupInlineRaw, bg = c.none },
    BlinkCmpKindSnippet = { fg = c.textMuted, bg = c.none },
    BlinkCmpKindStruct = { fg = c.tokenTypesDeclarationAndReferences, bg = c.none },
    BlinkCmpKindStructure = { fg = c.tokenTypesDeclarationAndReferences, bg = c.none },
    BlinkCmpKindSupermaven = { fg = c.success, bg = c.none },
    BlinkCmpKindTabNine = { fg = c.success, bg = c.none },
    BlinkCmpKindText = { fg = c.tokenString, bg = c.none },
    BlinkCmpKindType = { fg = c.tokenTypesDeclarationAndReferences, bg = c.none },
    BlinkCmpKindTypeParameter = { fg = c.tokenTypesDeclarationAndReferences, bg = c.none },
    BlinkCmpKindUnit = { fg = c.tokenConstantsAndEnums, bg = c.none },
    BlinkCmpKindValue = { fg = c.tokenConstantsAndEnums, bg = c.none },
    BlinkCmpKindVariable = { fg = c.tokenVariableAndParameterName, bg = c.none },
    BlinkCmpLabel = { fg = c.text, bg = c.none },
    BlinkCmpLabelDeprecated = { fg = c.textMuted, bg = c.none, strikethrough = true },
    BlinkCmpLabelMatch = { fg = c.accentBlue, bg = c.none, bold = true },
    BlinkCmpMenu = { fg = c.text, bg = cmp_panel_bg },
    BlinkCmpMenuBorder = { fg = c.border, bg = cmp_panel_bg },
    BlinkCmpSignatureHelp = { fg = c.text, bg = cmp_panel_bg },
    BlinkCmpSignatureHelpActiveParameter = { link = "LspSignatureActiveParameter" },
    BlinkCmpSignatureHelpBorder = { fg = c.border, bg = cmp_panel_bg },
    BlinkCmpSource = { fg = c.textDim, bg = c.none },

    ---! diffview.nvim
    DiffviewFilePanelDeletions = { fg = c.accentRed, bold = true },
    DiffviewFilePanelFileName = { fg = c.text, bold = true },
    DiffviewFilePanelInsertions = { fg = c.success, bold = true },
    DiffviewStatusModified = { fg = c.accentBlue, bold = true },

    ---! flash.nvim
    FlashBackdrop = { fg = c.textMuted },
    FlashCurrent = { fg = c.accentBlue, italic = true, bold = true },
    FlashLabel = { fg = t and c.none or c.base, bg = c.accentPurple, bold = true },
    FlashMatch = { fg = c.warning, italic = true },
    FlashPrompt = { fg = c.text, bg = std.color.mix(t and c.none or c.overlay, c.border, 12) },
    FlashPromptIcon = { fg = c.accentOrange, bg = c.none },

    ---! gitsigns.nvim
    GitSignsAdd = { fg = c.success },
    GitSignsAddNr = { link = "GitSignsAdd" },
    GitSignsChange = { fg = c.accentBlue },
    GitSignsChangeNr = { link = "GitSignsChange" },
    GitSignsDelete = { fg = c.accentRed },
    GitSignsDeleteNr = { link = "GitSignsDelete" },
    GitSignsTopdelete = { fg = c.accentRed },
    GitSignsTopdeleteNr = { link = "GitSignsTopdelete" },
    GitSignsUntracked = { fg = c.textMuted },
    GitSignsUntrackedNr = { link = "GitSignsUntracked" },
    GitSignsCurrentLineBlame = { fg = c.textMuted, italic = true },
    GitSignsStagedAdd = { fg = std.color.mix(c.base, c.success, 50) },
    GitSignsStagedAddNr = { link = "GitSignsStagedAdd" },
    GitSignsStagedChange = { fg = std.color.mix(c.base, c.accentBlue, 50) },
    GitSignsStagedChangeNr = { link = "GitSignsStagedChange" },
    GitSignsStagedDelete = { fg = std.color.mix(c.base, c.accentRed, 50) },
    GitSignsStagedDeleteNr = { link = "GitSignsStagedDelete" },
    GitSignsStagedTopdelete = { fg = std.color.mix(c.base, c.accentRed, 60) },
    GitSignsStagedTopdeleteNr = { link = "GitSignsStagedTopdelete" },
    GitSignsStagedUntracked = { fg = std.color.mix(c.base, c.textDim, 50) },
    GitSignsStagedUntrackedNr = { link = "GitSignsStagedUntracked" },

    ---! lazy.nvim
    LazyButton = { fg = c.text, bg = c.none },
    LazyButtonActive = { fg = u.pink, bg = c.none },
    LazyCommit = { fg = c.success },
    LazyCommitIssue = { fg = c.warning },
    LazyDir = { fg = c.text },
    LazyH1 = { fg = lazy_badge_fg, bg = u.pink, bold = true },
    LazyH2 = { fg = c.text, bold = true, underline = true },
    LazyNoCond = { fg = c.accentRed },
    LazyNormal = { fg = c.text, bg = lazy_panel_bg, blend = t and 0 or 40 },
    LazyProgressDone = { fg = c.accentBlue, bold = true },
    LazyProgressTodo = { fg = c.textMuted, italic = true },
    LazyReasonCmd = { fg = c.warning },
    LazyReasonEvent = { fg = c.warning },
    LazyReasonFt = { fg = c.tokenMarkupHeading },
    LazyReasonImport = { fg = c.text },
    LazyReasonKeys = { fg = c.accentBlue },
    LazyReasonPlugin = { fg = c.accentRed },
    LazyReasonRuntime = { fg = c.tokenKeyword },
    LazyReasonSource = { fg = c.success },
    LazyReasonStart = { fg = c.text },
    LazyOperator = { fg = c.text },
    LazyProp = { fg = c.tokenMarkupHeading, bold = true },
    LazySpecial = { fg = c.accentBlue },
    LazyTaskOutput = { fg = c.text },
    LazyUrl = { fg = c.accentBlue, underline = true },
    LazyValue = { fg = c.accentAqua },

    ---! mason.nvim
    MasonHeader = { fg = u.pink, bg = c.none },
    MasonHighlight = { fg = c.accentBlue },
    MasonHighlightBlock = { fg = lazy_badge_fg, bg = u.pink, bold = true },
    MasonHighlightBlockBold = { link = "MasonHighlightBlock" },
    MasonHeaderSecondary = { link = "MasonHighlightBlock" },
    MasonMuted = { fg = u.fg1 },
    MasonMutedBlock = { fg = u.fg1 },
    MasonNormal = { fg = c.text, bg = lazy_panel_bg, blend = t and 0 or 40 },

    ---! mini.icons
    MiniIconsAzure = { fg = c.accentBlue },
    MiniIconsBlue = { fg = c.accentBlue },
    MiniIconsCyan = { fg = c.accentAqua },
    MiniIconsGreen = { fg = c.success },
    MiniIconsGrey = { fg = c.textDim },
    MiniIconsOrange = { fg = c.accentOrange },
    MiniIconsPurple = { fg = c.accentPurple },
    MiniIconsRed = { fg = c.accentRed },
    MiniIconsYellow = { fg = c.accentYellow },

    ---! mini.indentscope
    MiniIndentscopeSymbol = { fg = c.accentPurple },
    MiniIndentscopeSymbolOff = { fg = c.accentRed },

    ---! neo-tree.nvim
    NeoTreeCursorLine = { link = "CursorLine" },
    NeoTreeCursorLineNr = { link = "CursorLineNr" },
    NeoTreeDirectoryIcon = { fg = c.accentBlue },
    NeoTreeDirectoryName = { fg = c.accentBlue },
    NeoTreeExpander = { fg = c.textMuted },
    NeoTreeFileName = { fg = c.text },
    NeoTreeFloatTitle = { link = "FloatTitle" },
    NeoTreeGitIgnored = { fg = c.textMuted },
    NeoTreeGitModified = { fg = c.warning },
    NeoTreeGitUntracked = { fg = c.success },
    NeoTreeIndentMarker = { fg = std.color.mix(t and c.none or c.base, c.border, 20) },
    NeoTreeNormal = { link = "Normal" },
    NeoTreeNormalNC = { link = "NormalNC" },
    NeoTreeRootName = { fg = c.text, bold = true },
    NeoTreeSignColumn = { link = "SignColumn" },
    NeoTreeFloatBorder = { link = "FloatBorder" },
    NeoTreeTab = { fg = c.textMuted, bg = c.none, bold = true },
    NeoTreeTabActive = { fg = t and c.none or c.base, bg = c.accentBlue, bold = true },
    NeoTreeTabSeparator = { fg = c.none, bg = c.none },
    NeoTreeTabSeparatorActive = { fg = c.accentBlue, bg = c.none },
    NeoTreeStatusLine = { link = "StatusLine" },
    NeoTreeStatusLineNC = { link = "StatusLineNC" },
    NeoTreeVertSplit = { link = "VertSplit" },
    NeoTreeEndOfBuffer = { link = "EndOfBuffer" },
    NeoTreeWinSeparator = { link = "WinSeparator" },
    NeoTreeWinbar = { fg = c.textMuted },
    NeoTreeHiddenByName = { fg = c.textDim },
    NeoTreeMessage = { fg = c.descriptionForeground },
    NeoTreeTitleBar = { fg = c.text },

    ---! nvim-dap
    DapBreakpoint = { fg = c.accentRed },
    DapBreakpointCondition = { fg = c.warning },
    DapBreakpointRejected = { fg = c.textMuted },
    DapLogPoint = { fg = c.accentBlue },
    DapStopped = { fg = c.accentOrange },
    DapStoppedLine = { bg = std.color.mix(t and c.none or c.base, c.accentOrange, 18), blend = 40 },

    ---! nvim-dap-ui
    DapUIBreakpointsCurrentLine = { fg = c.success, bold = true },
    DapUIBreakpointsDisabledLine = { fg = c.textMuted },
    DapUIBreakpointsInfo = { fg = c.success },
    DapUIBreakpointsLine = { fg = c.accentBlue },
    DapUIBreakpointsPath = { fg = c.accentBlue, bold = true },
    DapUICurrentFrameName = { fg = c.success, bold = true },
    DapUIDecoration = { fg = c.accentBlue },
    DapUIFloatBorder = { fg = c.border, bg = t and c.none or c.overlay },
    DapUILineNumber = { fg = c.accentBlue },
    DapUIModifiedValue = { fg = c.warning },
    DapUIPlayPause = { fg = c.success },
    DapUIRestart = { fg = c.accentBlue },
    DapUIScope = { fg = c.accentBlue },
    DapUISource = { fg = c.tokenMarkupHeading },
    DapUIStepBack = { fg = c.warning },
    DapUIStepInto = { fg = c.accentBlue },
    DapUIStepOut = { fg = c.accentBlue },
    DapUIStepOver = { fg = c.accentBlue },
    DapUIStop = { fg = c.accentRed },
    DapUIStopNC = { fg = c.accentRed },
    DapUIThread = { fg = c.success },
    DapUIEndofBuffer = { link = "EndOfBuffer" },
    DapUIFloatNormal = { link = "NormalFloat" },
    DapUIFrameName = { link = "Normal" },
    DapUINormal = { link = "Normal" },
    DapUIPlayPauseNC = { fg = c.success },
    DapUIRestartNC = { fg = c.success },
    DapUIStepBackNC = { fg = c.accentBlue },
    DapUIStepIntoNC = { fg = c.accentBlue },
    DapUIStepOutNC = { fg = c.accentBlue },
    DapUIStepOverNC = { fg = c.accentBlue },
    DapUIStoppedThread = { fg = c.accentAqua },
    DapUIType = { fg = c.accentPurple },
    DapUIUnavailable = { fg = c.textDim },
    DapUIUnavailableNC = { fg = c.textDim },
    DapUIValue = { fg = c.accentAqua },
    DapUIVariable = { fg = c.text },
    DapUIWatchesEmpty = { fg = c.accentRed },
    DapUIWatchesError = { fg = c.accentRed },
    DapUIWatchesValue = { fg = c.success },
    DapUIWinSelect = { fg = c.accentAqua, bold = true },

    ---! nvim-dap-virtual-text
    NvimDapVirtualText = {
      fg = c.textDim,
      bg = t and c.none or std.color.mix(c.base, c.accentOrange, 30),
      italic = true,
    },
    NvimDapVirtualTextChanged = {
      fg = c.text,
      bg = t and c.none or std.color.mix(c.base, c.accentOrange, 30),
      italic = true,
    },

    ---! snacks.nvim
    SnacksPickerLabel = { fg = c.accentBlue, bold = true },
    SnacksPickerFile = { fg = c.accentAqua },

    ---! notify.nvim
    NotifyERRORIcon = { fg = c.accentRed },
    NotifyWARNIcon = { fg = c.accentYellow },
    NotifyINFOIcon = { fg = c.success },
    NotifyDEBUGIcon = { fg = c.accentOrange },
    NotifyTRACEIcon = { fg = c.textDim },
    NotifyERRORTitle = { link = "NotifyERRORIcon" },
    NotifyWARNTitle = { link = "NotifyWARNIcon" },
    NotifyINFOTitle = { link = "NotifyINFOIcon" },
    NotifyDEBUGTitle = { link = "NotifyDEBUGIcon" },
    NotifyTRACETitle = { link = "NotifyTRACEIcon" },

    ---! treesitter-context
    TreesitterContext = { fg = c.text, bg = treesitter_context_bg },
    TreesitterContextBottom = { underline = true, sp = c.accentBlue },
    TreesitterContextLineNumber = {
      fg = c.accentOrange,
      bg = treesitter_context_bg,
    },
    TreesitterContextLineNumberBottom = { underline = true, sp = c.accentBlue },

    ---! which-key.nvim
    WhichKey = { fg = c.accentBlue, bold = true },
    WhichKeyDesc = { fg = c.descriptionForeground },
    WhichKeyGroup = { fg = c.accentPurple, italic = true },
    WhichKeyIconAzure = { fg = c.accentBlue },
    WhichKeyIconBlue = { fg = c.accentBlue },
    WhichKeyIconCyan = { fg = c.accentAqua },
    WhichKeyIconGreen = { fg = c.success },
    WhichKeyIconGrey = { fg = c.textDim },
    WhichKeyIconOrange = { fg = c.accentOrange },
    WhichKeyIconPurple = { fg = c.accentPurple },
    WhichKeyIconRed = { fg = c.accentRed },
    WhichKeyIconYellow = { fg = c.accentYellow },
    WhichKeyNormal = { fg = c.text, bg = t and c.none or c.list_dropBackground },
    WhichKeySeparator = { fg = c.textMuted },
    WhichKeyValue = { fg = c.success },
  }
end

return M
