# Use below command to show all available terminal colors.
#
# set_color --print-colors
#


set -U  fish_color_autosuggestion                (set_color white)
set -U  fish_color_command                       (set_color brblue)
set -U  fish_color_comment                       (set_color white)
set -U  fish_color_cancel                        (set_color --reverse)
set -U  fish_color_end                           (set_color bryellow)
set -U  fish_color_error                         (set_color red)
set -U  fish_color_escape                        (set_color brcyan)
set -U  fish_color_gray                          (set_color white)
set -U  fish_color_history_current               (set_color --bold)
set -U  fish_color_host_remote                   (set_color normal)
set -U  fish_color_keyword                       (set_color normal)
set -U  fish_color_operator                      (set_color bryellow)
set -U  fish_color_option                        (set_color normal)
set -U  fish_color_quote                         (set_color brgreen)
set -U  fish_color_match                         (set_color bryellow)
set -U  fish_color_normal                        (set_color brwhite)
set -U  fish_color_param                         (set_color brcyan)
set -U  fish_color_redirection                   (set_color brmagenta)
set -U  fish_color_search_match                  (set_color --background=bryellow)
set -U  fish_color_search_selection              (set_color --background=bryellow)
set -U  fish_color_status                        (set_color brred)
set -U  fish_color_valid_path                    (set_color --underline)
set -U  fish_pager_color_background              (set_color normal)
set -U  fish_pager_color_completion              (set_color normal)
set -U  fish_pager_color_description             (set_color white)
set -U  fish_pager_color_prefix                  (set_color normal --bold --underline)
set -U  fish_pager_color_progress                (set_color brwhite --background=cyan)
set -U  fish_pager_color_secondary_background    (set_color normal)
set -U  fish_pager_color_secondary_completion    (set_color normal)
set -U  fish_pager_color_secondary_description   (set_color normal)
set -U  fish_pager_color_secondary_prefix        (set_color normal)
set -U  fish_pager_color_selected_background     (set_color --background=bryellow)
set -U  fish_pager_color_selected_completion     (set_color normal)
set -U  fish_pager_color_selected_description    (set_color normal)
set -U  fish_pager_color_selected_prefix         (set_color normal)
