import fs from 'node:fs/promises'
import path from 'node:path'

import { gen_full_theme_name } from '#cli/theme/util'
import { XDG_CONFIG_HOME } from '#env'

async function publishBaseConfig(app) {
  await fs.copyFile(
    new URL('./base.conf', import.meta.url),
    path.join(app.home, 'base.conf'),
  )
}

export default {
  location: path.join(XDG_CONFIG_HOME, 'git-delta'),
  active: { directory: '.' },
  themes: 'theme/',
  extname: '.conf',
  local: 'config.conf',
  on_after_gen: publishBaseConfig,
  on_apply: async function (app, content, scheme) {
    const theme = gen_full_theme_name(scheme.theme, scheme.variant)
    const themePath = path.posix.join(app.themes, `${theme}${app.extname}`)
    await fs.mkdir(path.dirname(path.join(app.home, themePath)), { recursive: true })
    await publishBaseConfig(app)
    await fs.writeFile(path.join(app.home, themePath), content, 'utf8')

    // Keep selection separate so regeneration updates the active theme through its include.
    const selection = [
      '# Generated by guanghechen/asset/theme/template/git-delta/meta.mjs.',
      '[include]',
      '    path = base.conf',
      `    path = ${themePath}`,
      '',
      '[delta]',
      `    features = base ${theme}`,
      '',
    ].join('\n')
    await fs.writeFile(path.join(app.home, app.local), selection, 'utf8')
  },
}
