---@meta

---@module 'rstd'
---@class rstd
---@field public string                 rstd.string
---@field public fn                     rstd.fn
---@field public path                   rstd.path
---@field public fs                     rstd.fs
---@field public replace                rstd.replace
---@field public find                   rstd.find
---@field public search                 rstd.search
