---@class ghc.types.ui.theme.IColors
---@field public  white                 string
---@field public  darker_black          string
---@field public  black                 string
---@field public  black2                string
---@field public  one_bg                string
---@field public  one_bg2               string
---@field public  one_bg3               string
---@field public  grey                  string
---@field public  grey_fg               string
---@field public  grey_fg2              string
---@field public  light_grey            string
---@field public  red                   string
---@field public  baby_pink             string
---@field public  pink                  string
---@field public  line                  string
---@field public  green                 string
---@field public  vibrant_green         string
---@field public  nord_blue             string
---@field public  blue                  string
---@field public  yellow                string
---@field public  sun                   string
---@field public  purple                string
---@field public  dark_purple           string
---@field public  teal                  string
---@field public  orange                string
---@field public  cyan                  string
---@field public  statusline_bg         string
---@field public  lightbg               string
---@field public  pmenu_bg              string
---@field public  folder_bg             string
---@field public  diff_delete           string
---@field public  diff_add              string
---@field public  diff_delete_hl        string
---@field public  diff_add_hl           string

---@class ghc.types.ui.theme.IScheme
---@field public mode                   ghc.enums.theme.Mode
---@field public colors                 ghc.types.ui.theme.IColors

---@class ghc.types.ui.theme.IHighlightConfig
---@field public fg                     ?ghc.enums.theme.Color|"none"
---@field public bg                     ?ghc.enums.theme.Color|"none"
---@field public sp                     ?ghc.enums.theme.Color|"none"
---@field public blend                  ?integer  0-100 [0, 100]
---@field public bold                   ?boolean
---@field public standout               ?boolean
---@field public underline              ?boolean
---@field public undercurl              ?boolean
---@field public underdouble            ?boolean
---@field public underdotted            ?boolean
---@field public underdashed            ?boolean
---@field public strikethrough          ?boolean
---@field public italic                 ?boolean
---@field public reverse                ?boolean
---@field public nocombine              ?boolean
---@field public link                   ?string

---@class ghc.types.ui.theme.IHighlightGroup : vim.api.keyset.highlight

---@class ghc.types.ui.theme.IApplyParams
---@field public scheme                 ghc.types.ui.theme.IScheme
---@field public nsnr                   integer

---@class ghc.types.ui.theme.ICompileParams
---@field public scheme                 ghc.types.ui.theme.IScheme
---@field public filepath               string
---@field public nsnr                   integer

---@class ghc.types.ui.ITheme
---@field public apply                  fun(self: ghc.types.ui.ITheme, params: ghc.types.ui.theme.IApplyParams): nil
---@field public compile                fun(self: ghc.types.ui.ITheme, params: ghc.types.ui.theme.ICompileParams): nil
---@field public register               fun(self: ghc.types.ui.ITheme, hlname: string, hlconfig: ghc.types.ui.theme.IHighlightConfig): ghc.types.ui.ITheme
---@field public registers              fun(self: ghc.types.ui.ITheme, hlconfig_map: table<string, ghc.types.ui.theme.IHighlightConfig>): ghc.types.ui.ITheme
---@field public resolve                fun(self: ghc.types.ui.ITheme, scheme: ghc.types.ui.theme.IScheme): table<string, ghc.types.ui.theme.IHighlightGroup>
