---@class dot.theme.hlgroup.treesitter
local M = {}

---@param context                       dot.t.theme.IContext
---@return table<string, ark.t.theme.IHlgroup>
function M.gen_hlgroup_map(context)
  local md = string.format("dot.theme.hlgroup.%s.treesitter", context.scheme.theme) ---@type string
  local ok, mod = pcall(require, md)
  if ok and mod then
    return mod.gen_hlgroup_map(context)
  end

  return M.default_gen_hlgroup_map(context)
end

---@param context                       dot.t.theme.IContext
---@return table<string, ark.t.theme.IHlgroup>
function M.default_gen_hlgroup_map(context)
  local cs = ark.color
  local c = context.scheme.palette.unified ---@type ark.t.theme.UnifiedPalette

  return {
    ["@annotation"] = { fg = c.brightRed },
    ["@attribute"] = { link = "PreProc" },
    ["@attribute.c_sharp"] = { link = "@attribute" },
    ["@boolean"] = { link = "Boolean" },
    ["@character"] = { link = "Character" },
    ["@character.printf"] = { link = "SpecialChar" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@character.special.html"] = { link = "@character.special" },
    ["@comment"] = { link = "Comment" },
    ["@comment.danger"] = { fg = c.bg1, bg = c.red },
    ["@comment.documentation"] = { link = "Comment", italic = true },
    ["@comment.error"] = { link = "ErrorMsg" },
    ["@comment.hint"] = { link = "SpecialComment" },
    ["@comment.info"] = { link = "SpecialComment" },
    ["@comment.note"] = { link = "SpecialComment" },
    ["@comment.todo"] = { link = "Todo" },
    ["@comment.warning"] = { link = "WarningMsg" },
    ["@comment.warning.gitcommit"] = { link = "WarningMsg" },
    ["@conditional"] = { link = "Conditional" },
    ["@constant"] = { link = "Constant" },
    ["@constant.java"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "Special" },
    ["@constant.macro"] = { link = "Define" },
    ["@constructor"] = { link = "Special" },
    ["@constructor.lua"] = { link = "@constructor" },
    ["@constructor.python"] = { link = "@constructor" },
    ["@constructor.tsx"] = { link = "@constructor" },
    ["@debug"] = { link = "Debug" },
    ["@define"] = { link = "Define" },
    ["@diff.plus"] = { link = "DiffAdded" },
    ["@diff.minus"] = { link = "DiffRemoved" },
    ["@diff.delta"] = { link = "DiffChanged" },
    ["@error"] = { fg = c.red },
    ["@event"] = { fg = c.red },
    ["@exception"] = { link = "Exception" },
    ["@field"] = { link = "Identifier" },
    ["@float"] = { link = "Float" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { link = "Builtin" },
    ["@function.builtin.bash"] = { link = "@function.builtin" },
    ["@function.call"] = { link = "Function" },
    ["@function.macro"] = { link = "Macro" },
    ["@function.method"] = { link = "Method" },
    ["@function.method.call"] = { link = "@function.method" },
    ["@include"] = { link = "Include" },
    ["@keyword"] = { fg = c.purple, italic = true },
    ["@keyword.coroutine"] = { link = "Keyword" },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.conditional.ternary"] = { link = "Keyword" },
    ["@keyword.debug"] = { link = "Debug" },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.directive.css"] = { link = "@keyword.directive" },
    ["@keyword.directive.define"] = { link = "Define" },
    ["@keyword.exception"] = { link = "Exception" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.import.c"] = { link = "@keyword.import" },
    ["@keyword.import.cpp"] = { link = "@keyword.import" },
    ["@keyword.operator"] = { link = "Keyword" },
    ["@keyword.modifier"] = { link = "Keyword" },
    ["@keyword.repeat"] = { link = "Repeat" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@keyword.storage"] = { link = "StorageClass" },
    ["@keyword.type"] = { link = "Type" },
    ["@label"] = { link = "Label" },
    ["@label.yaml"] = { link = "@label" },
    ["@macro"] = { link = "Macro" },
    ["@markup"] = { fg = c.fg1 },
    ["@markup.emphasis"] = { italic = true },
    ["@markup.environment"] = { link = "Macro" },
    ["@markup.environment.name"] = { link = "Type" },
    ["@markup.heading"] = { fg = c.purple, bold = true },
    ["@markup.heading.1"] = { fg = c.purple, bg = cs.mix(c.bg0, c.purple, 15), bold = true },
    ["@markup.heading.1.markdown"] = { fg = c.purple, bg = cs.mix(c.bg0, c.purple, 15), bold = true },
    ["@markup.heading.2"] = { fg = c.aqua, bg = cs.mix(c.bg0, c.aqua, 15), bold = true },
    ["@markup.heading.2.markdown"] = { fg = c.aqua, bg = cs.mix(c.bg0, c.aqua, 15), bold = true },
    ["@markup.heading.3"] = { fg = c.orange, bg = cs.mix(c.bg0, c.orange, 15), bold = true },
    ["@markup.heading.3.markdown"] = { fg = c.orange, bg = cs.mix(c.bg0, c.orange, 15), bold = true },
    ["@markup.heading.4"] = { fg = c.yellow, bg = cs.mix(c.bg0, c.yellow, 15), bold = true },
    ["@markup.heading.4.markdown"] = { fg = c.yellow, bg = cs.mix(c.bg0, c.yellow, 15), bold = true },
    ["@markup.heading.5"] = { fg = c.blue, bg = cs.mix(c.bg0, c.blue, 15), bold = true },
    ["@markup.heading.5.markdown"] = { fg = c.blue, bg = cs.mix(c.bg0, c.blue, 15), bold = true },
    ["@markup.heading.6"] = { fg = c.green, bg = cs.mix(c.bg0, c.green, 15), bold = true },
    ["@markup.heading.6.markdown"] = { fg = c.green, bg = cs.mix(c.bg0, c.green, 15), bold = true },
    ["@markup.heading.1.marker"] = { link = "@markup.heading.1" },
    ["@markup.heading.1.marker.markdown"] = { link = "@markup.heading.1.markdown" },
    ["@markup.heading.2.marker"] = { link = "@markup.heading.2" },
    ["@markup.heading.2.marker.markdown"] = { link = "@markup.heading.2.markdown" },
    ["@markup.heading.3.marker"] = { link = "@markup.heading.3" },
    ["@markup.heading.3.marker.markdown"] = { link = "@markup.heading.3.markdown" },
    ["@markup.heading.4.marker"] = { link = "@markup.heading.4" },
    ["@markup.heading.4.marker.markdown"] = { link = "@markup.heading.4.markdown" },
    ["@markup.heading.5.marker"] = { link = "@markup.heading.5" },
    ["@markup.heading.5.marker.markdown"] = { link = "@markup.heading.5.markdown" },
    ["@markup.heading.6.marker"] = { link = "@markup.heading.6" },
    ["@markup.heading.6.marker.markdown"] = { link = "@markup.heading.6.markdown" },
    ["@markup.italic"] = { italic = true },
    ["@markup.link"] = { link = "Underlined" },
    ["@markup.link.label"] = { link = "SpecialChar" },
    ["@markup.link.label.html"] = { link = "@markup.link.label" },
    ["@markup.link.label.symbol"] = { link = "@markup.link.label" },
    ["@markup.list"] = { fg = c.blue },
    ["@markup.list.markdown"] = { link = "@markup.list" },
    ["@markup.list.checked"] = { fg = c.blue, blend = 10 },
    ["@markup.list.unchecked"] = { fg = c.fg4 },
    ["@markup.link.url"] = { fg = c.orange, underline = true },
    ["@markup.math"] = { link = "Special" },
    ["@markup.quote"] = { bg = c.bg1 },
    ["@markup.raw"] = { link = "String" },
    ["@markup.raw.markdown_inline"] = { link = "@markup.raw" },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.underline"] = { underline = true },
    ["@method"] = { link = "Function" },
    ["@method.call"] = { link = "Function" },
    ["@modifier"] = { fg = c.red },
    ["@module"] = { fg = c.fg1 },
    ["@module.builtin"] = { fg = c.fg2 },
    ["@namespace"] = { fg = c.fg1 },
    ["@namespace.builtin"] = { fg = c.fg2 },
    ["@none"] = { fg = c.fg1 },
    ["@number"] = { link = "Number" },
    ["@number.css"] = { link = "@number" },
    ["@number.float"] = { link = "Float" },
    ["@operator"] = { link = "Operator" },
    ["@parameter"] = { link = "Identifier" },
    ["@preproc"] = { link = "PreProc" },
    ["@property"] = { link = "Identifier" },
    ["@property.class.css"] = { link = "@property" },
    ["@property.css"] = { link = "@property" },
    ["@property.id.css"] = { link = "@property" },
    ["@property.scss"] = { link = "@property" },
    ["@punctuation"] = { link = "Delimiter" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { link = "Delimiter" },
    ["@punctuation.special"] = { link = "Delimiter" },
    ["@punctuation.special.markdown"] = { link = "@punctuation.special" },
    ["@reference"] = { fg = c.fg0 },
    ["@regexp"] = { fg = c.brightRed },
    ["@repeat"] = { link = "Repeat" },
    ["@scope"] = {},
    ["@string"] = { link = "String" },
    ["@string.documentation"] = { link = "@string" },
    ["@string.regex"] = { link = "String" },
    ["@string.regexp"] = { link = "String" },
    ["@string.escape"] = { link = "SpecialChar" },
    ["@string.special"] = { link = "SpecialChar" },
    ["@string.plain.css"] = { link = "@string" },
    ["@string.special.path"] = { link = "Underlined" },
    ["@string.special.symbol"] = { link = "Identifier" },
    ["@string.special.url"] = { link = "Underlined" },
    ["@string.special.url.html"] = { link = "@string.special.url" },
    ["@storageclass"] = { link = "StorageClass" },
    ["@structure"] = { link = "Structure" },
    ["@symbol"] = { link = "Identifier" },
    ["@tag"] = { link = "Tag" },
    ["@tag.builtin"] = { link = "@tag" },
    ["@tag.attribute"] = { link = "Identifier" },
    ["@tag.delimiter"] = { link = "Delimiter" },
    ["@tag.delimiter.tsx"] = { link = "@tag.delimiter" },
    ["@tag.javascript"] = { link = "@tag" },
    ["@tag.tsx"] = { link = "@tag" },
    ["@text"] = { fg = c.fg1 },
    ["@text.strong"] = {},
    ["@text.emphasis"] = { italic = true },
    ["@text.underline"] = { underline = true },
    ["@text.strike"] = { strikethrough = true },
    ["@text.title"] = { link = "Title" },
    ["@text.literal"] = { link = "String" },
    ["@text.uri"] = { link = "Underlined" },
    ["@text.math"] = { link = "Special" },
    ["@text.environment"] = { link = "Macro" },
    ["@text.environment.name"] = { link = "Type" },
    ["@text.reference"] = { link = "Constant" },
    ["@text.todo"] = { link = "Todo" },
    ["@text.todo.checked"] = { fg = c.green },
    ["@text.todo.unchecked"] = { fg = c.fg4 },
    ["@text.note"] = { link = "SpecialComment" },
    ["@text.note.comment"] = { fg = c.purple },
    ["@text.warning"] = { link = "WarningMsg" },
    ["@text.danger"] = { link = "ErrorMsg" },
    ["@text.danger.comment"] = { fg = c.fg0, bg = c.red },
    ["@text.diff.add"] = { link = "DiffAdded" },
    ["@text.diff.delete"] = { link = "DiffRemoved" },
    ["@type"] = { link = "Type" },
    ["@type.css"] = { link = "@type" },
    ["@type.tag.css"] = { link = "@type" },
    ["@type.tsx"] = { link = "Variable" },
    ["@type.builtin"] = { link = "Type" },
    ["@type.definition"] = { link = "Typedef" },
    ["@type.qualifier"] = { link = "Type" },
    ["@variable"] = { link = "Variable" },
    ["@variable.jsx"] = { fg = c.blue },
    ["@variable.tsx"] = { fg = c.blue },
    ["@variable.builtin"] = { link = "Builtin" },
    ["@variable.member"] = { link = "Member" },
    ["@variable.parameter"] = { link = "Parameter" },
    ["@variable.parameter.bash"] = { link = "@variable.parameter" },
    ["@variable.parameter.builtin"] = { link = "@variable.parameter" },
    ["@variable.parameter.luadoc"] = { link = "@variable.parameter" },
  }
end

return M
