---@diagnostic disable-next-line: unused-local
local __module_name__ = "dot.theme.hlgroup.treesitter.rosepine" ---@type string

-- Official syntax defaults: rose-pine/neovim@ff483051a47e.
---@class dot.theme.hlgroup.treesitter.rosepine
local M = {}

---@param context                       stl.t.theme.IContext
---@return table<string, stl.t.theme.IHlgroup>
function M.gen_hlgroup_map(context)
  local cs = stl.color
  local c = context.scheme.palette.rosepine ---@type stl.t.theme.IRosepinePalette

  return {
    ["@variable"] = { fg = c.text, italic = true },
    ["@variable.builtin"] = { fg = c.love, italic = true, bold = true },
    ["@variable.parameter"] = { fg = c.iris, italic = true },
    ["@variable.parameter.builtin"] = { fg = c.iris, italic = true, bold = true },
    ["@variable.member"] = { fg = c.foam },
    ["@constant"] = { fg = c.gold },
    ["@constant.builtin"] = { fg = c.gold, bold = true },
    ["@constant.macro"] = { fg = c.gold },
    ["@module"] = { fg = c.text },
    ["@module.builtin"] = { fg = c.text, bold = true },
    ["@label"] = { link = "Label" },
    ["@string"] = { link = "String" },
    ["@string.regexp"] = { fg = c.iris },
    ["@string.escape"] = { fg = c.pine },
    ["@string.special"] = { link = "String" },
    ["@string.special.symbol"] = { link = "Identifier" },
    ["@string.special.url"] = { fg = c.iris },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "Character" },
    ["@boolean"] = { link = "Boolean" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Number" },
    ["@float"] = { link = "Number" },
    ["@type"] = { fg = c.foam },
    ["@type.builtin"] = { fg = c.foam, bold = true },
    ["@attribute"] = { fg = c.iris },
    ["@attribute.builtin"] = { fg = c.iris, bold = true },
    ["@property"] = { fg = c.foam, italic = true },
    ["@function"] = { fg = c.rose },
    ["@function.builtin"] = { fg = c.rose, bold = true },
    ["@function.macro"] = { link = "Function" },
    ["@function.method"] = { fg = c.rose },
    ["@function.method.call"] = { fg = c.iris },
    ["@constructor"] = { fg = c.foam },
    ["@operator"] = { link = "Operator" },
    -- Basic keyword roles own the transparency adjustment for both syntax layers.
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.operator"] = { fg = c.subtle },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.storage"] = { fg = c.foam },
    ["@keyword.repeat"] = { link = "Repeat" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@keyword.debug"] = { fg = c.rose },
    ["@keyword.exception"] = { link = "Exception" },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.conditional.ternary"] = { link = "Conditional" },
    ["@keyword.directive"] = { fg = c.iris },
    ["@keyword.directive.define"] = { fg = c.iris },
    ["@punctuation.delimiter"] = { fg = c.subtle },
    ["@punctuation.bracket"] = { fg = c.subtle },
    ["@punctuation.special"] = { fg = c.subtle },
    ["@comment"] = { link = "Comment" },
    ["@comment.error"] = { fg = c.love },
    ["@comment.warning"] = { fg = c.gold },
    ["@comment.todo"] = { fg = c.rose, bg = cs.mix(c.base, c.rose, 15) },
    ["@comment.hint"] = { fg = c.iris, bg = cs.mix(c.base, c.iris, 15) },
    ["@comment.info"] = { fg = c.foam, bg = cs.mix(c.base, c.foam, 15) },
    ["@comment.note"] = { fg = c.pine, bg = cs.mix(c.base, c.pine, 15) },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.heading"] = { fg = c.foam, bold = true },
    ["@markup.quote"] = { fg = c.text },
    ["@markup.math"] = { link = "Special" },
    ["@markup.environment"] = { link = "Macro" },
    ["@markup.environment.name"] = { link = "@type" },
    ["@markup.link.markdown_inline"] = { fg = c.subtle },
    ["@markup.link.label.markdown_inline"] = { fg = c.foam },
    ["@markup.link.url"] = { fg = c.iris },
    ["@markup.raw.delimiter.markdown"] = { fg = c.subtle },
    ["@markup.list"] = { fg = c.pine },
    ["@markup.list.checked"] = { fg = c.foam, bg = cs.mix(c.base, c.foam, 10) },
    ["@markup.list.unchecked"] = { fg = c.text },
    ["@markup.heading.1.markdown"] = { fg = c.iris, bold = true },
    ["@markup.heading.2.markdown"] = { fg = c.foam, bold = true },
    ["@markup.heading.3.markdown"] = { fg = c.rose, bold = true },
    ["@markup.heading.4.markdown"] = { fg = c.gold, bold = true },
    ["@markup.heading.5.markdown"] = { fg = c.pine, bold = true },
    -- The local palette has no leaf; retain its existing foam color for H6.
    ["@markup.heading.6.markdown"] = { fg = c.foam, bold = true },
    ["@markup.heading.1.marker.markdown"] = { link = "@markup.heading.1.markdown" },
    ["@markup.heading.2.marker.markdown"] = { link = "@markup.heading.2.markdown" },
    ["@markup.heading.3.marker.markdown"] = { link = "@markup.heading.3.markdown" },
    ["@markup.heading.4.marker.markdown"] = { link = "@markup.heading.4.markdown" },
    ["@markup.heading.5.marker.markdown"] = { link = "@markup.heading.5.markdown" },
    ["@markup.heading.6.marker.markdown"] = { link = "@markup.heading.6.markdown" },
    ["@diff.plus"] = { fg = c.foam, bg = cs.mix(c.base, c.foam, 20) },
    ["@diff.minus"] = { fg = c.love, bg = cs.mix(c.base, c.love, 20) },
    ["@diff.delta"] = { bg = cs.mix(c.base, c.rose, 20) },
    ["@tag"] = { link = "Tag" },
    ["@tag.attribute"] = { fg = c.iris },
    ["@tag.delimiter"] = { fg = c.subtle },
    ["@conceal"] = { link = "Conceal" },
    ["@conceal.markdown"] = { fg = c.subtle },

    -- Restore native fallback behavior for captures overridden by other local themes.
    ["@annotation"] = {},
    ["@attribute.c_sharp"] = { link = "@attribute" },
    ["@character.printf"] = { link = "@character" },
    ["@character.special.html"] = { link = "@character.special" },
    ["@comment.danger"] = { link = "@comment" },
    ["@comment.documentation"] = { link = "@comment" },
    ["@comment.warning.gitcommit"] = { link = "@comment.warning" },
    ["@conditional"] = {},
    ["@constant.java"] = { link = "@constant" },
    ["@constructor.lua"] = { link = "@constructor" },
    ["@constructor.python"] = { link = "@constructor" },
    ["@constructor.tsx"] = { link = "@constructor" },
    ["@debug"] = {},
    ["@define"] = {},
    ["@error"] = {},
    ["@event"] = {},
    ["@exception"] = {},
    ["@field"] = {},
    ["@function.builtin.bash"] = { link = "@function.builtin" },
    ["@function.call"] = { link = "@function" },
    ["@include"] = {},
    ["@keyword.coroutine"] = { link = "@keyword" },
    ["@keyword.directive.css"] = { link = "@keyword.directive" },
    ["@keyword.function"] = { link = "@keyword" },
    ["@keyword.import.c"] = { link = "@keyword.import" },
    ["@keyword.import.cpp"] = { link = "@keyword.import" },
    ["@keyword.modifier"] = { link = "@keyword" },
    ["@keyword.type"] = { link = "@keyword" },
    ["@label.yaml"] = { link = "@label" },
    ["@macro"] = {},
    ["@markup"] = { link = "Special" },
    ["@markup.changed"] = { link = "@markup" },
    ["@markup.deleted"] = { link = "@markup" },
    ["@markup.emphasis"] = { link = "@markup" },
    ["@markup.heading.1"] = { link = "@markup.heading" },
    ["@markup.heading.1.marker"] = { link = "@markup.heading" },
    ["@markup.heading.2"] = { link = "@markup.heading" },
    ["@markup.heading.2.marker"] = { link = "@markup.heading" },
    ["@markup.heading.3"] = { link = "@markup.heading" },
    ["@markup.heading.3.marker"] = { link = "@markup.heading" },
    ["@markup.heading.4"] = { link = "@markup.heading" },
    ["@markup.heading.4.marker"] = { link = "@markup.heading" },
    ["@markup.heading.5"] = { link = "@markup.heading" },
    ["@markup.heading.5.marker"] = { link = "@markup.heading" },
    ["@markup.heading.6"] = { link = "@markup.heading" },
    ["@markup.heading.6.marker"] = { link = "@markup.heading" },
    ["@markup.inserted"] = { link = "@markup" },
    ["@markup.link"] = { link = "Underlined" },
    ["@markup.link.label"] = { link = "@markup.link" },
    ["@markup.link.label.html"] = { link = "@markup.link" },
    ["@markup.link.label.symbol"] = { link = "@markup.link" },
    ["@markup.list.markdown"] = { link = "@markup.list" },
    ["@markup.raw"] = { link = "@markup" },
    ["@markup.raw.markdown_inline"] = { link = "@markup" },
    ["@method"] = {},
    ["@method.call"] = {},
    ["@modifier"] = {},
    ["@namespace"] = {},
    ["@namespace.builtin"] = {},
    ["@none"] = {},
    ["@number.css"] = { link = "@number" },
    ["@operator.assignment"] = { link = "@operator" },
    ["@parameter"] = {},
    ["@preproc"] = {},
    ["@property.class.css"] = { link = "@property" },
    ["@property.css"] = { link = "@property" },
    ["@property.id.css"] = { link = "@property" },
    ["@property.scss"] = { link = "@property" },
    ["@punctuation"] = { link = "Delimiter" },
    ["@punctuation.special.markdown"] = { link = "@punctuation.special" },
    ["@reference"] = {},
    ["@regexp"] = {},
    ["@repeat"] = {},
    ["@scope"] = {},
    ["@storageclass"] = {},
    ["@string.documentation"] = { link = "@string" },
    ["@string.plain.css"] = { link = "@string" },
    ["@string.regex"] = { link = "@string" },
    ["@string.special.path"] = { link = "@string.special" },
    ["@string.special.url.html"] = { link = "@string.special.url" },
    ["@structure"] = {},
    ["@symbol"] = {},
    ["@tag.builtin"] = { link = "Special" },
    ["@tag.delimiter.tsx"] = { link = "@tag.delimiter" },
    ["@tag.javascript"] = { link = "@tag" },
    ["@tag.tsx"] = { link = "@tag" },
    ["@text"] = {},
    ["@text.danger"] = {},
    ["@text.danger.comment"] = {},
    ["@text.diff.add"] = {},
    ["@text.diff.delete"] = {},
    ["@text.emphasis"] = {},
    ["@text.environment"] = {},
    ["@text.environment.name"] = {},
    ["@text.literal"] = {},
    ["@text.math"] = {},
    ["@text.note"] = {},
    ["@text.note.comment"] = {},
    ["@text.reference"] = {},
    ["@text.strike"] = {},
    ["@text.strong"] = {},
    ["@text.title"] = {},
    ["@text.todo"] = {},
    ["@text.todo.checked"] = {},
    ["@text.todo.unchecked"] = {},
    ["@text.underline"] = {},
    ["@text.uri"] = {},
    ["@text.warning"] = {},
    ["@type.css"] = { link = "@type" },
    ["@type.definition"] = { link = "@type" },
    ["@type.qualifier"] = { link = "@type" },
    ["@type.tag.css"] = { link = "@type" },
    ["@type.tsx"] = { link = "@type" },
    ["@variable.jsx"] = { link = "@variable" },
    ["@variable.parameter.bash"] = { link = "@variable.parameter" },
    ["@variable.parameter.luadoc"] = { link = "@variable.parameter" },
    ["@variable.tsx"] = { link = "@variable" },
  }
end

return M
