/**
 * @typedef {Object} IThemeCatppuccinPalette
 * @property {string}                   base
 * @property {string}                   blue
 * @property {string}                   crust
 * @property {string}                   flamingo
 * @property {string}                   green
 * @property {string}                   lavender
 * @property {string}                   mantle
 * @property {string}                   maroon
 * @property {string}                   mauve
 * @property {string}                   overlay0
 * @property {string}                   overlay1
 * @property {string}                   overlay2
 * @property {string}                   peach
 * @property {string}                   pink
 * @property {string}                   red
 * @property {string}                   rosewater
 * @property {string}                   sapphire
 * @property {string}                   sky
 * @property {string}                   subtext0
 * @property {string}                   subtext1
 * @property {string}                   surface0
 * @property {string}                   surface1
 * @property {string}                   surface2
 * @property {string}                   teal
 * @property {string}                   text
 * @property {string}                   yellow
 */

/**
 * @typedef {Object} IThemeGruvboxPalette
 * @property {string}                   aqua
 * @property {string}                   bg
 * @property {string}                   bg0
 * @property {string}                   bg0_h
 * @property {string}                   bg0_s
 * @property {string}                   bg1
 * @property {string}                   bg2
 * @property {string}                   bg3
 * @property {string}                   bg4
 * @property {string}                   blue
 * @property {string}                   dark_aqua
 * @property {string}                   dark_blue
 * @property {string}                   dark_gray
 * @property {string}                   dark_green
 * @property {string}                   dark_orange
 * @property {string}                   dark_purple
 * @property {string}                   dark_red
 * @property {string}                   dark_yellow
 * @property {string}                   fg
 * @property {string}                   fg0
 * @property {string}                   fg0_h
 * @property {string}                   fg0_s
 * @property {string}                   fg1
 * @property {string}                   fg2
 * @property {string}                   fg3
 * @property {string}                   fg4
 * @property {string}                   gray
 * @property {string}                   green
 * @property {string}                   light_gray
 * @property {string}                   orange
 * @property {string}                   purple
 * @property {string}                   red
 * @property {string}                   yellow
 */

/**
 * @typedef {Object} IThemeNordPalette
 * @property {string}                   nord0
 * @property {string}                   nord1
 * @property {string}                   nord2
 * @property {string}                   nord3
 * @property {string}                   nord4
 * @property {string}                   nord5
 * @property {string}                   nord6
 * @property {string}                   nord7
 * @property {string}                   nord8
 * @property {string}                   nord9
 * @property {string}                   nord10
 * @property {string}                   nord11
 * @property {string}                   nord12
 * @property {string}                   nord13
 * @property {string}                   nord14
 * @property {string}                   nord15
 * @property {string}                   polarNight0
 * @property {string}                   polarNight1
 * @property {string}                   polarNight2
 * @property {string}                   polarNight3
 * @property {string}                   snowStorm0
 * @property {string}                   snowStorm1
 * @property {string}                   snowStorm2
 * @property {string}                   frost0
 * @property {string}                   frost1
 * @property {string}                   frost2
 * @property {string}                   frost3
 * @property {string}                   aurora0
 * @property {string}                   aurora1
 * @property {string}                   aurora2
 * @property {string}                   aurora3
 * @property {string}                   aurora4
 */

/**
 * @typedef {Object} IThemeOnehalfPalette
 * @property {string}                   background
 * @property {string}                   black
 * @property {string}                   blue
 * @property {string}                   comment
 * @property {string}                   cyan
 * @property {string}                   foreground
 * @property {string}                   green
 * @property {string}                   gutter
 * @property {string}                   guide
 * @property {string}                   orange
 * @property {string}                   purple
 * @property {string}                   red
 * @property {string}                   selection
 * @property {string}                   white
 * @property {string}                   yellow
 */

/**
 * @typedef {Object} IThemeRosepinePalette
 * @property {string}                   base
 * @property {string}                   foam
 * @property {string}                   gold
 * @property {string}                   highlightHigh
 * @property {string}                   highlightLow
 * @property {string}                   highlightMed
 * @property {string}                   iris
 * @property {string}                   love
 * @property {string}                   muted
 * @property {string}                   overlay
 * @property {string}                   pine
 * @property {string}                   rose
 * @property {string}                   subtle
 * @property {string}                   surface
 * @property {string}                   text
 */

/**
 * @typedef {Object} IThemeTokyonightPalette
 * @property {string}                   bg
 * @property {string}                   bg_dark
 * @property {string}                   bg_dark1
 * @property {string}                   bg_highlight
 * @property {string}                   bg_visual
 * @property {string}                   fg
 * @property {string}                   fg_dark
 * @property {string}                   fg_gutter
 * @property {string}                   fg_sidebar
 * @property {string}                   comment
 * @property {string}                   dark3
 * @property {string}                   dark5
 * @property {string}                   blue
 * @property {string}                   blue0
 * @property {string}                   blue1
 * @property {string}                   blue2
 * @property {string}                   blue5
 * @property {string}                   blue6
 * @property {string}                   blue7
 * @property {string}                   cyan
 * @property {string}                   green
 * @property {string}                   green1
 * @property {string}                   green2
 * @property {string}                   magenta
 * @property {string}                   magenta2
 * @property {string}                   orange
 * @property {string}                   purple
 * @property {string}                   red
 * @property {string}                   red1
 * @property {string}                   teal
 * @property {string}                   yellow
 * @property {string}                   terminal_black
 * @property {string}                   black
 * @property {string}                   border
 * @property {string}                   border_highlight
 * @property {string}                   git_add
 * @property {string}                   git_change
 * @property {string}                   git_delete
 * @property {string}                   diff_add
 * @property {string}                   diff_change
 * @property {string}                   diff_delete
 * @property {string}                   diff_text
 * @property {string}                   hint
 * @property {string}                   info
 * @property {string}                   todo
 * @property {string}                   warning
 */

/**
 * @typedef {Object} IThemeVscPalette
 * @property {string}                   accentAqua
 * @property {string}                   accentBlue
 * @property {string}                   accentGreen
 * @property {string}                   accentOrange
 * @property {string}                   accentPink
 * @property {string}                   accentPurple
 * @property {string}                   accentRed
 * @property {string}                   accentYellow
 * @property {string}                   actionBar_toggledBackground
 * @property {string}                   activityBarBadge_background
 * @property {string}                   activityBarBadge_foreground
 * @property {string}                   activityBar_activeBorder
 * @property {string}                   activityBar_background
 * @property {string}                   activityBar_border
 * @property {string}                   activityBar_foreground
 * @property {string}                   activityBar_inactiveForeground
 * @property {string}                   badge_background
 * @property {string}                   badge_foreground
 * @property {string}                   base
 * @property {string}                   border
 * @property {string}                   borderStrong
 * @property {string}                   brightAqua
 * @property {string}                   brightBlue
 * @property {string}                   brightGreen
 * @property {string}                   brightOrange
 * @property {string}                   brightPurple
 * @property {string}                   brightRed
 * @property {string}                   brightYellow
 * @property {string}                   button_background
 * @property {string}                   button_border
 * @property {string}                   button_foreground
 * @property {string}                   button_hoverBackground
 * @property {string}                   button_secondaryBackground
 * @property {string}                   button_secondaryForeground
 * @property {string}                   button_secondaryHoverBackground
 * @property {string}                   chat_editedFileForeground
 * @property {string}                   chat_slashCommandBackground
 * @property {string}                   chat_slashCommandForeground
 * @property {string}                   checkbox_background
 * @property {string}                   checkbox_border
 * @property {string}                   debugToolBar_background
 * @property {string}                   descriptionForeground
 * @property {string}                   diffEditor_unchangedRegionBackground
 * @property {string}                   dropdown_background
 * @property {string}                   dropdown_border
 * @property {string}                   dropdown_foreground
 * @property {string}                   dropdown_listBackground
 * @property {string}                   editorBracket_fg0
 * @property {string}                   editorBracket_fg1
 * @property {string}                   editorBracket_fg2
 * @property {string}                   editorBracket_fg3
 * @property {string}                   editorBracket_fg4
 * @property {string}                   editorBracket_fg5
 * @property {string}                   editorBracket_fg6
 * @property {string}                   editorGroupHeader_tabsBackground
 * @property {string}                   editorGroupHeader_tabsBorder
 * @property {string}                   editorGroup_border
 * @property {string}                   editorGutter_addedBackground
 * @property {string}                   editorGutter_deletedBackground
 * @property {string}                   editorGutter_modifiedBackground
 * @property {string}                   editorIndentGuide_activeBackground1
 * @property {string}                   editorIndentGuide_background1
 * @property {string}                   editorLineNumber_activeForeground
 * @property {string}                   editorLineNumber_foreground
 * @property {string}                   editorOverviewRuler_border
 * @property {string}                   editorSuggestWidget_background
 * @property {string}                   editorWidget_background
 * @property {string}                   editor_background
 * @property {string}                   editor_findMatchBackground
 * @property {string}                   editor_foreground
 * @property {string}                   editor_inactiveSelectionBackground
 * @property {string}                   editor_selectionHighlightBackground
 * @property {string}                   errorForeground
 * @property {string}                   focusBorder
 * @property {string}                   foreground
 * @property {string}                   icon_foreground
 * @property {string}                   inputOption_activeBackground
 * @property {string}                   inputOption_activeBorder
 * @property {string}                   inputOption_activeForeground
 * @property {string}                   input_background
 * @property {string}                   input_border
 * @property {string}                   input_foreground
 * @property {string}                   input_placeholderForeground
 * @property {string}                   keybindingLabel_foreground
 * @property {string}                   list_activeSelectionBackground
 * @property {string}                   list_activeSelectionForeground
 * @property {string}                   list_activeSelectionIconForeground
 * @property {string}                   list_dropBackground
 * @property {string}                   list_focusAndSelectionOutline
 * @property {string}                   list_hoverBackground
 * @property {string}                   menu_background
 * @property {string}                   menu_border
 * @property {string}                   menu_foreground
 * @property {string}                   menu_selectionBackground
 * @property {string}                   menu_selectionForeground
 * @property {string}                   menu_separatorBackground
 * @property {string}                   muted
 * @property {string}                   notebook_cellBorderColor
 * @property {string}                   notebook_selectedCellBackground
 * @property {string}                   notificationCenterHeader_background
 * @property {string}                   notificationCenterHeader_foreground
 * @property {string}                   notifications_background
 * @property {string}                   notifications_border
 * @property {string}                   notifications_foreground
 * @property {string}                   overlay
 * @property {string}                   panelInput_border
 * @property {string}                   panelTitle_activeBorder
 * @property {string}                   panelTitle_activeForeground
 * @property {string}                   panelTitle_inactiveForeground
 * @property {string}                   panel_background
 * @property {string}                   panel_border
 * @property {string}                   peekViewEditor_background
 * @property {string}                   peekViewEditor_matchHighlightBackground
 * @property {string}                   peekViewResult_background
 * @property {string}                   peekViewResult_matchHighlightBackground
 * @property {string}                   pickerGroup_border
 * @property {string}                   pickerGroup_foreground
 * @property {string}                   ports_iconRunningProcessForeground
 * @property {string}                   progressBar_background
 * @property {string}                   quickInput_background
 * @property {string}                   quickInput_foreground
 * @property {string}                   searchEditor_textInputBorder
 * @property {string}                   selection
 * @property {string}                   semanticCustomLiteral
 * @property {string}                   semanticNewOperator
 * @property {string}                   semanticNumberLiteral
 * @property {string}                   semanticStringLiteral
 * @property {string}                   settings_dropdownBackground
 * @property {string}                   settings_dropdownBorder
 * @property {string}                   settings_headerForeground
 * @property {string}                   settings_modifiedItemIndicator
 * @property {string}                   settings_numberInputBorder
 * @property {string}                   settings_textInputBorder
 * @property {string}                   sideBarSectionHeader_background
 * @property {string}                   sideBarSectionHeader_border
 * @property {string}                   sideBarSectionHeader_foreground
 * @property {string}                   sideBarTitle_foreground
 * @property {string}                   sideBar_background
 * @property {string}                   sideBar_border
 * @property {string}                   sideBar_foreground
 * @property {string}                   status
 * @property {string}                   statusBarItem_compactHoverBackground
 * @property {string}                   statusBarItem_errorBackground
 * @property {string}                   statusBarItem_focusBorder
 * @property {string}                   statusBarItem_hoverBackground
 * @property {string}                   statusBarItem_hoverForeground
 * @property {string}                   statusBarItem_prominentBackground
 * @property {string}                   statusBarItem_remoteBackground
 * @property {string}                   statusBarItem_remoteForeground
 * @property {string}                   statusBar_background
 * @property {string}                   statusBar_border
 * @property {string}                   statusBar_debuggingBackground
 * @property {string}                   statusBar_debuggingForeground
 * @property {string}                   statusBar_focusBorder
 * @property {string}                   statusBar_foreground
 * @property {string}                   statusBar_noFolderBackground
 * @property {string}                   subtle
 * @property {string}                   success
 * @property {string}                   surface
 * @property {string}                   tab_activeBackground
 * @property {string}                   tab_activeBorder
 * @property {string}                   tab_activeBorderTop
 * @property {string}                   tab_activeForeground
 * @property {string}                   tab_border
 * @property {string}                   tab_hoverBackground
 * @property {string}                   tab_inactiveBackground
 * @property {string}                   tab_inactiveForeground
 * @property {string}                   tab_lastPinnedBorder
 * @property {string}                   tab_selectedBackground
 * @property {string}                   tab_selectedBorderTop
 * @property {string}                   tab_selectedForeground
 * @property {string}                   tab_unfocusedActiveBorder
 * @property {string}                   tab_unfocusedActiveBorderTop
 * @property {string}                   tab_unfocusedHoverBackground
 * @property {string}                   terminalCursor_foreground
 * @property {string}                   terminal_foreground
 * @property {string}                   terminal_inactiveSelectionBackground
 * @property {string}                   terminal_tab_activeBorder
 * @property {string}                   text
 * @property {string}                   textBlockQuote_background
 * @property {string}                   textBlockQuote_border
 * @property {string}                   textCodeBlock_background
 * @property {string}                   textDim
 * @property {string}                   textLink_activeForeground
 * @property {string}                   textLink_foreground
 * @property {string}                   textMuted
 * @property {string}                   textPreformat_background
 * @property {string}                   textPreformat_foreground
 * @property {string}                   textSeparator_foreground
 * @property {string}                   titleBar_activeBackground
 * @property {string}                   titleBar_activeForeground
 * @property {string}                   titleBar_border
 * @property {string}                   titleBar_inactiveBackground
 * @property {string}                   titleBar_inactiveForeground
 * @property {string}                   tokenBracketsOfXmlHtmlTags
 * @property {string}                   tokenColoringOfTheJavaImportAndPackageIdentifiers
 * @property {string}                   tokenComment
 * @property {string}                   tokenConstantCharacter
 * @property {string}                   tokenConstantCharacterCharacterClassRegexp
 * @property {string}                   tokenConstantCharacterEscape
 * @property {string}                   tokenConstantLanguage
 * @property {string}                   tokenConstantNumeric
 * @property {string}                   tokenConstantRegexp
 * @property {string}                   tokenConstantShaGitRebase
 * @property {string}                   tokenConstantsAndEnums
 * @property {string}                   tokenControlFlowSpecialKeywords
 * @property {string}                   tokenCssPropertyValue
 * @property {string}                   tokenCssTagsInSelectorsXmlTags
 * @property {string}                   tokenEntityNameLabel
 * @property {string}                   tokenEntityNameSelector
 * @property {string}                   tokenEntityNameTag
 * @property {string}                   tokenEntityNameTagCss
 * @property {string}                   tokenEntityOtherAttributeName
 * @property {string}                   tokenEntityOtherAttributeNameClassCss
 * @property {string}                   tokenFunctionDeclarations
 * @property {string}                   tokenHeader
 * @property {string}                   tokenInvalid
 * @property {string}                   tokenKeyword
 * @property {string}                   tokenKeywordControl
 * @property {string}                   tokenKeywordOperator
 * @property {string}                   tokenKeywordOperatorNew
 * @property {string}                   tokenKeywordOperatorOrRegexp
 * @property {string}                   tokenKeywordOperatorQuantifierRegexp
 * @property {string}                   tokenKeywordOtherUnit
 * @property {string}                   tokenMarkupBold
 * @property {string}                   tokenMarkupChanged
 * @property {string}                   tokenMarkupDeleted
 * @property {string}                   tokenMarkupHeading
 * @property {string}                   tokenMarkupInlineRaw
 * @property {string}                   tokenMarkupInserted
 * @property {string}                   tokenMetaDiffHeader
 * @property {string}                   tokenMetaEmbedded
 * @property {string}                   tokenMetaPreprocessor
 * @property {string}                   tokenMetaPreprocessorNumeric
 * @property {string}                   tokenMetaPreprocessorString
 * @property {string}                   tokenMetaStructureDictionaryKeyPython
 * @property {string}                   tokenObjectKeysTsGrammarSpecific
 * @property {string}                   tokenPunctuationDefinitionListBeginMarkdown
 * @property {string}                   tokenPunctuationDefinitionQuoteBeginMarkdown
 * @property {string}                   tokenPunctuationSectionEmbeddedBeginPhp
 * @property {string}                   tokenRegularExpressionGroups
 * @property {string}                   tokenResetJavaScriptStringInterpolationExpression
 * @property {string}                   tokenStorage
 * @property {string}                   tokenStorageModifier
 * @property {string}                   tokenStorageType
 * @property {string}                   tokenString
 * @property {string}                   tokenStringCommentBufferedBlockPug
 * @property {string}                   tokenStringInterpolation
 * @property {string}                   tokenStringRegexp
 * @property {string}                   tokenStringTag
 * @property {string}                   tokenStringValue
 * @property {string}                   tokenSupportConstantPropertyValue
 * @property {string}                   tokenSupportFunctionGitRebase
 * @property {string}                   tokenSupportTypePropertyNameJson
 * @property {string}                   tokenSupportTypeVendoredPropertyName
 * @property {string}                   tokenThisSelf
 * @property {string}                   tokenTypesDeclarationAndReferences
 * @property {string}                   tokenTypesDeclarationAndReferencesTsGrammarSpecific
 * @property {string}                   tokenVariableAndParameterName
 * @property {string}                   warning
 * @property {string}                   welcomePage_progress_foreground
 * @property {string}                   welcomePage_tileBackground
 * @property {string}                   widget_border
 */

/**
 * @typedef {Object} IThemeUnifiedPalette
 * @property {string}                   bg0
 * @property {string}                   bg1
 * @property {string}                   bg2
 * @property {string}                   bg3
 * @property {string}                   bg4
 *
 * @property {string}                   fg0
 * @property {string}                   fg1
 * @property {string}                   fg2
 * @property {string}                   fg3
 * @property {string}                   fg4
 *
 * @property {string}                   red
 * @property {string}                   green
 * @property {string}                   yellow
 * @property {string}                   blue
 * @property {string}                   purple
 * @property {string}                   aqua
 * @property {string}                   orange
 *
 * @property {string}                   brightRed
 * @property {string}                   brightGreen
 * @property {string}                   brightYellow
 * @property {string}                   brightBlue
 * @property {string}                   brightPurple
 * @property {string}                   brightAqua
 * @property {string}                   brightOrange
 *
 * @property {string}                   black
 * @property {string}                   white
 * @property {string}                   grey
 * @property {string}                   pink
 *
 * @property {string}                   diffDel
 * @property {string}                   diffDelInline
 * @property {string}                   diffAdd
 * @property {string}                   diffAddInline
 */

/**
 * @typedef {Object} IThemePalette
 * @property {IThemeCatppuccinPalette|undefined}  catppuccin
 * @property {IThemeGruvboxPalette|undefined}     gruvbox
 * @property {IThemeNordPalette|undefined}        nord
 * @property {IThemeOnehalfPalette|undefined}     onehalf
 * @property {IThemeRosepinePalette|undefined}    rosepine
 * @property {IThemeTokyonightPalette|undefined}  tokyonight
 * @property {IThemeVscPalette|undefined}         vsc
 * @property {IThemeUnifiedPalette}               unified
 */

/**
 * @typedef {Object} IThemeScheme
 * @property {string}                   theme
 * @property {string}                   variant
 * @property {string}                   opposite
 * @property {boolean}                  darken
 * @property {IThemePalette}            palette
 */

/**
 * @typedef {Object} IAppConfig
 * @property {string}                       name
 * @property {string}                       home
 * @property {string|null}                  themes
 * @property {string}                       extname
 * @property {string|null}                  local
 * @property {(app: IAppConfig) => boolean} active
 * @property {(app: IAppConfig, template: string, scheme: IThemeScheme) => Promise<string>} render
 * @property {?((app: IAppConfig, scheme: IThemeScheme) => Promise<void>)} after_apply
 * @property {?((app: IAppConfig) => Promise<void>)} after_gen
 */

export {}
