# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# catppuccin-frappe

[delta]
hunk-header-style             = raw
hunk-header-decoration-style  = ul
hyperlinks                    = true
hyperlinks-file-link-format   = file://{path}:{line}
detect-dark-light             = auto
line-numbers                  = true
navigate                      = true    # use n and N to move between diff sections
paging                        = never
side-by-side                  = true

dark                          = true
syntax-theme                  = catppuccin-frappe
plus-style                    = syntax "#3A4C3A"
plus-emph-style               = syntax "#2A3A2A" bold
plus-non-emph-style           = syntax "#3A4C3A" bold
minus-style                   = syntax "#4C3A3A"
minus-emph-style              = syntax "#3A2A2A" bold
minus-non-emph-style          = syntax "#4C3A3A" bold
line-numbers-left-style       = "#B5BFE2"
line-numbers-right-style      = "#B5BFE2"
line-numbers-minus-style      = "#C6D0F5" "#4C3A3A" bold
line-numbers-plus-style       = "#C6D0F5" "#3A4C3A" bold
true-color                    = always

