selection_foreground    #5C5F77
selection_background    #FE640B

background              #EFF1F5
foreground              #5C5F77

# normal
color0                  #EFF1F5
color1                  #D20F39
color2                  #40A02B
color3                  #DF8E1D
color4                  #89B4FA
color5                  #8839EF
color6                  #179299
color7                  #8C8FA1

# bright
color8                  #7F849C
color9                  #D20F39
color10                 #40A02B
color11                 #DF8E1D
color12                 #89B4FA
color13                 #8839EF
color14                 #179299
color15                 #5C5F77

cursor                  #7C7F93
cursor_text_color       #ACB0BE
url_color               #89B4FA
