selection_foreground    #BAC2DE
selection_background    #FAB387

background              #1E1E2E
foreground              #BAC2DE

# normal
color0                  #1E1E2E
color1                  #F38BA8
color2                  #A6E3A1
color3                  #F9E2AF
color4                  #89B4FA
color5                  #CBA6F7
color6                  #94E2D5
color7                  #7F849C

# bright
color8                  #7F849C
color9                  #F38BA8
color10                 #A6E3A1
color11                 #F9E2AF
color12                 #89B4FA
color13                 #CBA6F7
color14                 #94E2D5
color15                 #BAC2DE

cursor                  #9399B2
cursor_text_color       #585B70
url_color               #89B4FA
