# catppuccin-mocha

[delta "customized-theme"]

dark              = truelight             = true
plus-style        = 'syntax #293232'
plus-emph-style   = 'syntax #476E6E bold'
minus-style       = 'syntax #362424'
minus-emph-style  = 'syntax #833535 bold'
true-color        = always

