# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# catppuccin-macchiato

[delta]
hunk-header-style             = raw
hunk-header-decoration-style  = ul
hyperlinks                    = true
hyperlinks-file-link-format   = file://{path}:{line}
detect-dark-light             = auto
line-numbers                  = true
navigate                      = true    # use n and N to move between diff sections
paging                        = never
side-by-side                  = true

dark                          = true
true-color                    = always
syntax-theme                  = catppuccin-macchiato
plus-emph-style               = syntax "#4A6E4A" bold
plus-non-emph-style           = syntax "#2A3A2A" bold
plus-style                    = syntax "#2A3A2A"
minus-emph-style              = syntax "#8B3A3A" bold
minus-non-emph-style          = syntax "#3A273A" bold
minus-style                   = syntax "#3A273A"
line-numbers-left-style       = "#CAD3F5"
line-numbers-right-style      = "#CAD3F5"
line-numbers-zero-style       = "#CAD3F5"
line-numbers-minus-style      = "#CAD3F5" "#3A273A" bold
line-numbers-plus-style       = "#CAD3F5" "#2A3A2A" bold
whitespace-error-style        = "#CAD3F5"

