##  catppuccin-mocha

set -g @GHC_SL_BG                       "default"

## Message
set -g @GHC_SL_BG_MESSAGE               "#F9E2AF"
set -g @GHC_SL_FG_MESSAGE               "#1E1E2E"

## Pane

set -g @GHC_PSL_FG_BORDER               "#585B70"
set -g @GHC_PSL_FG_BORDER_CUR           "#F5C2E7"

set -g @GHC_PSL_BG_SYM                  "#1E1E2E"
set -g @GHC_PSL_FG_SYM                  "#9399B2"
set -g @GHC_PSL_BG_TXT                  "#1E1E2E"
set -g @GHC_PSL_FG_TXT                  "#9399B2"

set -g @GHC_PSL_BG_SYM_ACTIVE           "#1E1E2E"
set -g @GHC_PSL_FG_SYM_ACTIVE           "#F5C2E7"
set -g @GHC_PSL_BG_TXT_ACTIVE           "#1E1E2E"
set -g @GHC_PSL_FG_TXT_ACTIVE           "#A6ADC8"

## Statusbar

set -g @GHC_SL_FG_BORDER                "#585B70"
set -g @GHC_SL_FG_BORDER_CUR            "#F5C2E7"

set -g @GHC_SL_BG_SYM                   "#1E1E2E"
set -g @GHC_SL_FG_SYM                   "#F5C2E7"
set -g @GHC_SL_BG_TXT                   "#1E1E2E"
set -g @GHC_SL_FG_TXT                   "#A6ADC8"

set -g @GHC_SL_BG_WIN_NAME              "#313244"
set -g @GHC_SL_FG_WIN_NAME              "#A6ADC8"
set -g @GHC_SL_BG_WIN_NUM               "#585B70"
set -g @GHC_SL_FG_WIN_NUM               "#A6ADC8"

set -g @GHC_SL_BG_WIN_NAME_ACTIVE       "#F5C2E7"
set -g @GHC_SL_FG_WIN_NAME_ACTIVE       "#1E1E2E"
set -g @GHC_SL_BG_WIN_NUM_ACTIVE        "#F5C2E7"
set -g @GHC_SL_FG_WIN_NUM_ACTIVE        "#1E1E2E"

