# catppuccin-macchiato

# Primary colors
background              #24273A
foreground              #B8C0E0

# Border colors
active_border_color     #C6A0F6
inactive_border_color   #6E738D

# Cursor colors
cursor                  #F5BDE6
cursor_text_color       #1E2030

# Selection colors
selection_background    #EED49F
selection_foreground    #1E2030

# Tab bar colors
active_tab_background   #24273A
active_tab_foreground   #C6A0F6
inactive_tab_background #A6DA95
inactive_tab_foreground #8AADF4
tab_bar_background      #A6DA95

# Url colors
url_color               #8AADF4

# Normal colors
color0                  #24273A
color1                  #ED8796
color2                  #A6DA95
color3                  #EED49F
color4                  #8AADF4
color5                  #C6A0F6
color6                  #8BD5CA
color7                  #8087A2

# Bright colors
color8                  #6E738D
color9                  #ED8796
color10                 #A6DA95
color11                 #EED49F
color12                 #8AADF4
color13                 #C6A0F6
color14                 #8BD5CA
color15                 #B8C0E0
