# catppuccin-latte

set -g @GHC_SL_BG                       "default"
set -g @GHC_PSL_BG                      "default"

## Cmdline
set -g @GHC_SL_BG_CMDLINE               "#179299"
set -g @GHC_SL_FG_CMDLINE               "#EFF1F5"

## Message
set -g @GHC_SL_BG_MESSAGE               "#DF8E1D"
set -g @GHC_SL_FG_MESSAGE               "#EFF1F5"

## Pane
set -g @GHC_PSL_FG_BORDER               "#ACB0BE"
set -g @GHC_PSL_FG_BORDER_CUR           "#EA76CB"

set -g @GHC_PSL_BG_SYM                  "default"
set -g @GHC_PSL_FG_SYM                  "#8C8FA1"
set -g @GHC_PSL_BG_TXT                  "default"
set -g @GHC_PSL_FG_TXT                  "#8C8FA1"

set -g @GHC_PSL_BG_SYM_ACTIVE           "default"
set -g @GHC_PSL_FG_SYM_ACTIVE           "#EA76CB"
set -g @GHC_PSL_BG_TXT_ACTIVE           "default"
set -g @GHC_PSL_FG_TXT_ACTIVE           "#5C5F77"

## Statusbar

set -g @GHC_SL_FG_BORDER                "#ACB0BE"
set -g @GHC_SL_FG_BORDER_CUR            "#EA76CB"

set -g @GHC_SL_BG_SYM                   "default"
set -g @GHC_SL_FG_SYM                   "#EA76CB"
set -g @GHC_SL_BG_TXT                   "default"
set -g @GHC_SL_FG_TXT                   "#7C7F93"

set -g @GHC_SL_BG_WIN_NAME              "#CCD0DA"
set -g @GHC_SL_FG_WIN_NAME              "#7C7F93"
set -g @GHC_SL_BG_WIN_NUM               "#ACB0BE"
set -g @GHC_SL_FG_WIN_NUM               "#7C7F93"

set -g @GHC_SL_BG_WIN_NAME_ACTIVE       "#EA76CB"
set -g @GHC_SL_FG_WIN_NAME_ACTIVE       "#EFF1F5"
set -g @GHC_SL_BG_WIN_NUM_ACTIVE        "#EA76CB"
set -g @GHC_SL_FG_WIN_NUM_ACTIVE        "#EFF1F5"

