# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# catppuccin-latte

[delta "catppuccin-latte"]
light                         = true
syntax-theme                  = catppuccin-latte

inline-hint-style             = "#2451B5"

####################################################################################################

file-style                    = "#303446" bold

hunk-header-line-number-style = "#4C4F69"

line-numbers-minus-style      = "#AD1635" normal bold
line-numbers-plus-style       = "#25651C" normal bold

minus-style                   = syntax "#ECDAE2"
plus-style                    = syntax "#DEE9E1"
minus-non-emph-style          = syntax "#ECDAE2"
plus-non-emph-style           = syntax "#DEE9E1"
minus-emph-style              = "#303446" "#E9BFCC" bold
plus-emph-style               = "#303446" "#C9DFC9" bold

plus-empty-line-marker-style  = "#DEE9E1" "#DEE9E1"
minus-empty-line-marker-style = "#ECDAE2" "#ECDAE2"

####################################################################################################

commit-style                  = "#7B4D0D" bold

blame-palette                 = "#EFF1F5" "#E6E9EF" "#DCE0E8"
blame-separator-style         = "#4C4F69" dim
