# Basic
set -g @GHC_TMUX_THEME                  "catppuccin-latte"
set -g @GHC_SL_COLOR_BG                 "default"

## MESSAGE
set -g @GHC_SL_COLOR_BG_MESSAGE         "#DF8E1D"
set -g @GHC_SL_COLOR_FG_MESSAGE         "#DCE0E8"

## BORDER
set -g @GHC_SL_COLOR_BORDER             "#ACB0BE"
set -g @GHC_SL_COLOR_BORDER_CUR         "#FE640B"

# Component

## APP
set -g @GHC_SL_COLOR_BG_APP_SYM         "#8839EF"
set -g @GHC_SL_COLOR_FG_APP_SYM         "#DCE0E8"
set -g @GHC_SL_COLOR_BG_APP_TEXT        "#DCE0E8"
set -g @GHC_SL_COLOR_FG_APP_TEXT        "#6C6F85"

## PID
set -g @GHC_SL_COLOR_BG_PID_SYM         "#1E66F5"
set -g @GHC_SL_COLOR_FG_PID_SYM         "#DCE0E8"
set -g @GHC_SL_COLOR_BG_PID_TEXT        "#DCE0E8"
set -g @GHC_SL_COLOR_FG_PID_TEXT        "#6C6F85"

## TIME
set -g @GHC_SL_COLOR_BG_TIME_SYM        "#1E66F5"
set -g @GHC_SL_COLOR_FG_TIME_SYM        "#DCE0E8"
set -g @GHC_SL_COLOR_BG_TIME_TEXT       "#DCE0E8"
set -g @GHC_SL_COLOR_FG_TIME_TEXT       "#6C6F85"

## DATE
set -g @GHC_SL_COLOR_BG_DATE_SYM        "#1E66F5"
set -g @GHC_SL_COLOR_FG_DATE_SYM        "#DCE0E8"
set -g @GHC_SL_COLOR_BG_DATE_TEXT       "#DCE0E8"
set -g @GHC_SL_COLOR_FG_DATE_TEXT       "#6C6F85"

## SESSION
set -g @GHC_SL_COLOR_BG_SESSION         "#DCE0E8"
set -g @GHC_SL_COLOR_FG_SESSION         "#EA76CB"

## USER
set -g @GHC_SL_COLOR_BG_USER            "#1E66F5"
set -g @GHC_SL_COLOR_FG_USER            "#DCE0E8"

## WINDOW
set -g @GHC_SL_COLOR_BG_WIN_NAME        "#CCD0DA"
set -g @GHC_SL_COLOR_FG_WIN_NAME        "#7C7F93"
set -g @GHC_SL_COLOR_BG_WIN_NUM         "#ACB0BE"
set -g @GHC_SL_COLOR_FG_WIN_NUM         "#7C7F93"

## WINDOW_CURRENT
set -g @GHC_SL_COLOR_BG_WIN_CUR_NAME    "#DCE0E8"
set -g @GHC_SL_COLOR_FG_WIN_CUR_NAME    "#5C5F77"
set -g @GHC_SL_COLOR_BG_WIN_CUR_NUM     "#8839EF"
set -g @GHC_SL_COLOR_FG_WIN_CUR_NUM     "#DCE0E8"

