# catppuccin-macchiato

set -g @GHC_SL_BG                       "default"
set -g @GHC_PSL_BG                      "default"

## Message
set -g @GHC_SL_BG_MESSAGE               "#EED49F"
set -g @GHC_SL_FG_MESSAGE               "#24273A"

## Pane
set -g @GHC_PSL_FG_BORDER               "#5B6078"
set -g @GHC_PSL_FG_BORDER_CUR           "#F5BDE6"

set -g @GHC_PSL_BG_SYM                  "default"
set -g @GHC_PSL_FG_SYM                  "#8087A2"
set -g @GHC_PSL_BG_TXT                  "default"
set -g @GHC_PSL_FG_TXT                  "#8087A2"

set -g @GHC_PSL_BG_SYM_ACTIVE           "default"
set -g @GHC_PSL_FG_SYM_ACTIVE           "#F5BDE6"
set -g @GHC_PSL_BG_TXT_ACTIVE           "default"
set -g @GHC_PSL_FG_TXT_ACTIVE           "#B8C0E0"

## Statusbar

set -g @GHC_SL_FG_BORDER                "#5B6078"
set -g @GHC_SL_FG_BORDER_CUR            "#F5BDE6"

set -g @GHC_SL_BG_SYM                   "default"
set -g @GHC_SL_FG_SYM                   "#F5BDE6"
set -g @GHC_SL_BG_TXT                   "default"
set -g @GHC_SL_FG_TXT                   "#939AB7"

set -g @GHC_SL_BG_WIN_NAME              "#363A4F"
set -g @GHC_SL_FG_WIN_NAME              "#939AB7"
set -g @GHC_SL_BG_WIN_NUM               "#5B6078"
set -g @GHC_SL_FG_WIN_NUM               "#939AB7"

set -g @GHC_SL_BG_WIN_NAME_ACTIVE       "#F5BDE6"
set -g @GHC_SL_FG_WIN_NAME_ACTIVE       "#24273A"
set -g @GHC_SL_BG_WIN_NUM_ACTIVE        "#F5BDE6"
set -g @GHC_SL_FG_WIN_NUM_ACTIVE        "#24273A"

