# catppuccin-frappe

# Primary colors
background              #303446
foreground              #B5BFE2

# Border colors
active_border_color     #CA9EE6
inactive_border_color   #737994

# Cursor colors
cursor                  #F4B8E4
cursor_text_color       #292C3C

# Selection colors
selection_background    #E5C890
selection_foreground    #292C3C

# Tab bar colors
active_tab_background   #303446
active_tab_foreground   #CA9EE6
inactive_tab_background #A6D189
inactive_tab_foreground #8CAAEE
tab_bar_background      #A6D189

# Url colors
url_color               #8CAAEE

# Normal colors
color0                  #303446
color1                  #E78284
color2                  #A6D189
color3                  #E5C890
color4                  #8CAAEE
color5                  #CA9EE6
color6                  #81C8BE
color7                  #838BA7

# Bright colors
color8                  #737994
color9                  #E78284
color10                 #A6D189
color11                 #E5C890
color12                 #8CAAEE
color13                 #CA9EE6
color14                 #81C8BE
color15                 #B5BFE2
