# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# catppuccin-macchiato

[delta]
hunk-header-style             = raw
hunk-header-decoration-style  = ul
hyperlinks                    = true
hyperlinks-file-link-format   = file://{path}:{line}
detect-dark-light             = auto
line-numbers                  = true
navigate                      = true    # use n and N to move between diff sections
paging                        = never
side-by-side                  = true


dark                          = true
plus-style                    = syntax "#2A3A2A"
plus-emph-style               = syntax "#4A6E4A" bold
plus-non-emph-style           = syntax auto
minus-style                   = syntax "#3A273A"
minus-emph-style              = syntax "#8B3A3A" bold
minus-non-emph-style          = syntax auto
true-color                    = always

