# catppuccin-mocha

# Default colors
[colors.primary]
background = "#1E1E2E"
foreground = "#CDD6F4"

# Normal colors
[colors.normal]
black   = "#1E1E2E"
red     = "#F38BA8"
green   = "#A6E3A1"
yellow  = "#F9E2AF"
blue    = "#89B4FA"
magenta = "#CBA6F7"
cyan    = "#94E2D5"
white   = "#9399B2"

# Bright colors
[colors.bright]
black   = "#7F849C"
red     = "#F38BA8"
green   = "#A6E3A1"
yellow  = "#F9E2AF"
blue    = "#89B4FA"
magenta = "#CBA6F7"
cyan    = "#94E2D5"
white   = "#CDD6F4"

# Dim colors
[colors.dim]
black   = "#1E1E2E"
red     = "#F38BA8"
green   = "#A6E3A1"
yellow  = "#F9E2AF"
blue    = "#89B4FA"
magenta = "#CBA6F7"
cyan    = "#94E2D5"
white   = "#9399B2"
