# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# catppuccin-mocha

[delta]
hunk-header-style             = raw
hunk-header-decoration-style  = ul
hyperlinks                    = true
hyperlinks-file-link-format   = file://{path}:{line}
detect-dark-light             = auto
line-numbers                  = true
navigate                      = true    # use n and N to move between diff sections
paging                        = never
side-by-side                  = true

dark                          = true
true-color                    = always
syntax-theme                  = catppuccin-mocha
plus-emph-style               = syntax "#476E6E" bold
plus-non-emph-style           = syntax "#293232" bold
plus-style                    = syntax "#293232"
minus-emph-style              = syntax "#833535" bold
minus-non-emph-style          = syntax "#362424" bold
minus-style                   = syntax "#362424"
line-numbers-left-style       = "#B4BEFE"
line-numbers-right-style      = "#B4BEFE"
line-numbers-zero-style       = "#B4BEFE"
line-numbers-minus-style      = "#B4BEFE" "#362424" bold
line-numbers-plus-style       = "#B4BEFE" "#293232" bold
whitespace-error-style        = "#B4BEFE"

