# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# catppuccin-latte

[delta]
hunk-header-style             = raw
hunk-header-decoration-style  = ul
hyperlinks                    = true
hyperlinks-file-link-format   = file://{path}:{line}
detect-dark-light             = auto
line-numbers                  = true
navigate                      = true    # use n and N to move between diff sections
paging                        = never
side-by-side                  = true

light                         = true
true-color                    = always
syntax-theme                  = catppuccin-latte
plus-emph-style               = syntax "#C3D9C3" bold
plus-non-emph-style           = syntax "#D2E1D5" bold
plus-style                    = syntax "#D2E1D5"
minus-emph-style              = syntax "#E5BAC5" bold
minus-non-emph-style          = syntax "#E8CDD6" bold
minus-style                   = syntax "#E8CDD6"
line-numbers-left-style       = "#4C4F69"
line-numbers-right-style      = "#4C4F69"
line-numbers-zero-style       = "#4C4F69"
line-numbers-minus-style      = "#4C4F69" "#E8CDD6" bold
line-numbers-plus-style       = "#4C4F69" "#D2E1D5" bold
whitespace-error-style        = "#4C4F69"

