# catppuccin-mocha

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

[colors.cursor]
cursor            = "#F5C2E7"
text              = "#11111B"

[colors.vi_mode_cursor]
cursor            = "#F5C2E7"
text              = "#11111B"

[colors.search.matches]
background        = "#F9E2AF"
foreground        = "#11111B"

[colors.search.focused_match]
background        = "#F9E2AF"
foreground        = "#11111B"

[colors.selection]
background        = "#FAB387"
text              = "#11111B"

[colors.footer_bar]
background        = "#313244"
foreground        = "#CDD6F4"

[colors.primary]
background        = "#1E1E2E"
foreground        = "#CDD6F4"
dim_foreground    = "#CDD6F4"
bright_foreground = "#CDD6F4"

[colors.normal]
black             = "#1E1E2E"
blue              = "#89B4FA"
cyan              = "#94E2D5"
green             = "#A6E3A1"
magenta           = "#CBA6F7"
red               = "#F38BA8"
yellow            = "#F9E2AF"
white             = "#9399B2"

[colors.bright]
black             = "#7F849C"
blue              = "#89B4FA"
cyan              = "#94E2D5"
green             = "#A6E3A1"
magenta           = "#CBA6F7"
red               = "#F38BA8"
yellow            = "#F9E2AF"
white             = "#CDD6F4"

[colors.dim]
black             = "#1E1E2E"
blue              = "#89B4FA"
cyan              = "#94E2D5"
green             = "#A6E3A1"
magenta           = "#CBA6F7"
red               = "#F38BA8"
yellow            = "#F9E2AF"
white             = "#9399B2"

