##  catppuccin-mocha

# Basic
set -g @GHC_SL_COLOR_BG                 "default"

## MESSAGE
set -g @GHC_SL_COLOR_BG_MESSAGE         "#F9E2AF"
set -g @GHC_SL_COLOR_FG_MESSAGE         "#1E1E2E"

## BORDER
set -g @GHC_SL_COLOR_BORDER             "#585B70"
set -g @GHC_SL_COLOR_BORDER_CUR         "#CBA6F7"

# Component

## APP
set -g @GHC_SL_COLOR_BG_APP_SYM         "#89B4FA"
set -g @GHC_SL_COLOR_FG_APP_SYM         "#1E1E2E"
set -g @GHC_SL_COLOR_BG_APP_TEXT        "#1E1E2E"
set -g @GHC_SL_COLOR_FG_APP_TEXT        "#A6ADC8"

## CPU
set -g @GHC_SL_COLOR_BG_CPU_SYM         "#89B4FA"
set -g @GHC_SL_COLOR_FG_CPU_SYM         "#1E1E2E"
set -g @GHC_SL_COLOR_BG_CPU_TEXT        "#1E1E2E"
set -g @GHC_SL_COLOR_FG_CPU_TEXT        "#A6ADC8"

## HOST
set -g @GHC_SL_COLOR_BG_HOST_SYM        "#F38BA8"
set -g @GHC_SL_COLOR_BG_HOST_TEXT       "#1E1E2E"
set -g @GHC_SL_COLOR_FG_HOST_SYM        "#1E1E2E"
set -g @GHC_SL_COLOR_FG_HOST_TEXT       "#F38BA8"

## NETWORK
set -g @GHC_SL_COLOR_BG_NET_SYM         "#89B4FA"
set -g @GHC_SL_COLOR_FG_NET_SYM         "#1E1E2E"
set -g @GHC_SL_COLOR_BG_NET_TEXT        "#1E1E2E"
set -g @GHC_SL_COLOR_FG_NET_TEXT        "#A6ADC8"

## PID
set -g @GHC_SL_COLOR_BG_PID_SYM         "#89B4FA"
set -g @GHC_SL_COLOR_FG_PID_SYM         "#1E1E2E"
set -g @GHC_SL_COLOR_BG_PID_TEXT        "#1E1E2E"
set -g @GHC_SL_COLOR_FG_PID_TEXT        "#A6ADC8"

## TIME
set -g @GHC_SL_COLOR_BG_TIME_SYM        "#89B4FA"
set -g @GHC_SL_COLOR_FG_TIME_SYM        "#1E1E2E"
set -g @GHC_SL_COLOR_BG_TIME_TEXT       "#1E1E2E"
set -g @GHC_SL_COLOR_FG_TIME_TEXT       "#A6ADC8"

## DATE
set -g @GHC_SL_COLOR_BG_DATE_SYM        "#89B4FA"
set -g @GHC_SL_COLOR_FG_DATE_SYM        "#1E1E2E"
set -g @GHC_SL_COLOR_BG_DATE_TEXT       "#1E1E2E"
set -g @GHC_SL_COLOR_FG_DATE_TEXT       "#A6ADC8"

## SESSION
set -g @GHC_SL_COLOR_BG_SESSION_SYM     "#A6E3A1"
set -g @GHC_SL_COLOR_FG_SESSION_SYM     "#1E1E2E"
set -g @GHC_SL_COLOR_BG_SESSION_TEXT    "#1E1E2E"
set -g @GHC_SL_COLOR_FG_SESSION_TEXT    "#A6E3A1"

## USER
set -g @GHC_SL_COLOR_BG_USER_SYM        "#F5C2E7"
set -g @GHC_SL_COLOR_BG_USER_TEXT       "#1E1E2E"
set -g @GHC_SL_COLOR_FG_USER_SYM        "#1E1E2E"
set -g @GHC_SL_COLOR_FG_USER_TEXT       "#F5C2E7"

## WINDOW
set -g @GHC_SL_COLOR_BG_WIN_NAME        "#313244"
set -g @GHC_SL_COLOR_FG_WIN_NAME        "#A6ADC8"
set -g @GHC_SL_COLOR_BG_WIN_NUM         "#585B70"
set -g @GHC_SL_COLOR_FG_WIN_NUM         "#A6ADC8"

## WINDOW_CURRENT
set -g @GHC_SL_COLOR_BG_WIN_CUR_NAME    "#94E2D5"
set -g @GHC_SL_COLOR_FG_WIN_CUR_NAME    "#1E1E2E"

