# gruvbox-dark

set -g @GHC_SL_BG                       "default"
set -g @GHC_PSL_BG                      "default"

## Message
set -g @GHC_SL_BG_MESSAGE               "#D79921"
set -g @GHC_SL_FG_MESSAGE               "#282828"

## Pane
set -g @GHC_PSL_FG_BORDER               "#7C6F64"
set -g @GHC_PSL_FG_BORDER_CUR           "#D3869B"

set -g @GHC_PSL_BG_SYM                  "default"
set -g @GHC_PSL_FG_SYM                  "#A89984"
set -g @GHC_PSL_BG_TXT                  "default"
set -g @GHC_PSL_FG_TXT                  "#A89984"

set -g @GHC_PSL_BG_SYM_ACTIVE           "default"
set -g @GHC_PSL_FG_SYM_ACTIVE           "#D3869B"
set -g @GHC_PSL_BG_TXT_ACTIVE           "default"
set -g @GHC_PSL_FG_TXT_ACTIVE           "#BDAE93"

## Statusbar

set -g @GHC_SL_FG_BORDER                "#7C6F64"
set -g @GHC_SL_FG_BORDER_CUR            "#D3869B"

set -g @GHC_SL_BG_SYM                   "default"
set -g @GHC_SL_FG_SYM                   "#D3869B"
set -g @GHC_SL_BG_TXT                   "default"
set -g @GHC_SL_FG_TXT                   "#BDAE93"

set -g @GHC_SL_BG_WIN_NAME              "#504945"
set -g @GHC_SL_FG_WIN_NAME              "#BDAE93"
set -g @GHC_SL_BG_WIN_NUM               "#7C6F64"
set -g @GHC_SL_FG_WIN_NUM               "#BDAE93"

set -g @GHC_SL_BG_WIN_NAME_ACTIVE       "#D3869B"
set -g @GHC_SL_FG_WIN_NAME_ACTIVE       "#282828"
set -g @GHC_SL_BG_WIN_NUM_ACTIVE        "#D3869B"
set -g @GHC_SL_FG_WIN_NUM_ACTIVE        "#282828"

