# gruvbox-light

# Primary colors
background              #FBF1C7
foreground              #3C3836

# Border colors
active_border_color     #8F3F71
inactive_border_color   #928374

# Cursor colors
cursor                  #D3869B
cursor_text_color       #EBDBB2

# Selection colors
selection_background    #D79921
selection_foreground    #EBDBB2

# Tab bar colors
active_tab_background   #FBF1C7
active_tab_foreground   #B16286
inactive_tab_background #98971A
inactive_tab_foreground #458588
tab_bar_background      #98971A

# Url colors
url_color               #458588

# Normal colors
color0                  #FBF1C7
color1                  #9D0006
color2                  #79740E
color3                  #B57614
color4                  #076678
color5                  #8F3F71
color6                  #427B58
color7                  #7C6F64

# Bright colors
color8                  #928374
color9                  #CC241D
color10                 #98971A
color11                 #D79921
color12                 #458588
color13                 #B16286
color14                 #689D6A
color15                 #3C3836
