# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# gruvbox-dark

[delta]
hunk-header-style             = raw
hunk-header-decoration-style  = ul
hyperlinks                    = true
hyperlinks-file-link-format   = file://{path}:{line}
detect-dark-light             = auto
line-numbers                  = true
navigate                      = true    # use n and N to move between diff sections
paging                        = never
side-by-side                  = true

dark                          = true
true-color                    = always
syntax-theme                  = gruvbox-dark
plus-emph-style               = syntax "#3F4531" bold
plus-non-emph-style           = syntax "#565B2F" bold
plus-style                    = syntax "#565B2F"
minus-emph-style              = syntax "#722824" bold
minus-non-emph-style          = syntax "#532020" bold
minus-style                   = syntax "#532020"
line-numbers-left-style       = "#F2E5BC"
line-numbers-right-style      = "#F2E5BC"
line-numbers-zero-style       = "#F2E5BC"
line-numbers-minus-style      = "#F2E5BC" "#532020" bold
line-numbers-plus-style       = "#F2E5BC" "#565B2F" bold
whitespace-error-style        = "#F2E5BC"

