# Basic
set -g @GHC_TMUX_THEME                  "gruvbox_light"
set -g @GHC_SL_COLOR_BG                 "default"

## MESSAGE
set -g @GHC_SL_COLOR_BG_MESSAGE         "#B57614"
set -g @GHC_SL_COLOR_FG_MESSAGE         "#EBDBB2"

## BORDER
set -g @GHC_SL_COLOR_BORDER             "#A89984"
set -g @GHC_SL_COLOR_BORDER_CUR         "#AF3A03"

# Component

## APP
set -g @GHC_SL_COLOR_BG_APP_SYM         "#076678"
set -g @GHC_SL_COLOR_FG_APP_SYM         "#EBDBB2"
set -g @GHC_SL_COLOR_BG_APP_TEXT        "#EBDBB2"
set -g @GHC_SL_COLOR_FG_APP_TEXT        "#504945"

## PID
set -g @GHC_SL_COLOR_BG_PID_SYM         "#076678"
set -g @GHC_SL_COLOR_FG_PID_SYM         "#EBDBB2"
set -g @GHC_SL_COLOR_BG_PID_TEXT        "#EBDBB2"
set -g @GHC_SL_COLOR_FG_PID_TEXT        "#504945"

## TIME
set -g @GHC_SL_COLOR_BG_TIME_SYM        "#076678"
set -g @GHC_SL_COLOR_FG_TIME_SYM        "#EBDBB2"
set -g @GHC_SL_COLOR_BG_TIME_TEXT       "#EBDBB2"
set -g @GHC_SL_COLOR_FG_TIME_TEXT       "#504945"

## DATE
set -g @GHC_SL_COLOR_BG_DATE_SYM        "#076678"
set -g @GHC_SL_COLOR_FG_DATE_SYM        "#EBDBB2"
set -g @GHC_SL_COLOR_BG_DATE_TEXT       "#EBDBB2"
set -g @GHC_SL_COLOR_FG_DATE_TEXT       "#504945"

## SESSION
set -g @GHC_SL_COLOR_BG_SESSION_SYM     "#D3869B"
set -g @GHC_SL_COLOR_FG_SESSION_SYM     "#EBDBB2"
set -g @GHC_SL_COLOR_BG_SESSION_TEXT    "#EBDBB2"
set -g @GHC_SL_COLOR_FG_SESSION_TEXT    "#D3869B"

## USER
set -g @GHC_SL_COLOR_BG_USER_SYM        "#076678"
set -g @GHC_SL_COLOR_BG_USER_TEXT       "#EBDBB2"
set -g @GHC_SL_COLOR_FG_USER_SYM        "#EBDBB2"
set -g @GHC_SL_COLOR_FG_USER_TEXT       "#076678"

## WINDOW
set -g @GHC_SL_COLOR_BG_WIN_NAME        "#D5C4A1"
set -g @GHC_SL_COLOR_FG_WIN_NAME        "#665C54"
set -g @GHC_SL_COLOR_BG_WIN_NUM         "#A89984"
set -g @GHC_SL_COLOR_FG_WIN_NUM         "#665C54"

## WINDOW_CURRENT
set -g @GHC_SL_COLOR_BG_WIN_CUR_NAME    "#427B58"
set -g @GHC_SL_COLOR_FG_WIN_CUR_NAME    "#EBDBB2"

