# gruvbox-light

# Primary colors
[colors.primary]
background  = "#F2E5BC"
foreground  = "#3C3836"

# Cursor colors
[colors.cursor]
cursor      = "#B16286"
text        = "#EBDBB2"

# Selection colors
[colors.selection]
background  = "#D65D0E"
text        = "#EBDBB2"

# Normal colors
[colors.normal]
black       = "#F2E5BC"
red         = "#CC241D"
green       = "#98971A"
yellow      = "#D79921"
blue        = "#458588"
magenta     = "#B16286"
cyan        = "#689D6A"
white       = "#7C6F64"

# Bright colors
[colors.bright]
black       = "#928374"
red         = "#9D0006"
green       = "#79740E"
yellow      = "#B57614"
blue        = "#076678"
magenta     = "#8F3F71"
cyan        = "#427B58"
white       = "#3C3836"

