# gruvbox_dark

# Primary colors
background              #282828
foreground              #EBDBB2

# Border colors
active_border_color     #D3869B
inactive_border_color   #928374

# Cursor colors
cursor                  #D3869B
cursor_text_color       #3C3836

# Selection colors
selection_background    #D79921
selection_foreground    #3C3836

# Tab bar colors
active_tab_background   #282828
active_tab_foreground   #B16286
inactive_tab_background #98971A
inactive_tab_foreground #458588
tab_bar_background      #98971A

# Url colors
url_color               #458588

# Normal colors
color0                  #282828
color1                  #FB4934
color2                  #B8BB26
color3                  #FABD2F
color4                  #83A598
color5                  #D3869B
color6                  #8EC07C
color7                  #A89984

# Bright colors
color8                  #928374
color9                  #CC241D
color10                 #98971A
color11                 #D79921
color12                 #458588
color13                 #B16286
color14                 #689D6A
color15                 #EBDBB2
