# gruvbox-light

set -g @GHC_SL_BG                       "default"
set -g @GHC_PSL_BG                      "default"

## Message
set -g @GHC_SL_BG_MESSAGE               "#D79921"
set -g @GHC_SL_FG_MESSAGE               "#F2E5BC"

## Pane
set -g @GHC_PSL_FG_BORDER               "#A89984"
set -g @GHC_PSL_FG_BORDER_CUR           "#B16286"

set -g @GHC_PSL_BG_SYM                  "default"
set -g @GHC_PSL_FG_SYM                  "#7C6F64"
set -g @GHC_PSL_BG_TXT                  "default"
set -g @GHC_PSL_FG_TXT                  "#7C6F64"

set -g @GHC_PSL_BG_SYM_ACTIVE           "default"
set -g @GHC_PSL_FG_SYM_ACTIVE           "#B16286"
set -g @GHC_PSL_BG_TXT_ACTIVE           "default"
set -g @GHC_PSL_FG_TXT_ACTIVE           "#665C54"

## Statusbar

set -g @GHC_SL_FG_BORDER                "#A89984"
set -g @GHC_SL_FG_BORDER_CUR            "#B16286"

set -g @GHC_SL_BG_SYM                   "default"
set -g @GHC_SL_FG_SYM                   "#B16286"
set -g @GHC_SL_BG_TXT                   "default"
set -g @GHC_SL_FG_TXT                   "#665C54"

set -g @GHC_SL_BG_WIN_NAME              "#D5C4A1"
set -g @GHC_SL_FG_WIN_NAME              "#665C54"
set -g @GHC_SL_BG_WIN_NUM               "#A89984"
set -g @GHC_SL_FG_WIN_NUM               "#665C54"

set -g @GHC_SL_BG_WIN_NAME_ACTIVE       "#B16286"
set -g @GHC_SL_FG_WIN_NAME_ACTIVE       "#F2E5BC"
set -g @GHC_SL_BG_WIN_NUM_ACTIVE        "#B16286"
set -g @GHC_SL_FG_WIN_NUM_ACTIVE        "#F2E5BC"

