# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# gruvbox-light

[delta]
light                         = true
syntax-theme                  = gruvbox-light

side-by-side                  = true
navigate                      = true
paging                        = never
tabs                          = 2
relative-paths                = true
wrap-max-lines                = 2
width                         = -0
line-buffer-size              = 64
line-fill-method              = ansi
max-line-distance             = 0.5
word-diff-regex               = "[a-zA-Z_][a-zA-Z0-9_]*|[0-9]+|."
inline-hint-style             = "#458588"

####################################################################################################

file-style                    = "#3C3836" bold
file-decoration-style         = ul

hunk-header-style             = line-number syntax
hunk-header-decoration-style  = ul
hunk-header-line-number-style = "#504945"

line-numbers                  = true
line-numbers-left-style       = normal normal
line-numbers-right-style      = normal normal
line-numbers-zero-style       = normal normal
line-numbers-minus-style      = "#CC241D" normal bold
line-numbers-plus-style       = "#98971A" normal bold

zero-style                    = syntax normal
minus-style                   = syntax "#FCC19F"
plus-style                    = syntax "#E8E6B0"
minus-non-emph-style          = syntax "#FCC19F"
plus-non-emph-style           = syntax "#E8E6B0"
minus-emph-style              = syntax "#EB9D82" bold
plus-emph-style               = syntax "#D3D192" bold

plus-empty-line-marker-style  = "#E8E6B0" "#E8E6B0"
minus-empty-line-marker-style = "#FCC19F" "#FCC19F"

####################################################################################################

commit-style                  = "#D79921" bold
commit-decoration-style       = none

blame-palette                 = "#F2E5BC" "#EBDBB2" "#D5C4A1"
blame-format                  = "{author:<12} {commit:<8} {timestamp:<10}"
blame-code-style              = syntax
blame-separator-style         = "#504945" dim

hyperlinks                    = true
hyperlinks-file-link-format   = file://{path}:{line}

merge-conflict-begin-symbol   = ⟵
merge-conflict-end-symbol     = ⟶

