# gruvbox_dark

# Default colors
selection_foreground    #EBDBB2
selection_background    #D65D0E

background              #282828
foreground              #EBDBB2

# normal
color0                  #282828
color1                  #FB4934
color2                  #B8BB26
color3                  #FABD2F
color4                  #83A598
color5                  #D3869B
color6                  #8EC07C
color7                  #A89984

# bright
color8                  #928374
color9                  #CC241D
color10                 #98971A
color11                 #D79921
color12                 #458588
color13                 #B16286
color14                 #689D6A
color15                 #EBDBB2

cursor                  #BDAE93
cursor_text_color       #665C54
url_color               #458588
