# gruvbox-light

# Primary colors
background              #F2E5BC
foreground              #3C3836
selection_background    #B16286
selection_foreground    #F2E5BC

# Cursor colors
cursor                  #B16286
cursor_text_color       #F2E5BC

# URL underline color when hovering with mouse
url_color               #B16286

# Border colors
active_border_color     #32302F
inactive_border_color   #7C6F64
bell_border_color       #D79921

# Tab bar colors
active_tab_foreground   #EBDBB2
active_tab_background   #B16286
inactive_tab_foreground #32302F
inactive_tab_background #EBDBB2
tab_bar_background      #EBDBB2

# Colors for marks (marked text in the terminal)
mark1_foreground        #F2E5BC
mark1_background        #32302F
mark2_foreground        #F2E5BC
mark2_background        #B16286
mark3_foreground        #F2E5BC
mark3_background        #458588

# Normal colors
color0                  #F2E5BC
color1                  #CC241D
color2                  #98971A
color3                  #D79921
color4                  #458588
color5                  #B16286
color6                  #689D6A
color7                  #7C6F64

# Bright colors
color8                  #928374
color9                  #9D0006
color10                 #79740E
color11                 #B57614
color12                 #076678
color13                 #8F3F71
color14                 #427B58
color15                 #504945
