# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# gruvbox-dark

[delta "gruvbox-dark"]
dark                          = true
syntax-theme                  = gruvbox-dark

inline-hint-style             = "#458588"

####################################################################################################

file-style                    = "#EBDBB2" bold

hunk-header-line-number-style = "#D5C4A1"

line-numbers-minus-style      = "#CC241D" normal bold
line-numbers-plus-style       = "#98971A" normal bold

minus-style                   = syntax "#532020"
plus-style                    = syntax "#565B2F"
minus-non-emph-style          = syntax "#532020"
plus-non-emph-style           = syntax "#565B2F"
minus-emph-style              = syntax "#722824" bold
plus-emph-style               = syntax "#3F4531" bold

plus-empty-line-marker-style  = "#565B2F" "#565B2F"
minus-empty-line-marker-style = "#532020" "#532020"

####################################################################################################

commit-style                  = "#D79921" bold

blame-palette                 = "#32302F" "#3C3836" "#504945"
blame-separator-style         = "#D5C4A1" dim
