##  gruvbox-dark

# Basic
set -g @GHC_SL_COLOR_BG                 "default"

## MESSAGE
set -g @GHC_SL_COLOR_BG_MESSAGE         "#D79921"
set -g @GHC_SL_COLOR_FG_MESSAGE         "#282828"

## BORDER
set -g @GHC_SL_COLOR_BORDER             "#7C6F64"
set -g @GHC_SL_COLOR_BORDER_CUR         "#D3869B"

# Component

## APP
set -g @GHC_SL_COLOR_BG_APP_SYM         "#282828"
set -g @GHC_SL_COLOR_FG_APP_SYM         "#D3869B"
set -g @GHC_SL_COLOR_BG_APP_TEXT        "#282828"
set -g @GHC_SL_COLOR_FG_APP_TEXT        "#BDAE93"

## CPU
set -g @GHC_SL_COLOR_BG_CPU_SYM         "#282828"
set -g @GHC_SL_COLOR_FG_CPU_SYM         "#D3869B"
set -g @GHC_SL_COLOR_BG_CPU_TEXT        "#282828"
set -g @GHC_SL_COLOR_FG_CPU_TEXT        "#BDAE93"

## HOST
set -g @GHC_SL_COLOR_BG_HOST_SYM        "#282828"
set -g @GHC_SL_COLOR_FG_HOST_SYM        "#D3869B"
set -g @GHC_SL_COLOR_BG_HOST_TEXT       "#282828"
set -g @GHC_SL_COLOR_FG_HOST_TEXT       "#BDAE93"

## NETWORK
set -g @GHC_SL_COLOR_BG_NET_SYM         "#282828"
set -g @GHC_SL_COLOR_FG_NET_SYM         "#D3869B"
set -g @GHC_SL_COLOR_BG_NET_TEXT        "#282828"
set -g @GHC_SL_COLOR_FG_NET_TEXT        "#BDAE93"

## PID
set -g @GHC_SL_COLOR_BG_PID_SYM         "#282828"
set -g @GHC_SL_COLOR_FG_PID_SYM         "#D3869B"
set -g @GHC_SL_COLOR_BG_PID_TEXT        "#282828"
set -g @GHC_SL_COLOR_FG_PID_TEXT        "#BDAE93"

## TIME
set -g @GHC_SL_COLOR_BG_TIME_SYM        "#282828"
set -g @GHC_SL_COLOR_FG_TIME_SYM        "#D3869B"
set -g @GHC_SL_COLOR_BG_TIME_TEXT       "#282828"
set -g @GHC_SL_COLOR_FG_TIME_TEXT       "#BDAE93"

## DATE
set -g @GHC_SL_COLOR_BG_DATE_SYM        "#282828"
set -g @GHC_SL_COLOR_FG_DATE_SYM        "#D3869B"
set -g @GHC_SL_COLOR_BG_DATE_TEXT       "#282828"
set -g @GHC_SL_COLOR_FG_DATE_TEXT       "#BDAE93"

## SESSION
set -g @GHC_SL_COLOR_BG_SESSION_SYM     "#282828"
set -g @GHC_SL_COLOR_FG_SESSION_SYM     "#D3869B"
set -g @GHC_SL_COLOR_BG_SESSION_TEXT    "#282828"
set -g @GHC_SL_COLOR_FG_SESSION_TEXT    "#BDAE93"

## USER
set -g @GHC_SL_COLOR_BG_USER_SEP        "#282828"
set -g @GHC_SL_COLOR_FG_USER_SEP        "#BDAE93"
set -g @GHC_SL_COLOR_BG_USER_TEXT       "#282828"
set -g @GHC_SL_COLOR_FG_USER_TEXT       "#BDAE93"

## WINDOW
set -g @GHC_SL_COLOR_BG_WIN_NAME        "#504945"
set -g @GHC_SL_COLOR_FG_WIN_NAME        "#BDAE93"
set -g @GHC_SL_COLOR_BG_WIN_NUM         "#7C6F64"
set -g @GHC_SL_COLOR_FG_WIN_NUM         "#BDAE93"

## WINDOW_CURRENT
set -g @GHC_SL_COLOR_BG_WIN_CUR_NAME    "#D3869B"
set -g @GHC_SL_COLOR_FG_WIN_CUR_NAME    "#282828"

