# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# gruvbox-dark

[delta]
hunk-header-style             = raw
hunk-header-decoration-style  = ul
hyperlinks                    = true
hyperlinks-file-link-format   = file://{path}:{line}
detect-dark-light             = auto
line-numbers                  = true
navigate                      = true    # use n and N to move between diff sections
paging                        = never
side-by-side                  = true

syntax-theme                  = gruvbox-dark
dark                          = true
plus-style                    = syntax "#565B2F"
plus-emph-style               = syntax "#3F4531" bold
plus-non-emph-style           = syntax auto
minus-style                   = syntax "#532020"
minus-emph-style              = syntax "#722824" bold
minus-non-emph-style          = syntax auto
true-color                    = always

