set -g @GHC_SL_COLOR_BG_APP_SYM       "#427B58"
set -g @GHC_SL_COLOR_BG_APP_TEXT      "#D5C4A1"
set -g @GHC_SL_COLOR_BG_BAR           "#D5C4A1"
set -g @GHC_SL_COLOR_BG_DATE_SYM      "#427B58"
set -g @GHC_SL_COLOR_BG_DATE_TEXT     "#D5C4A1"
set -g @GHC_SL_COLOR_BG_MESSAGE       "#B57614"
set -g @GHC_SL_COLOR_BG_PID_SYM       "#427B58"
set -g @GHC_SL_COLOR_BG_PID_TEXT      "#D5C4A1"
set -g @GHC_SL_COLOR_BG_SESSION       "#79740E"
set -g @GHC_SL_COLOR_BG_USER          "#076678"
set -g @GHC_SL_COLOR_BG_WIN_NAME      "#D5C4A1"
set -g @GHC_SL_COLOR_BG_WIN_NAME_CUR  "#EBDBB2"
set -g @GHC_SL_COLOR_BG_WIN_NUM       "#A89984"
set -g @GHC_SL_COLOR_BG_WIN_NUM_CUR   "#AF3A03"
set -g @GHC_SL_COLOR_BORDER           "#A89984"
set -g @GHC_SL_COLOR_BORDER_CUR       "#AF3A03"
set -g @GHC_SL_COLOR_FG_APP_SYM       "#EBDBB2"
set -g @GHC_SL_COLOR_FG_APP_TEXT      "#3C3836"
set -g @GHC_SL_COLOR_FG_DATE_SYM      "#EBDBB2"
set -g @GHC_SL_COLOR_FG_DATE_TEXT     "#3C3836"
set -g @GHC_SL_COLOR_FG_MESSAGE       "#EBDBB2"
set -g @GHC_SL_COLOR_FG_PID_SYM       "#EBDBB2"
set -g @GHC_SL_COLOR_FG_PID_TEXT      "#3C3836"
set -g @GHC_SL_COLOR_FG_WIN_NAME      "#3C3836"
set -g @GHC_SL_COLOR_FG_WIN_NAME_CUR  "#AF3A03"
set -g @GHC_SL_COLOR_FG_WIN_NUM       "#504945"
set -g @GHC_SL_COLOR_FG_WIN_NUM_CUR   "#EBDBB2"
set -g @GHC_SL_COLOR_SESSION          "#EBDBB2"
set -g @GHC_SL_COLOR_USER             "#EBDBB2"
