selection_foreground    #3C3836
selection_background    #AF3A03

background              #FBF1C7
foreground              #3C3836

# normal
color0                  #282828
color1                  #CC241D
color2                  #98971A
color3                  #D79921
color4                  #458588
color5                  #B16286
color6                  #689D6A
color7                  #A89984

# bright
color8                  #3C3836
color9                  #9D0006
color10                 #79740E
color11                 #B57614
color12                 #076678
color13                 #8F3F71
color14                 #427B58
color15                 #EBDBB2

cursor                  #665C54
cursor_text_color       #BDAE93
url_color               #076678
