# kanagawa-lotus

# Primary colors
background              #F2ECBC
foreground              #38384D
selection_background    #D5D6CE
selection_foreground    #38384D

# Cursor colors
cursor                  #655A35
cursor_text_color       #F2ECBC

# URL underline color when hovering with mouse
url_color               #3E5A87

# Border colors
active_border_color     #3E5A87
inactive_border_color   #ACA99A
bell_border_color       #655A35

# Tab bar colors
active_tab_foreground   #F2ECBC
active_tab_background   #655A35
inactive_tab_foreground #545464
inactive_tab_background #E5DDB0
tab_bar_background      #E5DDB0

# Colors for marks (marked text in the terminal)
mark1_foreground        #F2ECBC
mark1_background        #3E5A87
mark2_foreground        #F2ECBC
mark2_background        #655A35
mark3_foreground        #F2ECBC
mark3_background        #624C83

# Official ANSI colors
color0                  #1F1F28
color1                  #C84053
color2                  #6F894E
color3                  #77713F
color4                  #4D699B
color5                  #B35B79
color6                  #597B75
color7                  #545464

# Bright colors
color8                  #8A8980
color9                  #D7474B
color10                 #6E915F
color11                 #836F4A
color12                 #6693BF
color13                 #624C83
color14                 #5E857A
color15                 #43436C
