# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# kanagawa-lotus

[delta]
light                         = true
syntax-theme                  = kanagawa-lotus

side-by-side                  = true
navigate                      = true
paging                        = never
tabs                          = 2
relative-paths                = true
wrap-max-lines                = 2
width                         = -0
line-buffer-size              = 64
line-fill-method              = ansi
max-line-distance             = 0.5
word-diff-regex               = "[a-zA-Z_][a-zA-Z0-9_]*|[0-9]+|."
inline-hint-style             = "#4D699B"

####################################################################################################

file-style                    = "#43436C" bold
file-decoration-style         = ul

hunk-header-style             = line-number syntax
hunk-header-decoration-style  = ul
hunk-header-line-number-style = "#716E61"

line-numbers                  = true
line-numbers-left-style       = normal normal
line-numbers-right-style      = normal normal
line-numbers-zero-style       = normal normal
line-numbers-minus-style      = "#C84053" normal bold
line-numbers-plus-style       = "#6F894E" normal bold

zero-style                    = syntax normal
minus-style                   = syntax "#D9A594"
plus-style                    = syntax "#B7D0AE"
minus-non-emph-style          = syntax "#D9A594"
plus-non-emph-style           = syntax "#B7D0AE"
minus-emph-style              = syntax "#D7474B" bold
plus-emph-style               = syntax "#6E915F" bold

plus-empty-line-marker-style  = "#B7D0AE" "#B7D0AE"
minus-empty-line-marker-style = "#D9A594" "#D9A594"

####################################################################################################

commit-style                  = "#77713F" bold
commit-decoration-style       = none

blame-palette                 = "#F2ECBC" "#E7DBA0" "#E4D794"
blame-format                  = "{author:<12} {commit:<8} {timestamp:<10}"
blame-code-style              = syntax
blame-separator-style         = "#716E61" dim

hyperlinks                    = true
hyperlinks-file-link-format   = file://{path}:{line}

merge-conflict-begin-symbol   = ⟵
merge-conflict-end-symbol     = ⟶
