# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# kanagawa-dragon

[delta "kanagawa-dragon"]
dark                          = true
syntax-theme                  = kanagawa-dragon

inline-hint-style             = "#8BA4B0"

####################################################################################################

file-style                    = "#C5C9C5" bold

hunk-header-line-number-style = "#A6A69C"

line-numbers-minus-style      = "#D58C84" normal bold
line-numbers-plus-style       = "#87A987" normal bold

minus-style                   = syntax "#322322"
plus-style                    = syntax "#262E26"
minus-non-emph-style          = syntax "#322322"
plus-non-emph-style           = syntax "#262E26"
minus-emph-style              = "#C5C9C5" "#5B3B38" bold
plus-emph-style               = "#C5C9C5" "#3F4D3E" bold

plus-empty-line-marker-style  = "#262E26" "#262E26"
minus-empty-line-marker-style = "#322322" "#322322"

####################################################################################################

commit-style                  = "#C4B28A" bold

blame-palette                 = "#181616" "#12120F" "#282727"
blame-separator-style         = "#A6A69C" dim
