# kanagawa-lotus

# Primary colors
background              #F2ECBC
foreground              #43436C
selection_background    #B35B79
selection_foreground    #F2ECBC

# Cursor colors
cursor                  #B35B79
cursor_text_color       #F2ECBC

# URL underline color when hovering with mouse
url_color               #B35B79

# Border colors
active_border_color     #545464
inactive_border_color   #A09CAC
bell_border_color       #77713F

# Tab bar colors
active_tab_foreground   #F2ECBC
active_tab_background   #B35B79
inactive_tab_foreground #545464
inactive_tab_background #E7DBA0
tab_bar_background      #E7DBA0

# Colors for marks (marked text in the terminal)
mark1_foreground        #F2ECBC
mark1_background        #545464
mark2_foreground        #F2ECBC
mark2_background        #B35B79
mark3_foreground        #F2ECBC
mark3_background        #4D699B

# Normal colors
color0                  #F2ECBC
color1                  #C84053
color2                  #6F894E
color3                  #77713F
color4                  #4D699B
color5                  #B35B79
color6                  #597B75
color7                  #A09CAC

# Bright colors
color8                  #8A8980
color9                  #D7474B
color10                 #6E915F
color11                 #836F4A
color12                 #6693BF
color13                 #624C83
color14                 #5E857A
color15                 #716E61
