# kanagawa-dragon

# Primary colors
background              #181616
foreground              #C8C093
selection_background    #A292A3
selection_foreground    #181616

# Cursor colors
cursor                  #A292A3
cursor_text_color       #181616

# URL underline color when hovering with mouse
url_color               #A292A3

# Border colors
active_border_color     #C5C9C5
inactive_border_color   #737C73
bell_border_color       #C4B28A

# Tab bar colors
active_tab_foreground   #181616
active_tab_background   #A292A3
inactive_tab_foreground #C5C9C5
inactive_tab_background #282727
tab_bar_background      #282727

# Colors for marks (marked text in the terminal)
mark1_foreground        #181616
mark1_background        #C5C9C5
mark2_foreground        #181616
mark2_background        #A292A3
mark3_foreground        #181616
mark3_background        #8BA4B0

# Normal colors
color0                  #181616
color1                  #C4746E
color2                  #8A9A7B
color3                  #C4B28A
color4                  #8BA4B0
color5                  #A292A3
color6                  #8EA4A2
color7                  #737C73

# Bright colors
color8                  #A6A69C
color9                  #E46876
color10                 #87A987
color11                 #E6C384
color12                 #7FB4CA
color13                 #938AA9
color14                 #7AA89F
color15                 #A6A69C
