set -gx color_bg0_h           '#1E222A'
set -gx color_bg0             '#282828'
set -gx color_bg0_s           '#31353F'
set -gx color_bg1             '#353B45'
set -gx color_bg2             '#393F4A'
set -gx color_bg3             '#545862'
set -gx color_bg4             '#565C64'

set -gx color_fg              '#DCDFE4'
set -gx color_fg0             '#E5E5E6'
set -gx color_fg1             '#DCDFE4'
set -gx color_fg2             '#C8CCD4'
set -gx color_fg3             '#B6BDCA'
set -gx color_fg4             '#ABB2BF'

set -gx color_red             '#E06C75'
set -gx color_green           '#98C379'
set -gx color_yellow          '#E5C07B'
set -gx color_blue            '#61AFEF'
set -gx color_purple          '#C678DD'
set -gx color_aqua            '#56B6C2'
set -gx color_orange          '#DE8C92'
set -gx color_grey            '#ABB2BF'

set -gx color_neutral_red     '#E06C75'
set -gx color_neutral_green   '#98C379'
set -gx color_neutral_yellow  '#E5C07B'
set -gx color_neutral_blue    '#61AFEF'
set -gx color_neutral_purple  '#C678DD'
set -gx color_neutral_aqua    '#56B6C2'
set -gx color_neutral_orange  '#FF75A0'
set -gx color_neutral_grey    '#DCDFE4'
