# nord

# Primary colors
background              #2E3440
foreground              #E5E9F0

# Border colors
active_border_color     #B48EAD
inactive_border_color   #4C566A

# Cursor colors
cursor                  #FFA3A3
cursor_text_color       #3B4252

# Selection colors
selection_background    #EBCB8B
selection_foreground    #3B4252

# Tab bar colors
active_tab_background   #B48EAD
active_tab_foreground   #2E3440
inactive_tab_background #3B4252
inactive_tab_foreground #B48EAD
tab_bar_background      #2E3440

# Url colors
url_color               #81A1C1

# Normal colors
color0                  #2E3440
color1                  #BF616A
color2                  #A3BE8C
color3                  #EBCB8B
color4                  #5E81AC
color5                  #B48EAD
color6                  #88C0D0
color7                  #B0BEC5

# Bright colors
color8                  #4C566A
color9                  #BF616A
color10                 #A3BE8C
color11                 #EBCB8B
color12                 #81A1C1
color13                 #B48EAD
color14                 #8FBCBB
color15                 #E5E9F0
