# Basic
set -g @GHC_SL_COLOR_BG                 "default"


## MESSAGE
set -g @GHC_SL_COLOR_BG_MESSAGE         "#EBCB8B"
set -g @GHC_SL_COLOR_FG_MESSAGE         "#3B4252"

## BORDER
set -g @GHC_SL_COLOR_BORDER             "#545862"
set -g @GHC_SL_COLOR_BORDER_CUR         "#D08770"

# Component

## APP
set -g @GHC_SL_COLOR_BG_APP_SYM         "#88C0D0"
set -g @GHC_SL_COLOR_FG_APP_SYM         "#3B4252"
set -g @GHC_SL_COLOR_BG_APP_TEXT        "#3B4252"
set -g @GHC_SL_COLOR_FG_APP_TEXT        "#D8DEE9"

## DATE
set -g @GHC_SL_COLOR_BG_DATE_SYM        "#88C0D0"
set -g @GHC_SL_COLOR_FG_DATE_SYM        "#3B4252"
set -g @GHC_SL_COLOR_BG_DATE_TEXT       "#3B4252"
set -g @GHC_SL_COLOR_FG_DATE_TEXT       "#D8DEE9"

## PID
set -g @GHC_SL_COLOR_BG_PID_SYM         "#88C0D0"
set -g @GHC_SL_COLOR_FG_PID_SYM         "#3B4252"
set -g @GHC_SL_COLOR_BG_PID_TEXT        "#3B4252"
set -g @GHC_SL_COLOR_FG_PID_TEXT        "#D8DEE9"

## SESSION
set -g @GHC_SL_COLOR_BG_SESSION         "#434C5E"
set -g @GHC_SL_COLOR_FG_SESSION         "#B48EAD"

## USER
set -g @GHC_SL_COLOR_BG_USER            "#5E81AC"
set -g @GHC_SL_COLOR_FG_USER            "#434C5E"

## WINDOW
set -g @GHC_SL_COLOR_BG_WIN_NAME        "#434C5E"
set -g @GHC_SL_COLOR_FG_WIN_NAME        "#E5E9F0"
set -g @GHC_SL_COLOR_BG_WIN_NUM         "#545862"
set -g @GHC_SL_COLOR_FG_WIN_NUM         "#D8DEE9"

## WINDOW_CURRENT
set -g @GHC_SL_COLOR_BG_WIN_CUR_NAME    "default"
set -g @GHC_SL_COLOR_FG_WIN_CUR_NAME    "#E5E9F0"
set -g @GHC_SL_COLOR_BG_WIN_CUR_NUM     "#B48EAD"
set -g @GHC_SL_COLOR_FG_WIN_CUR_NUM     "#434C5E"

