set -g @GHC_SL_COLOR_BG_APP_SYM       "#88C0D0"
set -g @GHC_SL_COLOR_BG_APP_TEXT      "#434C5E"
set -g @GHC_SL_COLOR_BG_BAR           "#434C5E"
set -g @GHC_SL_COLOR_BG_DATE_SYM      "#88C0D0"
set -g @GHC_SL_COLOR_BG_DATE_TEXT     "#434C5E"
set -g @GHC_SL_COLOR_BG_MESSAGE       "#EBCB8B"
set -g @GHC_SL_COLOR_BG_SESSION       "#A3BE8C"
set -g @GHC_SL_COLOR_BG_USER          "#5E81AC"
set -g @GHC_SL_COLOR_BG_WIN_NAME      "#434C5E"
set -g @GHC_SL_COLOR_BG_WIN_NAME_CUR  "#3B4252"
set -g @GHC_SL_COLOR_BG_WIN_NUM       "#545862"
set -g @GHC_SL_COLOR_BG_WIN_NUM_CUR   "#D08770"
set -g @GHC_SL_COLOR_BORDER           "#545862"
set -g @GHC_SL_COLOR_BORDER_CUR       "#D08770"
set -g @GHC_SL_COLOR_FG_APP_SYM       "#3B4252"
set -g @GHC_SL_COLOR_FG_APP_TEXT      "#ECEFF4"
set -g @GHC_SL_COLOR_FG_DATE_SYM      "#3B4252"
set -g @GHC_SL_COLOR_FG_DATE_TEXT     "#ECEFF4"
set -g @GHC_SL_COLOR_FG_MESSAGE       "#3B4252"
set -g @GHC_SL_COLOR_FG_WIN_NAME      "#ECEFF4"
set -g @GHC_SL_COLOR_FG_WIN_NAME_CUR  "#D08770"
set -g @GHC_SL_COLOR_FG_WIN_NUM       "#E5E9F0"
set -g @GHC_SL_COLOR_FG_WIN_NUM_CUR   "#3B4252"
set -g @GHC_SL_COLOR_SESSION          "#3B4252"
set -g @GHC_SL_COLOR_USER             "#3B4252"
