# nord

set -g @GHC_SL_BG                       "default"
set -g @GHC_PSL_BG                      "default"

## Cmdline
set -g @GHC_SL_BG_CMDLINE               "#8FBCBB"
set -g @GHC_SL_FG_CMDLINE               "#2E3440"

## Message
set -g @GHC_SL_BG_MESSAGE               "#EBCB8B"
set -g @GHC_SL_FG_MESSAGE               "#2E3440"

## Pane
set -g @GHC_PSL_FG_BORDER               "#545862"
set -g @GHC_PSL_FG_BORDER_CUR           "#FFA3A3"

set -g @GHC_PSL_BG_SYM                  "default"
set -g @GHC_PSL_FG_SYM                  "#B0BEC5"
set -g @GHC_PSL_BG_TXT                  "default"
set -g @GHC_PSL_FG_TXT                  "#B0BEC5"

set -g @GHC_PSL_BG_SYM_ACTIVE           "default"
set -g @GHC_PSL_FG_SYM_ACTIVE           "#FFA3A3"
set -g @GHC_PSL_BG_TXT_ACTIVE           "default"
set -g @GHC_PSL_FG_TXT_ACTIVE           "#E5E9F0"

## Statusbar

set -g @GHC_SL_FG_BORDER                "#545862"
set -g @GHC_SL_FG_BORDER_CUR            "#FFA3A3"

set -g @GHC_SL_BG_SYM                   "default"
set -g @GHC_SL_FG_SYM                   "#FFA3A3"
set -g @GHC_SL_BG_TXT                   "default"
set -g @GHC_SL_FG_TXT                   "#C8CCD4"

set -g @GHC_SL_BG_WIN_NAME              "#434C5E"
set -g @GHC_SL_FG_WIN_NAME              "#C8CCD4"
set -g @GHC_SL_BG_WIN_NUM               "#545862"
set -g @GHC_SL_FG_WIN_NUM               "#C8CCD4"

set -g @GHC_SL_BG_WIN_NAME_ACTIVE       "#FFA3A3"
set -g @GHC_SL_FG_WIN_NAME_ACTIVE       "#2E3440"
set -g @GHC_SL_BG_WIN_NUM_ACTIVE        "#FFA3A3"
set -g @GHC_SL_FG_WIN_NUM_ACTIVE        "#2E3440"

