# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# nord

[delta]
hunk-header-style             = raw
hunk-header-decoration-style  = ul
hyperlinks                    = true
hyperlinks-file-link-format   = file://{path}:{line}
detect-dark-light             = auto
line-numbers                  = true
navigate                      = true    # use n and N to move between diff sections
paging                        = never
side-by-side                  = true

dark                          = true
syntax-theme                  = nord
plus-style                    = syntax "#444F44"
plus-emph-style               = syntax "#505F5D" bold
plus-non-emph-style           = syntax "#444F44" bold
minus-style                   = syntax "#582A33"
minus-emph-style              = syntax "#773A44" bold
minus-non-emph-style          = syntax "#582A33" bold
line-numbers-left-style       = "#E5E9F0"
line-numbers-right-style      = "#E5E9F0"
line-numbers-minus-style      = "#ECEFF4" "#582A33" bold
line-numbers-plus-style       = "#ECEFF4" "#444F44" bold
true-color                    = always

