# nord

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

[colors.cursor]
cursor            = "#FFA3A3"
text              = "#3B4252"

[colors.vi_mode_cursor]
cursor            = "#FFA3A3"
text              = "#3B4252"

[colors.search.matches]
background        = "#EBCB8B"
foreground        = "#3B4252"

[colors.search.focused_match]
background        = "#EBCB8B"
foreground        = "#3B4252"

[colors.selection]
background        = "#D08770"
text              = "#3B4252"

[colors.footer_bar]
background        = "#434C5E"
foreground        = "#E5E9F0"

[colors.primary]
background        = "#2E3440"
foreground        = "#E5E9F0"
dim_foreground    = "#E5E9F0"
bright_foreground = "#E5E9F0"

[colors.normal]
black             = "#2E3440"
blue              = "#5E81AC"
cyan              = "#88C0D0"
green             = "#A3BE8C"
magenta           = "#B48EAD"
red               = "#BF616A"
yellow            = "#EBCB8B"
white             = "#B0BEC5"

[colors.bright]
black             = "#4C566A"
blue              = "#81A1C1"
cyan              = "#8FBCBB"
green             = "#A3BE8C"
magenta           = "#B48EAD"
red               = "#BF616A"
yellow            = "#EBCB8B"
white             = "#E5E9F0"

[colors.dim]
black             = "#2E3440"
blue              = "#5E81AC"
cyan              = "#88C0D0"
green             = "#A3BE8C"
magenta           = "#B48EAD"
red               = "#BF616A"
yellow            = "#EBCB8B"
white             = "#B0BEC5"

