##  nord

set -g @GHC_SL_BG                       "default"

## Message
set -g @GHC_SL_BG_MESSAGE               "#EBCB8B"
set -g @GHC_SL_FG_MESSAGE               "#2E3440"

## Pane

set -g @GHC_PSL_FG_BORDER               "#545862"
set -g @GHC_PSL_FG_BORDER_CUR           "#FFA3A3"

set -g @GHC_PSL_BG_SYM                  "#2E3440"
set -g @GHC_PSL_FG_SYM                  "#B0BEC5"
set -g @GHC_PSL_BG_TXT                  "#2E3440"
set -g @GHC_PSL_FG_TXT                  "#B0BEC5"

set -g @GHC_PSL_BG_SYM_ACTIVE           "#2E3440"
set -g @GHC_PSL_FG_SYM_ACTIVE           "#FFA3A3"
set -g @GHC_PSL_BG_TXT_ACTIVE           "#2E3440"
set -g @GHC_PSL_FG_TXT_ACTIVE           "#C8CCD4"

## Statusbar

set -g @GHC_SL_FG_BORDER                "#545862"
set -g @GHC_SL_FG_BORDER_CUR            "#FFA3A3"

set -g @GHC_SL_BG_SYM                   "#2E3440"
set -g @GHC_SL_FG_SYM                   "#FFA3A3"
set -g @GHC_SL_BG_TXT                   "#2E3440"
set -g @GHC_SL_FG_TXT                   "#C8CCD4"

set -g @GHC_SL_BG_WIN_NAME              "#434C5E"
set -g @GHC_SL_FG_WIN_NAME              "#C8CCD4"
set -g @GHC_SL_BG_WIN_NUM               "#545862"
set -g @GHC_SL_FG_WIN_NUM               "#C8CCD4"

set -g @GHC_SL_BG_WIN_NAME_ACTIVE       "#FFA3A3"
set -g @GHC_SL_FG_WIN_NAME_ACTIVE       "#2E3440"
set -g @GHC_SL_BG_WIN_NUM_ACTIVE        "#FFA3A3"
set -g @GHC_SL_FG_WIN_NUM_ACTIVE        "#2E3440"

