# nord

# Primary colors
background              #2E3440
foreground              #E5E9F0
selection_background    #FFA3A3
selection_foreground    #2E3440

# Cursor colors
cursor                  #FFA3A3
cursor_text_color       #2E3440

# URL underline color when hovering with mouse
url_color               #FFA3A3

# Border colors
active_border_color     #ECEFF4
inactive_border_color   #B0BEC5
bell_border_color       #EBCB8B

# Tab bar colors
active_tab_foreground   #2E3440
active_tab_background   #FFA3A3
inactive_tab_foreground #ECEFF4
inactive_tab_background #3B4252
tab_bar_background      #3B4252

# Colors for marks (marked text in the terminal)
mark1_foreground        #2E3440
mark1_background        #ECEFF4
mark2_foreground        #2E3440
mark2_background        #B48EAD
mark3_foreground        #2E3440
mark3_background        #5E81AC

# Normal colors
color0                  #2E3440
color1                  #BF616A
color2                  #A3BE8C
color3                  #EBCB8B
color4                  #5E81AC
color5                  #B48EAD
color6                  #88C0D0
color7                  #B0BEC5

# Bright colors
color8                  #4C566A
color9                  #BF616A
color10                 #A3BE8C
color11                 #EBCB8B
color12                 #81A1C1
color13                 #B48EAD
color14                 #8FBCBB
color15                 #D8DEE9
