set -gx color_bg0             '#282828'
set -gx color_bg1             '#2E3440'
set -gx color_bg2             '#3B4252'
set -gx color_bg3             '#434C5E'
set -gx color_bg4             '#4C566A'

set -gx color_fg              '#ECEFF4'
set -gx color_fg0             '#E5E5E6'
set -gx color_fg1             '#ECEFF4'
set -gx color_fg2             '#E5E9F0'
set -gx color_fg3             '#D8DEE9'
set -gx color_fg4             '#C8CCD4'

set -gx color_red             '#BF616A'
set -gx color_green           '#A3BE8C'
set -gx color_yellow          '#EBCB8B'
set -gx color_blue            '#5E81AC'
set -gx color_purple          '#B48EAD'
set -gx color_aqua            '#88C0D0'
set -gx color_orange          '#D08770'

set -gx color_neutral_red     '#BF616A'
set -gx color_neutral_green   '#A3BE8C'
set -gx color_neutral_yellow  '#EBCB8B'
set -gx color_neutral_blue    '#81A1C1'
set -gx color_neutral_purple  '#B48EAD'
set -gx color_neutral_aqua    '#8FBCBB'
set -gx color_neutral_orange  '#D08770'
