# Default colors
[colors.primary]
background = "#282828"
foreground = "#ECEFF4"

# Normal colors
[colors.normal]
black   = "#282828"
red     = "#BF616A"
green   = "#A3BE8C"
yellow  = "#EBCB8B"
blue    = "#81A1C1"
magenta = "#B48EAD"
cyan    = "#8FBCBB"
white   = "#C8CCD4"

# Bright colors
[colors.bright]
black   = "#C8CCD4"
red     = "#BF616A"
green   = "#A3BE8C"
yellow  = "#EBCB8B"
blue    = "#5E81AC"
magenta = "#B48EAD"
cyan    = "#88C0D0"
white   = "#ECEFF4"
