# Colors (One Half Dark)

[colors.primary]
background = '#282c34'
foreground = '#dcdfe4'

[colors.normal]
black     = "#586069"
red       = "#e06c75"
green     = "#98c379"
yellow    = "#e5c07b"
blue      = "#61afef"
magenta   = "#c678dd"
cyan      = "#56b6c2"
white     = "#d1d5da"

[colors.bright]
black     = "#959da5"
red       = "#e06c75"
green     = "#98c379"
yellow    = "#e5c07b"
blue      = "#61afef"
magenta   = "#c678dd"
cyan      = "#56b6c2"
white     = "#fafbfc"

[[colors.indexed_colors]]
index     = 16
color     = "#d18616"

[[colors.indexed_colors]]
index     = 17
color     = "#f97583"
