# Basic
set -g @GHC_TMUX_THEME                  "one-half-dark"
set -g @GHC_SL_COLOR_BG                 "default"

## MESSAGE
set -g @GHC_SL_COLOR_BG_MESSAGE         "#E5C07B"
set -g @GHC_SL_COLOR_FG_MESSAGE         "#252931"

## BORDER
set -g @GHC_SL_COLOR_BORDER             "#565C64"
set -g @GHC_SL_COLOR_BORDER_CUR         "#C678DD"

# Component

## APP
set -g @GHC_SL_COLOR_BG_APP_SYM         "#61AFEF"
set -g @GHC_SL_COLOR_FG_APP_SYM         "#252931"
set -g @GHC_SL_COLOR_BG_APP_TEXT        "#252931"
set -g @GHC_SL_COLOR_FG_APP_TEXT        "#C8CCD4"

## CPU
set -g @GHC_SL_COLOR_BG_CPU_SYM         "#61AFEF"
set -g @GHC_SL_COLOR_FG_CPU_SYM         "#252931"
set -g @GHC_SL_COLOR_BG_CPU_TEXT        "#252931"
set -g @GHC_SL_COLOR_FG_CPU_TEXT        "#C8CCD4"

## NETWORK
set -g @GHC_SL_COLOR_BG_NET_SYM         "#61AFEF"
set -g @GHC_SL_COLOR_FG_NET_SYM         "#252931"
set -g @GHC_SL_COLOR_BG_NET_TEXT        "#252931"
set -g @GHC_SL_COLOR_FG_NET_TEXT        "#C8CCD4"

## PID
set -g @GHC_SL_COLOR_BG_PID_SYM         "#61AFEF"
set -g @GHC_SL_COLOR_FG_PID_SYM         "#252931"
set -g @GHC_SL_COLOR_BG_PID_TEXT        "#252931"
set -g @GHC_SL_COLOR_FG_PID_TEXT        "#C8CCD4"

## TIME
set -g @GHC_SL_COLOR_BG_TIME_SYM        "#61AFEF"
set -g @GHC_SL_COLOR_FG_TIME_SYM        "#252931"
set -g @GHC_SL_COLOR_BG_TIME_TEXT       "#252931"
set -g @GHC_SL_COLOR_FG_TIME_TEXT       "#C8CCD4"

## DATE
set -g @GHC_SL_COLOR_BG_DATE_SYM        "#61AFEF"
set -g @GHC_SL_COLOR_FG_DATE_SYM        "#252931"
set -g @GHC_SL_COLOR_BG_DATE_TEXT       "#252931"
set -g @GHC_SL_COLOR_FG_DATE_TEXT       "#C8CCD4"

## SESSION
set -g @GHC_SL_COLOR_BG_SESSION_SYM     "#DE8C92"
set -g @GHC_SL_COLOR_FG_SESSION_SYM     "#252931"
set -g @GHC_SL_COLOR_BG_SESSION_TEXT    "#252931"
set -g @GHC_SL_COLOR_FG_SESSION_TEXT    "#DE8C92"

## USER
set -g @GHC_SL_COLOR_BG_USER_SYM        "#61AFEF"
set -g @GHC_SL_COLOR_BG_USER_TEXT       "#252931"
set -g @GHC_SL_COLOR_FG_USER_SYM        "#252931"
set -g @GHC_SL_COLOR_FG_USER_TEXT       "#61AFEF"

## WINDOW
set -g @GHC_SL_COLOR_BG_WIN_NAME        "#3E4451"
set -g @GHC_SL_COLOR_FG_WIN_NAME        "#B6BDCA"
set -g @GHC_SL_COLOR_BG_WIN_NUM         "#565C64"
set -g @GHC_SL_COLOR_FG_WIN_NUM         "#B6BDCA"

## WINDOW_CURRENT
set -g @GHC_SL_COLOR_BG_WIN_CUR_NAME    "#56B6C2"
set -g @GHC_SL_COLOR_FG_WIN_CUR_NAME    "#252931"

