# Basic
set -g @GHC_TMUX_THEME                  "one-half-light"
set -g @GHC_SL_COLOR_BG                 "default"

## MESSAGE
set -g @GHC_SL_COLOR_BG_MESSAGE         "#DEA95F"
set -g @GHC_SL_COLOR_FG_MESSAGE         "#F0F0F0"

## BORDER
set -g @GHC_SL_COLOR_BORDER             "#D3D3D3"
set -g @GHC_SL_COLOR_BORDER_CUR         "#A28DCD"

# Component

## APP
set -g @GHC_SL_COLOR_BG_APP_SYM         "#4078F2"
set -g @GHC_SL_COLOR_FG_APP_SYM         "#F0F0F0"
set -g @GHC_SL_COLOR_BG_APP_TEXT        "#F0F0F0"
set -g @GHC_SL_COLOR_FG_APP_TEXT        "#5C5F66"

## CPU
set -g @GHC_SL_COLOR_BG_CPU_SYM         "#4078F2"
set -g @GHC_SL_COLOR_FG_CPU_SYM         "#F0F0F0"
set -g @GHC_SL_COLOR_BG_CPU_TEXT        "#F0F0F0"
set -g @GHC_SL_COLOR_FG_CPU_TEXT        "#5C5F66"

## NETWORK
set -g @GHC_SL_COLOR_BG_NET_SYM         "#4078F2"
set -g @GHC_SL_COLOR_FG_NET_SYM         "#F0F0F0"
set -g @GHC_SL_COLOR_BG_NET_TEXT        "#F0F0F0"
set -g @GHC_SL_COLOR_FG_NET_TEXT        "#5C5F66"

## PID
set -g @GHC_SL_COLOR_BG_PID_SYM         "#4078F2"
set -g @GHC_SL_COLOR_FG_PID_SYM         "#F0F0F0"
set -g @GHC_SL_COLOR_BG_PID_TEXT        "#F0F0F0"
set -g @GHC_SL_COLOR_FG_PID_TEXT        "#5C5F66"

## TIME
set -g @GHC_SL_COLOR_BG_TIME_SYM        "#4078F2"
set -g @GHC_SL_COLOR_FG_TIME_SYM        "#F0F0F0"
set -g @GHC_SL_COLOR_BG_TIME_TEXT       "#F0F0F0"
set -g @GHC_SL_COLOR_FG_TIME_TEXT       "#5C5F66"

## DATE
set -g @GHC_SL_COLOR_BG_DATE_SYM        "#4078F2"
set -g @GHC_SL_COLOR_FG_DATE_SYM        "#F0F0F0"
set -g @GHC_SL_COLOR_BG_DATE_TEXT       "#F0F0F0"
set -g @GHC_SL_COLOR_FG_DATE_TEXT       "#5C5F66"

## SESSION
set -g @GHC_SL_COLOR_BG_SESSION_SYM     "#F07178"
set -g @GHC_SL_COLOR_FG_SESSION_SYM     "#F0F0F0"
set -g @GHC_SL_COLOR_BG_SESSION_TEXT    "#F0F0F0"
set -g @GHC_SL_COLOR_FG_SESSION_TEXT    "#F07178"

## USER
set -g @GHC_SL_COLOR_BG_USER_SYM        "#4078F2"
set -g @GHC_SL_COLOR_BG_USER_TEXT       "#F0F0F0"
set -g @GHC_SL_COLOR_FG_USER_SYM        "#F0F0F0"
set -g @GHC_SL_COLOR_FG_USER_TEXT       "#4078F2"

## WINDOW
set -g @GHC_SL_COLOR_BG_WIN_NAME        "#E5E5E5"
set -g @GHC_SL_COLOR_FG_WIN_NAME        "#4F525A"
set -g @GHC_SL_COLOR_BG_WIN_NUM         "#D3D3D3"
set -g @GHC_SL_COLOR_FG_WIN_NUM         "#4F525A"

## WINDOW_CURRENT
set -g @GHC_SL_COLOR_BG_WIN_CUR_NAME    "#0B8EC6"
set -g @GHC_SL_COLOR_FG_WIN_CUR_NAME    "#F0F0F0"

