# one_half_dark

# Primary colors
background              #1E222A
foreground              #D7DAE0

# Border colors
active_border_color     #C678DD
inactive_border_color   #42464E

# Cursor colors
cursor                  #DE8C92
cursor_text_color       #252931

# Selection colors
selection_background    #D19A66
selection_foreground    #252931

# Tab bar colors
active_tab_background   #1E222A
active_tab_foreground   #B294BB
inactive_tab_background #7ECA9C
inactive_tab_foreground #61AFEF
tab_bar_background      #7ECA9C

# Url colors
url_color               #61AFEF

# Normal colors
color0                  #1E222A
color1                  #E06C75
color2                  #98C379
color3                  #E5C07B
color4                  #61AFEF
color5                  #C678DD
color6                  #56B6C2
color7                  #ABB2BF

# Bright colors
color8                  #42464E
color9                  #E06C75
color10                 #7ECA9C
color11                 #D19A66
color12                 #61AFEF
color13                 #B294BB
color14                 #4EC9B0
color15                 #D7DAE0
