# one_half_light

# Primary colors
background              #FAFAFA
foreground              #696D75

# Border colors
active_border_color     #A28DCD
inactive_border_color   #B7B7B7

# Cursor colors
cursor                  #F07178
cursor_text_color       #F0F0F0

# Selection colors
selection_background    #D19A66
selection_foreground    #F0F0F0

# Tab bar colors
active_tab_background   #FAFAFA
active_tab_foreground   #B294BB
inactive_tab_background #7ECA9C
inactive_tab_foreground #61AFEF
tab_bar_background      #7ECA9C

# Url colors
url_color               #61AFEF

# Normal colors
color0                  #FAFAFA
color1                  #D84A3D
color2                  #50A14F
color3                  #DEA95F
color4                  #4078F2
color5                  #A28DCD
color6                  #0B8EC6
color7                  #383A42

# Bright colors
color8                  #B7B7B7
color9                  #E06C75
color10                 #7ECA9C
color11                 #D19A66
color12                 #61AFEF
color13                 #B294BB
color14                 #4EC9B0
color15                 #696D75
