# Basic
set -g @GHC_TMUX_THEME                  "one_half_light"
set -g @GHC_SL_COLOR_BG                 "default"

## MESSAGE
set -g @GHC_SL_COLOR_BG_MESSAGE         "#DEA95F"
set -g @GHC_SL_COLOR_FG_MESSAGE         "#F0F0F0"

## BORDER
set -g @GHC_SL_COLOR_BORDER             "#D3D3D3"
set -g @GHC_SL_COLOR_BORDER_CUR         "#FF6A00"

# Component

## APP
set -g @GHC_SL_COLOR_BG_APP_SYM         "#0B8EC6"
set -g @GHC_SL_COLOR_FG_APP_SYM         "#F0F0F0"
set -g @GHC_SL_COLOR_BG_APP_TEXT        "#F0F0F0"
set -g @GHC_SL_COLOR_FG_APP_TEXT        "#5C5F66"

## DATE
set -g @GHC_SL_COLOR_BG_DATE_SYM        "#0B8EC6"
set -g @GHC_SL_COLOR_FG_DATE_SYM        "#F0F0F0"
set -g @GHC_SL_COLOR_BG_DATE_TEXT       "#F0F0F0"
set -g @GHC_SL_COLOR_FG_DATE_TEXT       "#5C5F66"

## PID
set -g @GHC_SL_COLOR_BG_PID_SYM         "#0B8EC6"
set -g @GHC_SL_COLOR_FG_PID_SYM         "#F0F0F0"
set -g @GHC_SL_COLOR_BG_PID_TEXT        "#F0F0F0"
set -g @GHC_SL_COLOR_FG_PID_TEXT        "#5C5F66"

## SESSION
set -g @GHC_SL_COLOR_BG_SESSION         "#E5E5E5"
set -g @GHC_SL_COLOR_FG_SESSION         "#F07178"

## USER
set -g @GHC_SL_COLOR_BG_USER            "#4078F2"
set -g @GHC_SL_COLOR_FG_USER            "#E5E5E5"

## WINDOW
set -g @GHC_SL_COLOR_BG_WIN_NAME        "#E5E5E5"
set -g @GHC_SL_COLOR_FG_WIN_NAME        "#4F525A"
set -g @GHC_SL_COLOR_BG_WIN_NUM         "#D3D3D3"
set -g @GHC_SL_COLOR_FG_WIN_NUM         "#4F525A"

## WINDOW_CURRENT
set -g @GHC_SL_COLOR_BG_WIN_CUR_NAME    "default"
set -g @GHC_SL_COLOR_FG_WIN_CUR_NAME    "#696D75"
set -g @GHC_SL_COLOR_BG_WIN_CUR_NUM     "#F07178"
set -g @GHC_SL_COLOR_FG_WIN_CUR_NUM     "#F0F0F0"

