selection_foreground    #D7DAE0
selection_background    #FE8655

background              #1E222A
foreground              #D7DAE0

# normal
color0                  #1E222A
color1                  #E06C75
color2                  #98C379
color3                  #E5C07B
color4                  #61AFEF
color5                  #C678DD
color6                  #56B6C2
color7                  #ABB2BF

# bright
color8                  #42464E
color9                  #E06C75
color10                 #7ECA9C
color11                 #D19A66
color12                 #61AFEF
color13                 #B294BB
color14                 #4EC9B0
color15                 #D7DAE0

cursor                  #B6BDCA
cursor_text_color       #545862
url_color               #61AFEF
