set -gx color_bg0_h           '#FAFAFA'
set -gx color_bg0             '#F4F4F4'
set -gx color_bg0_s           '#DCDFE4'
set -gx color_bg1             '#E5E5E6'
set -gx color_bg2             '#C8CCD4'
set -gx color_bg3             '#B6BDCA'
set -gx color_bg4             '#ABB2BF'

set -gx color_fg              '#353B45'
set -gx color_fg0             '#282828'
set -gx color_fg1             '#353B45'
set -gx color_fg2             '#393F4A'
set -gx color_fg3             '#545862'
set -gx color_fg4             '#565C64'

set -gx color_red             '#D84A3D'
set -gx color_green           '#50A14F'
set -gx color_yellow          '#DEA95F'
set -gx color_blue            '#4078F2'
set -gx color_purple          '#A28DCD'
set -gx color_aqua            '#0B8EC6'
set -gx color_orange          '#F07178'
set -gx color_grey            '#565C64'

set -gx color_neutral_red     '#E06C75'
set -gx color_neutral_green   '#98C379'
set -gx color_neutral_yellow  '#E5C07B'
set -gx color_neutral_blue    '#61AFEF'
set -gx color_neutral_purple  '#C678DD'
set -gx color_neutral_aqua    '#56B6C2'
set -gx color_neutral_orange  '#FF75A0'
set -gx color_neutral_grey    '#DCDFE4'
