set -g @GHC_SL_COLOR_BG_APP_SYM       "#0B8EC6"
set -g @GHC_SL_COLOR_BG_APP_TEXT      "#E5E5E5"
set -g @GHC_SL_COLOR_BG_BAR           "#E5E5E5"
set -g @GHC_SL_COLOR_BG_DATE_SYM      "#0B8EC6"
set -g @GHC_SL_COLOR_BG_DATE_TEXT     "#E5E5E5"
set -g @GHC_SL_COLOR_BG_MESSAGE       "#DEA95F"
set -g @GHC_SL_COLOR_BG_PID_SYM       "#0B8EC6"
set -g @GHC_SL_COLOR_BG_PID_TEXT      "#E5E5E5"
set -g @GHC_SL_COLOR_BG_SESSION       "#50A14F"
set -g @GHC_SL_COLOR_BG_USER          "#4078F2"
set -g @GHC_SL_COLOR_BG_WIN_NAME      "#E5E5E5"
set -g @GHC_SL_COLOR_BG_WIN_NAME_CUR  "#F0F0F0"
set -g @GHC_SL_COLOR_BG_WIN_NUM       "#D3D3D3"
set -g @GHC_SL_COLOR_BG_WIN_NUM_CUR   "#FF6A00"
set -g @GHC_SL_COLOR_BORDER           "#D3D3D3"
set -g @GHC_SL_COLOR_BORDER_CUR       "#FF6A00"
set -g @GHC_SL_COLOR_FG_APP_SYM       "#F0F0F0"
set -g @GHC_SL_COLOR_FG_APP_TEXT      "#696D75"
set -g @GHC_SL_COLOR_FG_DATE_SYM      "#F0F0F0"
set -g @GHC_SL_COLOR_FG_DATE_TEXT     "#696D75"
set -g @GHC_SL_COLOR_FG_MESSAGE       "#F0F0F0"
set -g @GHC_SL_COLOR_FG_PID_SYM       "#F0F0F0"
set -g @GHC_SL_COLOR_FG_PID_TEXT      "#696D75"
set -g @GHC_SL_COLOR_FG_WIN_NAME      "#696D75"
set -g @GHC_SL_COLOR_FG_WIN_NAME_CUR  "#FF6A00"
set -g @GHC_SL_COLOR_FG_WIN_NUM       "#5C5F66"
set -g @GHC_SL_COLOR_FG_WIN_NUM_CUR   "#F0F0F0"
set -g @GHC_SL_COLOR_SESSION          "#F0F0F0"
set -g @GHC_SL_COLOR_USER             "#F0F0F0"
