# one_half_light

# Default colors
selection_foreground    #696D75
selection_background    #FE8655

background              #FAFAFA
foreground              #696D75

# normal
color0                  #FAFAFA
color1                  #D84A3D
color2                  #50A14F
color3                  #DEA95F
color4                  #4078F2
color5                  #A28DCD
color6                  #0B8EC6
color7                  #383A42

# bright
color8                  #B7B7B7
color9                  #E06C75
color10                 #7ECA9C
color11                 #D19A66
color12                 #61AFEF
color13                 #B294BB
color14                 #4EC9B0
color15                 #696D75

cursor                  #4F525A
cursor_text_color       #DCDCDC
url_color               #61AFEF
