# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# onehalf-light

[delta]
hunk-header-style             = raw
hunk-header-decoration-style  = ul
hyperlinks                    = true
hyperlinks-file-link-format   = file://{path}:{line}
detect-dark-light             = auto
line-numbers                  = true
navigate                      = true    # use n and N to move between diff sections
paging                        = never
side-by-side                  = true

light                         = true
true-color                    = always
syntax-theme                  = onehalf-light
plus-emph-style               = syntax "#D4ECCD" bold
plus-non-emph-style           = syntax "#E7EDD9" bold
plus-style                    = syntax "#E7EDD9"
minus-emph-style              = syntax "#FBC8C8" bold
minus-non-emph-style          = syntax "#FBBBBE" bold
minus-style                   = syntax "#FBBBBE"
line-numbers-left-style       = "#767A83"
line-numbers-right-style      = "#767A83"
line-numbers-zero-style       = "#767A83"
line-numbers-minus-style      = "#767A83" "#FBBBBE" bold
line-numbers-plus-style       = "#767A83" "#E7EDD9" bold
whitespace-error-style        = "#767A83"

