# onehalf-light

set -g @GHC_SL_BG                       "default"
set -g @GHC_PSL_BG                      "default"

## Cmdline
set -g @GHC_SL_BG_CMDLINE               "#4EC9B0"
set -g @GHC_SL_FG_CMDLINE               "#F0F0F0"

## Message
set -g @GHC_SL_BG_MESSAGE               "#C18401"
set -g @GHC_SL_FG_MESSAGE               "#F0F0F0"

## Copy Mode
set -g @GHC_SL_BG_COPY_MODE             "#DCDCDC"
set -g @GHC_SL_FG_COPY_MODE             "#696D75"
set -g @GHC_SL_BG_COPY_MODE_MATCH       "#DEA95F"
set -g @GHC_SL_FG_COPY_MODE_MATCH       "#F0F0F0"
set -g @GHC_SL_BG_COPY_MODE_MARK        "#C18401"
set -g @GHC_SL_FG_COPY_MODE_MARK        "#F0F0F0"
set -g @GHC_SL_BG_COPY_MODE_POS         "#DEA95F"
set -g @GHC_SL_FG_COPY_MODE_POS         "#F0F0F0"
set -g @GHC_SL_BG_COPY_MODE_SEL         "#0B8EC6"
set -g @GHC_SL_FG_COPY_MODE_SEL         "#F0F0F0"

## Pane
set -g @GHC_PANE_BG                     "#F0F0F0"
set -g @GHC_PANE_BG_ACTIVE              "#FAFAFA"

set -g @GHC_PSL_FG_BORDER               "#D3D3D3"
set -g @GHC_PSL_FG_BORDER_CUR           "#F07178"

set -g @GHC_PSL_BG_SYM                  "default"
set -g @GHC_PSL_FG_SYM                  "#383A42"
set -g @GHC_PSL_BG_TXT                  "default"
set -g @GHC_PSL_FG_TXT                  "#383A42"

set -g @GHC_PSL_BG_SYM_ACTIVE           "default"
set -g @GHC_PSL_FG_SYM_ACTIVE           "#F07178"
set -g @GHC_PSL_BG_TXT_ACTIVE           "default"
set -g @GHC_PSL_FG_TXT_ACTIVE           "#4F525A"

## Statusbar

set -g @GHC_SL_FG_BORDER                "#D3D3D3"
set -g @GHC_SL_FG_BORDER_CUR            "#F07178"

set -g @GHC_SL_BG_SYM                   "default"
set -g @GHC_SL_FG_SYM                   "#F07178"
set -g @GHC_SL_BG_TXT                   "default"
set -g @GHC_SL_FG_TXT                   "#4F525A"

set -g @GHC_SL_BG_OS_SYM                "#FAFAFA"
set -g @GHC_SL_FG_OS_SYM                "#F07178"

set -g @GHC_SL_BG_PRIMARY_SEP           "#EAEAEA"
set -g @GHC_SL_FG_PRIMARY_SEP           "#F07178"
set -g @GHC_SL_BG_PRIMARY_SYM           "#F07178"
set -g @GHC_SL_FG_PRIMARY_SYM           "#F0F0F0"
set -g @GHC_SL_BG_PRIMARY_TXT           "#F07178"
set -g @GHC_SL_FG_PRIMARY_TXT           "#F0F0F0"
set -g @GHC_SL_BG_SECONDARY_SEP         "default"
set -g @GHC_SL_FG_SECONDARY_SEP         "#EAEAEA"
set -g @GHC_SL_BG_SECONDARY_SYM         "#EAEAEA"
set -g @GHC_SL_FG_SECONDARY_SYM         "#F07178"
set -g @GHC_SL_BG_SECONDARY_TXT         "#EAEAEA"
set -g @GHC_SL_FG_SECONDARY_TXT         "#F07178"

set -g @GHC_SL_BG_WIN_NAME              "#EAEAEA"
set -g @GHC_SL_FG_WIN_NAME              "#4F525A"
set -g @GHC_SL_BG_WIN_NUM               "#DCDCDC"
set -g @GHC_SL_FG_WIN_NUM               "#4F525A"
set -g @GHC_SL_BG_WIN_ICON_LAST         "#DCDCDC"
set -g @GHC_SL_FG_WIN_ICON_LAST         "#FF6A00"

set -g @GHC_SL_BG_WIN_ACTIVE_NAME       "#F07178"
set -g @GHC_SL_FG_WIN_ACTIVE_NAME       "#FAFAFA"
set -g @GHC_SL_BG_WIN_ACTIVE_NUM        "#F07178"
set -g @GHC_SL_FG_WIN_ACTIVE_NUM        "#FAFAFA"

set -g @GHC_SL_BG_WIN_LAST_NAME         "#FF6A00"
set -g @GHC_SL_FG_WIN_LAST_NAME         "#FAFAFA"
set -g @GHC_SL_BG_WIN_LAST_NUM          "#FF6A00"
set -g @GHC_SL_FG_WIN_LAST_NUM          "#FAFAFA"

