# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# onehalf-dark

[delta]
hunk-header-style             = raw
hunk-header-decoration-style  = ul
hyperlinks                    = true
hyperlinks-file-link-format   = file://{path}:{line}
detect-dark-light             = auto
line-numbers                  = true
navigate                      = true    # use n and N to move between diff sections
paging                        = never
side-by-side                  = true

dark                          = true
syntax-theme                  = onehalf-dark
plus-style                    = syntax "#3F483B"
plus-emph-style               = syntax "#32544E" bold
plus-non-emph-style           = syntax "#3F483B" bold
minus-style                   = syntax "#53232A"
minus-emph-style              = syntax "#751C22" bold
minus-non-emph-style          = syntax "#53232A" bold
line-numbers-left-style       = "#D7DAE0"
line-numbers-right-style      = "#D7DAE0"
line-numbers-minus-style      = "#E5E9F0" "#53232A" bold
line-numbers-plus-style       = "#E5E9F0" "#3F483B" bold
true-color                    = always

