# onehalf-light

[bell]
color = "#FF6A00"

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

[colors.cursor]
text              = "#FAFAFA"
cursor            = "#F07178"

[colors.vi_mode_cursor]
text              = "#FAFAFA"
cursor            = "#767A83"

[colors.search.matches]
foreground        = "#FAFAFA"
background        = "#5C5F66"

[colors.search.focused_match]
foreground        = "#FAFAFA"
background        = "#50A14F"

[colors.hints.start]
foreground        = "#FAFAFA"
background        = "#DEA95F"

[colors.hints.end]
foreground        = "#FAFAFA"
background        = "#5C5F66"

[colors.selection]
text              = "#FAFAFA"
background        = "#F07178"

[colors.footer_bar]
foreground        = "#FAFAFA"
background        = "#EAEAEA"

[colors.primary]
background        = "#FAFAFA"
foreground        = "#696D75"
dim_foreground    = "#383A42"
bright_foreground = "#696D75"

[colors.normal]
black             = "#FAFAFA"
red               = "#E45649"
green             = "#50A14F"
yellow            = "#DEA95F"
blue              = "#4078F2"
magenta           = "#A28DCD"
cyan              = "#0B8EC6"
white             = "#383A42"

[colors.bright]
black             = "#B7B7B7"
red               = "#D84A3D"
green             = "#7ECA9C"
yellow            = "#C18401"
blue              = "#4078F2"
magenta           = "#B294BB"
cyan              = "#4EC9B0"
white             = "#5C5F66"

[colors.dim]
black             = "#FAFAFA"
red               = "#E45649"
green             = "#50A14F"
yellow            = "#DEA95F"
blue              = "#4078F2"
magenta           = "#A28DCD"
cyan              = "#0B8EC6"
white             = "#383A42"

[[colors.indexed_colors]]
index = 16
color = "#FF6A00"

[[colors.indexed_colors]]
index = 17
color = "#F07178"
