# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# onehalf-dark

[delta]
dark                          = true
syntax-theme                  = onehalf-dark

side-by-side                  = true
navigate                      = true
paging                        = never
tabs                          = 2
relative-paths                = true
wrap-max-lines                = 0
width                         = -0
line-buffer-size              = 64
line-fill-method              = ansi
max-line-distance             = 0.5
word-diff-regex               = "[a-zA-Z_][a-zA-Z0-9_]*|[0-9]+|."
inline-hint-style             = "#61AFEF"

####################################################################################################

file-style                    = "#D7DAE0" bold
file-decoration-style         = ul

hunk-header-style             = line-number syntax
hunk-header-decoration-style  = ul
hunk-header-line-number-style = "#C8CCD4"

line-numbers                  = true
line-numbers-left-style       = "#C8CCD4" "#1E222A"
line-numbers-right-style      = "#C8CCD4" "#1E222A"
line-numbers-zero-style       = "#C8CCD4" "#1E222A"
line-numbers-minus-style      = "#C8CCD4" "#53232A" bold
line-numbers-plus-style       = "#C8CCD4" "#3F483B" bold

zero-style                    = syntax normal
minus-style                   = syntax "#53232A"
plus-style                    = syntax "#3F483B"
minus-non-emph-style          = syntax "#53232A"
plus-non-emph-style           = syntax "#3F483B"
minus-emph-style              = syntax "#751C22" bold
plus-emph-style               = syntax "#32544E" bold

plus-empty-line-marker-style  = "#3F483B" "#3F483B"
minus-empty-line-marker-style = "#53232A" "#53232A"

####################################################################################################

commit-style                  = "#E5C07B" bold
commit-decoration-style       = none

blame-palette                 = "#1E222A" "#252931" "#3E4451"
blame-format                  = "{author:<12} {commit:<8} {timestamp:<10}"
blame-code-style              = syntax
blame-separator-style         = "#C8CCD4" dim

hyperlinks                    = true
hyperlinks-file-link-format   = file://{path}:{line}

merge-conflict-begin-symbol   = ⟵
merge-conflict-end-symbol     = ⟶

