# onehalf-light

set -g @GHC_SL_BG                       "default"
set -g @GHC_PSL_BG                      "default"

## Cmdline
set -g @GHC_SL_BG_CMDLINE               "#4EC9B0"
set -g @GHC_SL_FG_CMDLINE               "#F0F0F0"

## Message
set -g @GHC_SL_BG_MESSAGE               "#C18401"
set -g @GHC_SL_FG_MESSAGE               "#F0F0F0"

## Mode
set -g @GHC_SL_BG_Mode                  "#DEA95F"
set -g @GHC_SL_FG_Mode                  "#F0F0F0"

## Pane
set -g @GHC_PSL_FG_BORDER               "#D3D3D3"
set -g @GHC_PSL_FG_BORDER_CUR           "#F07178"

set -g @GHC_PSL_BG_SYM                  "default"
set -g @GHC_PSL_FG_SYM                  "#383A42"
set -g @GHC_PSL_BG_TXT                  "default"
set -g @GHC_PSL_FG_TXT                  "#383A42"

set -g @GHC_PSL_BG_SYM_ACTIVE           "default"
set -g @GHC_PSL_FG_SYM_ACTIVE           "#F07178"
set -g @GHC_PSL_BG_TXT_ACTIVE           "default"
set -g @GHC_PSL_FG_TXT_ACTIVE           "#696D75"

## Statusbar

set -g @GHC_SL_FG_BORDER                "#D3D3D3"
set -g @GHC_SL_FG_BORDER_CUR            "#F07178"

set -g @GHC_SL_BG_SYM                   "default"
set -g @GHC_SL_FG_SYM                   "#F07178"
set -g @GHC_SL_BG_TXT                   "default"
set -g @GHC_SL_FG_TXT                   "#4F525A"

set -g @GHC_SL_BG_WIN_NAME              "#EAEAEA"
set -g @GHC_SL_FG_WIN_NAME              "#4F525A"
set -g @GHC_SL_BG_WIN_NUM               "#D3D3D3"
set -g @GHC_SL_FG_WIN_NUM               "#4F525A"

set -g @GHC_SL_BG_WIN_NAME_ACTIVE       "#F07178"
set -g @GHC_SL_FG_WIN_NAME_ACTIVE       "#F0F0F0"
set -g @GHC_SL_BG_WIN_NUM_ACTIVE        "#F07178"
set -g @GHC_SL_FG_WIN_NUM_ACTIVE        "#F0F0F0"

