# onehalf-dark

[delta "customized-theme"]
syntax-theme      = 'OneHalfDark'
dark              = truelight             = true
plus-style        = 'syntax #3F483B'
plus-emph-style   = 'syntax #32544E bold'
minus-style       = 'syntax #53232A'
minus-emph-style  = 'syntax #751C22 bold'
true-color        = always

