# onehalf-dark

set -g @GHC_SL_BG                       "default"
set -g @GHC_PSL_BG                      "default"

## Message
set -g @GHC_SL_BG_MESSAGE               "#E5C07B"
set -g @GHC_SL_FG_MESSAGE               "#1E222A"

## Pane
set -g @GHC_PSL_FG_BORDER               "#565C64"
set -g @GHC_PSL_FG_BORDER_CUR           "#DE8C92"

set -g @GHC_PSL_BG_SYM                  "default"
set -g @GHC_PSL_FG_SYM                  "#ABB2BF"
set -g @GHC_PSL_BG_TXT                  "default"
set -g @GHC_PSL_FG_TXT                  "#ABB2BF"

set -g @GHC_PSL_BG_SYM_ACTIVE           "default"
set -g @GHC_PSL_FG_SYM_ACTIVE           "#DE8C92"
set -g @GHC_PSL_BG_TXT_ACTIVE           "default"
set -g @GHC_PSL_FG_TXT_ACTIVE           "#D7DAE0"

## Statusbar

set -g @GHC_SL_FG_BORDER                "#565C64"
set -g @GHC_SL_FG_BORDER_CUR            "#DE8C92"

set -g @GHC_SL_BG_SYM                   "default"
set -g @GHC_SL_FG_SYM                   "#DE8C92"
set -g @GHC_SL_BG_TXT                   "default"
set -g @GHC_SL_FG_TXT                   "#B6BDCA"

set -g @GHC_SL_BG_WIN_NAME              "#3E4451"
set -g @GHC_SL_FG_WIN_NAME              "#B6BDCA"
set -g @GHC_SL_BG_WIN_NUM               "#565C64"
set -g @GHC_SL_FG_WIN_NUM               "#B6BDCA"

set -g @GHC_SL_BG_WIN_NAME_ACTIVE       "#DE8C92"
set -g @GHC_SL_FG_WIN_NAME_ACTIVE       "#1E222A"
set -g @GHC_SL_BG_WIN_NUM_ACTIVE        "#DE8C92"
set -g @GHC_SL_FG_WIN_NUM_ACTIVE        "#1E222A"

