# onehalf-dark

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

[colors.cursor]
text              = "#1E222A"
cursor            = "#DE8C92"

[colors.vi_mode_cursor]
text              = "#1E222A"
cursor            = "#E5E9F0"

[colors.search.matches]
foreground        = "#1E222A"
background        = "#C8CCD4"

[colors.search.focused_match]
foreground        = "#1E222A"
background        = "#98C379"

[colors.hints.start]
foreground        = "#1E222A"
background        = "#E5C07B"

[colors.hints.end]
foreground        = "#1E222A"
background        = "#C8CCD4"

[colors.selection]
text              = "#1E222A"
background        = "#DE8C92"

[colors.footer_bar]
foreground        = "#1E222A"
background        = "#3E4451"

[colors.primary]
background        = "#1E222A"
foreground        = "#D7DAE0"
dim_foreground    = "#ABB2BF"
bright_foreground = "#D7DAE0"

[colors.normal]
black             = "#1E222A"
red               = "#E06C75"
green             = "#98C379"
yellow            = "#E5C07B"
blue              = "#61AFEF"
magenta           = "#C678DD"
cyan              = "#56B6C2"
white             = "#ABB2BF"

[colors.bright]
black             = "#42464E"
red               = "#E06C75"
green             = "#7ECA9C"
yellow            = "#D19A66"
blue              = "#61AFEF"
magenta           = "#B294BB"
cyan              = "#4EC9B0"
white             = "#C8CCD4"

[colors.dim]
black             = "#1E222A"
red               = "#E06C75"
green             = "#98C379"
yellow            = "#E5C07B"
blue              = "#61AFEF"
magenta           = "#C678DD"
cyan              = "#56B6C2"
white             = "#ABB2BF"

[[colors.indexed_colors]]
index = 16
color = "#D75F00"

[[colors.indexed_colors]]
index = 17
color = "#DE8C92"
