# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# rosepine-moon

[delta]
dark                          = true
syntax-theme                  = rosepine-moon

side-by-side                  = true
navigate                      = true
paging                        = never
tabs                          = 2
relative-paths                = true
wrap-max-lines                = 0
width                         = -0
line-buffer-size              = 64
line-fill-method              = ansi
max-line-distance             = 0.5
word-diff-regex               = "[a-zA-Z_][a-zA-Z0-9_]*|[0-9]+|."
inline-hint-style             = "#3E8FB0"

####################################################################################################

file-style                    = "#E0DEF4" bold
file-decoration-style         = ul

hunk-header-style             = line-number syntax
hunk-header-decoration-style  = ul
hunk-header-line-number-style = "#908CAA"

line-numbers                  = true
line-numbers-left-style       = "#908CAA" "#232136"
line-numbers-right-style      = "#908CAA" "#232136"
line-numbers-zero-style       = "#908CAA" "#232136"
line-numbers-minus-style      = "#908CAA" "#362436" bold
line-numbers-plus-style       = "#908CAA" "#2A3645" bold

zero-style                    = syntax normal
minus-style                   = syntax "#362436"
plus-style                    = syntax "#2A3645"
minus-non-emph-style          = syntax "#362436"
plus-non-emph-style           = syntax "#2A3645"
minus-emph-style              = syntax "#442430" bold
plus-emph-style               = syntax "#254055" bold

plus-empty-line-marker-style  = "#2A3645" "#2A3645"
minus-empty-line-marker-style = "#362436" "#362436"

####################################################################################################

commit-style                  = "#F6C177" bold
commit-decoration-style       = none

blame-palette                 = "#232136" "#2A273F" "#393552"
blame-format                  = "{author:<12} {commit:<8} {timestamp:<10}"
blame-code-style              = syntax
blame-separator-style         = "#908CAA" dim

hyperlinks                    = true
hyperlinks-file-link-format   = file://{path}:{line}

merge-conflict-begin-symbol   = ⟵
merge-conflict-end-symbol     = ⟶

