# rosepine-dawn

set -g @GHC_SL_BG                       "default"
set -g @GHC_PSL_BG                      "default"

## Cmdline
set -g @GHC_SL_BG_CMDLINE               "#56949F"
set -g @GHC_SL_FG_CMDLINE               "#FFFAF3"

## Message
set -g @GHC_SL_BG_MESSAGE               "#EA9D34"
set -g @GHC_SL_FG_MESSAGE               "#FFFAF3"

## Copy Mode
set -g @GHC_SL_BG_COPY_MODE             "#DFDAD9"
set -g @GHC_SL_FG_COPY_MODE             "#464261"
set -g @GHC_SL_BG_COPY_MODE_MATCH       "#EA9D34"
set -g @GHC_SL_FG_COPY_MODE_MATCH       "#FFFAF3"
set -g @GHC_SL_BG_COPY_MODE_MARK        "#EA9D34"
set -g @GHC_SL_FG_COPY_MODE_MARK        "#FFFAF3"
set -g @GHC_SL_BG_COPY_MODE_POS         "#EA9D34"
set -g @GHC_SL_FG_COPY_MODE_POS         "#FFFAF3"
set -g @GHC_SL_BG_COPY_MODE_SEL         "#56949F"
set -g @GHC_SL_FG_COPY_MODE_SEL         "#FFFAF3"

## Pane
set -g @GHC_PANE_BG                     "#FFFAF3"
set -g @GHC_PANE_BG_ACTIVE              "#FAF4ED"

set -g @GHC_PSL_FG_BORDER               "#CECACD"
set -g @GHC_PSL_FG_BORDER_CUR           "#B4637A"

set -g @GHC_PSL_BG_SYM                  "default"
set -g @GHC_PSL_FG_SYM                  "#9893A5"
set -g @GHC_PSL_BG_TXT                  "default"
set -g @GHC_PSL_FG_TXT                  "#9893A5"

set -g @GHC_PSL_BG_SYM_ACTIVE           "default"
set -g @GHC_PSL_FG_SYM_ACTIVE           "#B4637A"
set -g @GHC_PSL_BG_TXT_ACTIVE           "default"
set -g @GHC_PSL_FG_TXT_ACTIVE           "#9893A5"

## Statusbar

set -g @GHC_SL_FG_BORDER                "#CECACD"
set -g @GHC_SL_FG_BORDER_CUR            "#B4637A"

set -g @GHC_SL_BG_SYM                   "default"
set -g @GHC_SL_FG_SYM                   "#B4637A"
set -g @GHC_SL_BG_TXT                   "default"
set -g @GHC_SL_FG_TXT                   "#9893A5"

set -g @GHC_SL_BG_OS_SYM                "#FAF4ED"
set -g @GHC_SL_FG_OS_SYM                "#B4637A"

set -g @GHC_SL_BG_PRIMARY_SEP           "#F2E9E1"
set -g @GHC_SL_FG_PRIMARY_SEP           "#B4637A"
set -g @GHC_SL_BG_PRIMARY_SYM           "#B4637A"
set -g @GHC_SL_FG_PRIMARY_SYM           "#FFFAF3"
set -g @GHC_SL_BG_PRIMARY_TXT           "#B4637A"
set -g @GHC_SL_FG_PRIMARY_TXT           "#FFFAF3"
set -g @GHC_SL_BG_SECONDARY_SEP         "default"
set -g @GHC_SL_FG_SECONDARY_SEP         "#F2E9E1"
set -g @GHC_SL_BG_SECONDARY_SYM         "#F2E9E1"
set -g @GHC_SL_FG_SECONDARY_SYM         "#B4637A"
set -g @GHC_SL_BG_SECONDARY_TXT         "#F2E9E1"
set -g @GHC_SL_FG_SECONDARY_TXT         "#B4637A"

set -g @GHC_SL_BG_WIN_NAME              "#F2E9E1"
set -g @GHC_SL_FG_WIN_NAME              "#9893A5"
set -g @GHC_SL_BG_WIN_NUM               "#DFDAD9"
set -g @GHC_SL_FG_WIN_NUM               "#9893A5"
set -g @GHC_SL_BG_WIN_ICON_BELL         "#DFDAD9"
set -g @GHC_SL_FG_WIN_ICON_BELL         "#D7827E"
set -g @GHC_SL_BG_WIN_ICON_LAST         "#DFDAD9"
set -g @GHC_SL_FG_WIN_ICON_LAST         "#D7827E"
set -g @GHC_SL_BG_WIN_ICON_ZOOM         "#DFDAD9"
set -g @GHC_SL_FG_WIN_ICON_ZOOM         "#286983"

set -g @GHC_SL_BG_WIN_ACTIVE_NAME       "#B4637A"
set -g @GHC_SL_FG_WIN_ACTIVE_NAME       "#FAF4ED"
set -g @GHC_SL_BG_WIN_ACTIVE_NUM        "#B4637A"
set -g @GHC_SL_FG_WIN_ACTIVE_NUM        "#FAF4ED"
set -g @GHC_SL_BG_WIN_ACTIVE_ICON_BELL  "#B4637A"
set -g @GHC_SL_FG_WIN_ACTIVE_ICON_BELL  "#FAF4ED"
set -g @GHC_SL_BG_WIN_ACTIVE_ICON_ZOOM  "#B4637A"
set -g @GHC_SL_FG_WIN_ACTIVE_ICON_ZOOM  "#FAF4ED"

set -g @GHC_SL_BG_WIN_LAST_NAME         "#F2E9E1"
set -g @GHC_SL_FG_WIN_LAST_NAME         "#D7827E"
set -g @GHC_SL_BG_WIN_LAST_NUM          "#DFDAD9"
set -g @GHC_SL_FG_WIN_LAST_NUM          "#D7827E"
set -g @GHC_SL_BG_WIN_LAST_ICON_BELL    "#DFDAD9"
set -g @GHC_SL_FG_WIN_LAST_ICON_BELL    "#D7827E"
set -g @GHC_SL_BG_WIN_LAST_ICON_ZOOM    "#DFDAD9"
set -g @GHC_SL_FG_WIN_LAST_ICON_ZOOM    "#D7827E"

