# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# rosepine-dawn

[delta "rosepine-dawn"]
light                         = true
syntax-theme                  = rosepine-dawn

inline-hint-style             = "#235965"

####################################################################################################

file-style                    = "#2C283B" bold

hunk-header-line-number-style = "#545064"

line-numbers-minus-style      = "#8A344D" normal bold
line-numbers-plus-style       = "#205569" normal bold

minus-style                   = syntax "#F5E7E5"
plus-style                    = syntax "#E4ECE7"
minus-non-emph-style          = syntax "#F5E7E5"
plus-non-emph-style           = syntax "#E4ECE7"
minus-emph-style              = "#2C283B" "#E4C9CB" bold
plus-emph-style               = "#2C283B" "#CBDDD6" bold

plus-empty-line-marker-style  = "#E4ECE7" "#E4ECE7"
minus-empty-line-marker-style = "#F5E7E5" "#F5E7E5"

####################################################################################################

commit-style                  = "#714A12" bold

blame-palette                 = "#FAF4ED" "#FFFAF3" "#F2E9E1"
blame-separator-style         = "#545064" dim
