# rose-pine-moon

# Primary colors
background              #232136
foreground              #E0DEF4

# Border colors
active_border_color     #C4A7E7
inactive_border_color   #908CAA

# Cursor colors
cursor                  #EB6F92
cursor_text_color       #2A273F

# Selection colors
selection_background    #F6C177
selection_foreground    #2A273F

# Tab bar colors
active_tab_background   #232136
active_tab_foreground   #C4A7E7
inactive_tab_background #95B1AC
inactive_tab_foreground #3E8FB0
tab_bar_background      #95B1AC

# Url colors
url_color               #3E8FB0

# Normal colors
color0                  #232136
color1                  #EB6F92
color2                  #95B1AC
color3                  #F6C177
color4                  #3E8FB0
color5                  #C4A7E7
color6                  #9CCFD8
color7                  #6E6A86

# Bright colors
color8                  #908CAA
color9                  #EB6F92
color10                 #95B1AC
color11                 #F6C177
color12                 #3E8FB0
color13                 #C4A7E7
color14                 #9CCFD8
color15                 #E0DEF4
