# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# rosepine-dawn

[delta]
light                         = true
syntax-theme                  = rosepine-dawn

side-by-side                  = true
navigate                      = true
paging                        = never
tabs                          = 2
relative-paths                = true
wrap-max-lines                = 2
width                         = -0
line-buffer-size              = 64
line-fill-method              = ansi
max-line-distance             = 0.5
word-diff-regex               = "[a-zA-Z_][a-zA-Z0-9_]*|[0-9]+|."
inline-hint-style             = "#286983"

####################################################################################################

file-style                    = "#464261" bold
file-decoration-style         = ul

hunk-header-style             = line-number syntax
hunk-header-decoration-style  = ul
hunk-header-line-number-style = "#797593"

line-numbers                  = true
line-numbers-left-style       = normal normal
line-numbers-right-style      = normal normal
line-numbers-zero-style       = normal normal
line-numbers-minus-style      = "#B4637A" normal bold
line-numbers-plus-style       = "#6D8F89" normal bold

zero-style                    = syntax normal
minus-style                   = syntax "#F5D8E0"
plus-style                    = syntax "#E4EBE4"
minus-non-emph-style          = syntax "#F5D8E0"
plus-non-emph-style           = syntax "#E4EBE4"
minus-emph-style              = syntax "#F0C6D2" bold
plus-emph-style               = syntax "#D5E0D5" bold

plus-empty-line-marker-style  = "#E4EBE4" "#E4EBE4"
minus-empty-line-marker-style = "#F5D8E0" "#F5D8E0"

####################################################################################################

commit-style                  = "#EA9D34" bold
commit-decoration-style       = none

blame-palette                 = "#FAF4ED" "#FFFAF3" "#F2E9E1"
blame-format                  = "{author:<12} {commit:<8} {timestamp:<10}"
blame-code-style              = syntax
blame-separator-style         = "#797593" dim

hyperlinks                    = true
hyperlinks-file-link-format   = file://{path}:{line}

merge-conflict-begin-symbol   = ⟵
merge-conflict-end-symbol     = ⟶

