# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# rosepine-main

[delta]
hunk-header-style             = raw
hunk-header-decoration-style  = ul
hyperlinks                    = true
hyperlinks-file-link-format   = file://{path}:{line}
detect-dark-light             = auto
line-numbers                  = true
navigate                      = true    # use n and N to move between diff sections
paging                        = never
side-by-side                  = true

dark                          = true
syntax-theme                  = rosepine-main
plus-style                    = syntax "#2A3440"
plus-emph-style               = syntax "#25404F" bold
plus-non-emph-style           = syntax auto
minus-style                   = syntax "#362434"
minus-emph-style              = syntax "#44242E" bold
minus-non-emph-style          = syntax auto
true-color                    = always

