# rosepine-main

[delta "customized-theme"]

dark              = truelight             = true
plus-style        = 'syntax #2A3440'
plus-emph-style   = 'syntax #25404F bold'
minus-style       = 'syntax #362434'
minus-emph-style  = 'syntax #44242E bold'
true-color        = always

