# rosepine-dawn

# Primary colors
background              #FAF4ED
foreground              #2C283B
selection_background    #DFDAD9
selection_foreground    #2C283B

# Cursor colors
cursor                  #853C3A
cursor_text_color       #FAF4ED

# URL underline color when hovering with mouse
url_color               #634873

# Border colors
active_border_color     #853C3A
inactive_border_color   #DFDAD9
bell_border_color       #714A12

# Tab bar colors
active_tab_foreground   #853C3A
active_tab_background   #F2E9E1
inactive_tab_foreground #545064
inactive_tab_background #FAF4ED
tab_bar_background      #FFFAF3

# Colors for marks (marked text in the terminal)
mark1_foreground        #FAF4ED
mark1_background        #853C3A
mark2_foreground        #FAF4ED
mark2_background        #634873
mark3_foreground        #FAF4ED
mark3_background        #235965

# Normal colors
color0                  #F2E9E1
color1                  #B4637A
color2                  #286983
color3                  #EA9D34
color4                  #56949F
color5                  #907AA9
color6                  #D7827E
color7                  #575279

# Bright colors
color8                  #9893A5
color9                  #B4637A
color10                 #286983
color11                 #EA9D34
color12                 #56949F
color13                 #907AA9
color14                 #D7827E
color15                 #575279
