# rosepine-main

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

[colors.cursor]
cursor            = "#EB6F92"
text              = "#1F1D2E"

[colors.vi_mode_cursor]
cursor            = "#EB6F92"
text              = "#1F1D2E"

[colors.search.matches]
background        = "#F6C177"
foreground        = "#1F1D2E"

[colors.search.focused_match]
background        = "#F6C177"
foreground        = "#1F1D2E"

[colors.selection]
background        = "#EBBCBA"
text              = "#1F1D2E"

[colors.footer_bar]
background        = "#26233A"
foreground        = "#E0DEF4"

[colors.primary]
background        = "#191724"
foreground        = "#E0DEF4"
dim_foreground    = "#E0DEF4"
bright_foreground = "#E0DEF4"

[colors.normal]
black             = "#191724"
blue              = "#31748F"
cyan              = "#9CCFD8"
green             = "#95B1AC"
magenta           = "#C4A7E7"
red               = "#EB6F92"
yellow            = "#F6C177"
white             = "#6E6A86"

[colors.bright]
black             = "#908CAA"
blue              = "#31748F"
cyan              = "#9CCFD8"
green             = "#95B1AC"
magenta           = "#C4A7E7"
red               = "#EB6F92"
yellow            = "#F6C177"
white             = "#E0DEF4"

[colors.dim]
black             = "#191724"
blue              = "#31748F"
cyan              = "#9CCFD8"
green             = "#95B1AC"
magenta           = "#C4A7E7"
red               = "#EB6F92"
yellow            = "#F6C177"
white             = "#6E6A86"

