##  rose-pine-main

# Basic
set -g @GHC_SL_COLOR_BG                 "default"

## MESSAGE
set -g @GHC_SL_COLOR_BG_MESSAGE         "#F6C177"
set -g @GHC_SL_COLOR_FG_MESSAGE         "#191724"

## BORDER
set -g @GHC_SL_COLOR_BORDER             "#524F67"
set -g @GHC_SL_COLOR_BORDER_CUR         "#EB6F92"

# Component

## APP
set -g @GHC_SL_COLOR_BG_APP_SYM         "#191724"
set -g @GHC_SL_COLOR_FG_APP_SYM         "#EB6F92"
set -g @GHC_SL_COLOR_BG_APP_TEXT        "#191724"
set -g @GHC_SL_COLOR_FG_APP_TEXT        "#6E6A86"

## CPU
set -g @GHC_SL_COLOR_BG_CPU_SYM         "#191724"
set -g @GHC_SL_COLOR_FG_CPU_SYM         "#EB6F92"
set -g @GHC_SL_COLOR_BG_CPU_TEXT        "#191724"
set -g @GHC_SL_COLOR_FG_CPU_TEXT        "#6E6A86"

## HOST
set -g @GHC_SL_COLOR_BG_HOST_SYM        "#191724"
set -g @GHC_SL_COLOR_FG_HOST_SYM        "#EB6F92"
set -g @GHC_SL_COLOR_BG_HOST_TEXT       "#191724"
set -g @GHC_SL_COLOR_FG_HOST_TEXT       "#6E6A86"

## NETWORK
set -g @GHC_SL_COLOR_BG_NET_SYM         "#191724"
set -g @GHC_SL_COLOR_FG_NET_SYM         "#EB6F92"
set -g @GHC_SL_COLOR_BG_NET_TEXT        "#191724"
set -g @GHC_SL_COLOR_FG_NET_TEXT        "#6E6A86"

## PID
set -g @GHC_SL_COLOR_BG_PID_SYM         "#191724"
set -g @GHC_SL_COLOR_FG_PID_SYM         "#EB6F92"
set -g @GHC_SL_COLOR_BG_PID_TEXT        "#191724"
set -g @GHC_SL_COLOR_FG_PID_TEXT        "#6E6A86"

## TIME
set -g @GHC_SL_COLOR_BG_TIME_SYM        "#191724"
set -g @GHC_SL_COLOR_FG_TIME_SYM        "#EB6F92"
set -g @GHC_SL_COLOR_BG_TIME_TEXT       "#191724"
set -g @GHC_SL_COLOR_FG_TIME_TEXT       "#6E6A86"

## DATE
set -g @GHC_SL_COLOR_BG_DATE_SYM        "#191724"
set -g @GHC_SL_COLOR_FG_DATE_SYM        "#EB6F92"
set -g @GHC_SL_COLOR_BG_DATE_TEXT       "#191724"
set -g @GHC_SL_COLOR_FG_DATE_TEXT       "#6E6A86"

## SESSION
set -g @GHC_SL_COLOR_BG_SESSION_SYM     "#191724"
set -g @GHC_SL_COLOR_FG_SESSION_SYM     "#EB6F92"
set -g @GHC_SL_COLOR_BG_SESSION_TEXT    "#191724"
set -g @GHC_SL_COLOR_FG_SESSION_TEXT    "#6E6A86"

## USER
set -g @GHC_SL_COLOR_BG_USER_SEP        "#191724"
set -g @GHC_SL_COLOR_FG_USER_SEP        "#6E6A86"
set -g @GHC_SL_COLOR_BG_USER_TEXT       "#191724"
set -g @GHC_SL_COLOR_FG_USER_TEXT       "#6E6A86"

## WINDOW
set -g @GHC_SL_COLOR_BG_WIN_NAME        "#26233A"
set -g @GHC_SL_COLOR_FG_WIN_NAME        "#6E6A86"
set -g @GHC_SL_COLOR_BG_WIN_NUM         "#524F67"
set -g @GHC_SL_COLOR_FG_WIN_NUM         "#6E6A86"

## WINDOW_CURRENT
set -g @GHC_SL_COLOR_BG_WIN_CUR_NAME    "#EB6F92"
set -g @GHC_SL_COLOR_FG_WIN_CUR_NAME    "#191724"

