# rosepine-moon

[delta "customized-theme"]

dark              = truelight             = true
plus-style        = 'syntax #2A3645'
plus-emph-style   = 'syntax #254055 bold'
minus-style       = 'syntax #362436'
minus-emph-style  = 'syntax #442430 bold'
true-color        = always

