# rosepine-dawn

[bell]
color = "#8A344D"

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

[colors.cursor]
text              = "#FAF4ED"
cursor            = "#853C3A"

[colors.vi_mode_cursor]
text              = "#FAF4ED"
cursor            = "#634873"

[colors.search.matches]
foreground        = "#2C283B"
background        = "#F2E9E1"

[colors.search.focused_match]
foreground        = "#FAF4ED"
background        = "#714A12"

[colors.hints.start]
foreground        = "#FAF4ED"
background        = "#235965"

[colors.hints.end]
foreground        = "#2C283B"
background        = "#F2E9E1"

[colors.selection]
text              = "#2C283B"
background        = "#DFDAD9"

[colors.footer_bar]
foreground        = "#2C283B"
background        = "#FFFAF3"

[colors.primary]
background        = "#FAF4ED"
foreground        = "#2C283B"
dim_foreground    = "#545064"
bright_foreground = "#2C283B"

[colors.normal]
black             = "#F2E9E1"
red               = "#B4637A"
green             = "#286983"
yellow            = "#EA9D34"
blue              = "#56949F"
magenta           = "#907AA9"
cyan              = "#D7827E"
white             = "#575279"

[colors.bright]
black             = "#9893A5"
red               = "#B4637A"
green             = "#286983"
yellow            = "#EA9D34"
blue              = "#56949F"
magenta           = "#907AA9"
cyan              = "#D7827E"
white             = "#575279"

[colors.dim]
black             = "#9893A5"
red               = "#B4637A"
green             = "#286983"
yellow            = "#EA9D34"
blue              = "#56949F"
magenta           = "#907AA9"
cyan              = "#D7827E"
white             = "#575279"

[[colors.indexed_colors]]
index = 16
color = "#853C3A"

[[colors.indexed_colors]]
index = 17
color = "#8A344D"
