# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# rosepine-main

[delta]
hunk-header-style             = raw
hunk-header-decoration-style  = ul
hyperlinks                    = true
hyperlinks-file-link-format   = file://{path}:{line}
detect-dark-light             = auto
line-numbers                  = true
navigate                      = true    # use n and N to move between diff sections
paging                        = never
side-by-side                  = true

dark                          = true
true-color                    = always
syntax-theme                  = rosepine-main
plus-emph-style               = syntax "#25404F" bold
plus-non-emph-style           = syntax "#2A3440" bold
plus-style                    = syntax "#2A3440"
minus-emph-style              = syntax "#44242E" bold
minus-non-emph-style          = syntax "#362434" bold
minus-style                   = syntax "#362434"
line-numbers-left-style       = "#E0DEF4"
line-numbers-right-style      = "#E0DEF4"
line-numbers-zero-style       = "#E0DEF4"
line-numbers-minus-style      = "#E0DEF4" "#362434" bold
line-numbers-plus-style       = "#E0DEF4" "#2A3440" bold
whitespace-error-style        = "#E0DEF4"

