# rosepine-dawn

set -g @GHC_SL_BG                       "default"
set -g @GHC_PSL_BG                      "default"

## Message
set -g @GHC_SL_BG_MESSAGE               "#EA9D34"
set -g @GHC_SL_FG_MESSAGE               "#FAF4ED"

## Pane
set -g @GHC_PSL_FG_BORDER               "#CECACD"
set -g @GHC_PSL_FG_BORDER_CUR           "#B4637A"

set -g @GHC_PSL_BG_SYM                  "default"
set -g @GHC_PSL_FG_SYM                  "#9893A5"
set -g @GHC_PSL_BG_TXT                  "default"
set -g @GHC_PSL_FG_TXT                  "#9893A5"

set -g @GHC_PSL_BG_SYM_ACTIVE           "default"
set -g @GHC_PSL_FG_SYM_ACTIVE           "#B4637A"
set -g @GHC_PSL_BG_TXT_ACTIVE           "default"
set -g @GHC_PSL_FG_TXT_ACTIVE           "#9893A5"

## Statusbar

set -g @GHC_SL_FG_BORDER                "#CECACD"
set -g @GHC_SL_FG_BORDER_CUR            "#B4637A"

set -g @GHC_SL_BG_SYM                   "default"
set -g @GHC_SL_FG_SYM                   "#B4637A"
set -g @GHC_SL_BG_TXT                   "default"
set -g @GHC_SL_FG_TXT                   "#9893A5"

set -g @GHC_SL_BG_WIN_NAME              "#F2E9E1"
set -g @GHC_SL_FG_WIN_NAME              "#9893A5"
set -g @GHC_SL_BG_WIN_NUM               "#CECACD"
set -g @GHC_SL_FG_WIN_NUM               "#9893A5"

set -g @GHC_SL_BG_WIN_NAME_ACTIVE       "#B4637A"
set -g @GHC_SL_FG_WIN_NAME_ACTIVE       "#FAF4ED"
set -g @GHC_SL_BG_WIN_NUM_ACTIVE        "#B4637A"
set -g @GHC_SL_FG_WIN_NUM_ACTIVE        "#FAF4ED"

