# rosepine-moon

# Primary colors
background              #232136
foreground              #E0DEF4
selection_background    #44415A
selection_foreground    #E0DEF4

# Cursor colors
cursor                  #56526E
cursor_text_color       #E0DEF4

# URL underline color when hovering with mouse
url_color               #C4A7E7

# Border colors
active_border_color     #3E8FB0
inactive_border_color   #44415A
bell_border_color       #F6C177

# Tab bar colors
active_tab_foreground   #E0DEF4
active_tab_background   #393552
inactive_tab_foreground #6E6A86
inactive_tab_background #232136
tab_bar_background      #2A273F

# Colors for marks (marked text in the terminal)
mark1_foreground        #232136
mark1_background        #EA9A97
mark2_foreground        #232136
mark2_background        #C4A7E7
mark3_foreground        #232136
mark3_background        #9CCFD8

# Normal colors
color0                  #393552
color1                  #EB6F92
color2                  #3E8FB0
color3                  #F6C177
color4                  #9CCFD8
color5                  #C4A7E7
color6                  #EA9A97
color7                  #E0DEF4

# Bright colors
color8                  #6E6A86
color9                  #EB6F92
color10                 #3E8FB0
color11                 #F6C177
color12                 #9CCFD8
color13                 #C4A7E7
color14                 #EA9A97
color15                 #E0DEF4
