# rosepine-moon

[bell]
color = "#EA9A97"

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

[colors.cursor]
text              = "#232136"
cursor            = "#EB6F92"

[colors.vi_mode_cursor]
text              = "#232136"
cursor            = "#E0DEF4"

[colors.search.matches]
foreground        = "#232136"
background        = "#908CAA"

[colors.search.focused_match]
foreground        = "#232136"
background        = "#3E8FB0"

[colors.hints.start]
foreground        = "#232136"
background        = "#F6C177"

[colors.hints.end]
foreground        = "#232136"
background        = "#908CAA"

[colors.selection]
text              = "#232136"
background        = "#EB6F92"

[colors.footer_bar]
foreground        = "#232136"
background        = "#393552"

[colors.primary]
background        = "#232136"
foreground        = "#E0DEF4"
dim_foreground    = "#6E6A86"
bright_foreground = "#E0DEF4"

[colors.normal]
black             = "#232136"
red               = "#EB6F92"
green             = "#3E8FB0"
yellow            = "#F6C177"
blue              = "#9CCFD8"
magenta           = "#C4A7E7"
cyan              = "#EA9A97"
white             = "#6E6A86"

[colors.bright]
black             = "#6E6A86"
red               = "#EB6F92"
green             = "#3E8FB0"
yellow            = "#F6C177"
blue              = "#9CCFD8"
magenta           = "#C4A7E7"
cyan              = "#EA9A97"
white             = "#908CAA"

[colors.dim]
black             = "#232136"
red               = "#EB6F92"
green             = "#3E8FB0"
yellow            = "#F6C177"
blue              = "#9CCFD8"
magenta           = "#C4A7E7"
cyan              = "#EA9A97"
white             = "#6E6A86"

[[colors.indexed_colors]]
index = 16
color = "#EA9A97"

[[colors.indexed_colors]]
index = 17
color = "#EB6F92"
