# rosepine-dawn

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

[colors.cursor]
cursor            = "#B4637A"
text              = "#FFFAF3"

[colors.vi_mode_cursor]
cursor            = "#B4637A"
text              = "#FFFAF3"

[colors.search.matches]
background        = "#EA9D34"
foreground        = "#FFFAF3"

[colors.search.focused_match]
background        = "#EA9D34"
foreground        = "#FFFAF3"

[colors.selection]
background        = "#D7827E"
text              = "#FFFAF3"

[colors.footer_bar]
background        = "#F2E9E1"
foreground        = "#464261"

[colors.primary]
background        = "#FAF4ED"
foreground        = "#464261"
dim_foreground    = "#464261"
bright_foreground = "#464261"

[colors.normal]
black             = "#FAF4ED"
blue              = "#286983"
cyan              = "#56949F"
green             = "#6D8F89"
magenta           = "#907AA9"
red               = "#B4637A"
yellow            = "#EA9D34"
white             = "#9893A5"

[colors.bright]
black             = "#9893A5"
blue              = "#286983"
cyan              = "#56949F"
green             = "#6D8F89"
magenta           = "#907AA9"
red               = "#D7827E"
yellow            = "#EA9D34"
white             = "#464261"

[colors.dim]
black             = "#FAF4ED"
blue              = "#286983"
cyan              = "#56949F"
green             = "#6D8F89"
magenta           = "#907AA9"
red               = "#B4637A"
yellow            = "#EA9D34"
white             = "#9893A5"

