# rosepine-moon

set -g @GHC_SL_BG                       "default"
set -g @GHC_PSL_BG                      "default"

## Message
set -g @GHC_SL_BG_MESSAGE               "#F6C177"
set -g @GHC_SL_FG_MESSAGE               "#232136"

## Pane
set -g @GHC_PSL_FG_BORDER               "#56526E"
set -g @GHC_PSL_FG_BORDER_CUR           "#EB6F92"

set -g @GHC_PSL_BG_SYM                  "default"
set -g @GHC_PSL_FG_SYM                  "#6E6A86"
set -g @GHC_PSL_BG_TXT                  "default"
set -g @GHC_PSL_FG_TXT                  "#6E6A86"

set -g @GHC_PSL_BG_SYM_ACTIVE           "default"
set -g @GHC_PSL_FG_SYM_ACTIVE           "#EB6F92"
set -g @GHC_PSL_BG_TXT_ACTIVE           "default"
set -g @GHC_PSL_FG_TXT_ACTIVE           "#6E6A86"

## Statusbar

set -g @GHC_SL_FG_BORDER                "#56526E"
set -g @GHC_SL_FG_BORDER_CUR            "#EB6F92"

set -g @GHC_SL_BG_SYM                   "default"
set -g @GHC_SL_FG_SYM                   "#EB6F92"
set -g @GHC_SL_BG_TXT                   "default"
set -g @GHC_SL_FG_TXT                   "#6E6A86"

set -g @GHC_SL_BG_WIN_NAME              "#393552"
set -g @GHC_SL_FG_WIN_NAME              "#6E6A86"
set -g @GHC_SL_BG_WIN_NUM               "#56526E"
set -g @GHC_SL_FG_WIN_NUM               "#6E6A86"

set -g @GHC_SL_BG_WIN_NAME_ACTIVE       "#EB6F92"
set -g @GHC_SL_FG_WIN_NAME_ACTIVE       "#232136"
set -g @GHC_SL_BG_WIN_NUM_ACTIVE        "#EB6F92"
set -g @GHC_SL_FG_WIN_NUM_ACTIVE        "#232136"

