##  rose-pine-dawn

# Basic
set -g @GHC_SL_COLOR_BG                 "default"

## MESSAGE
set -g @GHC_SL_COLOR_BG_MESSAGE         "#EA9D34"
set -g @GHC_SL_COLOR_FG_MESSAGE         "#FAF4ED"

## BORDER
set -g @GHC_SL_COLOR_BORDER             "#CECACD"
set -g @GHC_SL_COLOR_BORDER_CUR         "#907AA9"

# Component

## APP
set -g @GHC_SL_COLOR_BG_APP_SYM         "#286983"
set -g @GHC_SL_COLOR_FG_APP_SYM         "#FAF4ED"
set -g @GHC_SL_COLOR_BG_APP_TEXT        "#FAF4ED"
set -g @GHC_SL_COLOR_FG_APP_TEXT        "#9893A5"

## CPU
set -g @GHC_SL_COLOR_BG_CPU_SYM         "#286983"
set -g @GHC_SL_COLOR_FG_CPU_SYM         "#FAF4ED"
set -g @GHC_SL_COLOR_BG_CPU_TEXT        "#FAF4ED"
set -g @GHC_SL_COLOR_FG_CPU_TEXT        "#9893A5"

## HOST
set -g @GHC_SL_COLOR_BG_HOST_SYM        "#B4637A"
set -g @GHC_SL_COLOR_BG_HOST_TEXT       "#FAF4ED"
set -g @GHC_SL_COLOR_FG_HOST_SYM        "#FAF4ED"
set -g @GHC_SL_COLOR_FG_HOST_TEXT       "#B4637A"

## NETWORK
set -g @GHC_SL_COLOR_BG_NET_SYM         "#286983"
set -g @GHC_SL_COLOR_FG_NET_SYM         "#FAF4ED"
set -g @GHC_SL_COLOR_BG_NET_TEXT        "#FAF4ED"
set -g @GHC_SL_COLOR_FG_NET_TEXT        "#9893A5"

## PID
set -g @GHC_SL_COLOR_BG_PID_SYM         "#286983"
set -g @GHC_SL_COLOR_FG_PID_SYM         "#FAF4ED"
set -g @GHC_SL_COLOR_BG_PID_TEXT        "#FAF4ED"
set -g @GHC_SL_COLOR_FG_PID_TEXT        "#9893A5"

## TIME
set -g @GHC_SL_COLOR_BG_TIME_SYM        "#286983"
set -g @GHC_SL_COLOR_FG_TIME_SYM        "#FAF4ED"
set -g @GHC_SL_COLOR_BG_TIME_TEXT       "#FAF4ED"
set -g @GHC_SL_COLOR_FG_TIME_TEXT       "#9893A5"

## DATE
set -g @GHC_SL_COLOR_BG_DATE_SYM        "#286983"
set -g @GHC_SL_COLOR_FG_DATE_SYM        "#FAF4ED"
set -g @GHC_SL_COLOR_BG_DATE_TEXT       "#FAF4ED"
set -g @GHC_SL_COLOR_FG_DATE_TEXT       "#9893A5"

## SESSION
set -g @GHC_SL_COLOR_BG_SESSION_SYM     "#6D8F89"
set -g @GHC_SL_COLOR_FG_SESSION_SYM     "#FAF4ED"
set -g @GHC_SL_COLOR_BG_SESSION_TEXT    "#FAF4ED"
set -g @GHC_SL_COLOR_FG_SESSION_TEXT    "#6D8F89"

## USER
set -g @GHC_SL_COLOR_BG_USER_SYM        "#B4637A"
set -g @GHC_SL_COLOR_BG_USER_TEXT       "#FAF4ED"
set -g @GHC_SL_COLOR_FG_USER_SYM        "#FAF4ED"
set -g @GHC_SL_COLOR_FG_USER_TEXT       "#B4637A"

## WINDOW
set -g @GHC_SL_COLOR_BG_WIN_NAME        "#F2E9E1"
set -g @GHC_SL_COLOR_FG_WIN_NAME        "#9893A5"
set -g @GHC_SL_COLOR_BG_WIN_NUM         "#CECACD"
set -g @GHC_SL_COLOR_FG_WIN_NUM         "#9893A5"

## WINDOW_CURRENT
set -g @GHC_SL_COLOR_BG_WIN_CUR_NAME    "#56949F"
set -g @GHC_SL_COLOR_FG_WIN_CUR_NAME    "#FAF4ED"

