# rose-pine-dawn

# Primary colors
background              #faf4ed
foreground              #464261

# Border colors
active_border_color     #907aa9
inactive_border_color   #9893a5

# Cursor colors
cursor                  #b4637a
cursor_text_color       #fffaf3

# Selection colors
selection_background    #ea9d34
selection_foreground    #fffaf3

# Tab bar colors
active_tab_background   #faf4ed
active_tab_foreground   #907aa9
inactive_tab_background #6d8f89
inactive_tab_foreground #286983
tab_bar_background      #6d8f89

# Url colors
url_color               #286983

# Normal colors
color0                  #faf4ed
color1                  #b4637a
color2                  #6d8f89
color3                  #ea9d34
color4                  #286983
color5                  #907aa9
color6                  #56949f
color7                  #9893a5

# Bright colors
color8                  #9893a5
color9                  #b4637a
color10                 #6d8f89
color11                 #ea9d34
color12                 #286983
color13                 #907aa9
color14                 #56949f
color15                 #464261
