# tokyonight-moon

set -g @GHC_SL_BG                       "default"
set -g @GHC_PSL_BG                      "default"

## Cmdline
set -g @GHC_SL_BG_CMDLINE               "#4fd6be"
set -g @GHC_SL_FG_CMDLINE               "#1e2030"

## Message
set -g @GHC_SL_BG_MESSAGE               "#ffc777"
set -g @GHC_SL_FG_MESSAGE               "#1e2030"

## Copy Mode
set -g @GHC_SL_BG_COPY_MODE             "#2f334d"
set -g @GHC_SL_FG_COPY_MODE             "#b6c1e7"
set -g @GHC_SL_BG_COPY_MODE_MATCH       "#ffc777"
set -g @GHC_SL_FG_COPY_MODE_MATCH       "#1e2030"
set -g @GHC_SL_BG_COPY_MODE_MARK        "#ffc777"
set -g @GHC_SL_FG_COPY_MODE_MARK        "#1e2030"
set -g @GHC_SL_BG_COPY_MODE_POS         "#ffc777"
set -g @GHC_SL_FG_COPY_MODE_POS         "#1e2030"
set -g @GHC_SL_BG_COPY_MODE_SEL         "#86e1fc"
set -g @GHC_SL_FG_COPY_MODE_SEL         "#1e2030"

## Pane
set -g @GHC_PANE_BG                     "#1e2030"
set -g @GHC_PANE_BG_ACTIVE              "#222436"

set -g @GHC_PSL_FG_BORDER               "#2d3f76"
set -g @GHC_PSL_FG_BORDER_CUR           "#c099ff"

set -g @GHC_PSL_BG_SYM                  "default"
set -g @GHC_PSL_FG_SYM                  "#7c86ba"
set -g @GHC_PSL_BG_TXT                  "default"
set -g @GHC_PSL_FG_TXT                  "#7c86ba"

set -g @GHC_PSL_BG_SYM_ACTIVE           "default"
set -g @GHC_PSL_FG_SYM_ACTIVE           "#c099ff"
set -g @GHC_PSL_BG_TXT_ACTIVE           "default"
set -g @GHC_PSL_FG_TXT_ACTIVE           "#909bca"

## Statusbar

set -g @GHC_SL_FG_BORDER                "#2d3f76"
set -g @GHC_SL_FG_BORDER_CUR            "#c099ff"

set -g @GHC_SL_BG_SYM                   "default"
set -g @GHC_SL_FG_SYM                   "#c099ff"
set -g @GHC_SL_BG_TXT                   "default"
set -g @GHC_SL_FG_TXT                   "#909bca"

set -g @GHC_SL_BG_OS_SYM                "#222436"
set -g @GHC_SL_FG_OS_SYM                "#c099ff"

set -g @GHC_SL_BG_PRIMARY_SEP           "#191b29"
set -g @GHC_SL_FG_PRIMARY_SEP           "#c099ff"
set -g @GHC_SL_BG_PRIMARY_SYM           "#c099ff"
set -g @GHC_SL_FG_PRIMARY_SYM           "#1e2030"
set -g @GHC_SL_BG_PRIMARY_TXT           "#c099ff"
set -g @GHC_SL_FG_PRIMARY_TXT           "#1e2030"
set -g @GHC_SL_BG_SECONDARY_SEP         "default"
set -g @GHC_SL_FG_SECONDARY_SEP         "#191b29"
set -g @GHC_SL_BG_SECONDARY_SYM         "#191b29"
set -g @GHC_SL_FG_SECONDARY_SYM         "#c099ff"
set -g @GHC_SL_BG_SECONDARY_TXT         "#191b29"
set -g @GHC_SL_FG_SECONDARY_TXT         "#c099ff"

set -g @GHC_SL_BG_WIN_NAME              "#191b29"
set -g @GHC_SL_FG_WIN_NAME              "#909bca"
set -g @GHC_SL_BG_WIN_NUM               "#2f334d"
set -g @GHC_SL_FG_WIN_NUM               "#909bca"
set -g @GHC_SL_BG_WIN_ICON_LAST         "#2f334d"
set -g @GHC_SL_FG_WIN_ICON_LAST         "#ff966c"

set -g @GHC_SL_BG_WIN_ACTIVE_NAME       "#c099ff"
set -g @GHC_SL_FG_WIN_ACTIVE_NAME       "#222436"
set -g @GHC_SL_BG_WIN_ACTIVE_NUM        "#c099ff"
set -g @GHC_SL_FG_WIN_ACTIVE_NUM        "#222436"

set -g @GHC_SL_BG_WIN_LAST_NAME         "#ff966c"
set -g @GHC_SL_FG_WIN_LAST_NAME         "#222436"
set -g @GHC_SL_BG_WIN_LAST_NUM          "#ff966c"
set -g @GHC_SL_FG_WIN_LAST_NUM          "#222436"

