# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# tokyonight-moon

[delta "tokyonight-moon"]
dark                          = true
syntax-theme                  = tokyonight-moon

inline-hint-style             = "#82aaff"

####################################################################################################

file-style                    = "#c8d3f5" bold

hunk-header-line-number-style = "#aab6df"

line-numbers-minus-style      = "#ff8590" normal bold
line-numbers-plus-style       = "#c3e88d" normal bold

minus-style                   = syntax "#432e40"
plus-style                    = syntax "#293b47"
minus-non-emph-style          = syntax "#432e40"
plus-non-emph-style           = syntax "#293b47"
minus-emph-style              = "#c8d3f5" "#653d55" bold
plus-emph-style               = "#c8d3f5" "#365468" bold

plus-empty-line-marker-style  = "#293b47" "#293b47"
minus-empty-line-marker-style = "#432e40" "#432e40"

####################################################################################################

commit-style                  = "#ffc777" bold

blame-palette                 = "#222436" "#1e2030" "#2f334d"
blame-separator-style         = "#aab6df" dim
