# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# tokyonight-moon

[delta]
hunk-header-style             = raw
hunk-header-decoration-style  = ul
hyperlinks                    = true
hyperlinks-file-link-format   = file://{path}:{line}
detect-dark-light             = auto
line-numbers                  = true
navigate                      = true    # use n and N to move between diff sections
paging                        = never
side-by-side                  = true

dark                          = true
true-color                    = always
syntax-theme                  = tokyonight-moon
plus-emph-style               = syntax "#b8db87" bold
plus-non-emph-style           = syntax "#2a4556" bold
plus-style                    = syntax "#2a4556"
minus-emph-style              = syntax "#e26a75" bold
minus-non-emph-style          = syntax "#4b2a3d" bold
minus-style                   = syntax "#4b2a3d"
line-numbers-left-style       = "#c8d3f5"
line-numbers-right-style      = "#c8d3f5"
line-numbers-zero-style       = "#c8d3f5"
line-numbers-minus-style      = "#c8d3f5" "#4b2a3d" bold
line-numbers-plus-style       = "#c8d3f5" "#2a4556" bold
whitespace-error-style        = "#c8d3f5"

