# tokyonight-night

[bell]
color = "#ff9e64"

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

[colors.cursor]
text              = "#1a1b26"
cursor            = "#bb9af7"

[colors.vi_mode_cursor]
text              = "#1a1b26"
cursor            = "#c0caf5"

[colors.search.matches]
foreground        = "#1a1b26"
background        = "#9ba5cf"

[colors.search.focused_match]
foreground        = "#1a1b26"
background        = "#9ece6a"

[colors.hints.start]
foreground        = "#1a1b26"
background        = "#e0af68"

[colors.hints.end]
foreground        = "#1a1b26"
background        = "#9ba5cf"

[colors.selection]
text              = "#1a1b26"
background        = "#bb9af7"

[colors.footer_bar]
foreground        = "#1a1b26"
background        = "#0c0e14"

[colors.primary]
background        = "#1a1b26"
foreground        = "#adb7e2"
dim_foreground    = "#707aa4"
bright_foreground = "#adb7e2"

[colors.normal]
black             = "#1a1b26"
red               = "#f7768e"
green             = "#9ece6a"
yellow            = "#e0af68"
blue              = "#7aa2f7"
magenta           = "#9d7cd8"
cyan              = "#7dcfff"
white             = "#707aa4"

[colors.bright]
black             = "#565f89"
red               = "#db4b4b"
green             = "#73daca"
yellow            = "#e0af68"
blue              = "#2ac3de"
magenta           = "#bb9af7"
cyan              = "#1abc9c"
white             = "#9ba5cf"

[colors.dim]
black             = "#1a1b26"
red               = "#f7768e"
green             = "#9ece6a"
yellow            = "#e0af68"
blue              = "#7aa2f7"
magenta           = "#9d7cd8"
cyan              = "#7dcfff"
white             = "#707aa4"

[[colors.indexed_colors]]
index = 16
color = "#ff9e64"

[[colors.indexed_colors]]
index = 17
color = "#bb9af7"
