# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# tokyonight-day

[delta "tokyonight-day"]
light                         = true
syntax-theme                  = tokyonight-day

inline-hint-style             = "#254e96"

####################################################################################################

file-style                    = "#293552" bold

hunk-header-line-number-style = "#445270"

line-numbers-minus-style      = "#a21d49" normal bold
line-numbers-plus-style       = "#3e5d2c" normal bold

minus-style                   = syntax "#e3d4dc"
plus-style                    = syntax "#d1ddd9"
minus-non-emph-style          = syntax "#e3d4dc"
plus-non-emph-style           = syntax "#d1ddd9"
minus-emph-style              = "#293552" "#d5b7c5" bold
plus-emph-style               = "#293552" "#b0c9c4" bold

plus-empty-line-marker-style  = "#d1ddd9" "#d1ddd9"
minus-empty-line-marker-style = "#e3d4dc" "#e3d4dc"

####################################################################################################

commit-style                  = "#6b4d25" bold

blame-palette                 = "#e1e2e7" "#d0d5e3" "#d5d9e4"
blame-separator-style         = "#445270" dim
