# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# tokyonight-night

[delta]
hunk-header-style             = raw
hunk-header-decoration-style  = ul
hyperlinks                    = true
hyperlinks-file-link-format   = file://{path}:{line}
detect-dark-light             = auto
line-numbers                  = true
navigate                      = true    # use n and N to move between diff sections
paging                        = never
side-by-side                  = true

dark                          = true
true-color                    = always
syntax-theme                  = tokyonight-night
plus-emph-style               = syntax "#449dab" bold
plus-non-emph-style           = syntax "#243e4a" bold
plus-style                    = syntax "#243e4a"
minus-emph-style              = syntax "#914c54" bold
minus-non-emph-style          = syntax "#4a272f" bold
minus-style                   = syntax "#4a272f"
line-numbers-left-style       = "#c0caf5"
line-numbers-right-style      = "#c0caf5"
line-numbers-zero-style       = "#c0caf5"
line-numbers-minus-style      = "#c0caf5" "#4a272f" bold
line-numbers-plus-style       = "#c0caf5" "#243e4a" bold
whitespace-error-style        = "#c0caf5"

