# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# tokyonight-storm

[delta "tokyonight-storm"]
dark                          = true
syntax-theme                  = tokyonight-storm

inline-hint-style             = "#7aa2f7"

####################################################################################################

file-style                    = "#c0caf5" bold

hunk-header-line-number-style = "#a9b1d6"

line-numbers-minus-style      = "#f78498" normal bold
line-numbers-plus-style       = "#9ece6a" normal bold

minus-style                   = syntax "#422f3b"
plus-style                    = syntax "#2a3946"
minus-non-emph-style          = syntax "#422f3b"
plus-non-emph-style           = syntax "#2a3946"
minus-emph-style              = "#c0caf5" "#613e51" bold
plus-emph-style               = "#c0caf5" "#354f60" bold

plus-empty-line-marker-style  = "#2a3946" "#2a3946"
minus-empty-line-marker-style = "#422f3b" "#422f3b"

####################################################################################################

commit-style                  = "#e0af68" bold

blame-palette                 = "#24283b" "#1f2335" "#292e42"
blame-separator-style         = "#a9b1d6" dim
