# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# tokyonight-storm

[delta]
dark                          = true
syntax-theme                  = tokyonight-storm

side-by-side                  = true
navigate                      = true
paging                        = never
tabs                          = 2
relative-paths                = true
wrap-max-lines                = 0
width                         = -0
line-buffer-size              = 64
line-fill-method              = ansi
max-line-distance             = 0.5
word-diff-regex               = "[a-zA-Z_][a-zA-Z0-9_]*|[0-9]+|."
inline-hint-style             = "#7aa2f7"

####################################################################################################

file-style                    = "#adb7e2" bold
file-decoration-style         = ul

hunk-header-style             = line-number syntax
hunk-header-decoration-style  = ul
hunk-header-line-number-style = "#9ba5cf"

line-numbers                  = true
line-numbers-left-style       = "#9ba5cf" "#24283b"
line-numbers-right-style      = "#9ba5cf" "#24283b"
line-numbers-zero-style       = "#9ba5cf" "#24283b"
line-numbers-minus-style      = "#9ba5cf" "#52313f" bold
line-numbers-plus-style       = "#9ba5cf" "#2b485a" bold

zero-style                    = syntax normal
minus-style                   = syntax "#52313f"
plus-style                    = syntax "#2b485a"
minus-non-emph-style          = syntax "#52313f"
plus-non-emph-style           = syntax "#2b485a"
minus-emph-style              = syntax "#914c54" bold
plus-emph-style               = syntax "#449dab" bold

plus-empty-line-marker-style  = "#2b485a" "#2b485a"
minus-empty-line-marker-style = "#52313f" "#52313f"

####################################################################################################

commit-style                  = "#e0af68" bold
commit-decoration-style       = none

blame-palette                 = "#24283b" "#1f2335" "#1b1e2d"
blame-format                  = "{author:<12} {commit:<8} {timestamp:<10}"
blame-code-style              = syntax
blame-separator-style         = "#9ba5cf" dim

hyperlinks                    = true
hyperlinks-file-link-format   = file://{path}:{line}

merge-conflict-begin-symbol   = ⟵
merge-conflict-end-symbol     = ⟶

