# tokyonight-day

# Primary colors
background              #e1e2e7
foreground              #3054a8
selection_background    #9854f1
selection_foreground    #e1e2e7

# Cursor colors
cursor                  #9854f1
cursor_text_color       #e1e2e7

# URL underline color when hovering with mouse
url_color               #9854f1

# Border colors
active_border_color     #3760bf
inactive_border_color   #1e3469
bell_border_color       #8c6c3e

# Tab bar colors
active_tab_foreground   #e1e2e7
active_tab_background   #9854f1
inactive_tab_foreground #3760bf
inactive_tab_background #d0d5e3
tab_bar_background      #d0d5e3

# Colors for marks (marked text in the terminal)
mark1_foreground        #e1e2e7
mark1_background        #3760bf
mark2_foreground        #e1e2e7
mark2_background        #7847bd
mark3_foreground        #e1e2e7
mark3_background        #2e7de9

# Normal colors
color0                  #e1e2e7
color1                  #f52a65
color2                  #587539
color3                  #8c6c3e
color4                  #2e7de9
color5                  #7847bd
color6                  #007197
color7                  #1e3469

# Bright colors
color8                  #848cb5
color9                  #c64343
color10                 #387068
color11                 #8c6c3e
color12                 #188092
color13                 #9854f1
color14                 #118c74
color15                 #294891
