# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# tokyonight-night

[delta "tokyonight-night"]
dark                          = true
syntax-theme                  = tokyonight-night

inline-hint-style             = "#7aa2f7"

####################################################################################################

file-style                    = "#c0caf5" bold

hunk-header-line-number-style = "#a9b1d6"

line-numbers-minus-style      = "#f78498" normal bold
line-numbers-plus-style       = "#9ece6a" normal bold

minus-style                   = syntax "#3e2836"
plus-style                    = syntax "#20343e"
minus-non-emph-style          = syntax "#3e2836"
plus-non-emph-style           = syntax "#20343e"
minus-emph-style              = "#c0caf5" "#613849" bold
plus-emph-style               = "#c0caf5" "#30505d" bold

plus-empty-line-marker-style  = "#20343e" "#20343e"
minus-empty-line-marker-style = "#3e2836" "#3e2836"

####################################################################################################

commit-style                  = "#e0af68" bold

blame-palette                 = "#1a1b26" "#16161e" "#292e42"
blame-separator-style         = "#a9b1d6" dim
