# tokyonight-storm

set -g @GHC_SL_BG                       "default"
set -g @GHC_PSL_BG                      "default"

## Cmdline
set -g @GHC_SL_BG_CMDLINE               "#1abc9c"
set -g @GHC_SL_FG_CMDLINE               "#1f2335"

## Message
set -g @GHC_SL_BG_MESSAGE               "#e0af68"
set -g @GHC_SL_FG_MESSAGE               "#1f2335"

## Copy Mode
set -g @GHC_SL_BG_COPY_MODE             "#292e42"
set -g @GHC_SL_FG_COPY_MODE             "#adb7e2"
set -g @GHC_SL_BG_COPY_MODE_MATCH       "#e0af68"
set -g @GHC_SL_FG_COPY_MODE_MATCH       "#1f2335"
set -g @GHC_SL_BG_COPY_MODE_MARK        "#e0af68"
set -g @GHC_SL_FG_COPY_MODE_MARK        "#1f2335"
set -g @GHC_SL_BG_COPY_MODE_POS         "#e0af68"
set -g @GHC_SL_FG_COPY_MODE_POS         "#1f2335"
set -g @GHC_SL_BG_COPY_MODE_SEL         "#7dcfff"
set -g @GHC_SL_FG_COPY_MODE_SEL         "#1f2335"

## Pane
set -g @GHC_PANE_BG                     "#1f2335"
set -g @GHC_PANE_BG_ACTIVE              "#24283b"

set -g @GHC_PSL_FG_BORDER               "#2e3c64"
set -g @GHC_PSL_FG_BORDER_CUR           "#bb9af7"

set -g @GHC_PSL_BG_SYM                  "default"
set -g @GHC_PSL_FG_SYM                  "#707aa4"
set -g @GHC_PSL_BG_TXT                  "default"
set -g @GHC_PSL_FG_TXT                  "#707aa4"

set -g @GHC_PSL_BG_SYM_ACTIVE           "default"
set -g @GHC_PSL_FG_SYM_ACTIVE           "#bb9af7"
set -g @GHC_PSL_BG_TXT_ACTIVE           "default"
set -g @GHC_PSL_FG_TXT_ACTIVE           "#868fba"

## Statusbar

set -g @GHC_SL_FG_BORDER                "#2e3c64"
set -g @GHC_SL_FG_BORDER_CUR            "#bb9af7"

set -g @GHC_SL_BG_SYM                   "default"
set -g @GHC_SL_FG_SYM                   "#bb9af7"
set -g @GHC_SL_BG_TXT                   "default"
set -g @GHC_SL_FG_TXT                   "#868fba"

set -g @GHC_SL_BG_OS_SYM                "#24283b"
set -g @GHC_SL_FG_OS_SYM                "#bb9af7"

set -g @GHC_SL_BG_PRIMARY_SEP           "#1b1e2d"
set -g @GHC_SL_FG_PRIMARY_SEP           "#bb9af7"
set -g @GHC_SL_BG_PRIMARY_SYM           "#bb9af7"
set -g @GHC_SL_FG_PRIMARY_SYM           "#1f2335"
set -g @GHC_SL_BG_PRIMARY_TXT           "#bb9af7"
set -g @GHC_SL_FG_PRIMARY_TXT           "#1f2335"
set -g @GHC_SL_BG_SECONDARY_SEP         "default"
set -g @GHC_SL_FG_SECONDARY_SEP         "#1b1e2d"
set -g @GHC_SL_BG_SECONDARY_SYM         "#1b1e2d"
set -g @GHC_SL_FG_SECONDARY_SYM         "#bb9af7"
set -g @GHC_SL_BG_SECONDARY_TXT         "#1b1e2d"
set -g @GHC_SL_FG_SECONDARY_TXT         "#bb9af7"

set -g @GHC_SL_BG_WIN_NAME              "#1b1e2d"
set -g @GHC_SL_FG_WIN_NAME              "#868fba"
set -g @GHC_SL_BG_WIN_NUM               "#292e42"
set -g @GHC_SL_FG_WIN_NUM               "#868fba"

set -g @GHC_SL_BG_WIN_NAME_ACTIVE       "#bb9af7"
set -g @GHC_SL_FG_WIN_NAME_ACTIVE       "#24283b"
set -g @GHC_SL_BG_WIN_NUM_ACTIVE        "#bb9af7"
set -g @GHC_SL_FG_WIN_NUM_ACTIVE        "#24283b"

