# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# vsc-light-modern

[delta "vsc-light-modern"]
light                         = true
syntax-theme                  = vsc-light-modern

inline-hint-style             = "#005FB8"

####################################################################################################

file-style                    = "#3B3B3B" bold

hunk-header-line-number-style = "#616161"

line-numbers-minus-style      = "#F85149" normal bold
line-numbers-plus-style       = "#2EA043" normal bold

minus-style                   = syntax "#FFCCCC"
plus-style                    = syntax "#E9EFDB"
minus-non-emph-style          = syntax "#FFCCCC"
plus-non-emph-style           = syntax "#E9EFDB"
minus-emph-style              = syntax "#FFA3A3" bold
plus-emph-style               = syntax "#D3E4AE" bold

plus-empty-line-marker-style  = "#E9EFDB" "#E9EFDB"
minus-empty-line-marker-style = "#FFCCCC" "#FFCCCC"

####################################################################################################

commit-style                  = "#795E26" bold

blame-palette                 = "#FFFFFF" "#F2F2F2" "#E8E8E8"
blame-separator-style         = "#616161" dim
