# vsc-light-modern

set -g @GHC_SL_BG                       "default"
set -g @GHC_PSL_BG                      "default"

## Cmdline
set -g @GHC_SL_BG_CMDLINE               "#0070C1"
set -g @GHC_SL_FG_CMDLINE               "#F8F8F8"

## Message
set -g @GHC_SL_BG_MESSAGE               "#795E26"
set -g @GHC_SL_FG_MESSAGE               "#F8F8F8"

## Copy Mode
set -g @GHC_SL_BG_COPY_MODE             "#E5E5E5"
set -g @GHC_SL_FG_COPY_MODE             "#3B3B3B"
set -g @GHC_SL_BG_COPY_MODE_MATCH       "#795E26"
set -g @GHC_SL_FG_COPY_MODE_MATCH       "#F8F8F8"
set -g @GHC_SL_BG_COPY_MODE_MARK        "#795E26"
set -g @GHC_SL_FG_COPY_MODE_MARK        "#F8F8F8"
set -g @GHC_SL_BG_COPY_MODE_POS         "#795E26"
set -g @GHC_SL_FG_COPY_MODE_POS         "#F8F8F8"
set -g @GHC_SL_BG_COPY_MODE_SEL         "#267F99"
set -g @GHC_SL_FG_COPY_MODE_SEL         "#F8F8F8"

## Pane
set -g @GHC_PANE_BG                     "#F8F8F8"
set -g @GHC_PANE_BG_ACTIVE              "#FFFFFF"

set -g @GHC_PSL_FG_BORDER               "#E5E5E5"
set -g @GHC_PSL_FG_BORDER_CUR           "#FD716C"

set -g @GHC_PSL_BG_SYM                  "default"
set -g @GHC_PSL_FG_SYM                  "#767676"
set -g @GHC_PSL_BG_TXT                  "default"
set -g @GHC_PSL_FG_TXT                  "#767676"

set -g @GHC_PSL_BG_SYM_ACTIVE           "default"
set -g @GHC_PSL_FG_SYM_ACTIVE           "#FD716C"
set -g @GHC_PSL_BG_TXT_ACTIVE           "default"
set -g @GHC_PSL_FG_TXT_ACTIVE           "#6E7681"

## Statusbar

set -g @GHC_SL_FG_BORDER                "#E5E5E5"
set -g @GHC_SL_FG_BORDER_CUR            "#FD716C"

set -g @GHC_SL_BG_SYM                   "default"
set -g @GHC_SL_FG_SYM                   "#FD716C"
set -g @GHC_SL_BG_TXT                   "default"
set -g @GHC_SL_FG_TXT                   "#6E7681"

set -g @GHC_SL_BG_OS_SYM                "#FFFFFF"
set -g @GHC_SL_FG_OS_SYM                "#FD716C"

set -g @GHC_SL_BG_PRIMARY_SEP           "#F2F2F2"
set -g @GHC_SL_FG_PRIMARY_SEP           "#FD716C"
set -g @GHC_SL_BG_PRIMARY_SYM           "#FD716C"
set -g @GHC_SL_FG_PRIMARY_SYM           "#F8F8F8"
set -g @GHC_SL_BG_PRIMARY_TXT           "#FD716C"
set -g @GHC_SL_FG_PRIMARY_TXT           "#F8F8F8"
set -g @GHC_SL_BG_SECONDARY_SEP         "default"
set -g @GHC_SL_FG_SECONDARY_SEP         "#F2F2F2"
set -g @GHC_SL_BG_SECONDARY_SYM         "#F2F2F2"
set -g @GHC_SL_FG_SECONDARY_SYM         "#FD716C"
set -g @GHC_SL_BG_SECONDARY_TXT         "#F2F2F2"
set -g @GHC_SL_FG_SECONDARY_TXT         "#FD716C"

set -g @GHC_SL_BG_WIN_NAME              "#F2F2F2"
set -g @GHC_SL_FG_WIN_NAME              "#6E7681"
set -g @GHC_SL_BG_WIN_NUM               "#E5E5E5"
set -g @GHC_SL_FG_WIN_NUM               "#6E7681"

set -g @GHC_SL_BG_WIN_NAME_ACTIVE       "#FD716C"
set -g @GHC_SL_FG_WIN_NAME_ACTIVE       "#FFFFFF"
set -g @GHC_SL_BG_WIN_NUM_ACTIVE        "#FD716C"
set -g @GHC_SL_FG_WIN_NUM_ACTIVE        "#FFFFFF"

