# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# vsc-light-modern

[delta]
hunk-header-style             = raw
hunk-header-decoration-style  = ul
hyperlinks                    = true
hyperlinks-file-link-format   = file://{path}:{line}
detect-dark-light             = auto
line-numbers                  = true
navigate                      = true    # use n and N to move between diff sections
paging                        = never
side-by-side                  = true

light                         = true
true-color                    = always
syntax-theme                  = vsc-light-modern
plus-emph-style               = syntax "#86EFAC" bold
plus-non-emph-style           = syntax "#BBF7D0" bold
plus-style                    = syntax "#BBF7D0"
minus-emph-style              = syntax "#FCA5A5" bold
minus-non-emph-style          = syntax "#FECACA" bold
minus-style                   = syntax "#FECACA"
line-numbers-left-style       = "#000000"
line-numbers-right-style      = "#000000"
line-numbers-zero-style       = "#000000"
line-numbers-minus-style      = "#000000" "#FECACA" bold
line-numbers-plus-style       = "#000000" "#BBF7D0" bold
whitespace-error-style        = "#000000"

