# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# vsc-dark-modern

[delta]
hunk-header-style             = raw
hunk-header-decoration-style  = ul
hyperlinks                    = true
hyperlinks-file-link-format   = file://{path}:{line}
detect-dark-light             = auto
line-numbers                  = true
navigate                      = true    # use n and N to move between diff sections
paging                        = never
side-by-side                  = true

dark                          = true
true-color                    = always
syntax-theme                  = vsc-dark-modern
plus-emph-style               = syntax "#27432C" bold
plus-non-emph-style           = syntax "#1E2D22" bold
plus-style                    = syntax "#1E2D22"
minus-emph-style              = syntax "#5A2E30" bold
minus-non-emph-style          = syntax "#3B2021" bold
minus-style                   = syntax "#3B2021"
line-numbers-left-style       = "#FFFFFF"
line-numbers-right-style      = "#FFFFFF"
line-numbers-zero-style       = "#FFFFFF"
line-numbers-minus-style      = "#FFFFFF" "#3B2021" bold
line-numbers-plus-style       = "#FFFFFF" "#1E2D22" bold
whitespace-error-style        = "#FFFFFF"

