# vsc-dark-modern

set -g @GHC_SL_BG                       "default"
set -g @GHC_PSL_BG                      "default"

## Cmdline
set -g @GHC_SL_BG_CMDLINE               "#4FC1FF"
set -g @GHC_SL_FG_CMDLINE               "#181818"

## Message
set -g @GHC_SL_BG_MESSAGE               "#DCDCAA"
set -g @GHC_SL_FG_MESSAGE               "#181818"

## Copy Mode
set -g @GHC_SL_BG_COPY_MODE             "#2B2B2B"
set -g @GHC_SL_FG_COPY_MODE             "#CCCCCC"
set -g @GHC_SL_BG_COPY_MODE_MATCH       "#DCDCAA"
set -g @GHC_SL_FG_COPY_MODE_MATCH       "#181818"
set -g @GHC_SL_BG_COPY_MODE_MARK        "#DCDCAA"
set -g @GHC_SL_FG_COPY_MODE_MARK        "#181818"
set -g @GHC_SL_BG_COPY_MODE_POS         "#DCDCAA"
set -g @GHC_SL_FG_COPY_MODE_POS         "#181818"
set -g @GHC_SL_BG_COPY_MODE_SEL         "#4EC9B0"
set -g @GHC_SL_FG_COPY_MODE_SEL         "#181818"

## Pane
set -g @GHC_PANE_BG                     "#181818"
set -g @GHC_PANE_BG_ACTIVE              "#1F1F1F"

set -g @GHC_PSL_FG_BORDER               "#313131"
set -g @GHC_PSL_FG_BORDER_CUR           "#CE9178"

set -g @GHC_PSL_BG_SYM                  "default"
set -g @GHC_PSL_FG_SYM                  "#989898"
set -g @GHC_PSL_BG_TXT                  "default"
set -g @GHC_PSL_FG_TXT                  "#989898"

set -g @GHC_PSL_BG_SYM_ACTIVE           "default"
set -g @GHC_PSL_FG_SYM_ACTIVE           "#CE9178"
set -g @GHC_PSL_BG_TXT_ACTIVE           "default"
set -g @GHC_PSL_FG_TXT_ACTIVE           "#6E7681"

## Statusbar

set -g @GHC_SL_FG_BORDER                "#313131"
set -g @GHC_SL_FG_BORDER_CUR            "#CE9178"

set -g @GHC_SL_BG_SYM                   "default"
set -g @GHC_SL_FG_SYM                   "#CE9178"
set -g @GHC_SL_BG_TXT                   "default"
set -g @GHC_SL_FG_TXT                   "#6E7681"

set -g @GHC_SL_BG_OS_SYM                "#1F1F1F"
set -g @GHC_SL_FG_OS_SYM                "#CE9178"

set -g @GHC_SL_BG_PRIMARY_SEP           "#2A2D2E"
set -g @GHC_SL_FG_PRIMARY_SEP           "#CE9178"
set -g @GHC_SL_BG_PRIMARY_SYM           "#CE9178"
set -g @GHC_SL_FG_PRIMARY_SYM           "#181818"
set -g @GHC_SL_BG_PRIMARY_TXT           "#CE9178"
set -g @GHC_SL_FG_PRIMARY_TXT           "#181818"
set -g @GHC_SL_BG_SECONDARY_SEP         "default"
set -g @GHC_SL_FG_SECONDARY_SEP         "#2A2D2E"
set -g @GHC_SL_BG_SECONDARY_SYM         "#2A2D2E"
set -g @GHC_SL_FG_SECONDARY_SYM         "#CE9178"
set -g @GHC_SL_BG_SECONDARY_TXT         "#2A2D2E"
set -g @GHC_SL_FG_SECONDARY_TXT         "#CE9178"

set -g @GHC_SL_BG_WIN_NAME              "#2A2D2E"
set -g @GHC_SL_FG_WIN_NAME              "#6E7681"
set -g @GHC_SL_BG_WIN_NUM               "#2B2B2B"
set -g @GHC_SL_FG_WIN_NUM               "#6E7681"

set -g @GHC_SL_BG_WIN_NAME_ACTIVE       "#CE9178"
set -g @GHC_SL_FG_WIN_NAME_ACTIVE       "#1F1F1F"
set -g @GHC_SL_BG_WIN_NUM_ACTIVE        "#CE9178"
set -g @GHC_SL_FG_WIN_NUM_ACTIVE        "#1F1F1F"

