# https://github.com/dandavison/delta/blob/main/themes.gitconfig
# vsc-light-modern

[delta]
hunk-header-style             = raw
hunk-header-decoration-style  = ul
hyperlinks                    = true
hyperlinks-file-link-format   = file://{path}:{line}
detect-dark-light             = auto
line-numbers                  = true
navigate                      = true    # use n and N to move between diff sections
paging                        = never
side-by-side                  = true

light                         = true
true-color                    = always
syntax-theme                  = vsc-light-modern
plus-emph-style               = syntax "#C8E6C9" bold
plus-non-emph-style           = syntax "#DFF0D8" bold
plus-style                    = syntax "#DFF0D8"
minus-emph-style              = syntax "#F8CAB5" bold
minus-non-emph-style          = syntax "#FFE2DA" bold
minus-style                   = syntax "#FFE2DA"
line-numbers-left-style       = "#1F1F1F"
line-numbers-right-style      = "#1F1F1F"
line-numbers-zero-style       = "#1F1F1F"
line-numbers-minus-style      = "#1F1F1F" "#FFE2DA" bold
line-numbers-plus-style       = "#1F1F1F" "#DFF0D8" bold
whitespace-error-style        = "#1F1F1F"

