# vsc-dark-modern

# Primary colors
background              #1F1F1F
foreground              #CCCCCC
selection_background    #F5A9B8
selection_foreground    #1F1F1F

# Cursor colors
cursor                  #F5A9B8
cursor_text_color       #1F1F1F

# URL underline color when hovering with mouse
url_color               #F5A9B8

# Border colors
active_border_color     #FFFFFF
inactive_border_color   #6E7681
bell_border_color       #DCDCAA

# Tab bar colors
active_tab_foreground   #1F1F1F
active_tab_background   #F5A9B8
inactive_tab_foreground #FFFFFF
inactive_tab_background #202020
tab_bar_background      #202020

# Colors for marks (marked text in the terminal)
mark1_foreground        #1F1F1F
mark1_background        #FFFFFF
mark2_foreground        #1F1F1F
mark2_background        #C586C0
mark3_foreground        #1F1F1F
mark3_background        #0078D4

# Normal colors
color0                  #1F1F1F
color1                  #F85149
color2                  #2EA043
color3                  #DCDCAA
color4                  #0078D4
color5                  #C586C0
color6                  #4EC9B0
color7                  #6E7681

# Bright colors
color8                  #707070
color9                  #F85149
color10                 #B5CEA8
color11                 #DCDCAA
color12                 #9CDCFE
color13                 #C586C0
color14                 #4FC1FF
color15                 #9D9D9D
