---@class t.fml.ux.theme.IPalette
---@field public black                  string
---@field public blue                   string
---@field public cyan                   string
---@field public green                  string
---@field public grey                   string
---@field public lavender               string
---@field public pink                   string
---@field public purple                 string
---@field public red                    string
---@field public white                  string
---@field public yellow                 string
---@field public dark_black             string
---@field public dark_blue              string
---@field public dark_cyan              string
---@field public dark_green             string
---@field public dark_pink              string
---@field public dark_purple            string
---@field public dark_red               string
---@field public dark_white             string
---@field public dark_yellow            string
---
---@field public bg0                    string
---@field public bg1                    string
---@field public bg2                    string
---@field public bg3                    string
---@field public bg_blue                string
---@field public bg_cyan                string
---@field public bg_pink                string
---@field public bg_yellow              string
---@field public fg0                    string
---@field public fg1                    string
---@field public fg2                    string
---@field public fg3                    string
---
---@field public diff_add               string
---@field public diff_add_word          string
---@field public diff_del               string
---@field public diff_del_word          string

---@class t.fml.ux.theme.IScheme
---@field public theme                  t.eve.e.Theme
---@field public mode                   t.eve.e.ThemeMode
---@field public palette                t.fml.ux.theme.IPalette

---@class t.fml.ux.theme.IHlgroup : vim.api.keyset.highlight

---@class t.fml.ux.theme.IApplyParams
---@field public scheme                 t.fml.ux.theme.IScheme
---@field public nsnr                   integer

---@class t.fml.ux.theme.ICompileParams
---@field public scheme                 t.fml.ux.theme.IScheme
---@field public filepath               string
---@field public nsnr                   integer

---@class t.fml.ux.ITheme
---@field public apply                  fun(self: t.fml.ux.ITheme, params: t.fml.ux.theme.IApplyParams): nil
---@field public compile                fun(self: t.fml.ux.ITheme, params: t.fml.ux.theme.ICompileParams): nil
---@field public register               fun(self: t.fml.ux.ITheme, hlname: string, hlgroup: t.fml.ux.theme.IHlgroup): t.fml.ux.ITheme
---@field public registers              fun(self: t.fml.ux.ITheme, hlgroup_map: table<string, t.fml.ux.theme.IHlgroup | nil>): t.fml.ux.ITheme
