---@class t.fml.ux.theme.IPalette
---@field public red                    string
---@field public green                  string
---@field public yellow                 string
---@field public blue                   string
---@field public purple                 string
---@field public aqua                   string
---@field public orange                 string
---@field public grey                   string
---
---@field public neutral_red            string
---@field public neutral_green          string
---@field public neutral_yellow         string
---@field public neutral_blue           string
---@field public neutral_purple         string
---@field public neutral_aqua           string
---@field public neutral_orange         string
---@field public neutral_grey          string
--
---@field public bg0_h                  string
---@field public bg0                    string
---@field public bg0_s                  string
---@field public bg1                    string
---@field public bg2                    string
---@field public bg3                    string
---@field public bg4                    string
---
---@field public fg                     string
---@field public fg0                    string
---@field public fg1                    string
---@field public fg2                    string
---@field public fg3                    string
---@field public fg4                    string
---
---@field public lavender               string

---@class t.fml.ux.theme.IScheme
---@field public theme                  t.eve.e.Theme
---@field public mode                   t.eve.e.ThemeMode
---@field public palette                t.fml.ux.theme.IPalette

---@class t.fml.ux.theme.IHlgroup : vim.api.keyset.highlight

---@class t.fml.ux.theme.IApplyParams
---@field public scheme                 t.fml.ux.theme.IScheme
---@field public nsnr                   integer

---@class t.fml.ux.theme.ICompileParams
---@field public scheme                 t.fml.ux.theme.IScheme
---@field public filepath               string
---@field public nsnr                   integer

---@class t.fml.ux.ITheme
---@field public apply                  fun(self: t.fml.ux.ITheme, params: t.fml.ux.theme.IApplyParams): nil
---@field public compile                fun(self: t.fml.ux.ITheme, params: t.fml.ux.theme.ICompileParams): nil
---@field public register               fun(self: t.fml.ux.ITheme, hlname: string, hlgroup: t.fml.ux.theme.IHlgroup): t.fml.ux.ITheme
---@field public registers              fun(self: t.fml.ux.ITheme, hlgroup_map: table<string, t.fml.ux.theme.IHlgroup | nil>): t.fml.ux.ITheme
