# catppuccin-macchiato

# Main bg
theme[main_bg]="#24273A"

# Main text color
theme[main_fg]="#CAD3F5"

# Title color for boxes
theme[title]="#CAD3F5"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#8AADF4"

# Background color of selected item in processes box
theme[selected_bg]="#363A4F"

# Foreground color of selected item in processes box
theme[selected_fg]="#CAD3F5"

# Color of inactive/disabled text
theme[inactive_fg]="#6E738D"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#8AADF4"

# Color of text in graphs
theme[graph_text]="#A5ADCB"

# Background color of meters
theme[meter_bg]="#363A4F"

# Cpu box outline color
theme[cpu_box]="#494D64"

# Memory/disks box outline color
theme[mem_box]="#494D64"

# Net up/down box outline color
theme[net_box]="#494D64"

# Processes box outline color
theme[proc_box]="#494D64"

# Box divider line and small boxes line color
theme[div_line]="#494D64"

# Temperature graph colors (green -> yellow -> red)
theme[temp_start]="#A6DA95"
theme[temp_mid]="#EED49F"
theme[temp_end]="#ED8796"

# CPU graph colors
theme[cpu_start]="#A6DA95"
theme[cpu_mid]="#EED49F"
theme[cpu_end]="#ED8796"

# Mem/Disk free meter
theme[free_start]="#A6DA95"
theme[free_mid]="#EED49F"
theme[free_end]="#ED8796"

# Mem/Disk cached meter
theme[cached_start]="#8BD5CA"
theme[cached_mid]="#8AADF4"
theme[cached_end]="#F5BDE6"

# Mem/Disk available meter
theme[available_start]="#A6DA95"
theme[available_mid]="#EED49F"
theme[available_end]="#F5A97F"

# Mem/Disk used meter
theme[used_start]="#A6DA95"
theme[used_mid]="#EED49F"
theme[used_end]="#ED8796"

# Download graph colors
theme[download_start]="#A6DA95"
theme[download_mid]="#8BD5CA"
theme[download_end]="#8AADF4"

# Upload graph colors
theme[upload_start]="#F5BDE6"
theme[upload_mid]="#F5BDE6"
theme[upload_end]="#ED8796"

# Process box gradient
theme[process_start]="#8BD5CA"
theme[process_mid]="#B7BDF8"
theme[process_end]="#C6A0F6"

# Background color when process is paused (e.g. after pressing 'p')
theme[proc_pause_bg]="#ED8796"
