# gruvbox-light

# Main bg
theme[main_bg]="#F2E5BC"

# Main text color
theme[main_fg]="#3C3836"

# Title color for boxes
theme[title]="#3C3836"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#458588"

# Background color of selected item in processes box
theme[selected_bg]="#D5C4A1"

# Foreground color of selected item in processes box
theme[selected_fg]="#32302F"

# Color of inactive/disabled text
theme[inactive_fg]="#7C6F64"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#458588"

# Color of text in graphs
theme[graph_text]="#665C54"

# Background color of meters
theme[meter_bg]="#EBDBB2"

# Cpu box outline color
theme[cpu_box]="#BDAE93"

# Memory/disks box outline color
theme[mem_box]="#BDAE93"

# Net up/down box outline color
theme[net_box]="#BDAE93"

# Processes box outline color
theme[proc_box]="#BDAE93"

# Box divider line and small boxes line color
theme[div_line]="#BDAE93"

# Temperature graph colors (green -> yellow -> red)
theme[temp_start]="#98971A"
theme[temp_mid]="#D79921"
theme[temp_end]="#CC241D"

# CPU graph colors
theme[cpu_start]="#98971A"
theme[cpu_mid]="#D79921"
theme[cpu_end]="#CC241D"

# Mem/Disk free meter
theme[free_start]="#98971A"
theme[free_mid]="#D79921"
theme[free_end]="#CC241D"

# Mem/Disk cached meter
theme[cached_start]="#689D6A"
theme[cached_mid]="#458588"
theme[cached_end]="#B16286"

# Mem/Disk available meter
theme[available_start]="#98971A"
theme[available_mid]="#D79921"
theme[available_end]="#D65D0E"

# Mem/Disk used meter
theme[used_start]="#98971A"
theme[used_mid]="#D79921"
theme[used_end]="#CC241D"

# Download graph colors
theme[download_start]="#98971A"
theme[download_mid]="#689D6A"
theme[download_end]="#458588"

# Upload graph colors
theme[upload_start]="#B16286"
theme[upload_mid]="#B16286"
theme[upload_end]="#CC241D"

# Process box gradient
theme[process_start]="#689D6A"
theme[process_mid]="#458588"
theme[process_end]="#B16286"

# Background color when process is paused (e.g. after pressing 'p')
theme[proc_pause_bg]="#CC241D"
