# kanagawa-dragon

# Main bg
theme[main_bg]="#181616"

# Main text color
theme[main_fg]="#C8C093"

# Title color for boxes
theme[title]="#C8C093"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#8BA4B0"

# Background color of selected item in processes box
theme[selected_bg]="#393836"

# Foreground color of selected item in processes box
theme[selected_fg]="#C5C9C5"

# Color of inactive/disabled text
theme[inactive_fg]="#737C73"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#8BA4B0"

# Color of text in graphs
theme[graph_text]="#9E9B93"

# Background color of meters
theme[meter_bg]="#282727"

# Cpu box outline color
theme[cpu_box]="#223249"

# Memory/disks box outline color
theme[mem_box]="#223249"

# Net up/down box outline color
theme[net_box]="#223249"

# Processes box outline color
theme[proc_box]="#223249"

# Box divider line and small boxes line color
theme[div_line]="#223249"

# Temperature graph colors (green -> yellow -> red)
theme[temp_start]="#8A9A7B"
theme[temp_mid]="#C4B28A"
theme[temp_end]="#C4746E"

# CPU graph colors
theme[cpu_start]="#8A9A7B"
theme[cpu_mid]="#C4B28A"
theme[cpu_end]="#C4746E"

# Mem/Disk free meter
theme[free_start]="#8A9A7B"
theme[free_mid]="#C4B28A"
theme[free_end]="#C4746E"

# Mem/Disk cached meter
theme[cached_start]="#8EA4A2"
theme[cached_mid]="#8BA4B0"
theme[cached_end]="#A292A3"

# Mem/Disk available meter
theme[available_start]="#8A9A7B"
theme[available_mid]="#C4B28A"
theme[available_end]="#B6927B"

# Mem/Disk used meter
theme[used_start]="#8A9A7B"
theme[used_mid]="#C4B28A"
theme[used_end]="#C4746E"

# Download graph colors
theme[download_start]="#8A9A7B"
theme[download_mid]="#8EA4A2"
theme[download_end]="#8BA4B0"

# Upload graph colors
theme[upload_start]="#A292A3"
theme[upload_mid]="#A292A3"
theme[upload_end]="#C4746E"

# Process box gradient
theme[process_start]="#8EA4A2"
theme[process_mid]="#8BA4B0"
theme[process_end]="#A292A3"

# Background color when process is paused (e.g. after pressing 'p')
theme[proc_pause_bg]="#C4746E"
