# onehalf-dark

# Main bg
theme[main_bg]="#1E222A"

# Main text color
theme[main_fg]="#D7DAE0"

# Title color for boxes
theme[title]="#D7DAE0"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#61AFEF"

# Background color of selected item in processes box
theme[selected_bg]="#3E4451"

# Foreground color of selected item in processes box
theme[selected_fg]="#E5E9F0"

# Color of inactive/disabled text
theme[inactive_fg]="#ABB2BF"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#61AFEF"

# Color of text in graphs
theme[graph_text]="#B6BDCA"

# Background color of meters
theme[meter_bg]="#252931"

# Cpu box outline color
theme[cpu_box]="#545862"

# Memory/disks box outline color
theme[mem_box]="#545862"

# Net up/down box outline color
theme[net_box]="#545862"

# Processes box outline color
theme[proc_box]="#545862"

# Box divider line and small boxes line color
theme[div_line]="#545862"

# Temperature graph colors (green -> yellow -> red)
theme[temp_start]="#98C379"
theme[temp_mid]="#E5C07B"
theme[temp_end]="#E06C75"

# CPU graph colors
theme[cpu_start]="#98C379"
theme[cpu_mid]="#E5C07B"
theme[cpu_end]="#E06C75"

# Mem/Disk free meter
theme[free_start]="#98C379"
theme[free_mid]="#E5C07B"
theme[free_end]="#E06C75"

# Mem/Disk cached meter
theme[cached_start]="#56B6C2"
theme[cached_mid]="#61AFEF"
theme[cached_end]="#C678DD"

# Mem/Disk available meter
theme[available_start]="#98C379"
theme[available_mid]="#E5C07B"
theme[available_end]="#D75F00"

# Mem/Disk used meter
theme[used_start]="#98C379"
theme[used_mid]="#E5C07B"
theme[used_end]="#E06C75"

# Download graph colors
theme[download_start]="#98C379"
theme[download_mid]="#56B6C2"
theme[download_end]="#61AFEF"

# Upload graph colors
theme[upload_start]="#C678DD"
theme[upload_mid]="#DE8C92"
theme[upload_end]="#E06C75"

# Process box gradient
theme[process_start]="#56B6C2"
theme[process_mid]="#61AFEF"
theme[process_end]="#C678DD"

# Background color when process is paused (e.g. after pressing 'p')
theme[proc_pause_bg]="#E06C75"
