# rosepine-dawn

# Main bg
theme[main_bg]="#FAF4ED"

# Main text color
theme[main_fg]="#464261"

# Title color for boxes
theme[title]="#464261"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#56949F"

# Background color of selected item in processes box
theme[selected_bg]="#F2E9E1"

# Foreground color of selected item in processes box
theme[selected_fg]="#464261"

# Color of inactive/disabled text
theme[inactive_fg]="#9893A5"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#56949F"

# Color of text in graphs
theme[graph_text]="#9893A5"

# Background color of meters
theme[meter_bg]="#FFFAF3"

# Cpu box outline color
theme[cpu_box]="#DFDAD9"

# Memory/disks box outline color
theme[mem_box]="#DFDAD9"

# Net up/down box outline color
theme[net_box]="#DFDAD9"

# Processes box outline color
theme[proc_box]="#DFDAD9"

# Box divider line and small boxes line color
theme[div_line]="#DFDAD9"

# Temperature graph colors (green -> yellow -> red)
theme[temp_start]="#286983"
theme[temp_mid]="#EA9D34"
theme[temp_end]="#B4637A"

# CPU graph colors
theme[cpu_start]="#286983"
theme[cpu_mid]="#EA9D34"
theme[cpu_end]="#B4637A"

# Mem/Disk free meter
theme[free_start]="#286983"
theme[free_mid]="#EA9D34"
theme[free_end]="#B4637A"

# Mem/Disk cached meter
theme[cached_start]="#D7827E"
theme[cached_mid]="#56949F"
theme[cached_end]="#907AA9"

# Mem/Disk available meter
theme[available_start]="#286983"
theme[available_mid]="#EA9D34"
theme[available_end]="#D7827E"

# Mem/Disk used meter
theme[used_start]="#286983"
theme[used_mid]="#EA9D34"
theme[used_end]="#B4637A"

# Download graph colors
theme[download_start]="#286983"
theme[download_mid]="#D7827E"
theme[download_end]="#56949F"

# Upload graph colors
theme[upload_start]="#907AA9"
theme[upload_mid]="#B4637A"
theme[upload_end]="#B4637A"

# Process box gradient
theme[process_start]="#D7827E"
theme[process_mid]="#56949F"
theme[process_end]="#907AA9"

# Background color when process is paused (e.g. after pressing 'p')
theme[proc_pause_bg]="#B4637A"
