# rosepine-main

# Main bg
theme[main_bg]="#191724"

# Main text color
theme[main_fg]="#E0DEF4"

# Title color for boxes
theme[title]="#E0DEF4"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#EBBCBA"

# Background color of selected item in processes box
theme[selected_bg]="#403D52"

# Foreground color of selected item in processes box
theme[selected_fg]="#E0DEF4"

# Color of inactive/disabled text
theme[inactive_fg]="#6E6A86"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#C4A7E7"

# Color of text in graphs
theme[graph_text]="#908CAA"

# Background color of meters
theme[meter_bg]="#403D52"

# Cpu box outline color
theme[cpu_box]="#524F67"

# Memory/disks box outline color
theme[mem_box]="#524F67"

# Net up/down box outline color
theme[net_box]="#524F67"

# Processes box outline color
theme[proc_box]="#EBBCBA"

# Box divider line and small boxes line color
theme[div_line]="#403D52"

# Temperature graph colors (green -> yellow -> red)
theme[temp_start]="#6FA3B6"
theme[temp_mid]="#F6C177"
theme[temp_end]="#EB6F92"

# CPU graph colors
theme[cpu_start]="#6FA3B6"
theme[cpu_mid]="#9CCFD8"
theme[cpu_end]="#C4A7E7"

# Mem/Disk free meter
theme[free_start]="#6FA3B6"
theme[free_mid]="#6FA3B6"
theme[free_end]="#6FA3B6"

# Mem/Disk cached meter
theme[cached_start]="#9CCFD8"
theme[cached_mid]="#9CCFD8"
theme[cached_end]="#9CCFD8"

# Mem/Disk available meter
theme[available_start]="#6FA3B6"
theme[available_mid]="#6FA3B6"
theme[available_end]="#6FA3B6"

# Mem/Disk used meter
theme[used_start]="#C4A7E7"
theme[used_mid]="#C4A7E7"
theme[used_end]="#C4A7E7"

# Download graph colors
theme[download_start]="#6FA3B6"
theme[download_mid]="#9CCFD8"
theme[download_end]="#9CCFD8"

# Upload graph colors
theme[upload_start]="#EBBCBA"
theme[upload_mid]="#C4A7E7"
theme[upload_end]="#C4A7E7"

# Process box gradient
theme[process_start]="#908CAA"
theme[process_mid]="#9CCFD8"
theme[process_end]="#9CCFD8"

# Background color when process is paused (e.g. after pressing 'p')
theme[proc_pause_bg]="#403D52"
