--- tokyonight-storm

---@type ark.t.theme.IScheme
local M = {
  theme = "tokyonight",
  variant = "storm",
  opposite = "day",
  darken = true,
  -- stylua: ignore start
  palette = {
    unified = {
      none          = "none",

      bg0           = "#24283b",
      bg1           = "#1f2335",
      bg2           = "#1b1e2d",
      bg3           = "#292e42",
      bg4           = "#2e3c64",

      fg0           = "#c0caf5",
      fg1           = "#adb7e2",
      fg2           = "#9ba5cf",
      fg3           = "#868fba",
      fg4           = "#707aa4",

      red           = "#f7768e",
      green         = "#9ece6a",
      yellow        = "#e0af68",
      blue          = "#7aa2f7",
      purple        = "#9d7cd8",
      aqua          = "#7dcfff",
      orange        = "#ff9e64",

      brightRed     = "#db4b4b",
      brightGreen   = "#73daca",
      brightYellow  = "#e0af68",
      brightBlue    = "#2ac3de",
      brightPurple  = "#bb9af7",
      brightAqua    = "#1abc9c",
      brightOrange  = "#ff9e64",

      grey          = "#565f89",
      pink          = "#bb9af7",

      diffDel       = "#52313f",
      diffDelInline = "#914c54",
      diffAdd       = "#2b485a",
      diffAddInline = "#449dab",
    },
    tokyonight = {
      none          = "none",

      bg            = "#24283b",
      bg_dark       = "#1f2335",
      bg_dark1      = "#1b1e2d",
      bg_highlight  = "#292e42",
      bg_visual     = "#2e3c64",
      fg            = "#c0caf5",
      fg_dark       = "#a9b1d6",
      fg_gutter     = "#3b4261",
      fg_sidebar    = "#a9b1d6",
      comment       = "#565f89",
      dark3         = "#545c7e",
      dark5         = "#737aa2",
      blue          = "#7aa2f7",
      blue0         = "#3d59a1",
      blue1         = "#2ac3de",
      blue2         = "#0db9d7",
      blue5         = "#89ddff",
      blue6         = "#b4f9f8",
      blue7         = "#394b70",
      cyan          = "#7dcfff",
      green         = "#9ece6a",
      green1        = "#73daca",
      green2        = "#41a6b5",
      magenta       = "#bb9af7",
      magenta2      = "#ff007c",
      orange        = "#ff9e64",
      purple        = "#9d7cd8",
      red           = "#f7768e",
      red1          = "#db4b4b",
      teal          = "#1abc9c",
      yellow        = "#e0af68",
      terminal_black = "#414868",
      black         = "#1d202f",
      border        = "#1d202f",
      border_highlight = "#29a4bd",
      git_add       = "#449dab",
      git_change    = "#6183bb",
      git_delete    = "#914c54",
      diff_add      = "#2b485a",
      diff_change   = "#272d43",
      diff_delete   = "#52313f",
      diff_text     = "#394b70",
      hint          = "#1abc9c",
      info          = "#0db9d7",
      todo          = "#7aa2f7",
      warning       = "#e0af68",
    },
  },
  -- stylua: ignore end
}

return M
