export interface IThemeCatppuccinPalette {
  base: string
  blue: string
  crust: string
  flamingo: string
  green: string
  lavender: string
  mantle: string
  maroon: string
  mauve: string
  overlay0: string
  overlay1: string
  overlay2: string
  peach: string
  pink: string
  red: string
  rosewater: string
  sapphire: string
  sky: string
  subtext0: string
  subtext1: string
  surface0: string
  surface1: string
  surface2: string
  teal: string
  text: string
  yellow: string
}

export interface IThemeGruvboxPalette {
  aqua: string
  bg: string
  bg0: string
  bg0_h: string
  bg0_s: string
  bg1: string
  bg2: string
  bg3: string
  bg4: string
  blue: string
  dark_aqua: string
  dark_blue: string
  dark_gray: string
  dark_green: string
  dark_orange: string
  dark_purple: string
  dark_red: string
  dark_yellow: string
  fg: string
  fg0: string
  fg0_h: string
  fg0_s: string
  fg1: string
  fg2: string
  fg3: string
  fg4: string
  gray: string
  green: string
  light_gray: string
  orange: string
  purple: string
  red: string
  yellow: string
}

export interface IThemeNordPalette {
  nord0: string
  nord1: string
  nord2: string
  nord3: string
  nord4: string
  nord5: string
  nord6: string
  nord7: string
  nord8: string
  nord9: string
  nord10: string
  nord11: string
  nord12: string
  nord13: string
  nord14: string
  nord15: string
  polarNight0: string
  polarNight1: string
  polarNight2: string
  polarNight3: string
  snowStorm0: string
  snowStorm1: string
  snowStorm2: string
  frost0: string
  frost1: string
  frost2: string
  frost3: string
  aurora0: string
  aurora1: string
  aurora2: string
  aurora3: string
  aurora4: string
}

export interface IThemeOnehalfPalette {
  background: string
  black: string
  blue: string
  comment: string
  cyan: string
  foreground: string
  green: string
  gutter: string
  guide: string
  orange: string
  purple: string
  red: string
  selection: string
  white: string
  yellow: string
}

export interface IThemeRosepinePalette {
  base: string
  foam: string
  gold: string
  highlightHigh: string
  highlightLow: string
  highlightMed: string
  iris: string
  love: string
  muted: string
  overlay: string
  pine: string
  rose: string
  subtle: string
  surface: string
  text: string
}

export interface IThemeTokyonightPalette {
  bg: string
  bg_dark: string
  bg_dark1: string
  bg_highlight: string
  bg_visual: string
  fg: string
  fg_dark: string
  fg_gutter: string
  fg_sidebar: string
  comment: string
  dark3: string
  dark5: string
  blue: string
  blue0: string
  blue1: string
  blue2: string
  blue5: string
  blue6: string
  blue7: string
  cyan: string
  green: string
  green1: string
  green2: string
  magenta: string
  magenta2: string
  orange: string
  purple: string
  red: string
  red1: string
  teal: string
  yellow: string
  terminal_black: string
  black: string
  border: string
  border_highlight: string
  git_add: string
  git_change: string
  git_delete: string
  diff_add: string
  diff_change: string
  diff_delete: string
  diff_text: string
  hint: string
  info: string
  todo: string
  warning: string
}

export interface IThemeVscPalette {
  accentAqua: string
  accentBlue: string
  accentGreen: string
  accentOrange: string
  accentPink: string
  accentPurple: string
  accentRed: string
  accentYellow: string
  actionBar_toggledBackground: string
  activityBarBadge_background: string
  activityBarBadge_foreground: string
  activityBar_activeBorder: string
  activityBar_background: string
  activityBar_border: string
  activityBar_foreground: string
  activityBar_inactiveForeground: string
  badge_background: string
  badge_foreground: string
  base: string
  border: string
  borderStrong: string
  brightAqua: string
  brightBlue: string
  brightGreen: string
  brightOrange: string
  brightPurple: string
  brightRed: string
  brightYellow: string
  button_background: string
  button_border: string
  button_foreground: string
  button_hoverBackground: string
  button_secondaryBackground: string
  button_secondaryForeground: string
  button_secondaryHoverBackground: string
  chat_editedFileForeground: string
  chat_slashCommandBackground: string
  chat_slashCommandForeground: string
  checkbox_background: string
  checkbox_border: string
  debugToolBar_background: string
  descriptionForeground: string
  diffEditor_unchangedRegionBackground: string
  dropdown_background: string
  dropdown_border: string
  dropdown_foreground: string
  dropdown_listBackground: string
  editorBracket_fg0: string
  editorBracket_fg1: string
  editorBracket_fg2: string
  editorBracket_fg3: string
  editorBracket_fg4: string
  editorBracket_fg5: string
  editorBracket_fg6: string
  editorGroupHeader_tabsBackground: string
  editorGroupHeader_tabsBorder: string
  editorGroup_border: string
  editorGutter_addedBackground: string
  editorGutter_deletedBackground: string
  editorGutter_modifiedBackground: string
  editorIndentGuide_activeBackground1: string
  editorIndentGuide_background1: string
  editorLineNumber_activeForeground: string
  editorLineNumber_foreground: string
  editorOverviewRuler_border: string
  editorSuggestWidget_background: string
  editorWidget_background: string
  editor_background: string
  editor_findMatchBackground: string
  editor_foreground: string
  editor_inactiveSelectionBackground: string
  editor_selectionHighlightBackground: string
  errorForeground: string
  focusBorder: string
  foreground: string
  icon_foreground: string
  inputOption_activeBackground: string
  inputOption_activeBorder: string
  inputOption_activeForeground: string
  input_background: string
  input_border: string
  input_foreground: string
  input_placeholderForeground: string
  keybindingLabel_foreground: string
  list_activeSelectionBackground: string
  list_activeSelectionForeground: string
  list_activeSelectionIconForeground: string
  list_dropBackground: string
  list_focusAndSelectionOutline: string
  list_hoverBackground: string
  menu_background: string
  menu_border: string
  menu_foreground: string
  menu_selectionBackground: string
  menu_selectionForeground: string
  menu_separatorBackground: string
  muted: string
  notebook_cellBorderColor: string
  notebook_selectedCellBackground: string
  notificationCenterHeader_background: string
  notificationCenterHeader_foreground: string
  notifications_background: string
  notifications_border: string
  notifications_foreground: string
  overlay: string
  panelInput_border: string
  panelTitle_activeBorder: string
  panelTitle_activeForeground: string
  panelTitle_inactiveForeground: string
  panel_background: string
  panel_border: string
  peekViewEditor_background: string
  peekViewEditor_matchHighlightBackground: string
  peekViewResult_background: string
  peekViewResult_matchHighlightBackground: string
  pickerGroup_border: string
  pickerGroup_foreground: string
  ports_iconRunningProcessForeground: string
  progressBar_background: string
  quickInput_background: string
  quickInput_foreground: string
  searchEditor_textInputBorder: string
  selection: string
  semanticCustomLiteral: string
  semanticNewOperator: string
  semanticNumberLiteral: string
  semanticStringLiteral: string
  settings_dropdownBackground: string
  settings_dropdownBorder: string
  settings_headerForeground: string
  settings_modifiedItemIndicator: string
  settings_numberInputBorder: string
  settings_textInputBorder: string
  sideBarSectionHeader_background: string
  sideBarSectionHeader_border: string
  sideBarSectionHeader_foreground: string
  sideBarTitle_foreground: string
  sideBar_background: string
  sideBar_border: string
  sideBar_foreground: string
  status: string
  statusBarItem_compactHoverBackground: string
  statusBarItem_errorBackground: string
  statusBarItem_focusBorder: string
  statusBarItem_hoverBackground: string
  statusBarItem_hoverForeground: string
  statusBarItem_prominentBackground: string
  statusBarItem_remoteBackground: string
  statusBarItem_remoteForeground: string
  statusBar_background: string
  statusBar_border: string
  statusBar_debuggingBackground: string
  statusBar_debuggingForeground: string
  statusBar_focusBorder: string
  statusBar_foreground: string
  statusBar_noFolderBackground: string
  subtle: string
  success: string
  surface: string
  tab_activeBackground: string
  tab_activeBorder: string
  tab_activeBorderTop: string
  tab_activeForeground: string
  tab_border: string
  tab_hoverBackground: string
  tab_inactiveBackground: string
  tab_inactiveForeground: string
  tab_lastPinnedBorder: string
  tab_selectedBackground: string
  tab_selectedBorderTop: string
  tab_selectedForeground: string
  tab_unfocusedActiveBorder: string
  tab_unfocusedActiveBorderTop: string
  tab_unfocusedHoverBackground: string
  terminalCursor_foreground: string
  terminal_foreground: string
  terminal_inactiveSelectionBackground: string
  terminal_tab_activeBorder: string
  text: string
  textBlockQuote_background: string
  textBlockQuote_border: string
  textCodeBlock_background: string
  textDim: string
  textLink_activeForeground: string
  textLink_foreground: string
  textMuted: string
  textPreformat_background: string
  textPreformat_foreground: string
  textSeparator_foreground: string
  titleBar_activeBackground: string
  titleBar_activeForeground: string
  titleBar_border: string
  titleBar_inactiveBackground: string
  titleBar_inactiveForeground: string
  tokenBracketsOfXmlHtmlTags: string
  tokenColoringOfTheJavaImportAndPackageIdentifiers: string
  tokenComment: string
  tokenConstantCharacter: string
  tokenConstantCharacterCharacterClassRegexp: string
  tokenConstantCharacterEscape: string
  tokenConstantLanguage: string
  tokenConstantNumeric: string
  tokenConstantRegexp: string
  tokenConstantShaGitRebase: string
  tokenConstantsAndEnums: string
  tokenControlFlowSpecialKeywords: string
  tokenCssPropertyValue: string
  tokenCssTagsInSelectorsXmlTags: string
  tokenEntityNameLabel: string
  tokenEntityNameSelector: string
  tokenEntityNameTag: string
  tokenEntityNameTagCss: string
  tokenEntityOtherAttributeName: string
  tokenEntityOtherAttributeNameClassCss: string
  tokenFunctionDeclarations: string
  tokenHeader: string
  tokenInvalid: string
  tokenKeyword: string
  tokenKeywordControl: string
  tokenKeywordOperator: string
  tokenKeywordOperatorNew: string
  tokenKeywordOperatorOrRegexp: string
  tokenKeywordOperatorQuantifierRegexp: string
  tokenKeywordOtherUnit: string
  tokenMarkupBold: string
  tokenMarkupChanged: string
  tokenMarkupDeleted: string
  tokenMarkupHeading: string
  tokenMarkupInlineRaw: string
  tokenMarkupInserted: string
  tokenMetaDiffHeader: string
  tokenMetaEmbedded: string
  tokenMetaPreprocessor: string
  tokenMetaPreprocessorNumeric: string
  tokenMetaPreprocessorString: string
  tokenMetaStructureDictionaryKeyPython: string
  tokenObjectKeysTsGrammarSpecific: string
  tokenPunctuationDefinitionListBeginMarkdown: string
  tokenPunctuationDefinitionQuoteBeginMarkdown: string
  tokenPunctuationSectionEmbeddedBeginPhp: string
  tokenRegularExpressionGroups: string
  tokenResetJavaScriptStringInterpolationExpression: string
  tokenStorage: string
  tokenStorageModifier: string
  tokenStorageType: string
  tokenString: string
  tokenStringCommentBufferedBlockPug: string
  tokenStringInterpolation: string
  tokenStringRegexp: string
  tokenStringTag: string
  tokenStringValue: string
  tokenSupportConstantPropertyValue: string
  tokenSupportFunctionGitRebase: string
  tokenSupportTypePropertyNameJson: string
  tokenSupportTypeVendoredPropertyName: string
  tokenThisSelf: string
  tokenTypesDeclarationAndReferences: string
  tokenTypesDeclarationAndReferencesTsGrammarSpecific: string
  tokenVariableAndParameterName: string
  warning: string
  welcomePage_progress_foreground: string
  welcomePage_tileBackground: string
  widget_border: string
}

export interface IThemeUnifiedPalette {
  bg0: string
  bg1: string
  bg2: string
  bg3: string
  bg4: string

  fg0: string
  fg1: string
  fg2: string
  fg3: string
  fg4: string

  red: string
  green: string
  yellow: string
  blue: string
  purple: string
  aqua: string
  orange: string

  brightRed: string
  brightGreen: string
  brightYellow: string
  brightBlue: string
  brightPurple: string
  brightAqua: string
  brightOrange: string

  black: string
  white: string
  grey: string
  pink: string

  diffDel: string
  diffDelInline: string
  diffAdd: string
  diffAddInline: string

  tokenKeyword: string
  tokenString: string
  tokenFunction: string
  tokenType: string
  tokenConstant: string
  tokenVariable: string
  tokenParameter: string
  tokenComment: string
  tokenOperator: string
  tokenPunctuation: string
  tokenNumber: string
  tokenProperty: string
  tokenTag: string
  tokenAttribute: string
  tokenDecorator: string
}

export interface IThemePalette {
  catppuccin?: IThemeCatppuccinPalette
  gruvbox?: IThemeGruvboxPalette
  nord?: IThemeNordPalette
  onehalf?: IThemeOnehalfPalette
  rosepine?: IThemeRosepinePalette
  tokyonight?: IThemeTokyonightPalette
  vsc?: IThemeVscPalette
  unified: IThemeUnifiedPalette
}

export interface IThemeScheme {
  theme: string
  variant: string
  opposite: string
  darken: boolean
  uuid?: string
  palette: IThemePalette
}

export type { IReporter } from '../../src/stl/src/reporter.d.ts'

export interface IAppConfig {
  name: string
  home: string
  themes: string | null
  extname: string
  local?: string | null
  active: (app: IAppConfig) => boolean
  render: (app: IAppConfig, template: string, scheme: IThemeScheme) => Promise<string>
  after_apply?: (app: IAppConfig, scheme: IThemeScheme, reporter: IReporter) => Promise<void>
  after_gen?: (app: IAppConfig, reporter: IReporter) => Promise<void>
}
