import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { describe, it } from 'node:test'

import definition from '../../asset/theme/template/zed/meta.mjs'
import { load_theme_scheme } from './util.mjs'

const scheme = { theme: 'rosepine', variant: 'main' }
const theme = JSON.stringify({
  name: 'rosepine-main',
  themes: [{ name: 'rosepine-main', appearance: 'dark', style: {} }],
})

/** @param {import('node:test').TestContext} t */
async function createFixture(t) {
  const home = await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(), 'zed-update-')))
  t.after(() => fs.rm(home, { recursive: true, force: true }))
  const settings = path.join(home, 'settings.json')
  const globalSettings = path.join(home, definition.local)
  const themePath = path.join(home, 'themes', 'rosepine-main.json')
  await fs.writeFile(settings, '{\n  // personal preference\n  "buffer_font_size": 18,\n}\n')
  return { home, settings, globalSettings, themePath, app: { home, local: definition.local, themes: definition.themes } }
}

describe('Zed VSC mapping', () => {
  for (const [variant, background, string] of [
    ['dark-modern', '#1F1F1F', '#BA846E'],
    ['light-modern', '#FFFFFF', '#AD2F2F'],
  ]) {
    it(`preserves the independent ${variant} mapping`, async () => {
      const reporter = { error(message) { throw new Error(message) } }
      const scheme = await load_theme_scheme(reporter, `vsc-${variant}`)
      assert.ok(scheme)
      const template = await fs.readFile(new URL('../../asset/theme/template/zed/vsc.hbs', import.meta.url), 'utf8')
      const output = await definition.on_render({}, template, scheme)
      const theme = JSON.parse(output).themes[0]
      assert.equal(theme.name, `vsc-${variant}`)
      assert.equal(theme.style['editor.background'], background)
      assert.equal(theme.style.syntax.string.color, string)
      assert.equal(theme.style.syntax.keyword.color, scheme.palette.vsc.tokenControlFlowSpecialKeywords)
      assert.notEqual(theme.style.syntax.string.color, scheme.palette.unified.tokenString)
      assert.doesNotMatch(output, /\{\{|[\t ]+$/m)
    })
  }
})

describe('Zed settings updates', { concurrency: false }, () => {
  it('selects the complete theme name through the generated layer without touching user settings', async t => {
    const { app, settings, globalSettings, themePath } = await createFixture(t)
    const source = await fs.readFile(settings, 'utf8')
    const before = await fs.stat(settings)
    await definition.on_prepare(app, theme, scheme)
    await definition.on_apply(app, theme, scheme)
    assert.equal(await fs.readFile(settings, 'utf8'), source)
    const after = await fs.stat(settings)
    for (const key of ['ino', 'mode', 'size', 'mtimeMs', 'ctimeMs']) assert.equal(after[key], before[key], key)
    assert.equal(await fs.readFile(themePath, 'utf8'), theme)
    const generated = await fs.readFile(globalSettings, 'utf8')
    assert.match(generated, /^\/\/ Generated by the theme CLI\./)
    assert.deepEqual(JSON.parse(generated.slice(generated.indexOf('\n') + 1)), { theme: 'rosepine-main' })
  })

  it('preserves settings saved while publishing the theme', async t => {
    const { app, settings, themePath } = await createFixture(t)
    const concurrent = '{\n  // keep this preference\n  "buffer_font_size": 24,\n}\n'
    const rename = fs.rename.bind(fs)
    t.mock.method(fs, 'rename', async (source, target) => {
      await rename(source, target)
      if (target === themePath) await fs.writeFile(settings, concurrent)
    })
    await definition.on_prepare(app, theme, scheme)
    await definition.on_apply(app, theme, scheme)
    assert.equal(await fs.readFile(settings, 'utf8'), concurrent)
  })

  it('preserves a user save immediately before the final settings rename', async t => {
    const { app, settings, globalSettings, home } = await createFixture(t)
    const concurrent = '{"buffer_font_size":24,"nested":{"keep":true}}'
    const rename = fs.rename.bind(fs)
    let saved = false
    t.mock.method(fs, 'rename', async (source, target) => {
      if (target === globalSettings) {
        await fs.writeFile(settings, concurrent)
        saved = true
      }
      await rename(source, target)
    })
    await definition.on_apply(app, theme, scheme)
    assert.equal(saved, true)
    assert.equal(await fs.readFile(settings, 'utf8'), concurrent)
    assert.deepEqual((await fs.readdir(home)).sort(), ['global_settings.json', 'settings.json', 'themes'])
  })

  it('retains explicit user theme overrides and settings symlinks', { skip: process.platform === 'win32' }, async t => {
    const { app, settings, home } = await createFixture(t)
    const target = path.join(home, 'personal.json')
    const source = '{"theme":"manually-selected","buffer_font_size":24}'
    await fs.rename(settings, target)
    await fs.writeFile(target, source)
    await fs.symlink(target, settings)
    await definition.on_apply(app, theme, scheme)
    assert.equal((await fs.lstat(settings)).isSymbolicLink(), true)
    assert.equal(await fs.readFile(target, 'utf8'), source)
  })

  it('refuses to take over an existing unmanaged global settings file', async t => {
    const { app, globalSettings, home } = await createFixture(t)
    const source = '{"buffer_font_size":24}'
    await fs.writeFile(globalSettings, source)
    await assert.rejects(definition.on_prepare(app, theme, scheme), /unmanaged Zed settings/)
    await assert.rejects(definition.on_apply(app, theme, scheme), /unmanaged Zed settings/)
    assert.equal(await fs.readFile(globalSettings, 'utf8'), source)
    assert.deepEqual((await fs.readdir(home)).sort(), ['global_settings.json', 'settings.json'])
  })

  it('keeps the previous selection when publishing the theme fails', async t => {
    const { app, settings, globalSettings, themePath, home } = await createFixture(t)
    await definition.on_apply(app, theme, scheme)
    const previous = await fs.readFile(globalSettings, 'utf8')
    const personal = await fs.readFile(settings, 'utf8')
    const rename = fs.rename.bind(fs)
    t.mock.method(fs, 'rename', async (source, target) => {
      if (target === themePath) throw new Error('theme publication failed')
      await rename(source, target)
    })
    await assert.rejects(definition.on_apply(app, theme + '\n', scheme), /theme publication failed/)
    assert.equal(await fs.readFile(globalSettings, 'utf8'), previous)
    assert.equal(await fs.readFile(settings, 'utf8'), personal)
    assert.deepEqual((await fs.readdir(home)).sort(), ['global_settings.json', 'settings.json', 'themes'])
  })

  it('keeps user settings and the previous selection when publishing global settings fails', async t => {
    const { app, settings, globalSettings, home } = await createFixture(t)
    await definition.on_apply(app, theme, scheme)
    const previous = await fs.readFile(globalSettings, 'utf8')
    const personal = await fs.readFile(settings, 'utf8')
    const rename = fs.rename.bind(fs)
    t.mock.method(fs, 'rename', async (source, target) => {
      if (target === globalSettings) throw new Error('selection publication failed')
      await rename(source, target)
    })
    await assert.rejects(definition.on_apply(app, '{}', { theme: 'rosepine', variant: 'moon' }), /selection publication failed/)
    assert.equal(await fs.readFile(globalSettings, 'utf8'), previous)
    assert.equal(await fs.readFile(settings, 'utf8'), personal)
    assert.deepEqual((await fs.readdir(home)).sort(), ['global_settings.json', 'settings.json', 'themes'])
  })

  for (const mask of [0o022, 0o077]) {
    it(`preserves existing modes under umask ${mask.toString(8)}`, { skip: process.platform === 'win32' }, async t => {
      const { app, settings, globalSettings, themePath } = await createFixture(t)
      await definition.on_apply(app, theme, scheme)
      const previousSelection = await fs.readFile(globalSettings, 'utf8')
      await fs.writeFile(globalSettings, previousSelection.replace('rosepine-main', 'rosepine-moon'))
      await fs.writeFile(themePath, 'old theme')
      await fs.chmod(settings, 0o664)
      await fs.chmod(globalSettings, 0o664)
      await fs.chmod(themePath, 0o640)
      const previous = process.umask(mask)
      try {
        await definition.on_apply(app, theme, scheme)
        assert.equal((await fs.stat(settings)).mode & 0o777, 0o664)
        assert.equal((await fs.stat(globalSettings)).mode & 0o777, 0o664)
        assert.equal((await fs.stat(themePath)).mode & 0o777, 0o640)
      } finally {
        process.umask(previous)
      }
    })
  }

  it('keeps restrictive umask permissions for newly generated files', { skip: process.platform === 'win32' }, async t => {
    const { app, globalSettings, themePath } = await createFixture(t)
    const previous = process.umask(0o077)
    try {
      await definition.on_apply(app, theme, scheme)
      assert.equal((await fs.stat(themePath)).mode & 0o777, 0o600)
      assert.equal((await fs.stat(globalSettings)).mode & 0o777, 0o600)
    } finally {
      process.umask(previous)
    }
  })
})
