# Bash completion for kit
# Generated by @guanghechen/commander

_kit_completions() {
  local cur prev words cword
  _init_completion || return

  case "${words[1]}" in
    pm)
    case "${words[2]}" in
      daemon)
      opts="-h --help --no-help -V --version --no-version"
        ;;
      list|ls)
      opts="-h --help --no-help -V --version --no-version"
        ;;
      start)
      opts="-h --help --no-help -V --version --no-version"
        ;;
      add)
      opts="-h --help --no-help -V --version --no-version"
        ;;
      restart)
      opts="-h --help --no-help -V --version --no-version"
        ;;
      stop)
      opts="-h --help --no-help -V --version --no-version"
        ;;
      kill)
      opts="-h --help --no-help -V --version --no-version"
        ;;
      clean|flush)
      opts="-h --help --no-help -V --version --no-version"
        ;;
      show|logs)
      opts="-h --help --no-help -V --version --no-version --track --no-track -n --lines --type"
        ;;
      save)
      opts="-h --help --no-help -V --version --no-version"
        ;;
      kill-daemon)
      opts="-h --help --no-help -V --version --no-version"
        ;;
      monit)
      opts="-h --help --no-help -V --version --no-version"
        ;;
      *)
        opts="-h --help --no-help -V --version --no-version daemon list ls start add restart stop kill clean flush show logs save kill-daemon monit"
        ;;
    esac
      ;;
    file|f)
    case "${words[2]}" in
      split|s)
      opts="-h --help --no-help -V --version --no-version -o --output --part-size --part-total --part-code-prefix"
        ;;
      merge|m)
      opts="-h --help --no-help -V --version --no-version -o --output --part-code-prefix"
        ;;
      *)
        opts="-h --help --no-help -V --version --no-version split s merge m"
        ;;
    esac
      ;;
    copilot|cp)
    case "${words[2]}" in
      start)
      opts="-h --help --no-help -V --version --no-version -H --host -p --port -l --log-path --log-level --colorful --no-colorful --devmode --no-devmode --strict --no-strict --filter-tools"
        ;;
      auth)
      opts="-h --help --no-help -V --version --no-version --force --no-force"
        ;;
      *)
        opts="-h --help --no-help -V --version --no-version start auth"
        ;;
    esac
      ;;
    copy|c)
    opts="-h --help --no-help -V --version --no-version -f --file"
      ;;
    paste|p)
    opts="-h --help --no-help -V --version --no-version -o --output -a --append"
      ;;
    video|v)
    case "${words[2]}" in
      checkhealth)
      opts="-h --help --no-help -V --version --no-version --log-level -v --verbose --no-verbose -t --test --no-test -c --category"
        ;;
      prepare)
      opts="-h --help --no-help -V --version --no-version -w --workspace-dir -s --scenario -m --material-path -q --query -n --name --log-level -v --verbose --no-verbose"
        ;;
      preference)
      opts="-h --help --no-help -V --version --no-version -w --workspace-dir --log-level --force --no-force -v --verbose --no-verbose"
        ;;
      outline)
      opts="-h --help --no-help -V --version --no-version -w --workspace-dir --log-level --force --no-force -v --verbose --no-verbose"
        ;;
      transcript)
      opts="-h --help --no-help -V --version --no-version -w --workspace-dir --log-level --force --no-force -v --verbose --no-verbose"
        ;;
      image)
      opts="-h --help --no-help -V --version --no-version -w --workspace-dir --log-level --force --no-force -v --verbose --no-verbose --source --quality --parallel --slides"
        ;;
      ocr)
      opts="-h --help --no-help -V --version --no-version -w --workspace-dir --log-level --force --no-force -v --verbose --no-verbose --provider --parallel"
        ;;
      pdf)
      opts="-h --help --no-help -V --version --no-version -w --workspace-dir --log-level --force --no-force -v --verbose --no-verbose"
        ;;
      pptx)
      opts="-h --help --no-help -V --version --no-version -w --workspace-dir --log-level --force --no-force -v --verbose --no-verbose"
        ;;
      tts)
      opts="-h --help --no-help -V --version --no-version -w --workspace-dir --log-level --force --no-force -v --verbose --no-verbose --source --speech-voice"
        ;;
      tts-align)
      opts="-h --help --no-help -V --version --no-version -w --workspace-dir --log-level --force --no-force -v --verbose --no-verbose --stt --no-stt --srt --no-srt"
        ;;
      video)
      opts="-h --help --no-help -V --version --no-version -w --workspace-dir --log-level --force --no-force -v --verbose --no-verbose --srt --no-srt --transition --transition-duration"
        ;;
      autogen)
      opts="-h --help --no-help -V --version --no-version -s --scenario -o --output --pdf --no-pdf --pptx --no-pptx --tts --no-tts --video --no-video --ocr --no-ocr --dry-run --no-dry-run -v --verbose --no-verbose --debug --no-debug --silent --no-silent --image-source --image-quality --tts-source --speech-voice --transition --transition-duration --stage-image-parallel --stage-ocr-parallel --stt --no-stt --srt --no-srt --query --query-path --force-prepare --no-force-prepare --only-prepare --no-only-prepare --force-preference --no-force-preference --only-preference --no-only-preference --force-outline --no-force-outline --only-outline --no-only-outline --force-transcript --no-force-transcript --only-transcript --no-only-transcript --force-image --no-force-image --only-image --no-only-image --force-ocr --no-force-ocr --only-ocr --no-only-ocr --force-pdf --no-force-pdf --only-pdf --no-only-pdf --force-pptx --no-force-pptx --only-pptx --no-only-pptx --force-tts --no-force-tts --only-tts --no-only-tts --force-tts-align --no-force-tts-align --only-tts-align --no-only-tts-align --force-video --no-force-video --only-video --no-only-video"
        ;;
      *)
        opts="-h --help --no-help -V --version --no-version checkhealth prepare preference outline transcript image ocr pdf pptx tts tts-align video autogen"
        ;;
    esac
      ;;
    wsl)
    case "${words[2]}" in
      path)
      opts="-h --help --no-help -V --version --no-version"
        ;;
      *)
        opts="-h --help --no-help -V --version --no-version path"
        ;;
    esac
      ;;
    completion)
    opts="-h --help --no-help -V --version --no-version --bash --no-bash --fish --no-fish --pwsh --no-pwsh -w --write"
      ;;
    *)
      opts="-h --help --no-help -V --version --no-version pm file f copilot cp copy c paste p video v wsl completion"
      ;;
  esac

  COMPREPLY=($(compgen -W "$opts" -- "$cur"))
}

complete -F _kit_completions kit
