# PowerShell completion for kit
# Generated by @guanghechen/commander

Register-ArgumentCompleter -Native -CommandName kit -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)

  $commands = @{
    description = 'Unified CLI for all kit tools'
    options = @(
      @{
        long = 'color'
        description = 'Enable colored help output'
        type = 'boolean'
        args = 'none'
        canNegate = $true
      }
      @{
        long = 'log-level'
        description = 'Set log level'
        type = 'string'
        args = 'required'
        canNegate = $false
        choices = @('debug', 'info', 'hint', 'warn', 'error')
      }
      @{
        long = 'silent'
        description = 'Suppress non-error output'
        type = 'boolean'
        args = 'none'
        canNegate = $true
      }
      @{
        long = 'log-date'
        description = 'Enable log timestamp'
        type = 'boolean'
        args = 'none'
        canNegate = $true
      }
      @{
        long = 'log-colorful'
        description = 'Enable colorful log output'
        type = 'boolean'
        args = 'none'
        canNegate = $true
      }
      @{
        long = 'help'
        description = 'Show help information'
        type = 'boolean'
        args = 'none'
        canNegate = $false
      }
      @{
        long = 'version'
        description = 'Show version number'
        type = 'boolean'
        args = 'none'
        canNegate = $false
      }
    )
    arguments = @(
    )
    subcommands = @{
      'pm' = @{
        description = 'Lightweight Node.js process manager'
        options = @(
          @{
            long = 'color'
            description = 'Enable colored help output'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'log-level'
            description = 'Set log level'
            type = 'string'
            args = 'required'
            canNegate = $false
            choices = @('debug', 'info', 'hint', 'warn', 'error')
          }
          @{
            long = 'silent'
            description = 'Suppress non-error output'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'log-date'
            description = 'Enable log timestamp'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'log-colorful'
            description = 'Enable colorful log output'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'help'
            description = 'Show help information'
            type = 'boolean'
            args = 'none'
            canNegate = $false
          }
          @{
            long = 'version'
            description = 'Show version number'
            type = 'boolean'
            args = 'none'
            canNegate = $false
          }
        )
        arguments = @(
        )
        subcommands = @{
          'daemon' = @{
            description = 'Start the daemon process'
            options = @(
              @{
                long = 'color'
                description = 'Enable colored help output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-level'
                description = 'Set log level'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('debug', 'info', 'hint', 'warn', 'error')
              }
              @{
                long = 'silent'
                description = 'Suppress non-error output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-date'
                description = 'Enable log timestamp'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-colorful'
                description = 'Enable colorful log output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'help'
                description = 'Show help information'
                type = 'boolean'
                args = 'none'
                canNegate = $false
              }
            )
            arguments = @(
            )
          }
          'list' = @{
            description = 'List all apps'
            options = @(
              @{
                long = 'color'
                description = 'Enable colored help output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-level'
                description = 'Set log level'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('debug', 'info', 'hint', 'warn', 'error')
              }
              @{
                long = 'silent'
                description = 'Suppress non-error output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-date'
                description = 'Enable log timestamp'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-colorful'
                description = 'Enable colorful log output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'help'
                description = 'Show help information'
                type = 'boolean'
                args = 'none'
                canNegate = $false
              }
            )
            arguments = @(
            )
          }
          'ls' = @{
            description = 'List all apps'
            options = @(
              @{
                long = 'color'
                description = 'Enable colored help output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-level'
                description = 'Set log level'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('debug', 'info', 'hint', 'warn', 'error')
              }
              @{
                long = 'silent'
                description = 'Suppress non-error output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-date'
                description = 'Enable log timestamp'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-colorful'
                description = 'Enable colorful log output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'help'
                description = 'Show help information'
                type = 'boolean'
                args = 'none'
                canNegate = $false
              }
            )
            arguments = @(
            )
          }
          'start' = @{
            description = 'Start apps from config file'
            options = @(
              @{
                long = 'color'
                description = 'Enable colored help output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-level'
                description = 'Set log level'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('debug', 'info', 'hint', 'warn', 'error')
              }
              @{
                long = 'silent'
                description = 'Suppress non-error output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-date'
                description = 'Enable log timestamp'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-colorful'
                description = 'Enable colorful log output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'help'
                description = 'Show help information'
                type = 'boolean'
                args = 'none'
                canNegate = $false
              }
            )
            arguments = @(
              @{
                name = 'target'
                kind = 'optional'
                type = 'string'
              }
            )
          }
          'add' = @{
            description = 'Add apps from config file (without starting)'
            options = @(
              @{
                long = 'color'
                description = 'Enable colored help output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-level'
                description = 'Set log level'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('debug', 'info', 'hint', 'warn', 'error')
              }
              @{
                long = 'silent'
                description = 'Suppress non-error output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-date'
                description = 'Enable log timestamp'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-colorful'
                description = 'Enable colorful log output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'help'
                description = 'Show help information'
                type = 'boolean'
                args = 'none'
                canNegate = $false
              }
            )
            arguments = @(
              @{
                name = 'config'
                kind = 'required'
                type = 'string'
              }
            )
          }
          'restart' = @{
            description = 'Restart app(s)'
            options = @(
              @{
                long = 'color'
                description = 'Enable colored help output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-level'
                description = 'Set log level'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('debug', 'info', 'hint', 'warn', 'error')
              }
              @{
                long = 'silent'
                description = 'Suppress non-error output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-date'
                description = 'Enable log timestamp'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-colorful'
                description = 'Enable colorful log output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'help'
                description = 'Show help information'
                type = 'boolean'
                args = 'none'
                canNegate = $false
              }
            )
            arguments = @(
              @{
                name = 'target'
                kind = 'optional'
                type = 'string'
              }
            )
          }
          'stop' = @{
            description = 'Stop app(s)'
            options = @(
              @{
                long = 'color'
                description = 'Enable colored help output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-level'
                description = 'Set log level'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('debug', 'info', 'hint', 'warn', 'error')
              }
              @{
                long = 'silent'
                description = 'Suppress non-error output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-date'
                description = 'Enable log timestamp'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-colorful'
                description = 'Enable colorful log output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'help'
                description = 'Show help information'
                type = 'boolean'
                args = 'none'
                canNegate = $false
              }
            )
            arguments = @(
              @{
                name = 'target'
                kind = 'optional'
                type = 'string'
              }
            )
          }
          'kill' = @{
            description = 'Kill apps/daemon by mode'
            options = @(
              @{
                long = 'color'
                description = 'Enable colored help output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-level'
                description = 'Set log level'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('debug', 'info', 'hint', 'warn', 'error')
              }
              @{
                long = 'silent'
                description = 'Suppress non-error output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-date'
                description = 'Enable log timestamp'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-colorful'
                description = 'Enable colorful log output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'help'
                description = 'Show help information'
                type = 'boolean'
                args = 'none'
                canNegate = $false
              }
            )
            arguments = @(
              @{
                name = 'mode'
                kind = 'required'
                type = 'choice'
                choices = @('processes', 'daemon', 'all')
              }
              @{
                name = 'target'
                kind = 'optional'
                type = 'string'
              }
            )
          }
          'clean' = @{
            description = 'Clean resources by scope'
            options = @(
              @{
                long = 'color'
                description = 'Enable colored help output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-level'
                description = 'Set log level'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('debug', 'info', 'hint', 'warn', 'error')
              }
              @{
                long = 'silent'
                description = 'Suppress non-error output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-date'
                description = 'Enable log timestamp'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-colorful'
                description = 'Enable colorful log output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'help'
                description = 'Show help information'
                type = 'boolean'
                args = 'none'
                canNegate = $false
              }
            )
            arguments = @(
              @{
                name = 'scope'
                kind = 'required'
                type = 'choice'
                choices = @('logs')
              }
            )
          }
          'flush' = @{
            description = 'Clean resources by scope'
            options = @(
              @{
                long = 'color'
                description = 'Enable colored help output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-level'
                description = 'Set log level'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('debug', 'info', 'hint', 'warn', 'error')
              }
              @{
                long = 'silent'
                description = 'Suppress non-error output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-date'
                description = 'Enable log timestamp'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-colorful'
                description = 'Enable colorful log output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'help'
                description = 'Show help information'
                type = 'boolean'
                args = 'none'
                canNegate = $false
              }
            )
            arguments = @(
              @{
                name = 'scope'
                kind = 'required'
                type = 'choice'
                choices = @('logs')
              }
            )
          }
          'show' = @{
            description = 'Show app logs'
            options = @(
              @{
                long = 'color'
                description = 'Enable colored help output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-level'
                description = 'Set log level'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('debug', 'info', 'hint', 'warn', 'error')
              }
              @{
                long = 'silent'
                description = 'Suppress non-error output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-date'
                description = 'Enable log timestamp'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-colorful'
                description = 'Enable colorful log output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'track'
                description = 'Track logs in real-time (default: false)'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                short = 'n'
                long = 'lines'
                description = 'Number of lines to show'
                type = 'number'
                args = 'required'
                canNegate = $false
              }
              @{
                long = 'type'
                description = 'Log type: stdout, stderr, both'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('stdout', 'stderr', 'both')
              }
              @{
                long = 'help'
                description = 'Show help information'
                type = 'boolean'
                args = 'none'
                canNegate = $false
              }
            )
            arguments = @(
              @{
                name = 'appName'
                kind = 'required'
                type = 'string'
              }
            )
          }
          'logs' = @{
            description = 'Track app logs in real-time'
            options = @(
              @{
                long = 'color'
                description = 'Enable colored help output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-level'
                description = 'Set log level'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('debug', 'info', 'hint', 'warn', 'error')
              }
              @{
                long = 'silent'
                description = 'Suppress non-error output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-date'
                description = 'Enable log timestamp'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-colorful'
                description = 'Enable colorful log output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'track'
                description = 'Track logs in real-time (default: true)'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                short = 'n'
                long = 'lines'
                description = 'Number of lines to show'
                type = 'number'
                args = 'required'
                canNegate = $false
              }
              @{
                long = 'type'
                description = 'Log type: stdout, stderr, both'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('stdout', 'stderr', 'both')
              }
              @{
                long = 'help'
                description = 'Show help information'
                type = 'boolean'
                args = 'none'
                canNegate = $false
              }
            )
            arguments = @(
              @{
                name = 'appName'
                kind = 'required'
                type = 'string'
              }
            )
          }
          'monit' = @{
            description = 'Real-time app monitoring'
            options = @(
              @{
                long = 'color'
                description = 'Enable colored help output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-level'
                description = 'Set log level'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('debug', 'info', 'hint', 'warn', 'error')
              }
              @{
                long = 'silent'
                description = 'Suppress non-error output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-date'
                description = 'Enable log timestamp'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-colorful'
                description = 'Enable colorful log output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'help'
                description = 'Show help information'
                type = 'boolean'
                args = 'none'
                canNegate = $false
              }
            )
            arguments = @(
            )
          }
        }
      }
      'file' = @{
        description = 'CLI tool to split / merge big files'
        options = @(
          @{
            long = 'color'
            description = 'Enable colored help output'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'log-level'
            description = 'Set log level'
            type = 'string'
            args = 'required'
            canNegate = $false
            choices = @('debug', 'info', 'hint', 'warn', 'error')
          }
          @{
            long = 'silent'
            description = 'Suppress non-error output'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'log-date'
            description = 'Enable log timestamp'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'log-colorful'
            description = 'Enable colorful log output'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'help'
            description = 'Show help information'
            type = 'boolean'
            args = 'none'
            canNegate = $false
          }
          @{
            long = 'version'
            description = 'Show version number'
            type = 'boolean'
            args = 'none'
            canNegate = $false
          }
        )
        arguments = @(
        )
        subcommands = @{
          'split' = @{
            description = 'Split big file into multiple parts'
            options = @(
              @{
                long = 'color'
                description = 'Enable colored help output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-level'
                description = 'Set log level'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('debug', 'info', 'hint', 'warn', 'error')
              }
              @{
                long = 'silent'
                description = 'Suppress non-error output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-date'
                description = 'Enable log timestamp'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-colorful'
                description = 'Enable colorful log output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                short = 'o'
                long = 'output'
                description = 'Output directory for split parts'
                type = 'string'
                args = 'required'
                canNegate = $false
              }
              @{
                long = 'part-size'
                description = 'Maximum bytes of each file part (e.g., 1MB, 512KB)'
                type = 'string'
                args = 'required'
                canNegate = $false
              }
              @{
                long = 'part-total'
                description = 'Number of file parts (used when partSize is not specified)'
                type = 'number'
                args = 'required'
                canNegate = $false
              }
              @{
                long = 'part-code-prefix'
                description = 'Prefix for each file part code'
                type = 'string'
                args = 'required'
                canNegate = $false
              }
              @{
                long = 'help'
                description = 'Show help information'
                type = 'boolean'
                args = 'none'
                canNegate = $false
              }
            )
            arguments = @(
              @{
                name = 'filepath'
                kind = 'required'
                type = 'string'
              }
            )
          }
          's' = @{
            description = 'Split big file into multiple parts'
            options = @(
              @{
                long = 'color'
                description = 'Enable colored help output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-level'
                description = 'Set log level'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('debug', 'info', 'hint', 'warn', 'error')
              }
              @{
                long = 'silent'
                description = 'Suppress non-error output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-date'
                description = 'Enable log timestamp'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-colorful'
                description = 'Enable colorful log output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                short = 'o'
                long = 'output'
                description = 'Output directory for split parts'
                type = 'string'
                args = 'required'
                canNegate = $false
              }
              @{
                long = 'part-size'
                description = 'Maximum bytes of each file part (e.g., 1MB, 512KB)'
                type = 'string'
                args = 'required'
                canNegate = $false
              }
              @{
                long = 'part-total'
                description = 'Number of file parts (used when partSize is not specified)'
                type = 'number'
                args = 'required'
                canNegate = $false
              }
              @{
                long = 'part-code-prefix'
                description = 'Prefix for each file part code'
                type = 'string'
                args = 'required'
                canNegate = $false
              }
              @{
                long = 'help'
                description = 'Show help information'
                type = 'boolean'
                args = 'none'
                canNegate = $false
              }
            )
            arguments = @(
              @{
                name = 'filepath'
                kind = 'required'
                type = 'string'
              }
            )
          }
          'merge' = @{
            description = 'Merge file parts into the complete file'
            options = @(
              @{
                long = 'color'
                description = 'Enable colored help output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-level'
                description = 'Set log level'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('debug', 'info', 'hint', 'warn', 'error')
              }
              @{
                long = 'silent'
                description = 'Suppress non-error output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-date'
                description = 'Enable log timestamp'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-colorful'
                description = 'Enable colorful log output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                short = 'o'
                long = 'output'
                description = 'Output filepath for the merged file'
                type = 'string'
                args = 'required'
                canNegate = $false
              }
              @{
                long = 'part-code-prefix'
                description = 'Prefix for each file part code'
                type = 'string'
                args = 'required'
                canNegate = $false
              }
              @{
                long = 'help'
                description = 'Show help information'
                type = 'boolean'
                args = 'none'
                canNegate = $false
              }
            )
            arguments = @(
              @{
                name = 'filepath'
                kind = 'required'
                type = 'string'
              }
            )
          }
          'm' = @{
            description = 'Merge file parts into the complete file'
            options = @(
              @{
                long = 'color'
                description = 'Enable colored help output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-level'
                description = 'Set log level'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('debug', 'info', 'hint', 'warn', 'error')
              }
              @{
                long = 'silent'
                description = 'Suppress non-error output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-date'
                description = 'Enable log timestamp'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-colorful'
                description = 'Enable colorful log output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                short = 'o'
                long = 'output'
                description = 'Output filepath for the merged file'
                type = 'string'
                args = 'required'
                canNegate = $false
              }
              @{
                long = 'part-code-prefix'
                description = 'Prefix for each file part code'
                type = 'string'
                args = 'required'
                canNegate = $false
              }
              @{
                long = 'help'
                description = 'Show help information'
                type = 'boolean'
                args = 'none'
                canNegate = $false
              }
            )
            arguments = @(
              @{
                name = 'filepath'
                kind = 'required'
                type = 'string'
              }
            )
          }
        }
      }
      'copilot' = @{
        description = 'Copilot Proxy Server - Route AI requests through GitHub Copilot'
        options = @(
          @{
            long = 'color'
            description = 'Enable colored help output'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'log-level'
            description = 'Set log level'
            type = 'string'
            args = 'required'
            canNegate = $false
            choices = @('debug', 'info', 'hint', 'warn', 'error')
          }
          @{
            long = 'silent'
            description = 'Suppress non-error output'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'log-date'
            description = 'Enable log timestamp'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'log-colorful'
            description = 'Enable colorful log output'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'help'
            description = 'Show help information'
            type = 'boolean'
            args = 'none'
            canNegate = $false
          }
          @{
            long = 'version'
            description = 'Show version number'
            type = 'boolean'
            args = 'none'
            canNegate = $false
          }
        )
        arguments = @(
        )
        subcommands = @{
          'start' = @{
            description = 'Start the Copilot proxy server'
            options = @(
              @{
                long = 'color'
                description = 'Enable colored help output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-level'
                description = 'Set log level'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('debug', 'info', 'hint', 'warn', 'error')
              }
              @{
                long = 'silent'
                description = 'Suppress non-error output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-date'
                description = 'Enable log timestamp'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-colorful'
                description = 'Enable colorful log output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                short = 'H'
                long = 'host'
                description = 'Host to bind to'
                type = 'string'
                args = 'required'
                canNegate = $false
              }
              @{
                short = 'p'
                long = 'port'
                description = 'Port to listen on'
                type = 'number'
                args = 'required'
                canNegate = $false
              }
              @{
                short = 'l'
                long = 'log-path'
                description = 'Log file path (disabled by default)'
                type = 'string'
                args = 'required'
                canNegate = $false
              }
              @{
                long = 'colorful'
                description = 'Enable colorful log output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'devmode'
                description = 'Disable log sanitization and truncation for debugging'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'strict'
                description = 'Enable strict request validation with Zod'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'filter-tools'
                description = 'Comma-separated tool types to filter out (e.g., web_search,mcp,local_shell)'
                type = 'string'
                args = 'required'
                canNegate = $false
              }
              @{
                long = 'help'
                description = 'Show help information'
                type = 'boolean'
                args = 'none'
                canNegate = $false
              }
            )
            arguments = @(
            )
          }
          'auth' = @{
            description = 'Authenticate with GitHub and store GH_PRIMARY_TOKEN'
            options = @(
              @{
                long = 'color'
                description = 'Enable colored help output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-level'
                description = 'Set log level'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('debug', 'info', 'hint', 'warn', 'error')
              }
              @{
                long = 'silent'
                description = 'Suppress non-error output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-date'
                description = 'Enable log timestamp'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-colorful'
                description = 'Enable colorful log output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'force'
                description = 'Force re-authentication even if token exists'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'help'
                description = 'Show help information'
                type = 'boolean'
                args = 'none'
                canNegate = $false
              }
            )
            arguments = @(
            )
          }
        }
      }
      'copy' = @{
        description = 'Copy content to system clipboard'
        options = @(
          @{
            long = 'color'
            description = 'Enable colored help output'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'log-level'
            description = 'Set log level'
            type = 'string'
            args = 'required'
            canNegate = $false
            choices = @('debug', 'info', 'hint', 'warn', 'error')
          }
          @{
            long = 'silent'
            description = 'Suppress non-error output'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'log-date'
            description = 'Enable log timestamp'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'log-colorful'
            description = 'Enable colorful log output'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            short = 'f'
            long = 'file'
            description = 'Read content from file'
            type = 'string'
            args = 'required'
            canNegate = $false
          }
          @{
            long = 'trim'
            description = 'Trim input content before copying to clipboard'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'help'
            description = 'Show help information'
            type = 'boolean'
            args = 'none'
            canNegate = $false
          }
          @{
            long = 'version'
            description = 'Show version number'
            type = 'boolean'
            args = 'none'
            canNegate = $false
          }
        )
        arguments = @(
          @{
            name = 'text'
            kind = 'optional'
            type = 'string'
          }
        )
      }
      'paste' = @{
        description = 'Paste content from system clipboard'
        options = @(
          @{
            long = 'color'
            description = 'Enable colored help output'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'log-level'
            description = 'Set log level'
            type = 'string'
            args = 'required'
            canNegate = $false
            choices = @('debug', 'info', 'hint', 'warn', 'error')
          }
          @{
            long = 'silent'
            description = 'Suppress non-error output'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'log-date'
            description = 'Enable log timestamp'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'log-colorful'
            description = 'Enable colorful log output'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            short = 'o'
            long = 'output'
            description = 'Write output to file instead of stdout'
            type = 'string'
            args = 'required'
            canNegate = $false
          }
          @{
            short = 'a'
            long = 'append'
            description = 'Append to file instead of overwriting (use with --output)'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'help'
            description = 'Show help information'
            type = 'boolean'
            args = 'none'
            canNegate = $false
          }
          @{
            long = 'version'
            description = 'Show version number'
            type = 'boolean'
            args = 'none'
            canNegate = $false
          }
        )
        arguments = @(
        )
      }
      'profile' = @{
        description = 'Render profile environment variables as shell commands'
        options = @(
          @{
            long = 'color'
            description = 'Enable colored help output'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'log-level'
            description = 'Set log level'
            type = 'string'
            args = 'required'
            canNegate = $false
            choices = @('debug', 'info', 'hint', 'warn', 'error')
          }
          @{
            long = 'silent'
            description = 'Suppress non-error output'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'log-date'
            description = 'Enable log timestamp'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'log-colorful'
            description = 'Enable colorful log output'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            short = 'p'
            long = 'profile'
            description = 'Profile selector: <name> or <name>:<variant>'
            type = 'string'
            args = 'required'
            canNegate = $false
          }
          @{
            long = 'set'
            description = 'Template values in key:value format (variadic tokens)'
            type = 'string'
            args = 'variadic'
            canNegate = $false
          }
          @{
            long = 'allow-env'
            description = 'Allow blocked env keys explicitly (variadic tokens)'
            type = 'string'
            args = 'variadic'
            canNegate = $false
          }
          @{
            short = 's'
            long = 'shell'
            description = 'Target shell type: fish, bash, pwsh'
            type = 'string'
            args = 'required'
            canNegate = $false
          }
          @{
            long = 'fish'
            description = 'Shorthand for --shell fish'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'bash'
            description = 'Shorthand for --shell bash'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'pwsh'
            description = 'Shorthand for --shell pwsh'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'help'
            description = 'Show help information'
            type = 'boolean'
            args = 'none'
            canNegate = $false
          }
          @{
            long = 'version'
            description = 'Show version number'
            type = 'boolean'
            args = 'none'
            canNegate = $false
          }
        )
        arguments = @(
        )
      }
      'repo' = @{
        description = 'Git repository sync tool based on worktree mode'
        options = @(
          @{
            long = 'color'
            description = 'Enable colored help output'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'log-level'
            description = 'Set log level'
            type = 'string'
            args = 'required'
            canNegate = $false
            choices = @('debug', 'info', 'hint', 'warn', 'error')
          }
          @{
            long = 'silent'
            description = 'Suppress non-error output'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'log-date'
            description = 'Enable log timestamp'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'log-colorful'
            description = 'Enable colorful log output'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'help'
            description = 'Show help information'
            type = 'boolean'
            args = 'none'
            canNegate = $false
          }
          @{
            long = 'version'
            description = 'Show version number'
            type = 'boolean'
            args = 'none'
            canNegate = $false
          }
        )
        arguments = @(
        )
        subcommands = @{
          'sync' = @{
            description = 'Sync repositories based on edition'
            options = @(
              @{
                long = 'color'
                description = 'Enable colored help output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-level'
                description = 'Set log level'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('debug', 'info', 'hint', 'warn', 'error')
              }
              @{
                long = 'silent'
                description = 'Suppress non-error output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-date'
                description = 'Enable log timestamp'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-colorful'
                description = 'Enable colorful log output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                short = 'c'
                long = 'config-paths'
                description = 'Config file paths (variadic tokens)'
                type = 'string'
                args = 'variadic'
                canNegate = $false
              }
              @{
                short = 'e'
                long = 'edition'
                description = 'Edition to sync (e.g., nix, osx, win)'
                type = 'string'
                args = 'required'
                canNegate = $false
              }
              @{
                long = 'only-conf'
                description = 'Only sync repositories from specified config names or paths (variadic tokens)'
                type = 'string'
                args = 'variadic'
                canNegate = $false
              }
              @{
                long = 'only-repo'
                description = 'Only sync specified repos (variadic tokens)'
                type = 'string'
                args = 'variadic'
                canNegate = $false
              }
              @{
                long = 'only-branch'
                description = 'Only sync specified branches (variadic tokens)'
                type = 'string'
                args = 'variadic'
                canNegate = $false
              }
              @{
                long = 'skip-conf'
                description = 'Skip repositories from specified config names or paths (variadic tokens)'
                type = 'string'
                args = 'variadic'
                canNegate = $false
              }
              @{
                long = 'skip-repo'
                description = 'Skip specified repos (variadic tokens)'
                type = 'string'
                args = 'variadic'
                canNegate = $false
              }
              @{
                long = 'skip-branch'
                description = 'Skip specified branches (variadic tokens)'
                type = 'string'
                args = 'variadic'
                canNegate = $false
              }
              @{
                long = 'dry-run'
                description = 'Preview effective repos/branches without executing git sync'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'help'
                description = 'Show help information'
                type = 'boolean'
                args = 'none'
                canNegate = $false
              }
            )
            arguments = @(
            )
          }
          'list' = @{
            description = 'List configured repositories'
            options = @(
              @{
                long = 'color'
                description = 'Enable colored help output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-level'
                description = 'Set log level'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('debug', 'info', 'hint', 'warn', 'error')
              }
              @{
                long = 'silent'
                description = 'Suppress non-error output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-date'
                description = 'Enable log timestamp'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-colorful'
                description = 'Enable colorful log output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                short = 'c'
                long = 'config-paths'
                description = 'Config file paths (variadic tokens)'
                type = 'string'
                args = 'variadic'
                canNegate = $false
              }
              @{
                short = 'e'
                long = 'edition'
                description = 'Show branches for specific edition'
                type = 'string'
                args = 'required'
                canNegate = $false
              }
              @{
                long = 'help'
                description = 'Show help information'
                type = 'boolean'
                args = 'none'
                canNegate = $false
              }
            )
            arguments = @(
            )
          }
          'status' = @{
            description = 'Show repository sync status'
            options = @(
              @{
                long = 'color'
                description = 'Enable colored help output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-level'
                description = 'Set log level'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('debug', 'info', 'hint', 'warn', 'error')
              }
              @{
                long = 'silent'
                description = 'Suppress non-error output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-date'
                description = 'Enable log timestamp'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-colorful'
                description = 'Enable colorful log output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                short = 'c'
                long = 'config-paths'
                description = 'Config file paths (variadic tokens)'
                type = 'string'
                args = 'variadic'
                canNegate = $false
              }
              @{
                short = 'e'
                long = 'edition'
                description = 'Show status for specific edition only'
                type = 'string'
                args = 'required'
                canNegate = $false
              }
              @{
                long = 'help'
                description = 'Show help information'
                type = 'boolean'
                args = 'none'
                canNegate = $false
              }
            )
            arguments = @(
            )
          }
          'get' = @{
            description = 'Get a config value'
            options = @(
              @{
                long = 'color'
                description = 'Enable colored help output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-level'
                description = 'Set log level'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('debug', 'info', 'hint', 'warn', 'error')
              }
              @{
                long = 'silent'
                description = 'Suppress non-error output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-date'
                description = 'Enable log timestamp'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-colorful'
                description = 'Enable colorful log output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                short = 's'
                long = 'setting-path'
                description = 'Setting file path (supports ~, default: ~/.config/kit/repo/setting.json)'
                type = 'string'
                args = 'required'
                canNegate = $false
              }
              @{
                long = 'help'
                description = 'Show help information'
                type = 'boolean'
                args = 'none'
                canNegate = $false
              }
            )
            arguments = @(
              @{
                name = 'key'
                kind = 'required'
                type = 'choice'
                choices = @('config.edition')
              }
            )
          }
          'set' = @{
            description = 'Set a config value'
            options = @(
              @{
                long = 'color'
                description = 'Enable colored help output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-level'
                description = 'Set log level'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('debug', 'info', 'hint', 'warn', 'error')
              }
              @{
                long = 'silent'
                description = 'Suppress non-error output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-date'
                description = 'Enable log timestamp'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-colorful'
                description = 'Enable colorful log output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                short = 's'
                long = 'setting-path'
                description = 'Setting file path (supports ~, default: ~/.config/kit/repo/setting.json)'
                type = 'string'
                args = 'required'
                canNegate = $false
              }
              @{
                long = 'help'
                description = 'Show help information'
                type = 'boolean'
                args = 'none'
                canNegate = $false
              }
            )
            arguments = @(
              @{
                name = 'key'
                kind = 'required'
                type = 'choice'
                choices = @('config.edition')
              }
              @{
                name = 'value'
                kind = 'required'
                type = 'string'
              }
            )
          }
          'validate' = @{
            description = 'Validate a config file'
            options = @(
              @{
                long = 'color'
                description = 'Enable colored help output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-level'
                description = 'Set log level'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('debug', 'info', 'hint', 'warn', 'error')
              }
              @{
                long = 'silent'
                description = 'Suppress non-error output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-date'
                description = 'Enable log timestamp'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-colorful'
                description = 'Enable colorful log output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'help'
                description = 'Show help information'
                type = 'boolean'
                args = 'none'
                canNegate = $false
              }
            )
            arguments = @(
              @{
                name = 'file'
                kind = 'required'
                type = 'string'
              }
            )
          }
        }
      }
      'wsl' = @{
        description = 'WSL utility commands'
        options = @(
          @{
            long = 'color'
            description = 'Enable colored help output'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'log-level'
            description = 'Set log level'
            type = 'string'
            args = 'required'
            canNegate = $false
            choices = @('debug', 'info', 'hint', 'warn', 'error')
          }
          @{
            long = 'silent'
            description = 'Suppress non-error output'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'log-date'
            description = 'Enable log timestamp'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'log-colorful'
            description = 'Enable colorful log output'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'help'
            description = 'Show help information'
            type = 'boolean'
            args = 'none'
            canNegate = $false
          }
          @{
            long = 'version'
            description = 'Show version number'
            type = 'boolean'
            args = 'none'
            canNegate = $false
          }
        )
        arguments = @(
        )
        subcommands = @{
          'path' = @{
            description = 'Convert between WSL and Windows paths'
            options = @(
              @{
                long = 'color'
                description = 'Enable colored help output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-level'
                description = 'Set log level'
                type = 'string'
                args = 'required'
                canNegate = $false
                choices = @('debug', 'info', 'hint', 'warn', 'error')
              }
              @{
                long = 'silent'
                description = 'Suppress non-error output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-date'
                description = 'Enable log timestamp'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'log-colorful'
                description = 'Enable colorful log output'
                type = 'boolean'
                args = 'none'
                canNegate = $true
              }
              @{
                long = 'help'
                description = 'Show help information'
                type = 'boolean'
                args = 'none'
                canNegate = $false
              }
            )
            arguments = @(
              @{
                name = 'path'
                kind = 'optional'
                type = 'string'
              }
            )
          }
        }
      }
      'completion' = @{
        description = 'Generate shell completion script'
        options = @(
          @{
            long = 'color'
            description = 'Enable colored help output'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'log-level'
            description = 'Set log level'
            type = 'string'
            args = 'required'
            canNegate = $false
            choices = @('debug', 'info', 'hint', 'warn', 'error')
          }
          @{
            long = 'silent'
            description = 'Suppress non-error output'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'log-date'
            description = 'Enable log timestamp'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'log-colorful'
            description = 'Enable colorful log output'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'bash'
            description = 'Generate Bash completion script'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'fish'
            description = 'Generate Fish completion script'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            long = 'pwsh'
            description = 'Generate PowerShell completion script'
            type = 'boolean'
            args = 'none'
            canNegate = $true
          }
          @{
            short = 'w'
            long = 'write'
            description = 'Write to file (use shell default path when value is omitted or empty)'
            type = 'string'
            args = 'optional'
            canNegate = $false
          }
          @{
            long = 'help'
            description = 'Show help information'
            type = 'boolean'
            args = 'none'
            canNegate = $false
          }
        )
        arguments = @(
        )
      }
    }
  }

  $words = $commandAst.CommandElements | ForEach-Object { $_.ToString() }
  $current = $wordToComplete

  # Find current command context
  $cmd = $commands
  $commandDepth = 1
  foreach ($word in $words[1..($words.Count - 1)]) {
    if ($word.StartsWith("-")) { continue }
    if ($cmd.subcommands -and $cmd.subcommands.ContainsKey($word)) {
      $cmd = $cmd.subcommands[$word]
      $commandDepth += 1
    }
  }

  # Generate completions
  $completions = @()

  # Option value slot (always higher priority than arguments)
  $previous = if ($words.Count -ge 2) { $words[$words.Count - 2] } else { $null }
  if ($previous) {
    foreach ($opt in $cmd.options) {
      $isLong = $previous -eq "--$($opt.long)"
      $isShort = $opt.short -and $previous -eq "-$($opt.short)"
      if ($isLong -or $isShort) {
        if ($opt.choices) {
          foreach ($choice in $opt.choices) {
            if ($choice -like "$current*") {
              $completions += [System.Management.Automation.CompletionResult]::new(
                $choice,
                $choice,
                "ParameterValue",
                $choice
              )
            }
          }
        }
        return $completions
      }
    }
  }

  # Determine argument slot
  $positionalCount = 0
  $expectValue = $false
  for ($i = $commandDepth; $i -lt ($words.Count - 1); $i += 1) {
    $token = $words[$i]
    if ($expectValue) {
      $expectValue = $false
      continue
    }
    if ($token.StartsWith("--")) {
      if ($token.Contains("=")) { continue }
      foreach ($opt in $cmd.options) {
        if ($token -eq "--$($opt.long)" -and $opt.args -ne "none") {
          $expectValue = $true
          break
        }
      }
      continue
    }
    if ($token.StartsWith("-") -and $token -ne "-") {
      if ($token.Length -eq 2) {
        foreach ($opt in $cmd.options) {
          if ($opt.short -and $token -eq "-$($opt.short)" -and $opt.args -ne "none") {
            $expectValue = $true
            break
          }
        }
      }
      continue
    }
    $positionalCount += 1
  }
  if ($expectValue) {
    return $completions
  }
  if (-not $current.StartsWith("-") -and $cmd.arguments -and $cmd.arguments.Count -gt 0) {
    $argSlot = -1
    $argCount = $cmd.arguments.Count
    $lastArg = $cmd.arguments[$argCount - 1]
    $hasRest = $lastArg.kind -eq "variadic" -or $lastArg.kind -eq "some"
    if ($hasRest -and $positionalCount -ge ($argCount - 1)) {
      $argSlot = $argCount - 1
    } elseif ($positionalCount -lt $argCount) {
      $argSlot = $positionalCount
    }
    if ($argSlot -ge 0) {
      $argMeta = $cmd.arguments[$argSlot]
      if ($argMeta.choices) {
        foreach ($choice in $argMeta.choices) {
          if ($choice -like "$current*") {
            $completions += [System.Management.Automation.CompletionResult]::new(
              $choice,
              $choice,
              "ParameterValue",
              $choice
            )
          }
        }
        return $completions
      }
    }
  }

  # Options
  if ($current.StartsWith("-")) {
    foreach ($opt in $cmd.options) {
      if ("--$($opt.long)" -like "$current*") {
        $completions += [System.Management.Automation.CompletionResult]::new(
          "--$($opt.long)",
          $opt.long,
          "ParameterName",
          $opt.description
        )
      }
      if ($opt.canNegate -and "--no-$($opt.long)" -like "$current*") {
        $completions += [System.Management.Automation.CompletionResult]::new(
          "--no-$($opt.long)",
          "no-$($opt.long)",
          "ParameterName",
          $opt.description
        )
      }
      if ($opt.short -and "-$($opt.short)" -like "$current*") {
        $completions += [System.Management.Automation.CompletionResult]::new(
          "-$($opt.short)",
          $opt.short,
          "ParameterName",
          $opt.description
        )
      }
    }
  }

  # Subcommands
  if ($cmd.subcommands) {
    foreach ($sub in $cmd.subcommands.Keys) {
      if ($sub -like "$current*") {
        $completions += [System.Management.Automation.CompletionResult]::new(
          $sub,
          $sub,
          "Command",
          $cmd.subcommands[$sub].description
        )
      }
    }
  }

  return $completions
}
