# Bash completion for kit
# Generated by @guanghechen/commander

_kit_completions() {
  local cur prev words cword
  local opts arg_choices prefer_value_choices
  _init_completion || return

  case "${words[1]}" in
    pm)
    case "${words[2]}" in
      daemon)
      opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful --help"
      prefer_value_choices=0
      if [[ "$cur" != -* ]]; then
        case "$prev" in
          --log-level)
            opts="debug info hint warn error"
            prefer_value_choices=1
            ;;
        esac
      fi
      if [[ $prefer_value_choices -eq 0 ]]; then
        positional_count=0
        expect_value=0
        for ((idx=3; idx<cword; idx++)); do
          token="${words[idx]}"
          if [[ $expect_value -eq 1 ]]; then
            expect_value=0
            continue
          fi
          if [[ "$token" == --* ]]; then
            if [[ "$token" == *=* ]]; then
              continue
            fi
            case "$token" in
              --log-level) expect_value=1 ;;
            esac
            continue
          fi
          if [[ "$token" == -* && "$token" != "-" ]]; then
            if [[ ${#token} -eq 2 ]]; then
            fi
            continue
          fi
          positional_count=$((positional_count + 1))
        done
        if [[ $expect_value -eq 1 ]]; then
          opts=""
          prefer_value_choices=1
        elif [[ "$cur" != -* ]]; then
          arg_slot=-1
          arg_count=0
          has_rest=0
          if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
            arg_slot=$((arg_count - 1))
          elif [[ $positional_count -lt $arg_count ]]; then
            arg_slot=$positional_count
          fi
          case "$arg_slot" in
          esac
        fi
      fi
        ;;
      list|ls)
      opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful --help"
      prefer_value_choices=0
      if [[ "$cur" != -* ]]; then
        case "$prev" in
          --log-level)
            opts="debug info hint warn error"
            prefer_value_choices=1
            ;;
        esac
      fi
      if [[ $prefer_value_choices -eq 0 ]]; then
        positional_count=0
        expect_value=0
        for ((idx=3; idx<cword; idx++)); do
          token="${words[idx]}"
          if [[ $expect_value -eq 1 ]]; then
            expect_value=0
            continue
          fi
          if [[ "$token" == --* ]]; then
            if [[ "$token" == *=* ]]; then
              continue
            fi
            case "$token" in
              --log-level) expect_value=1 ;;
            esac
            continue
          fi
          if [[ "$token" == -* && "$token" != "-" ]]; then
            if [[ ${#token} -eq 2 ]]; then
            fi
            continue
          fi
          positional_count=$((positional_count + 1))
        done
        if [[ $expect_value -eq 1 ]]; then
          opts=""
          prefer_value_choices=1
        elif [[ "$cur" != -* ]]; then
          arg_slot=-1
          arg_count=0
          has_rest=0
          if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
            arg_slot=$((arg_count - 1))
          elif [[ $positional_count -lt $arg_count ]]; then
            arg_slot=$positional_count
          fi
          case "$arg_slot" in
          esac
        fi
      fi
        ;;
      start)
      opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful --help"
      prefer_value_choices=0
      if [[ "$cur" != -* ]]; then
        case "$prev" in
          --log-level)
            opts="debug info hint warn error"
            prefer_value_choices=1
            ;;
        esac
      fi
      if [[ $prefer_value_choices -eq 0 ]]; then
        positional_count=0
        expect_value=0
        for ((idx=3; idx<cword; idx++)); do
          token="${words[idx]}"
          if [[ $expect_value -eq 1 ]]; then
            expect_value=0
            continue
          fi
          if [[ "$token" == --* ]]; then
            if [[ "$token" == *=* ]]; then
              continue
            fi
            case "$token" in
              --log-level) expect_value=1 ;;
            esac
            continue
          fi
          if [[ "$token" == -* && "$token" != "-" ]]; then
            if [[ ${#token} -eq 2 ]]; then
            fi
            continue
          fi
          positional_count=$((positional_count + 1))
        done
        if [[ $expect_value -eq 1 ]]; then
          opts=""
          prefer_value_choices=1
        elif [[ "$cur" != -* ]]; then
          arg_slot=-1
          arg_count=1
          has_rest=0
          if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
            arg_slot=$((arg_count - 1))
          elif [[ $positional_count -lt $arg_count ]]; then
            arg_slot=$positional_count
          fi
          case "$arg_slot" in
          esac
        fi
      fi
        ;;
      add)
      opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful --help"
      prefer_value_choices=0
      if [[ "$cur" != -* ]]; then
        case "$prev" in
          --log-level)
            opts="debug info hint warn error"
            prefer_value_choices=1
            ;;
        esac
      fi
      if [[ $prefer_value_choices -eq 0 ]]; then
        positional_count=0
        expect_value=0
        for ((idx=3; idx<cword; idx++)); do
          token="${words[idx]}"
          if [[ $expect_value -eq 1 ]]; then
            expect_value=0
            continue
          fi
          if [[ "$token" == --* ]]; then
            if [[ "$token" == *=* ]]; then
              continue
            fi
            case "$token" in
              --log-level) expect_value=1 ;;
            esac
            continue
          fi
          if [[ "$token" == -* && "$token" != "-" ]]; then
            if [[ ${#token} -eq 2 ]]; then
            fi
            continue
          fi
          positional_count=$((positional_count + 1))
        done
        if [[ $expect_value -eq 1 ]]; then
          opts=""
          prefer_value_choices=1
        elif [[ "$cur" != -* ]]; then
          arg_slot=-1
          arg_count=1
          has_rest=0
          if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
            arg_slot=$((arg_count - 1))
          elif [[ $positional_count -lt $arg_count ]]; then
            arg_slot=$positional_count
          fi
          case "$arg_slot" in
          esac
        fi
      fi
        ;;
      restart)
      opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful --help"
      prefer_value_choices=0
      if [[ "$cur" != -* ]]; then
        case "$prev" in
          --log-level)
            opts="debug info hint warn error"
            prefer_value_choices=1
            ;;
        esac
      fi
      if [[ $prefer_value_choices -eq 0 ]]; then
        positional_count=0
        expect_value=0
        for ((idx=3; idx<cword; idx++)); do
          token="${words[idx]}"
          if [[ $expect_value -eq 1 ]]; then
            expect_value=0
            continue
          fi
          if [[ "$token" == --* ]]; then
            if [[ "$token" == *=* ]]; then
              continue
            fi
            case "$token" in
              --log-level) expect_value=1 ;;
            esac
            continue
          fi
          if [[ "$token" == -* && "$token" != "-" ]]; then
            if [[ ${#token} -eq 2 ]]; then
            fi
            continue
          fi
          positional_count=$((positional_count + 1))
        done
        if [[ $expect_value -eq 1 ]]; then
          opts=""
          prefer_value_choices=1
        elif [[ "$cur" != -* ]]; then
          arg_slot=-1
          arg_count=1
          has_rest=0
          if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
            arg_slot=$((arg_count - 1))
          elif [[ $positional_count -lt $arg_count ]]; then
            arg_slot=$positional_count
          fi
          case "$arg_slot" in
          esac
        fi
      fi
        ;;
      stop)
      opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful --help"
      prefer_value_choices=0
      if [[ "$cur" != -* ]]; then
        case "$prev" in
          --log-level)
            opts="debug info hint warn error"
            prefer_value_choices=1
            ;;
        esac
      fi
      if [[ $prefer_value_choices -eq 0 ]]; then
        positional_count=0
        expect_value=0
        for ((idx=3; idx<cword; idx++)); do
          token="${words[idx]}"
          if [[ $expect_value -eq 1 ]]; then
            expect_value=0
            continue
          fi
          if [[ "$token" == --* ]]; then
            if [[ "$token" == *=* ]]; then
              continue
            fi
            case "$token" in
              --log-level) expect_value=1 ;;
            esac
            continue
          fi
          if [[ "$token" == -* && "$token" != "-" ]]; then
            if [[ ${#token} -eq 2 ]]; then
            fi
            continue
          fi
          positional_count=$((positional_count + 1))
        done
        if [[ $expect_value -eq 1 ]]; then
          opts=""
          prefer_value_choices=1
        elif [[ "$cur" != -* ]]; then
          arg_slot=-1
          arg_count=1
          has_rest=0
          if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
            arg_slot=$((arg_count - 1))
          elif [[ $positional_count -lt $arg_count ]]; then
            arg_slot=$positional_count
          fi
          case "$arg_slot" in
          esac
        fi
      fi
        ;;
      kill)
      opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful --help"
      prefer_value_choices=0
      if [[ "$cur" != -* ]]; then
        case "$prev" in
          --log-level)
            opts="debug info hint warn error"
            prefer_value_choices=1
            ;;
        esac
      fi
      if [[ $prefer_value_choices -eq 0 ]]; then
        positional_count=0
        expect_value=0
        for ((idx=3; idx<cword; idx++)); do
          token="${words[idx]}"
          if [[ $expect_value -eq 1 ]]; then
            expect_value=0
            continue
          fi
          if [[ "$token" == --* ]]; then
            if [[ "$token" == *=* ]]; then
              continue
            fi
            case "$token" in
              --log-level) expect_value=1 ;;
            esac
            continue
          fi
          if [[ "$token" == -* && "$token" != "-" ]]; then
            if [[ ${#token} -eq 2 ]]; then
            fi
            continue
          fi
          positional_count=$((positional_count + 1))
        done
        if [[ $expect_value -eq 1 ]]; then
          opts=""
          prefer_value_choices=1
        elif [[ "$cur" != -* ]]; then
          arg_slot=-1
          arg_count=2
          has_rest=0
          if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
            arg_slot=$((arg_count - 1))
          elif [[ $positional_count -lt $arg_count ]]; then
            arg_slot=$positional_count
          fi
          case "$arg_slot" in
            0) opts="processes daemon all" ;;
          esac
        fi
      fi
        ;;
      clean|flush)
      opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful --help"
      prefer_value_choices=0
      if [[ "$cur" != -* ]]; then
        case "$prev" in
          --log-level)
            opts="debug info hint warn error"
            prefer_value_choices=1
            ;;
        esac
      fi
      if [[ $prefer_value_choices -eq 0 ]]; then
        positional_count=0
        expect_value=0
        for ((idx=3; idx<cword; idx++)); do
          token="${words[idx]}"
          if [[ $expect_value -eq 1 ]]; then
            expect_value=0
            continue
          fi
          if [[ "$token" == --* ]]; then
            if [[ "$token" == *=* ]]; then
              continue
            fi
            case "$token" in
              --log-level) expect_value=1 ;;
            esac
            continue
          fi
          if [[ "$token" == -* && "$token" != "-" ]]; then
            if [[ ${#token} -eq 2 ]]; then
            fi
            continue
          fi
          positional_count=$((positional_count + 1))
        done
        if [[ $expect_value -eq 1 ]]; then
          opts=""
          prefer_value_choices=1
        elif [[ "$cur" != -* ]]; then
          arg_slot=-1
          arg_count=1
          has_rest=0
          if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
            arg_slot=$((arg_count - 1))
          elif [[ $positional_count -lt $arg_count ]]; then
            arg_slot=$positional_count
          fi
          case "$arg_slot" in
            0) opts="logs" ;;
          esac
        fi
      fi
        ;;
      show)
      opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful --track --no-track -n --lines --type --help"
      prefer_value_choices=0
      if [[ "$cur" != -* ]]; then
        case "$prev" in
          --log-level)
            opts="debug info hint warn error"
            prefer_value_choices=1
            ;;
          --type)
            opts="stdout stderr both"
            prefer_value_choices=1
            ;;
        esac
      fi
      if [[ $prefer_value_choices -eq 0 ]]; then
        positional_count=0
        expect_value=0
        for ((idx=3; idx<cword; idx++)); do
          token="${words[idx]}"
          if [[ $expect_value -eq 1 ]]; then
            expect_value=0
            continue
          fi
          if [[ "$token" == --* ]]; then
            if [[ "$token" == *=* ]]; then
              continue
            fi
            case "$token" in
              --log-level|--lines|--type) expect_value=1 ;;
            esac
            continue
          fi
          if [[ "$token" == -* && "$token" != "-" ]]; then
            if [[ ${#token} -eq 2 ]]; then
              case "${token:1:1}" in
                n) expect_value=1 ;;
              esac
            fi
            continue
          fi
          positional_count=$((positional_count + 1))
        done
        if [[ $expect_value -eq 1 ]]; then
          opts=""
          prefer_value_choices=1
        elif [[ "$cur" != -* ]]; then
          arg_slot=-1
          arg_count=1
          has_rest=0
          if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
            arg_slot=$((arg_count - 1))
          elif [[ $positional_count -lt $arg_count ]]; then
            arg_slot=$positional_count
          fi
          case "$arg_slot" in
          esac
        fi
      fi
        ;;
      logs)
      opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful --track --no-track -n --lines --type --help"
      prefer_value_choices=0
      if [[ "$cur" != -* ]]; then
        case "$prev" in
          --log-level)
            opts="debug info hint warn error"
            prefer_value_choices=1
            ;;
          --type)
            opts="stdout stderr both"
            prefer_value_choices=1
            ;;
        esac
      fi
      if [[ $prefer_value_choices -eq 0 ]]; then
        positional_count=0
        expect_value=0
        for ((idx=3; idx<cword; idx++)); do
          token="${words[idx]}"
          if [[ $expect_value -eq 1 ]]; then
            expect_value=0
            continue
          fi
          if [[ "$token" == --* ]]; then
            if [[ "$token" == *=* ]]; then
              continue
            fi
            case "$token" in
              --log-level|--lines|--type) expect_value=1 ;;
            esac
            continue
          fi
          if [[ "$token" == -* && "$token" != "-" ]]; then
            if [[ ${#token} -eq 2 ]]; then
              case "${token:1:1}" in
                n) expect_value=1 ;;
              esac
            fi
            continue
          fi
          positional_count=$((positional_count + 1))
        done
        if [[ $expect_value -eq 1 ]]; then
          opts=""
          prefer_value_choices=1
        elif [[ "$cur" != -* ]]; then
          arg_slot=-1
          arg_count=1
          has_rest=0
          if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
            arg_slot=$((arg_count - 1))
          elif [[ $positional_count -lt $arg_count ]]; then
            arg_slot=$positional_count
          fi
          case "$arg_slot" in
          esac
        fi
      fi
        ;;
      monit)
      opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful --help"
      prefer_value_choices=0
      if [[ "$cur" != -* ]]; then
        case "$prev" in
          --log-level)
            opts="debug info hint warn error"
            prefer_value_choices=1
            ;;
        esac
      fi
      if [[ $prefer_value_choices -eq 0 ]]; then
        positional_count=0
        expect_value=0
        for ((idx=3; idx<cword; idx++)); do
          token="${words[idx]}"
          if [[ $expect_value -eq 1 ]]; then
            expect_value=0
            continue
          fi
          if [[ "$token" == --* ]]; then
            if [[ "$token" == *=* ]]; then
              continue
            fi
            case "$token" in
              --log-level) expect_value=1 ;;
            esac
            continue
          fi
          if [[ "$token" == -* && "$token" != "-" ]]; then
            if [[ ${#token} -eq 2 ]]; then
            fi
            continue
          fi
          positional_count=$((positional_count + 1))
        done
        if [[ $expect_value -eq 1 ]]; then
          opts=""
          prefer_value_choices=1
        elif [[ "$cur" != -* ]]; then
          arg_slot=-1
          arg_count=0
          has_rest=0
          if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
            arg_slot=$((arg_count - 1))
          elif [[ $positional_count -lt $arg_count ]]; then
            arg_slot=$positional_count
          fi
          case "$arg_slot" in
          esac
        fi
      fi
        ;;
      *)
        opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful --help --version daemon list ls start add restart stop kill clean flush show logs monit"
        prefer_value_choices=0
        if [[ "$cur" != -* ]]; then
          case "$prev" in
            --log-level)
              opts="debug info hint warn error"
              prefer_value_choices=1
              ;;
          esac
        fi
        if [[ $prefer_value_choices -eq 0 ]]; then
          positional_count=0
          expect_value=0
          for ((idx=2; idx<cword; idx++)); do
            token="${words[idx]}"
            if [[ $expect_value -eq 1 ]]; then
              expect_value=0
              continue
            fi
            if [[ "$token" == --* ]]; then
              if [[ "$token" == *=* ]]; then
                continue
              fi
              case "$token" in
                --log-level) expect_value=1 ;;
              esac
              continue
            fi
            if [[ "$token" == -* && "$token" != "-" ]]; then
              if [[ ${#token} -eq 2 ]]; then
              fi
              continue
            fi
            positional_count=$((positional_count + 1))
          done
          if [[ $expect_value -eq 1 ]]; then
            opts=""
            prefer_value_choices=1
          elif [[ "$cur" != -* ]]; then
            arg_slot=-1
            arg_count=0
            has_rest=0
            if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
              arg_slot=$((arg_count - 1))
            elif [[ $positional_count -lt $arg_count ]]; then
              arg_slot=$positional_count
            fi
            case "$arg_slot" in
            esac
          fi
        fi
        ;;
    esac
      ;;
    file)
    case "${words[2]}" in
      split|s)
      opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful -o --output --part-size --part-total --part-code-prefix --help"
      prefer_value_choices=0
      if [[ "$cur" != -* ]]; then
        case "$prev" in
          --log-level)
            opts="debug info hint warn error"
            prefer_value_choices=1
            ;;
        esac
      fi
      if [[ $prefer_value_choices -eq 0 ]]; then
        positional_count=0
        expect_value=0
        for ((idx=3; idx<cword; idx++)); do
          token="${words[idx]}"
          if [[ $expect_value -eq 1 ]]; then
            expect_value=0
            continue
          fi
          if [[ "$token" == --* ]]; then
            if [[ "$token" == *=* ]]; then
              continue
            fi
            case "$token" in
              --log-level|--output|--part-size|--part-total|--part-code-prefix) expect_value=1 ;;
            esac
            continue
          fi
          if [[ "$token" == -* && "$token" != "-" ]]; then
            if [[ ${#token} -eq 2 ]]; then
              case "${token:1:1}" in
                o) expect_value=1 ;;
              esac
            fi
            continue
          fi
          positional_count=$((positional_count + 1))
        done
        if [[ $expect_value -eq 1 ]]; then
          opts=""
          prefer_value_choices=1
        elif [[ "$cur" != -* ]]; then
          arg_slot=-1
          arg_count=1
          has_rest=0
          if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
            arg_slot=$((arg_count - 1))
          elif [[ $positional_count -lt $arg_count ]]; then
            arg_slot=$positional_count
          fi
          case "$arg_slot" in
          esac
        fi
      fi
        ;;
      merge|m)
      opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful -o --output --part-code-prefix --help"
      prefer_value_choices=0
      if [[ "$cur" != -* ]]; then
        case "$prev" in
          --log-level)
            opts="debug info hint warn error"
            prefer_value_choices=1
            ;;
        esac
      fi
      if [[ $prefer_value_choices -eq 0 ]]; then
        positional_count=0
        expect_value=0
        for ((idx=3; idx<cword; idx++)); do
          token="${words[idx]}"
          if [[ $expect_value -eq 1 ]]; then
            expect_value=0
            continue
          fi
          if [[ "$token" == --* ]]; then
            if [[ "$token" == *=* ]]; then
              continue
            fi
            case "$token" in
              --log-level|--output|--part-code-prefix) expect_value=1 ;;
            esac
            continue
          fi
          if [[ "$token" == -* && "$token" != "-" ]]; then
            if [[ ${#token} -eq 2 ]]; then
              case "${token:1:1}" in
                o) expect_value=1 ;;
              esac
            fi
            continue
          fi
          positional_count=$((positional_count + 1))
        done
        if [[ $expect_value -eq 1 ]]; then
          opts=""
          prefer_value_choices=1
        elif [[ "$cur" != -* ]]; then
          arg_slot=-1
          arg_count=1
          has_rest=0
          if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
            arg_slot=$((arg_count - 1))
          elif [[ $positional_count -lt $arg_count ]]; then
            arg_slot=$positional_count
          fi
          case "$arg_slot" in
          esac
        fi
      fi
        ;;
      *)
        opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful --help --version split s merge m"
        prefer_value_choices=0
        if [[ "$cur" != -* ]]; then
          case "$prev" in
            --log-level)
              opts="debug info hint warn error"
              prefer_value_choices=1
              ;;
          esac
        fi
        if [[ $prefer_value_choices -eq 0 ]]; then
          positional_count=0
          expect_value=0
          for ((idx=2; idx<cword; idx++)); do
            token="${words[idx]}"
            if [[ $expect_value -eq 1 ]]; then
              expect_value=0
              continue
            fi
            if [[ "$token" == --* ]]; then
              if [[ "$token" == *=* ]]; then
                continue
              fi
              case "$token" in
                --log-level) expect_value=1 ;;
              esac
              continue
            fi
            if [[ "$token" == -* && "$token" != "-" ]]; then
              if [[ ${#token} -eq 2 ]]; then
              fi
              continue
            fi
            positional_count=$((positional_count + 1))
          done
          if [[ $expect_value -eq 1 ]]; then
            opts=""
            prefer_value_choices=1
          elif [[ "$cur" != -* ]]; then
            arg_slot=-1
            arg_count=0
            has_rest=0
            if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
              arg_slot=$((arg_count - 1))
            elif [[ $positional_count -lt $arg_count ]]; then
              arg_slot=$positional_count
            fi
            case "$arg_slot" in
            esac
          fi
        fi
        ;;
    esac
      ;;
    copilot)
    case "${words[2]}" in
      start)
      opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful -H --host -p --port -l --log-path --colorful --no-colorful --devmode --no-devmode --strict --no-strict --filter-tools --help"
      prefer_value_choices=0
      if [[ "$cur" != -* ]]; then
        case "$prev" in
          --log-level)
            opts="debug info hint warn error"
            prefer_value_choices=1
            ;;
        esac
      fi
      if [[ $prefer_value_choices -eq 0 ]]; then
        positional_count=0
        expect_value=0
        for ((idx=3; idx<cword; idx++)); do
          token="${words[idx]}"
          if [[ $expect_value -eq 1 ]]; then
            expect_value=0
            continue
          fi
          if [[ "$token" == --* ]]; then
            if [[ "$token" == *=* ]]; then
              continue
            fi
            case "$token" in
              --log-level|--host|--port|--log-path|--filter-tools) expect_value=1 ;;
            esac
            continue
          fi
          if [[ "$token" == -* && "$token" != "-" ]]; then
            if [[ ${#token} -eq 2 ]]; then
              case "${token:1:1}" in
                H|p|l) expect_value=1 ;;
              esac
            fi
            continue
          fi
          positional_count=$((positional_count + 1))
        done
        if [[ $expect_value -eq 1 ]]; then
          opts=""
          prefer_value_choices=1
        elif [[ "$cur" != -* ]]; then
          arg_slot=-1
          arg_count=0
          has_rest=0
          if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
            arg_slot=$((arg_count - 1))
          elif [[ $positional_count -lt $arg_count ]]; then
            arg_slot=$positional_count
          fi
          case "$arg_slot" in
          esac
        fi
      fi
        ;;
      auth)
      opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful --force --no-force --help"
      prefer_value_choices=0
      if [[ "$cur" != -* ]]; then
        case "$prev" in
          --log-level)
            opts="debug info hint warn error"
            prefer_value_choices=1
            ;;
        esac
      fi
      if [[ $prefer_value_choices -eq 0 ]]; then
        positional_count=0
        expect_value=0
        for ((idx=3; idx<cword; idx++)); do
          token="${words[idx]}"
          if [[ $expect_value -eq 1 ]]; then
            expect_value=0
            continue
          fi
          if [[ "$token" == --* ]]; then
            if [[ "$token" == *=* ]]; then
              continue
            fi
            case "$token" in
              --log-level) expect_value=1 ;;
            esac
            continue
          fi
          if [[ "$token" == -* && "$token" != "-" ]]; then
            if [[ ${#token} -eq 2 ]]; then
            fi
            continue
          fi
          positional_count=$((positional_count + 1))
        done
        if [[ $expect_value -eq 1 ]]; then
          opts=""
          prefer_value_choices=1
        elif [[ "$cur" != -* ]]; then
          arg_slot=-1
          arg_count=0
          has_rest=0
          if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
            arg_slot=$((arg_count - 1))
          elif [[ $positional_count -lt $arg_count ]]; then
            arg_slot=$positional_count
          fi
          case "$arg_slot" in
          esac
        fi
      fi
        ;;
      *)
        opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful --help --version start auth"
        prefer_value_choices=0
        if [[ "$cur" != -* ]]; then
          case "$prev" in
            --log-level)
              opts="debug info hint warn error"
              prefer_value_choices=1
              ;;
          esac
        fi
        if [[ $prefer_value_choices -eq 0 ]]; then
          positional_count=0
          expect_value=0
          for ((idx=2; idx<cword; idx++)); do
            token="${words[idx]}"
            if [[ $expect_value -eq 1 ]]; then
              expect_value=0
              continue
            fi
            if [[ "$token" == --* ]]; then
              if [[ "$token" == *=* ]]; then
                continue
              fi
              case "$token" in
                --log-level) expect_value=1 ;;
              esac
              continue
            fi
            if [[ "$token" == -* && "$token" != "-" ]]; then
              if [[ ${#token} -eq 2 ]]; then
              fi
              continue
            fi
            positional_count=$((positional_count + 1))
          done
          if [[ $expect_value -eq 1 ]]; then
            opts=""
            prefer_value_choices=1
          elif [[ "$cur" != -* ]]; then
            arg_slot=-1
            arg_count=0
            has_rest=0
            if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
              arg_slot=$((arg_count - 1))
            elif [[ $positional_count -lt $arg_count ]]; then
              arg_slot=$positional_count
            fi
            case "$arg_slot" in
            esac
          fi
        fi
        ;;
    esac
      ;;
    copy)
    opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful -f --file --trim --no-trim --help --version"
    prefer_value_choices=0
    if [[ "$cur" != -* ]]; then
      case "$prev" in
        --log-level)
          opts="debug info hint warn error"
          prefer_value_choices=1
          ;;
      esac
    fi
    if [[ $prefer_value_choices -eq 0 ]]; then
      positional_count=0
      expect_value=0
      for ((idx=2; idx<cword; idx++)); do
        token="${words[idx]}"
        if [[ $expect_value -eq 1 ]]; then
          expect_value=0
          continue
        fi
        if [[ "$token" == --* ]]; then
          if [[ "$token" == *=* ]]; then
            continue
          fi
          case "$token" in
            --log-level|--file) expect_value=1 ;;
          esac
          continue
        fi
        if [[ "$token" == -* && "$token" != "-" ]]; then
          if [[ ${#token} -eq 2 ]]; then
            case "${token:1:1}" in
              f) expect_value=1 ;;
            esac
          fi
          continue
        fi
        positional_count=$((positional_count + 1))
      done
      if [[ $expect_value -eq 1 ]]; then
        opts=""
        prefer_value_choices=1
      elif [[ "$cur" != -* ]]; then
        arg_slot=-1
        arg_count=1
        has_rest=0
        if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
          arg_slot=$((arg_count - 1))
        elif [[ $positional_count -lt $arg_count ]]; then
          arg_slot=$positional_count
        fi
        case "$arg_slot" in
        esac
      fi
    fi
      ;;
    paste)
    opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful -o --output -a --append --no-append --help --version"
    prefer_value_choices=0
    if [[ "$cur" != -* ]]; then
      case "$prev" in
        --log-level)
          opts="debug info hint warn error"
          prefer_value_choices=1
          ;;
      esac
    fi
    if [[ $prefer_value_choices -eq 0 ]]; then
      positional_count=0
      expect_value=0
      for ((idx=2; idx<cword; idx++)); do
        token="${words[idx]}"
        if [[ $expect_value -eq 1 ]]; then
          expect_value=0
          continue
        fi
        if [[ "$token" == --* ]]; then
          if [[ "$token" == *=* ]]; then
            continue
          fi
          case "$token" in
            --log-level|--output) expect_value=1 ;;
          esac
          continue
        fi
        if [[ "$token" == -* && "$token" != "-" ]]; then
          if [[ ${#token} -eq 2 ]]; then
            case "${token:1:1}" in
              o) expect_value=1 ;;
            esac
          fi
          continue
        fi
        positional_count=$((positional_count + 1))
      done
      if [[ $expect_value -eq 1 ]]; then
        opts=""
        prefer_value_choices=1
      elif [[ "$cur" != -* ]]; then
        arg_slot=-1
        arg_count=0
        has_rest=0
        if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
          arg_slot=$((arg_count - 1))
        elif [[ $positional_count -lt $arg_count ]]; then
          arg_slot=$positional_count
        fi
        case "$arg_slot" in
        esac
      fi
    fi
      ;;
    profile)
    opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful -p --profile --set --allow-env -s --shell --fish --no-fish --bash --no-bash --pwsh --no-pwsh --help --version"
    prefer_value_choices=0
    if [[ "$cur" != -* ]]; then
      case "$prev" in
        --log-level)
          opts="debug info hint warn error"
          prefer_value_choices=1
          ;;
      esac
    fi
    if [[ $prefer_value_choices -eq 0 ]]; then
      positional_count=0
      expect_value=0
      for ((idx=2; idx<cword; idx++)); do
        token="${words[idx]}"
        if [[ $expect_value -eq 1 ]]; then
          expect_value=0
          continue
        fi
        if [[ "$token" == --* ]]; then
          if [[ "$token" == *=* ]]; then
            continue
          fi
          case "$token" in
            --log-level|--profile|--set|--allow-env|--shell) expect_value=1 ;;
          esac
          continue
        fi
        if [[ "$token" == -* && "$token" != "-" ]]; then
          if [[ ${#token} -eq 2 ]]; then
            case "${token:1:1}" in
              p|s) expect_value=1 ;;
            esac
          fi
          continue
        fi
        positional_count=$((positional_count + 1))
      done
      if [[ $expect_value -eq 1 ]]; then
        opts=""
        prefer_value_choices=1
      elif [[ "$cur" != -* ]]; then
        arg_slot=-1
        arg_count=0
        has_rest=0
        if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
          arg_slot=$((arg_count - 1))
        elif [[ $positional_count -lt $arg_count ]]; then
          arg_slot=$positional_count
        fi
        case "$arg_slot" in
        esac
      fi
    fi
      ;;
    repo)
    case "${words[2]}" in
      sync)
      opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful -c --config-paths -e --edition --only-conf --only-repo --only-branch --skip-conf --skip-repo --skip-branch --dry-run --no-dry-run --help"
      prefer_value_choices=0
      if [[ "$cur" != -* ]]; then
        case "$prev" in
          --log-level)
            opts="debug info hint warn error"
            prefer_value_choices=1
            ;;
        esac
      fi
      if [[ $prefer_value_choices -eq 0 ]]; then
        positional_count=0
        expect_value=0
        for ((idx=3; idx<cword; idx++)); do
          token="${words[idx]}"
          if [[ $expect_value -eq 1 ]]; then
            expect_value=0
            continue
          fi
          if [[ "$token" == --* ]]; then
            if [[ "$token" == *=* ]]; then
              continue
            fi
            case "$token" in
              --log-level|--config-paths|--edition|--only-conf|--only-repo|--only-branch|--skip-conf|--skip-repo|--skip-branch) expect_value=1 ;;
            esac
            continue
          fi
          if [[ "$token" == -* && "$token" != "-" ]]; then
            if [[ ${#token} -eq 2 ]]; then
              case "${token:1:1}" in
                c|e) expect_value=1 ;;
              esac
            fi
            continue
          fi
          positional_count=$((positional_count + 1))
        done
        if [[ $expect_value -eq 1 ]]; then
          opts=""
          prefer_value_choices=1
        elif [[ "$cur" != -* ]]; then
          arg_slot=-1
          arg_count=0
          has_rest=0
          if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
            arg_slot=$((arg_count - 1))
          elif [[ $positional_count -lt $arg_count ]]; then
            arg_slot=$positional_count
          fi
          case "$arg_slot" in
          esac
        fi
      fi
        ;;
      list)
      opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful -c --config-paths -e --edition --help"
      prefer_value_choices=0
      if [[ "$cur" != -* ]]; then
        case "$prev" in
          --log-level)
            opts="debug info hint warn error"
            prefer_value_choices=1
            ;;
        esac
      fi
      if [[ $prefer_value_choices -eq 0 ]]; then
        positional_count=0
        expect_value=0
        for ((idx=3; idx<cword; idx++)); do
          token="${words[idx]}"
          if [[ $expect_value -eq 1 ]]; then
            expect_value=0
            continue
          fi
          if [[ "$token" == --* ]]; then
            if [[ "$token" == *=* ]]; then
              continue
            fi
            case "$token" in
              --log-level|--config-paths|--edition) expect_value=1 ;;
            esac
            continue
          fi
          if [[ "$token" == -* && "$token" != "-" ]]; then
            if [[ ${#token} -eq 2 ]]; then
              case "${token:1:1}" in
                c|e) expect_value=1 ;;
              esac
            fi
            continue
          fi
          positional_count=$((positional_count + 1))
        done
        if [[ $expect_value -eq 1 ]]; then
          opts=""
          prefer_value_choices=1
        elif [[ "$cur" != -* ]]; then
          arg_slot=-1
          arg_count=0
          has_rest=0
          if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
            arg_slot=$((arg_count - 1))
          elif [[ $positional_count -lt $arg_count ]]; then
            arg_slot=$positional_count
          fi
          case "$arg_slot" in
          esac
        fi
      fi
        ;;
      status)
      opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful -c --config-paths -e --edition --help"
      prefer_value_choices=0
      if [[ "$cur" != -* ]]; then
        case "$prev" in
          --log-level)
            opts="debug info hint warn error"
            prefer_value_choices=1
            ;;
        esac
      fi
      if [[ $prefer_value_choices -eq 0 ]]; then
        positional_count=0
        expect_value=0
        for ((idx=3; idx<cword; idx++)); do
          token="${words[idx]}"
          if [[ $expect_value -eq 1 ]]; then
            expect_value=0
            continue
          fi
          if [[ "$token" == --* ]]; then
            if [[ "$token" == *=* ]]; then
              continue
            fi
            case "$token" in
              --log-level|--config-paths|--edition) expect_value=1 ;;
            esac
            continue
          fi
          if [[ "$token" == -* && "$token" != "-" ]]; then
            if [[ ${#token} -eq 2 ]]; then
              case "${token:1:1}" in
                c|e) expect_value=1 ;;
              esac
            fi
            continue
          fi
          positional_count=$((positional_count + 1))
        done
        if [[ $expect_value -eq 1 ]]; then
          opts=""
          prefer_value_choices=1
        elif [[ "$cur" != -* ]]; then
          arg_slot=-1
          arg_count=0
          has_rest=0
          if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
            arg_slot=$((arg_count - 1))
          elif [[ $positional_count -lt $arg_count ]]; then
            arg_slot=$positional_count
          fi
          case "$arg_slot" in
          esac
        fi
      fi
        ;;
      get)
      opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful -s --setting-path --help"
      prefer_value_choices=0
      if [[ "$cur" != -* ]]; then
        case "$prev" in
          --log-level)
            opts="debug info hint warn error"
            prefer_value_choices=1
            ;;
        esac
      fi
      if [[ $prefer_value_choices -eq 0 ]]; then
        positional_count=0
        expect_value=0
        for ((idx=3; idx<cword; idx++)); do
          token="${words[idx]}"
          if [[ $expect_value -eq 1 ]]; then
            expect_value=0
            continue
          fi
          if [[ "$token" == --* ]]; then
            if [[ "$token" == *=* ]]; then
              continue
            fi
            case "$token" in
              --log-level|--setting-path) expect_value=1 ;;
            esac
            continue
          fi
          if [[ "$token" == -* && "$token" != "-" ]]; then
            if [[ ${#token} -eq 2 ]]; then
              case "${token:1:1}" in
                s) expect_value=1 ;;
              esac
            fi
            continue
          fi
          positional_count=$((positional_count + 1))
        done
        if [[ $expect_value -eq 1 ]]; then
          opts=""
          prefer_value_choices=1
        elif [[ "$cur" != -* ]]; then
          arg_slot=-1
          arg_count=1
          has_rest=0
          if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
            arg_slot=$((arg_count - 1))
          elif [[ $positional_count -lt $arg_count ]]; then
            arg_slot=$positional_count
          fi
          case "$arg_slot" in
            0) opts="config.edition" ;;
          esac
        fi
      fi
        ;;
      set)
      opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful -s --setting-path --help"
      prefer_value_choices=0
      if [[ "$cur" != -* ]]; then
        case "$prev" in
          --log-level)
            opts="debug info hint warn error"
            prefer_value_choices=1
            ;;
        esac
      fi
      if [[ $prefer_value_choices -eq 0 ]]; then
        positional_count=0
        expect_value=0
        for ((idx=3; idx<cword; idx++)); do
          token="${words[idx]}"
          if [[ $expect_value -eq 1 ]]; then
            expect_value=0
            continue
          fi
          if [[ "$token" == --* ]]; then
            if [[ "$token" == *=* ]]; then
              continue
            fi
            case "$token" in
              --log-level|--setting-path) expect_value=1 ;;
            esac
            continue
          fi
          if [[ "$token" == -* && "$token" != "-" ]]; then
            if [[ ${#token} -eq 2 ]]; then
              case "${token:1:1}" in
                s) expect_value=1 ;;
              esac
            fi
            continue
          fi
          positional_count=$((positional_count + 1))
        done
        if [[ $expect_value -eq 1 ]]; then
          opts=""
          prefer_value_choices=1
        elif [[ "$cur" != -* ]]; then
          arg_slot=-1
          arg_count=2
          has_rest=0
          if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
            arg_slot=$((arg_count - 1))
          elif [[ $positional_count -lt $arg_count ]]; then
            arg_slot=$positional_count
          fi
          case "$arg_slot" in
            0) opts="config.edition" ;;
          esac
        fi
      fi
        ;;
      validate)
      opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful --help"
      prefer_value_choices=0
      if [[ "$cur" != -* ]]; then
        case "$prev" in
          --log-level)
            opts="debug info hint warn error"
            prefer_value_choices=1
            ;;
        esac
      fi
      if [[ $prefer_value_choices -eq 0 ]]; then
        positional_count=0
        expect_value=0
        for ((idx=3; idx<cword; idx++)); do
          token="${words[idx]}"
          if [[ $expect_value -eq 1 ]]; then
            expect_value=0
            continue
          fi
          if [[ "$token" == --* ]]; then
            if [[ "$token" == *=* ]]; then
              continue
            fi
            case "$token" in
              --log-level) expect_value=1 ;;
            esac
            continue
          fi
          if [[ "$token" == -* && "$token" != "-" ]]; then
            if [[ ${#token} -eq 2 ]]; then
            fi
            continue
          fi
          positional_count=$((positional_count + 1))
        done
        if [[ $expect_value -eq 1 ]]; then
          opts=""
          prefer_value_choices=1
        elif [[ "$cur" != -* ]]; then
          arg_slot=-1
          arg_count=1
          has_rest=0
          if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
            arg_slot=$((arg_count - 1))
          elif [[ $positional_count -lt $arg_count ]]; then
            arg_slot=$positional_count
          fi
          case "$arg_slot" in
          esac
        fi
      fi
        ;;
      *)
        opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful --help --version sync list status get set validate"
        prefer_value_choices=0
        if [[ "$cur" != -* ]]; then
          case "$prev" in
            --log-level)
              opts="debug info hint warn error"
              prefer_value_choices=1
              ;;
          esac
        fi
        if [[ $prefer_value_choices -eq 0 ]]; then
          positional_count=0
          expect_value=0
          for ((idx=2; idx<cword; idx++)); do
            token="${words[idx]}"
            if [[ $expect_value -eq 1 ]]; then
              expect_value=0
              continue
            fi
            if [[ "$token" == --* ]]; then
              if [[ "$token" == *=* ]]; then
                continue
              fi
              case "$token" in
                --log-level) expect_value=1 ;;
              esac
              continue
            fi
            if [[ "$token" == -* && "$token" != "-" ]]; then
              if [[ ${#token} -eq 2 ]]; then
              fi
              continue
            fi
            positional_count=$((positional_count + 1))
          done
          if [[ $expect_value -eq 1 ]]; then
            opts=""
            prefer_value_choices=1
          elif [[ "$cur" != -* ]]; then
            arg_slot=-1
            arg_count=0
            has_rest=0
            if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
              arg_slot=$((arg_count - 1))
            elif [[ $positional_count -lt $arg_count ]]; then
              arg_slot=$positional_count
            fi
            case "$arg_slot" in
            esac
          fi
        fi
        ;;
    esac
      ;;
    wsl)
    case "${words[2]}" in
      path)
      opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful --help"
      prefer_value_choices=0
      if [[ "$cur" != -* ]]; then
        case "$prev" in
          --log-level)
            opts="debug info hint warn error"
            prefer_value_choices=1
            ;;
        esac
      fi
      if [[ $prefer_value_choices -eq 0 ]]; then
        positional_count=0
        expect_value=0
        for ((idx=3; idx<cword; idx++)); do
          token="${words[idx]}"
          if [[ $expect_value -eq 1 ]]; then
            expect_value=0
            continue
          fi
          if [[ "$token" == --* ]]; then
            if [[ "$token" == *=* ]]; then
              continue
            fi
            case "$token" in
              --log-level) expect_value=1 ;;
            esac
            continue
          fi
          if [[ "$token" == -* && "$token" != "-" ]]; then
            if [[ ${#token} -eq 2 ]]; then
            fi
            continue
          fi
          positional_count=$((positional_count + 1))
        done
        if [[ $expect_value -eq 1 ]]; then
          opts=""
          prefer_value_choices=1
        elif [[ "$cur" != -* ]]; then
          arg_slot=-1
          arg_count=1
          has_rest=0
          if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
            arg_slot=$((arg_count - 1))
          elif [[ $positional_count -lt $arg_count ]]; then
            arg_slot=$positional_count
          fi
          case "$arg_slot" in
          esac
        fi
      fi
        ;;
      *)
        opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful --help --version path"
        prefer_value_choices=0
        if [[ "$cur" != -* ]]; then
          case "$prev" in
            --log-level)
              opts="debug info hint warn error"
              prefer_value_choices=1
              ;;
          esac
        fi
        if [[ $prefer_value_choices -eq 0 ]]; then
          positional_count=0
          expect_value=0
          for ((idx=2; idx<cword; idx++)); do
            token="${words[idx]}"
            if [[ $expect_value -eq 1 ]]; then
              expect_value=0
              continue
            fi
            if [[ "$token" == --* ]]; then
              if [[ "$token" == *=* ]]; then
                continue
              fi
              case "$token" in
                --log-level) expect_value=1 ;;
              esac
              continue
            fi
            if [[ "$token" == -* && "$token" != "-" ]]; then
              if [[ ${#token} -eq 2 ]]; then
              fi
              continue
            fi
            positional_count=$((positional_count + 1))
          done
          if [[ $expect_value -eq 1 ]]; then
            opts=""
            prefer_value_choices=1
          elif [[ "$cur" != -* ]]; then
            arg_slot=-1
            arg_count=0
            has_rest=0
            if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
              arg_slot=$((arg_count - 1))
            elif [[ $positional_count -lt $arg_count ]]; then
              arg_slot=$positional_count
            fi
            case "$arg_slot" in
            esac
          fi
        fi
        ;;
    esac
      ;;
    completion)
    opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful --bash --no-bash --fish --no-fish --pwsh --no-pwsh -w --write --help"
    prefer_value_choices=0
    if [[ "$cur" != -* ]]; then
      case "$prev" in
        --log-level)
          opts="debug info hint warn error"
          prefer_value_choices=1
          ;;
      esac
    fi
    if [[ $prefer_value_choices -eq 0 ]]; then
      positional_count=0
      expect_value=0
      for ((idx=2; idx<cword; idx++)); do
        token="${words[idx]}"
        if [[ $expect_value -eq 1 ]]; then
          expect_value=0
          continue
        fi
        if [[ "$token" == --* ]]; then
          if [[ "$token" == *=* ]]; then
            continue
          fi
          case "$token" in
            --log-level|--write) expect_value=1 ;;
          esac
          continue
        fi
        if [[ "$token" == -* && "$token" != "-" ]]; then
          if [[ ${#token} -eq 2 ]]; then
            case "${token:1:1}" in
              w) expect_value=1 ;;
            esac
          fi
          continue
        fi
        positional_count=$((positional_count + 1))
      done
      if [[ $expect_value -eq 1 ]]; then
        opts=""
        prefer_value_choices=1
      elif [[ "$cur" != -* ]]; then
        arg_slot=-1
        arg_count=0
        has_rest=0
        if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
          arg_slot=$((arg_count - 1))
        elif [[ $positional_count -lt $arg_count ]]; then
          arg_slot=$positional_count
        fi
        case "$arg_slot" in
        esac
      fi
    fi
      ;;
    *)
      opts="--color --no-color --log-level --silent --no-silent --log-date --no-log-date --log-colorful --no-log-colorful --help --version pm file copilot copy paste profile repo wsl completion"
      prefer_value_choices=0
      if [[ "$cur" != -* ]]; then
        case "$prev" in
          --log-level)
            opts="debug info hint warn error"
            prefer_value_choices=1
            ;;
        esac
      fi
      if [[ $prefer_value_choices -eq 0 ]]; then
        positional_count=0
        expect_value=0
        for ((idx=1; idx<cword; idx++)); do
          token="${words[idx]}"
          if [[ $expect_value -eq 1 ]]; then
            expect_value=0
            continue
          fi
          if [[ "$token" == --* ]]; then
            if [[ "$token" == *=* ]]; then
              continue
            fi
            case "$token" in
              --log-level) expect_value=1 ;;
            esac
            continue
          fi
          if [[ "$token" == -* && "$token" != "-" ]]; then
            if [[ ${#token} -eq 2 ]]; then
            fi
            continue
          fi
          positional_count=$((positional_count + 1))
        done
        if [[ $expect_value -eq 1 ]]; then
          opts=""
          prefer_value_choices=1
        elif [[ "$cur" != -* ]]; then
          arg_slot=-1
          arg_count=0
          has_rest=0
          if [[ $has_rest -eq 1 && $positional_count -ge $((arg_count - 1)) ]]; then
            arg_slot=$((arg_count - 1))
          elif [[ $positional_count -lt $arg_count ]]; then
            arg_slot=$positional_count
          fi
          case "$arg_slot" in
          esac
        fi
      fi
      ;;
  esac

  COMPREPLY=($(compgen -W "$opts" -- "$cur"))
}

complete -F _kit_completions kit
