return {
  -- trouble
  TroubleCount = { fg = "pink" },
  TroubleCode = { fg = "white" },
  TroubleWarning = { fg = "orange" },
  TroubleSignWarning = { link = "DiagnosticWarn" },
  TroubleTextWarning = { fg = "white" },
  TroublePreview = { fg = "red" },
  TroubleSource = { fg = "cyan" },
  TroubleSignHint = { link = "DiagnosticHint" },
  TroubleTextHint = { fg = "white" },
  TroubleHint = { fg = "orange" },
  TroubleSignOther = { link = "DiagnosticNormal" },
  TroubleSignInformation = { fg = "white" },
  TroubleTextInformation = { fg = "white" },
  TroubleInformation = { fg = "white" },
  TroubleError = { fg = "red" },
  TroubleTextError = { fg = "white" },
  TroubleSignError = { link = "DiagnosticError" },
  TroubleText = { fg = "white" },
  TroubleFile = { fg = "yellow" },
  TroubleFoldIcon = { link = "Folded" },
  TroubleNormal = { fg = "white" },
  TroubleLocation = { fg = "red" },
  TroubleIndent = { link = "Comment" },

  -- vim-notify
  NotifyERRORBorder = { fg = "red" },
  NotifyERRORIcon = { fg = "red" },
  NotifyERRORTitle = { fg = "red" },
  NotifyWARNBorder = { fg = "orange" },
  NotifyWARNIcon = { fg = "orange" },
  NotifyWARNTitle = { fg = "orange" },
  NotifyINFOBorder = { fg = "green" },
  NotifyINFOIcon = { fg = "green" },
  NotifyINFOTitle = { fg = "green" },
  NotifyDEBUGBorder = { fg = "grey" },
  NotifyDEBUGIcon = { fg = "grey" },
  NotifyDEBUGTitle = { fg = "grey" },
  NotifyTRACEBorder = { fg = "purple" },
  NotifyTRACEIcon = { fg = "purple" },
  NotifyTRACETitle = { fg = "purple" },
}
