gui:
  border: "rounded"
  nerdFontsVersion: "3"
  showFileTree: true
  showIcons: true

git:
  autoFetch: false
  paging:
    # cargo install git-delta
    colorArg: always
    pager: delta
    useConfig: false

os:
  editCommand: "nvim"
  editCommandTemplate: "{{editor}} {{filename}}"
