set   -g pane-border-format "\
#[default] \
\
#[fg=#{@GHC_SL_COLOR_FG_APP_SYM},       bg=#{@GHC_SL_COLOR_BG_APP_SYM}]#{@GHC_SL_SYM_APP} \
#[fg=#{@GHC_SL_COLOR_FG_APP_TEXT},      bg=#{@GHC_SL_COLOR_BG_APP_TEXT}]#{pane_title}\
\
#[default]  \
\
#[fg=#{@GHC_SL_COLOR_FG_PID_SYM},       bg=#{@GHC_SL_COLOR_BG_PID_SYM}]#{@GHC_SL_SYM_PID} \
#[fg=#{@GHC_SL_COLOR_FG_PID_TEXT},      bg=#{@GHC_SL_COLOR_BG_PID_TEXT}]#{pane_pid}:#(ps -o pid= -t '#{pane_tty}' | rg -o '\\d+' | tail -1)\
\
#[default] \
"


