set   -g pane-border-format "\
#[default] \
#[fg=#{?pane_active,#{@GHC_PSL_FG_SYM_ACTIVE},#{@GHC_PSL_FG_SYM}}, bg=#{?pane_active,#{@GHC_PSL_BG_SYM_ACTIVE},#{@GHC_PSL_BG_SYM}}]#{@GHC_SYM_APP} \
#[fg=#{?pane_active,#{@GHC_PSL_FG_TXT_ACTIVE},#{@GHC_PSL_FG_TXT}}, bg=#{?pane_active,#{@GHC_PSL_BG_TXT_ACTIVE},#{@GHC_PSL_BG_TXT}}]#{pane_title}\
#[default]  \
#[fg=#{?pane_active,#{@GHC_PSL_FG_SYM_ACTIVE},#{@GHC_PSL_FG_SYM}}, bg=#{?pane_active,#{@GHC_PSL_BG_SYM_ACTIVE},#{@GHC_PSL_BG_SYM}}]#{@GHC_SYM_PID} \
#[fg=#{?pane_active,#{@GHC_PSL_FG_TXT_ACTIVE},#{@GHC_PSL_FG_TXT}}, bg=#{?pane_active,#{@GHC_PSL_BG_TXT_ACTIVE},#{@GHC_PSL_BG_TXT}}]#{pane_pid}:#(ps -o pid= -t '#{pane_tty}' | rg -o '\\d+' | tail -1)\
#[default] \
"


