set -g status-left "\
#[default]\
#[fg=#{@GHC_SL_FG_SYM},           bg=#{@GHC_SL_BG_SYM}, bold]#{@GHC_SYM_OS} \
#[fg=#{@GHC_SL_FG_PRIMARY_TXT},   bg=#{@GHC_SL_BG_PRIMARY_TXT}, bold] #{@GHC_SYM_SESSION}\
#[fg=#{@GHC_SL_FG_PRIMARY_TXT},   bg=#{@GHC_SL_BG_PRIMARY_TXT}, bold] #{USER}\
#[fg=#{@GHC_SL_FG_PRIMARY_TXT},   bg=#{@GHC_SL_BG_PRIMARY_TXT}, bold]@\
#[fg=#{@GHC_SL_FG_PRIMARY_TXT},   bg=#{@GHC_SL_BG_PRIMARY_TXT}, bold]#{=21:host}\
#[fg=#{@GHC_SL_FG_PRIMARY_SEP},   bg=#{@GHC_SL_BG_PRIMARY_SEP}, bold]#{@GHC_SEP_RIGHT}\
#[default]\
#[fg=#{@GHC_SL_FG_SECONDARY_TXT}, bg=#{@GHC_SL_BG_SECONDARY_TXT}] #S\
#[fg=#{@GHC_SL_FG_SECONDARY_SEP}, bg=#{@GHC_SL_BG_SECONDARY_SEP}]#{@GHC_SEP_RIGHT} \
#[default] \
"

set -g status-right "\
#[default] \
#[fg=#{@GHC_SL_FG_TXT}, bg=#{@GHC_SL_BG_TXT}]%H:%M:%S\
#[default]\
"

