set -g status-left "\
#[default]\
#[fg=#{@GHC_SL_BG_PILL_HOST}]#{@GHC_SEP_ROUND_LEFT}#[fg=#{@GHC_SL_FG_PILL_ICON}#,bg=#{@GHC_SL_BG_PILL_HOST}]#{@GHC_SYM_OS} #[default]#[fg=#{@GHC_SL_FG_PILL_TXT}] #{=16:host} \
#[fg=#{@GHC_SL_BG_PILL_SESSION}]#{@GHC_SEP_ROUND_LEFT}#[fg=#{@GHC_SL_FG_PILL_ICON}#,bg=#{@GHC_SL_BG_PILL_SESSION}]#{@GHC_SYM_SESSION} #[default]#[fg=#{@GHC_SL_FG_PILL_TXT}] #S#[fg=#{@GHC_SL_FG_PILL_WINNR}]#{window_id} \
#{?window_zoomed_flag,#[fg=#{@GHC_SL_BG_PILL_ZOOM}]#{@GHC_SEP_ROUND_LEFT}#[fg=#{@GHC_SL_FG_PILL_ICON}#,bg=#{@GHC_SL_BG_PILL_ZOOM}]#{@GHC_SYM_WIN_ZOOM} #[default]#[fg=#{@GHC_SL_FG_PILL_TXT}] #{pane_index}/#{window_panes} ,}\
#{?client_prefix,#[fg=#{@GHC_SL_FG_PREFIX}]#{@GHC_SYM_PREFIX} ,}\
#[default]\
"

set -g status-right "\
#[default] \
#{?session_bell_flag,#[fg=#{@GHC_SL_BG_ALERT}]#{@GHC_SEP_ROUND_LEFT}#[fg=#{@GHC_SL_FG_ALERT}#,bg=#{@GHC_SL_BG_ALERT}]#{@GHC_SYM_ALERT}#[fg=#{@GHC_SL_BG_ALERT}#,bg=default]#{@GHC_SEP_ROUND_RIGHT} ,}\
#[fg=#{@GHC_SL_BG_PILL_DURATION}]#{@GHC_SEP_ROUND_LEFT}#[fg=#{@GHC_SL_FG_PILL_ICON}#,bg=#{@GHC_SL_BG_PILL_DURATION}]#{@GHC_SYM_DURATION} #[default]#[fg=#{@GHC_SL_FG_PILL_TXT}] #(~/.config/tmux/script/duration.sh #{session_created}) \
#[fg=#{@GHC_SL_BG_PILL_DATE}]#{@GHC_SEP_ROUND_LEFT}#[fg=#{@GHC_SL_FG_PILL_ICON}#,bg=#{@GHC_SL_BG_PILL_DATE}]#{@GHC_SYM_DATE} #[default]#[fg=#{@GHC_SL_FG_PILL_TXT}] %a, %d %b \
#[fg=#{@GHC_SL_BG_PILL_TIME}]#{@GHC_SEP_ROUND_LEFT}#[fg=#{@GHC_SL_FG_PILL_ICON}#,bg=#{@GHC_SL_BG_PILL_TIME}]#{@GHC_SYM_TIME} #[default]#[fg=#{@GHC_SL_FG_PILL_TXT}] %H:%M:%S \
#(bash ~/.config/tmux/script/session-status.sh #{q:session_name} '#{@GHC_SL_FG_SESSION_LIST_ACTIVE}' '#{@GHC_SL_BG_SESSION_LIST_ACTIVE}' 'fg=#{@GHC_SL_FG_SESSION_LIST_INACTIVE},bg=#{@GHC_SL_BG_SESSION_LIST_INACTIVE},dim' '#{@GHC_SL_BG_SESSION_LIST_SURFACE}' '#{@GHC_SEP_ROUND_LEFT}' '#{@GHC_SEP_ROUND_RIGHT}')\
#[default]\
"
