set -g status-left ""

set -g status-right "\
#[default]\
#[fg=#{@GHC_SL_FG_SYM}, bg=#{@GHC_SL_BG_SYM}]#{@GHC_SYM_TIME} \
#[fg=#{@GHC_SL_FG_TXT}, bg=#{@GHC_SL_BG_TXT}]%H:%M:%S\
#[default]  \
#[fg=#{@GHC_SL_FG_SYM}, bg=#{@GHC_SL_BG_SYM}]#{@GHC_SYM_SESSION} \
#[fg=#{@GHC_SL_FG_TXT}, bg=#{@GHC_SL_BG_TXT}]#S\
#[default]\
"

