set -g status-left "\
#[default]\
\
#[fg=#{@GHC_SL_COLOR_FG_SESSION_SYM},   bg=#{@GHC_SL_COLOR_BG_SESSION_SYM}]#{@GHC_SL_SYM_SESSION} \
#[fg=#{@GHC_SL_COLOR_FG_SESSION_TEXT},  bg=#{@GHC_SL_COLOR_BG_SESSION_TEXT}, bold]#S \
\
#[default] \
"

set -g status-right "\
#[default]\
\
#[fg=#{@GHC_SL_COLOR_FG_TIME_SYM},      bg=#{@GHC_SL_COLOR_BG_TIME_SYM}]#{@GHC_SL_SYM_TIME} \
#[fg=#{@GHC_SL_COLOR_FG_TIME_TEXT},     bg=#{@GHC_SL_COLOR_BG_TIME_TEXT}, bold]%H:%M:%S\
\
#[default]  \
\
#[fg=#{@GHC_SL_COLOR_FG_DATE_SYM},      bg=#{@GHC_SL_COLOR_BG_DATE_SYM}]#{@GHC_SL_SYM_DATE} \
#[fg=#{@GHC_SL_COLOR_FG_DATE_TEXT},     bg=#{@GHC_SL_COLOR_BG_DATE_TEXT}, bold]%a %b %d, %Y\
\
#[default] \
"

