set -g status-left " "

set -g status-right "\
#[default] \
#[fg=#{@GHC_SL_FG_TXT},         bg=#{@GHC_SL_BG_TXT}]%H:%M:%S\
#[default]  \
#[fg=#{@GHC_SL_FG_PRIMARY_SEP}, bg=#{@GHC_SL_BG_PRIMARY_SEP}, bold]#{@GHC_SEP_LEFT}\
#[fg=#{@GHC_SL_FG_PRIMARY_TXT}, bg=#{@GHC_SL_BG_PRIMARY_TXT}, bold]#S \
#[fg=#{@GHC_SL_FG_PRIMARY_TXT}, bg=#{@GHC_SL_BG_PRIMARY_TXT}, bold]#{@GHC_SYM_SESSION} \
#[fg=#{@GHC_SL_FG_SYM},         bg=#{@GHC_SL_BG_SYM}, bold] #{@GHC_SYM_OS} \
#[default]\
"

