---@class eve.types.collection.IDirtier : eve.types.collection.IObservable
---@field public is_dirty               fun(self: eve.types.collection.IDirtier): boolean
---@field public mark_clean             fun(self: eve.types.collection.IDirtier): nil
---@field public mark_dirty             fun(self: eve.types.collection.IDirtier): nil
