---@class t.eve.collection.IDirtier : t.eve.collection.IObservable
---@field public is_dirty               fun(self: t.eve.collection.IDirtier): boolean
---@field public mark_clean             fun(self: t.eve.collection.IDirtier): nil
---@field public mark_dirty             fun(self: t.eve.collection.IDirtier): nil
