---@class eve.t.collection.IDirtier : eve.t.collection.IObservable
---@field public is_dirty               fun(self: eve.t.collection.IDirtier): boolean
---@field public mark_clean             fun(self: eve.t.collection.IDirtier): nil
---@field public mark_dirty             fun(self: eve.t.collection.IDirtier): nil
