---@class t.eve.collection.ICircularQueue
---@field public capacity               fun(self: t.eve.collection.ICircularQueue): integer
---@field public size                   fun(self: t.eve.collection.ICircularQueue): integer
---@field public at                     fun(self: t.eve.collection.ICircularQueue, index: integer): t.eve.T|nil
---@field public back                   fun(self: t.eve.collection.ICircularQueue): t.eve.T|nil
---@field public clear                  fun(self: t.eve.collection.ICircularQueue): nil
---@field public collect                fun(self: t.eve.collection.ICircularQueue): t.eve.T[]
---@field public count                  fun(self: t.eve.collection.ICircularQueue, filter: t.eve.IFilter): integer
---@field public dequeue                fun(self: t.eve.collection.ICircularQueue): t.eve.T|nil
---@field public dequeue_back           fun(self: t.eve.collection.ICircularQueue): t.eve.T|nil
---@field public enqueue                fun(self: t.eve.collection.ICircularQueue, element: t.eve.T): nil
---@field public fork                   fun(self: t.eve.collection.ICircularQueue, filter: t.eve.IFilter): t.eve.collection.ICircularQueue
---@field public front                  fun(self: t.eve.collection.ICircularQueue): t.eve.T|nil
---@field public iterator               fun(self: t.eve.collection.ICircularQueue): fun(): t.eve.T|nil
---@field public iterator_reverse       fun(self: t.eve.collection.ICircularQueue): fun(): t.eve.T|nil
---@field public rearrange              fun(self: t.eve.collection.ICircularQueue, filter: t.eve.IFilter): fun(): t.eve.T|nil
---@field public reset                  fun(self: t.eve.collection.ICircularQueue, elements: t.eve.T[]): boolean): fun(): t.eve.T|nil
---@field public update                 fun(self: t.eve.collection.ICircularQueue, index: integer, value: t.eve.T): nil
