---@class eve.t.collection.ICircularStack
---@field public capacity               fun(self: eve.t.collection.ICircularStack): integer
---@field public size                   fun(self: eve.t.collection.ICircularStack): integer
---@field public at                     fun(self: eve.t.collection.ICircularStack, index: integer): eve.t.T|nil
---@field public clear                  fun(self: eve.t.collection.ICircularStack): nil
---@field public collect                fun(self: eve.t.collection.ICircularStack): eve.t.T[]
---@field public count                  fun(self: eve.t.collection.ICircularStack, filter: eve.t.IFilter): integer
---@field public fork                   fun(self: eve.t.collection.ICircularStack, filter: eve.t.IFilter): eve.t.collection.ICircularStack
---@field public iterator               fun(self: eve.t.collection.ICircularStack): fun(): eve.t.T|nil
---@field public iterator_reverse       fun(self: eve.t.collection.ICircularStack): fun(): eve.t.T|nil
---@field public pop                    fun(self: eve.t.collection.ICircularStack): eve.t.T|nil
---@field public push                   fun(self: eve.t.collection.ICircularStack, element: eve.t.T): nil
---@field public rearrange              fun(self: eve.t.collection.ICircularStack, filter: eve.t.IFilter): fun(): eve.t.T|nil
---@field public reset                  fun(self: eve.t.collection.ICircularStack, elements: eve.t.T[]): boolean): fun(): eve.t.T|nil
---@field public top                    fun(self: eve.t.collection.ICircularStack): eve.t.T|nil
---@field public update                 fun(self: eve.t.collection.ICircularStack, index: integer, value: eve.t.T): nil
