---@class t.eve.collection.theme.IPalette
---@field public bg0                    string
---@field public bg1                    string
---@field public bg2                    string
---@field public bg3                    string
---@field public bg4                    string
---
---@field public fg0                    string
---@field public fg1                    string
---@field public fg2                    string
---@field public fg3                    string
---@field public fg4                    string
---
---@field public red                    string
---@field public green                  string
---@field public yellow                 string
---@field public blue                   string
---@field public purple                 string
---@field public aqua                   string
---@field public orange                 string
---
---@field public neutral_red            string
---@field public neutral_green          string
---@field public neutral_yellow         string
---@field public neutral_blue           string
---@field public neutral_purple         string
---@field public neutral_aqua           string
---@field public neutral_orange         string
---
---@field public grey                   string
---@field public pink                   string

---@class t.eve.collection.theme.IScheme
---@field public theme                  t.eve.e.Theme
---@field public variant                t.eve.e.ThemeVariant
---@field public palette                t.eve.collection.theme.IPalette

---@class t.eve.collection.theme.IHlgroup : vim.api.keyset.highlight

---@class t.eve.collection.theme.IApplyParams
---@field public scheme                 t.eve.collection.theme.IScheme
---@field public nsnr                   integer

---@class t.eve.collection.theme.ICompileParams
---@field public scheme                 t.eve.collection.theme.IScheme
---@field public filepath               string
---@field public nsnr                   integer

---@class t.eve.collection.ITheme
---@field public apply                  fun(self: t.eve.collection.ITheme, params: t.eve.collection.theme.IApplyParams): nil
---@field public compile                fun(self: t.eve.collection.ITheme, params: t.eve.collection.theme.ICompileParams): nil
---@field public register               fun(self: t.eve.collection.ITheme, hlname: string, hlgroup: t.eve.collection.theme.IHlgroup): t.eve.collection.ITheme
---@field public registers              fun(self: t.eve.collection.ITheme, hlgroup_map: table<string, t.eve.collection.theme.IHlgroup | nil>): t.eve.collection.ITheme
