---@class eve.t.collection.theme.IPalette
---@field public bg0                    string
---@field public bg1                    string
---@field public bg2                    string
---@field public bg3                    string
---@field public bg4                    string
---
---@field public fg0                    string
---@field public fg1                    string
---@field public fg2                    string
---@field public fg3                    string
---@field public fg4                    string
---
---@field public red                    string
---@field public green                  string
---@field public yellow                 string
---@field public blue                   string
---@field public purple                 string
---@field public aqua                   string
---@field public orange                 string
---
---@field public neutral_red            string
---@field public neutral_green          string
---@field public neutral_yellow         string
---@field public neutral_blue           string
---@field public neutral_purple         string
---@field public neutral_aqua           string
---@field public neutral_orange         string
---
---@field public grey                   string
---@field public pink                   string

---@class eve.t.collection.theme.IScheme
---@field public theme                  eve.e.Theme
---@field public variant                eve.e.ThemeVariant
---@field public palette                eve.t.collection.theme.IPalette

---@class eve.t.collection.theme.IHlgroup : vim.api.keyset.highlight

---@class eve.t.collection.theme.IApplyParams
---@field public scheme                 eve.t.collection.theme.IScheme
---@field public nsnr                   integer

---@class eve.t.collection.theme.ICompileParams
---@field public scheme                 eve.t.collection.theme.IScheme
---@field public filepath               string
---@field public nsnr                   integer

---@class eve.t.collection.ITheme
---@field public apply                  fun(self: eve.t.collection.ITheme, params: eve.t.collection.theme.IApplyParams): nil
---@field public compile                fun(self: eve.t.collection.ITheme, params: eve.t.collection.theme.ICompileParams): nil
---@field public register               fun(self: eve.t.collection.ITheme, hlname: string, hlgroup: eve.t.collection.theme.IHlgroup): eve.t.collection.ITheme
---@field public registers              fun(self: eve.t.collection.ITheme, hlgroup_map: table<string, eve.t.collection.theme.IHlgroup | nil>): eve.t.collection.ITheme
