---@class eve.t.ux.IWidget
---@field public name                   string|nil
---@field public statusline_items       eve.t.ux.widget.IStatuslineItem[]|nil
---@field public status                 fun(self: eve.t.ux.IWidget): eve.e.WidgetStatus
---@field public close                  fun(self: eve.t.ux.IWidget): nil
---@field public hide                   fun(self: eve.t.ux.IWidget): nil
---@field public show                   fun(self: eve.t.ux.IWidget): nil
---@field public resize                 fun(self: eve.t.ux.IWidget): nil

---@class eve.t.ux.widget.IStatuslineItem
---@field public type                   eve.e.WidgetStatuslineItemType
---@field public state                  eve.lib.collection.IObservable
---@field public symbol                 string
---@field public callback_fn            string

---@class eve.t.ux.widget.IRawStatuslineItem
---@field public type                   eve.e.WidgetStatuslineItemType
---@field public desc                   string
---@field public state                  eve.lib.collection.IObservable
---@field public symbol                 string
---@field public callback               fun(): nil
