---@class eve.t.ux.IRawWidget
---@field public name                   string|nil
---@field public close                  fun(widget: eve.t.ux.IWidget): nil
---@field public focus                  fun(widget: eve.t.ux.IWidget): nil
---@field public hide                   fun(widget: eve.t.ux.IWidget): nil
---@field public isdisposed             fun(self: eve.t.ux.IWidget): boolean
---@field public isfocused              fun(self: eve.t.ux.IWidget): boolean
---@field public isvisible              fun(self: eve.t.ux.IWidget): boolean
---@field public resize                 fun(widget: eve.t.ux.IWidget): nil
---@field public statusline_items       eve.t.ux.widget.IStatuslineItem[]|nil

---@class eve.t.ux.IWidget
---@field public name                   string|nil
---@field public close                  fun(self: eve.t.ux.IWidget): nil
---@field public focus                  fun(self: eve.t.ux.IWidget): nil
---@field public hide                   fun(self: eve.t.ux.IWidget): nil
---@field public isdisposed             fun(self: eve.t.ux.IWidget): boolean
---@field public isfocused              fun(self: eve.t.ux.IWidget): boolean
---@field public isvisible              fun(self: eve.t.ux.IWidget): boolean
---@field public resize                 fun(self: eve.t.ux.IWidget): nil
---@field public statusline_items       eve.t.ux.widget.IStatuslineItem[]|nil

---@class eve.t.ux.widget.IStatuslineItem
---@field public type                   eve.e.WidgetStatuslineItemType
---@field public state                  eve.std.collection.IObservable
---@field public symbol                 string
---@field public callback_fn            string

---@class eve.t.ux.widget.IRawStatuslineItem
---@field public disabled               boolean|nil
---@field public type                   eve.e.WidgetStatuslineItemType
---@field public desc                   string
---@field public state                  eve.std.collection.IObservable
---@field public symbol                 string
---@field public callback               fun(): nil
