---@param context                       fml.t.ux.IThemeContext
---@return fml.ux.theme.integration.nvimbar.hlgroups
local function gen_hlgroup_map(context)
  local c = context.scheme.palette ---@type eve.lib.collection.theme.IPalette
  local t = context.transparency ---@type boolean
  local bg_sl = t and "none" or c.bg1 ---@type string
  local bg_buf_item_cur = t and "none" or c.bg2 ---@type string
  local bg_mode = t and "none" or c.bg2 ---@type string

  ---@class fml.ux.theme.integration.nvimbar.hlgroups : table<string, eve.lib.collection.theme.IHlgroup>
  local hlgroup_map = {
    f_sl_bg = { fg = bg_sl, bg = bg_sl },
    f_sl_buf_item = { fg = c.bg4, bg = bg_sl },
    f_sl_buf_item_cur = { fg = c.bg4, bg = bg_buf_item_cur },
    f_sl_buf_indicator = { fg = c.blue, bg = bg_buf_item_cur, bold = true },
    f_sl_buf_mod = { fg = c.red, bg = bg_sl },
    f_sl_buf_mod_cur = { fg = c.green, bg = bg_buf_item_cur },
    f_sl_buf_ommitter = { fg = c.blue, bg = bg_sl },
    f_sl_buf_ommitter_sep = { fg = c.bg4, bg = bg_sl },
    f_sl_buf_sep = { fg = c.bg4, bg = bg_sl },
    f_sl_buf_title = { fg = c.fg3, bg = bg_sl },
    f_sl_buf_title_cur = { fg = c.fg2, bg = bg_buf_item_cur, bold = true },
    f_sl_copilot_InProgress = { fg = c.aqua, bg = bg_sl },
    f_sl_copilot_Inactive = { fg = c.red, bg = bg_sl },
    f_sl_copilot_Normal = { fg = c.blue, bg = bg_sl },
    f_sl_copilot_Warning = { fg = c.yellow, bg = bg_sl },
    f_sl_cwd = { fg = c.bg0, bg = c.green, bold = true },
    f_sl_devmode = { fg = c.bg0, bg = c.yellow, bold = true },
    f_sl_diagnostics_error = { fg = c.red, bg = bg_sl },
    f_sl_diagnostics_hint = { fg = c.purple, bg = bg_sl },
    f_sl_diagnostics_info = { fg = c.green, bg = bg_sl },
    f_sl_diagnostics_warn = { fg = c.yellow, bg = bg_sl },
    f_sl_dirpath_sep = { fg = c.fg1, bg = bg_sl },
    f_sl_dirpath_text = { fg = c.blue, bg = bg_sl },
    f_sl_filename_text = { fg = c.fg1, bg = bg_sl },
    f_sl_flag = { fg = c.fg1, bg = t and "none" or c.bg3 },
    f_sl_flag_enabled = { fg = c.bg1, bg = c.blue },
    f_sl_flag_scope = { fg = c.bg1, bg = c.orange },
    f_sl_indicator = { fg = c.orange, bg = bg_sl },
    f_sl_lsp_icon = { fg = c.neutral_purple, bg = bg_sl },
    f_sl_lsp_icon_Array = { fg = c.blue, bg = bg_sl },
    f_sl_lsp_icon_Boolean = { fg = c.orange, bg = bg_sl },
    f_sl_lsp_icon_Class = { fg = c.neutral_aqua, bg = bg_sl },
    f_sl_lsp_icon_Color = { fg = c.fg1, bg = bg_sl },
    f_sl_lsp_icon_Constant = { fg = c.orange, bg = bg_sl },
    f_sl_lsp_icon_Constructor = { fg = c.blue, bg = bg_sl },
    f_sl_lsp_icon_Enum = { fg = c.blue, bg = bg_sl },
    f_sl_lsp_icon_EnumMember = { fg = c.neutral_purple, bg = bg_sl },
    f_sl_lsp_icon_Event = { fg = c.yellow, bg = bg_sl },
    f_sl_lsp_icon_Field = { fg = c.red, bg = bg_sl },
    f_sl_lsp_icon_File = { fg = c.fg1, bg = bg_sl },
    f_sl_lsp_icon_Folder = { fg = c.fg1, bg = bg_sl },
    f_sl_lsp_icon_Function = { fg = c.blue, bg = bg_sl },
    f_sl_lsp_icon_Identifier = { fg = c.red, bg = bg_sl },
    f_sl_lsp_icon_Interface = { fg = c.green, bg = bg_sl },
    f_sl_lsp_icon_Key = { fg = c.red, bg = bg_sl },
    f_sl_lsp_icon_Keyword = { fg = c.fg1, bg = bg_sl },
    f_sl_lsp_icon_Method = { fg = c.blue, bg = bg_sl },
    f_sl_lsp_icon_Module = { fg = c.yellow, bg = bg_sl },
    f_sl_lsp_icon_Namespace = { fg = c.neutral_aqua, bg = bg_sl },
    f_sl_lsp_icon_Null = { fg = c.aqua, bg = bg_sl },
    f_sl_lsp_icon_Number = { fg = c.orange, bg = bg_sl },
    f_sl_lsp_icon_Object = { fg = c.neutral_purple, bg = bg_sl },
    f_sl_lsp_icon_Operator = { fg = c.fg1, bg = bg_sl },
    f_sl_lsp_icon_Package = { fg = c.green, bg = bg_sl },
    f_sl_lsp_icon_Property = { fg = c.red, bg = bg_sl },
    f_sl_lsp_icon_Reference = { fg = c.fg1, bg = bg_sl },
    f_sl_lsp_icon_Snippet = { fg = c.red, bg = bg_sl },
    f_sl_lsp_icon_String = { fg = c.green, bg = bg_sl },
    f_sl_lsp_icon_Struct = { fg = c.neutral_purple, bg = bg_sl },
    f_sl_lsp_icon_Structure = { fg = c.neutral_purple, bg = bg_sl },
    f_sl_lsp_icon_Text = { fg = c.green, bg = bg_sl },
    f_sl_lsp_icon_Type = { fg = c.yellow, bg = bg_sl },
    f_sl_lsp_icon_TypeParameter = { fg = c.red, bg = bg_sl },
    f_sl_lsp_icon_Unit = { fg = c.neutral_purple, bg = bg_sl },
    f_sl_lsp_icon_Value = { fg = c.aqua, bg = bg_sl },
    f_sl_lsp_icon_Variable = { fg = c.neutral_purple, bg = bg_sl },
    f_sl_lsp_sep = { fg = c.fg3, bg = bg_sl },
    f_sl_lsp_text = { fg = c.fg3, bg = bg_sl },
    f_sl_noice_command = { fg = c.fg1, bg = bg_sl },
    f_sl_noice_mode = { fg = c.yellow, bg = bg_sl },
    f_sl_pos = { fg = c.bg1, bg = c.fg3 },
    f_sl_pos_bot = { fg = c.bg1, bg = c.green, bold = true },
    f_sl_pos_top = { fg = c.bg1, bg = c.green, bold = true },
    f_sl_readonly = { fg = c.orange, bg = bg_sl },
    f_sl_sidebar_blank = { fg = c.fg1, bg = bg_sl },
    f_sl_sidebar_indicator = { fg = c.orange, bg = bg_sl },
    f_sl_sidebar_split = { fg = c.fg4, bg = bg_sl },
    f_sl_sidebar_text = { fg = c.fg2, bg = bg_sl, bold = true },
    f_sl_tab_add = { fg = c.fg1, bg = c.bg3 },
    f_sl_tab_item = { fg = c.fg1, bg = bg_sl },
    f_sl_tab_item_cur = { fg = c.red, bg = bg_buf_item_cur },
    f_sl_tab_toggle = { fg = c.bg1, bg = c.green },
    f_sl_text = { fg = c.fg2, bg = bg_sl },
    f_sl_text_command = { fg = c.green, bg = bg_mode, bold = true },
    f_sl_text_confirm = { fg = c.neutral_aqua, bg = bg_mode, bold = true },
    f_sl_text_insert = { fg = c.neutral_purple, bg = bg_mode, bold = true },
    f_sl_text_normal = { fg = c.aqua, bg = bg_mode, bold = true },
    f_sl_text_nterminal = { fg = c.yellow, bg = bg_mode, bold = true },
    f_sl_text_replace = { fg = c.yellow, bg = bg_mode, bold = true },
    f_sl_text_select = { fg = c.blue, bg = bg_mode, bold = true },
    f_sl_text_terminal = { fg = c.green, bg = bg_mode, bold = true },
    f_sl_text_visual = { fg = c.aqua, bg = bg_mode },
    f_sl_username = { fg = c.bg1, bg = c.blue },
  }
  return hlgroup_map
end

return gen_hlgroup_map
