[package]
name = "yoz"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
globset = "0.4.18"
grep = "0.4.1"
ignore = "0.4.25"
libc = "0.2.177"
md-5 = "0.10.6"
mlua = { version = "0.11.4", default-features = false, features = ["luajit", "module"] }
regex = "1.12.2"
same-file = "1.0.6"
serde = { version = "1.0.228", features = ["derive"] }
time = { version = "0.3.44", features = ["macros", "formatting", "local-offset"] }
uuid = { version = "1.18.1", features = ["v4", "fast-rng"] }
