---@class fml.types.collection.IBatchHandler
---@field public  cleanup               fun(self: fml.types.collection.IBatchHandler): nil
---@field public  run                   fun(self: fml.types.collection.IBatchHandler, action: fun(): nil): nil
---@field public  summary               fun(self: fml.types.collection.IBatchHandler, title: string): nil): nil
