---@class fml.types.collection.IHistory
---@field public name                   string
---@field public comparator             fun(x: fml.types.T, y: fml.types.T): number
---@field public validate               fun(v: fml.types.T): boolean
---@field public back                   fun(self: fml.types.collection.IHistory, step ?:number): fml.types.T|nil
---@field public clear                  fun(self: fml.types.collection.IHistory): nil
---@field public empty                  fun(self: fml.types.collection.IHistory): boolean
---@field public forward                fun(self: fml.types.collection.IHistory, step ?:number): fml.types.T|nil
---@field public iterator               fun(self: fml.types.collection.IHistory): fun(): fml.types.T|nil
---@field public iterator_reverse       fun(self: fml.types.collection.IHistory): fun(): fml.types.T|nil
---@field public present                fun(self: fml.types.collection.IHistory): fml.types.T|nil
---@field public print                  fun(self: fml.types.collection.IHistory): nil
---@field public push                   fun(self: fml.types.collection.IHistory, element: fml.types.T|nil): nil
