---@class fml.types.collection.ICircularQueue

---@class fml.types.collection.ICircularQueue
---@field public capacity               fun(self: fml.types.collection.ICircularQueue): integer
---@field public size                   fun(self: fml.types.collection.ICircularQueue): integer
---@field public at                     fun(self: fml.types.collection.ICircularQueue, index: integer): fml.types.T|nil
---@field public back                   fun(self: fml.types.collection.ICircularQueue): fml.types.T|nil
---@field public clear                  fun(self: fml.types.collection.ICircularQueue): nil
---@field public collect                fun(self: fml.types.collection.ICircularQueue): fml.types.T[]
---@field public count                  fun(self: fml.types.collection.ICircularQueue, filter: fml.types.IFilter): integer
---@field public dequeue                fun(self: fml.types.collection.ICircularQueue): fml.types.T|nil
---@field public dequeue_back           fun(self: fml.types.collection.ICircularQueue): fml.types.T|nil
---@field public enqueue                fun(self: fml.types.collection.ICircularQueue, element: fml.types.T): nil
---@field public fork                   fun(self: fml.types.collection.ICircularQueue, filter: fml.types.IFilter): fml.types.collection.ICircularQueue
---@field public front                  fun(self: fml.types.collection.ICircularQueue): fml.types.T|nil
---@field public iterator               fun(self: fml.types.collection.ICircularQueue): fun(): fml.types.T|nil
---@field public iterator_reverse       fun(self: fml.types.collection.ICircularQueue): fun(): fml.types.T|nil
---@field public rearrange              fun(self: fml.types.collection.ICircularQueue, filter: fml.types.IFilter): fun(): fml.types.T|nil
---@field public reset                  fun(self: fml.types.collection.ICircularQueue, elements: fml.types.T[]): boolean): fun(): fml.types.T|nil
---@field public update                 fun(self: fml.types.collection.ICircularQueue, index: integer, value: fml.types.T): nil
