---@class dot.hlgroup.catppuccin.basic
local M = {}

---@param context                       dot.t.theme.IContext
---@return dot.hlgroup.common.modes_color_map
function M.gen_modes_color_map(context)
  local c = context.scheme.palette.unified ---@type dot.t.theme.UnifiedPalette
  local mc = {
    command = c.brightBlue,
    confirm = c.brightAqua,
    insert = c.brightPurple,
    normal = c.brightAqua,
    nterminal = c.yellow,
    replace = c.brightYellow,
    select = c.brightOrange,
    terminal = c.brightBlue,
    visual = c.brightOrange,
  }
  return mc
end

---@param context                       dot.t.theme.IContext
---@return table<string, dot.t.theme.IHlgroup>
function M.gen_hlgroup_map(context)
  local cs = dot.lib.color
  local t = context.transparency ---@type boolean
  local c = context.scheme.palette.catppuccin ---@type dot.t.theme.CatppuccinPalette
  local u = context.scheme.palette.unified ---@type dot.t.theme.UnifiedPalette

  local bg = t and c.none or c.base ---@type string

  ---@type table<string, dot.t.theme.IHlgroup>
  local hlgroup_map = {
    ---Completion
    ComplHint = { fg = c.overlay1, italic = true },
    ComplHintMore = { fg = c.peach, italic = true },

    Added = { fg = c.green },
    Bold = { bold = true },
    Boolean = { fg = c.peach },
    Builtin = { fg = c.peach },
    Changed = { fg = c.yellow },
    Character = { fg = c.teal },
    ColorColumn = { bg = c.surface0 },
    Comment = { fg = c.overlay2, italic = true },
    Conceal = { fg = c.overlay1 },
    Conditional = { fg = c.mauve },
    Constant = { fg = c.peach },
    CurSearch = { bg = c.red, fg = c.mantle },
    Cursor = { fg = c.base, bg = c.rosewater },
    CursorColumn = { bg = c.mantle },
    CursorLine = { bg = c.surface0 },
    CursorLineNr = { fg = c.lavender, bold = true },
    Debug = { fg = c.red },
    Define = { fg = c.pink },
    Delimiter = { fg = c.overlay2 },
    DevIconDefault = { fg = c.red },
    Diagnostic_ERROR = { fg = c.red },
    Diagnostic_HINT = { fg = c.mauve },
    Diagnostic_INFO = { fg = c.sky },
    Diagnostic_WARN = { fg = c.yellow },
    DiagnosticError = { fg = c.red },
    DiagnosticFloatingError = { fg = c.red },
    DiagnosticFloatingHint = { fg = c.mauve },
    DiagnosticFloatingInfo = { fg = c.sky },
    DiagnosticFloatingOk = { fg = c.green },
    DiagnosticFloatingWarn = { fg = c.yellow },
    DiagnosticHint = { fg = c.mauve },
    DiagnosticInfo = { fg = c.sky },
    DiagnosticOk = { fg = c.green },
    DiagnosticSignError = { fg = c.red },
    DiagnosticSignHint = { fg = c.mauve },
    DiagnosticSignInfo = { fg = c.sky },
    DiagnosticSignOk = { fg = c.green },
    DiagnosticSignWarn = { fg = c.yellow },
    DiagnosticUnderlineError = { undercurl = true, sp = c.red },
    DiagnosticUnderlineHint = { undercurl = true, sp = c.mauve },
    DiagnosticUnderlineInfo = { undercurl = true, sp = c.sky },
    DiagnosticUnderlineWarn = { undercurl = true, sp = c.yellow },
    DiagnosticVirtualTextError = { fg = c.red, bg = t and c.none or cs.mix(c.base, c.red, 12) },
    DiagnosticVirtualTextHint = { fg = c.mauve, bg = t and c.none or cs.mix(c.base, c.mauve, 12) },
    DiagnosticVirtualTextInfo = { fg = c.sky, bg = t and c.none or cs.mix(c.base, c.sky, 12) },
    DiagnosticVirtualTextWarn = { fg = c.yellow, bg = t and c.none or cs.mix(c.base, c.yellow, 12) },
    DiagnosticVirtualTextOk = { fg = c.green, bg = t and c.none or cs.mix(c.base, c.green, 12) },
    DiagnosticVirtualLinesError = { fg = c.red, bg = t and c.none or cs.mix(c.base, c.red, 12), italic = true },
    DiagnosticVirtualLinesHint = { fg = c.mauve, bg = t and c.none or cs.mix(c.base, c.mauve, 12), italic = true },
    DiagnosticVirtualLinesInfo = { fg = c.sky, bg = t and c.none or cs.mix(c.base, c.sky, 12), italic = true },
    DiagnosticVirtualLinesWarn = { fg = c.yellow, bg = t and c.none or cs.mix(c.base, c.yellow, 12), italic = true },
    DiagnosticVirtualLinesOk = { fg = c.green, bg = t and c.none or cs.mix(c.base, c.green, 12), italic = true },
    DiagnosticWarn = { fg = c.yellow },
    DiffAdd = { bg = cs.mix(bg, c.green, 18) },
    DiffAddLeft = { bg = cs.mix(bg, c.red, 30) },
    DiffAddRight = { bg = cs.mix(bg, c.green, 30) },
    DiffAdded = { fg = c.green },
    DiffChange = { bg = cs.mix(bg, c.blue, 7) },
    DiffChanged = { fg = c.blue },
    DiffDelLeft = { bg = cs.mix(bg, c.red, 30) },
    DiffDelRight = { bg = cs.mix(bg, c.red, 30) },
    DiffDelete = { bg = cs.mix(bg, c.red, 18) },
    DiffFile = { fg = c.blue },
    DiffIndexLine = { fg = c.teal },
    DiffLine = { fg = c.overlay0 },
    DiffModLeft = { bg = cs.mix(bg, c.red, 30) },
    DiffModRight = { bg = cs.mix(bg, c.green, 30) },
    DiffNewFile = { fg = c.peach },
    DiffOldFile = { fg = c.yellow },
    DiffRemoved = { fg = c.red },
    DiffText = { bg = cs.mix(bg, c.blue, 30) },
    DiffWordLeft = { bg = cs.mix(bg, c.red, 60) },
    DiffWordRight = { bg = cs.mix(bg, c.green, 60) },
    Directory = { fg = c.blue, bold = true },
    Done = { fg = c.peach, bold = true, italic = true },
    EndOfBuffer = { fg = c.surface1 },
    Error = { fg = c.red },
    ErrorMsg = { fg = c.red, bold = true, italic = true },
    Exception = { fg = c.mauve },
    Float = { fg = c.peach },
    FloatActiveBorder = { link = t and "ms_b_bg0" or "ms_b_none" },
    FloatActiveTitle = { link = "ms_b_bg0" },
    FloatBorder = { fg = c.blue, bg = c.mantle, blend = t and 50 or 0 },
    FloatNormal = { fg = c.text, bg = c.mantle },
    FloatTitle = { fg = c.subtext0, bg = c.mantle },
    FoldColumn = { fg = c.overlay0 },
    Folded = { fg = c.blue, bg = c.surface1 },
    Function = { fg = c.blue },
    healthError = { fg = c.red },
    healthSuccess = { fg = c.teal },
    healthWarning = { fg = c.yellow },
    iCursor = { fg = c.base, bg = c.rosewater },
    Identifier = { fg = c.flamingo },
    IncSearch = { bg = cs.change_hex_lightness(c.sky, -70), fg = c.mantle },
    Include = { fg = c.mauve },
    Italic = { italic = true },
    Keyword = { fg = c.mauve },
    Label = { fg = c.sapphire },
    lCursor = { fg = c.base, bg = c.rosewater },
    LineNr = { fg = c.surface1 },
    LspCodeLens = { fg = c.overlay0 },
    LspInlayHint = { fg = c.overlay0, bg = t and c.none or c.surface0 },
    LspReferenceRead = { bg = c.surface1 },
    LspReferenceText = { bg = c.surface1 },
    LspReferenceWrite = { bg = c.surface1 },
    LspSignatureActiveParameter = { bg = c.surface0, bold = true },
    Macro = { fg = c.mauve },
    MatchParen = { fg = c.peach, bg = c.surface1, bold = true },
    MatchWord = { fg = c.text, bg = c.surface1 },
    Member = { fg = c.lavender },
    Method = { fg = c.blue },
    ModeMsg = { fg = c.text, bold = true },
    MoreMsg = { fg = c.blue },
    MsgArea = { link = "Normal" },
    NonText = { fg = cs.mix(bg, c.overlay0, 45), italic = true },
    Normal = { fg = c.text, bg = u.bg0, blend = t and 50 or 0 },
    NormalFloat = { fg = c.text, bg = c.mantle },
    NormalNC = { fg = c.text, bg = u.bg1, blend = t and 50 or 0 },
    Number = { fg = c.peach },
    NvimInternalError = { fg = c.red },
    Operator = { fg = c.sky },
    Parameter = { fg = c.maroon },
    Pmenu = { fg = c.overlay2, bg = c.mantle },
    PmenuSbar = { bg = c.surface0 },
    PmenuSel = { bg = c.surface0, bold = true },
    PmenuThumb = { bg = c.overlay0 },
    PreCondit = { fg = c.pink },
    PreProc = { fg = c.pink },
    Question = { fg = c.blue },
    QuickFixLine = { bg = c.surface1, bold = true },
    Removed = { fg = c.red },
    RenamerBorder = { link = t and "ms_b_bg0" or "ms_b_none" },
    RenamerTitle = { link = t and "ms_b_bg0" or "ms_b_none" },
    Repeat = { fg = c.mauve },
    Search = { bg = cs.change_hex_lightness(c.sky, -30), fg = c.text },
    SignColumn = { fg = c.surface1 },
    Special = { fg = c.pink },
    SpecialChar = { fg = c.pink },
    SpecialKey = { link = "NonText" },
    SpellBad = { undercurl = true, sp = c.red },
    SpellCap = { undercurl = true, sp = c.yellow },
    SpellLocal = { undercurl = true, sp = c.blue },
    SpellRare = { undercurl = true, sp = c.green },
    Statement = { fg = c.mauve },
    StatusColumnMark = { link = "DiagnosticHint", default = true },
    StatusLine = { fg = c.text, bg = c.mantle, blend = t and 50 or 0 },
    StatusLineNC = { fg = c.surface1, bg = c.mantle, blend = t and 50 or 0 },
    StorageClass = { fg = c.yellow },
    String = { fg = c.green },
    Structure = { fg = c.yellow },
    Substitute = { bg = c.surface1, fg = c.pink },
    TabLine = { bg = c.crust, fg = c.overlay0 },
    TabLineFill = { bg = c.mantle, blend = t and 50 or 0 },
    TabLineSel = { link = "Normal" },
    Tag = { fg = c.lavender, bold = true },
    Title = { fg = c.blue, bold = true },
    Todo = { fg = c.base, bg = c.flamingo, bold = true },
    TooLong = { fg = c.red },
    Type = { fg = c.yellow },
    Typedef = { fg = c.yellow },
    Variable = { fg = c.text },
    UnderLined = { underline = true },
    vCursor = { fg = c.base, bg = c.rosewater },
    VertSplit = { fg = t and c.surface1 or c.crust },
    VertSplitActive = { fg = c.peach },
    Visual = { bg = c.surface1, bold = true },
    VisualNOS = { bg = c.surface1, bold = true },
    WarningMsg = { fg = c.yellow },
    Whitespace = { fg = c.surface1 },
    WildMenu = { bg = c.overlay0 },
    WinBar = { fg = c.rosewater, bg = u.bg0 },
    WinBarNC = { fg = c.rosewater, bg = u.bg1 },
    WinSeparator = { fg = t and c.surface1 or c.crust },
  }

  return hlgroup_map
end

return M
