import type { editor } from 'monaco-editor'

export const baseEditorOptions: editor.IStandaloneEditorConstructionOptions = {
  minimap: { enabled: false },
  fontSize: 14,
  lineNumbers: 'on',
  wordWrap: 'on' as const,
  automaticLayout: true,
  scrollBeyondLastLine: false,
  tabSize: 2,
  insertSpaces: true,
  folding: true,
  lineDecorationsWidth: 10,
  lineNumbersMinChars: 3,
  renderWhitespace: 'selection',
  selectOnLineNumbers: true,
  mouseWheelZoom: true,
  suggest: {
    showKeywords: true,
    showSnippets: true,
    showFunctions: true,
    showVariables: true,
    showClasses: true,
    showInterfaces: true,
    showModules: true,
    showProperties: true,
    showColors: true,
    showFiles: true,
    showReferences: true,
    showFolders: true,
    showTypeParameters: true,
    showIssues: true,
    showUsers: true,
    showValues: true,
  },
  quickSuggestions: {
    other: true,
    comments: false,
    strings: false,
  },
  suggestOnTriggerCharacters: true,
  acceptSuggestionOnCommitCharacter: true,
  acceptSuggestionOnEnter: 'on',
  wordBasedSuggestions: 'allDocuments' as const,
  parameterHints: {
    enabled: true,
  },
  hover: {
    enabled: true,
  },
  formatOnType: true,
  formatOnPaste: true,
}
