[package]
name = "rstd"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
md-5 = "0.10.6"
mlua = { version = "0.9", default-features = false, features = ["luajit", "module"] }
uuid = { version = "1.18.1", features = ["v4", "fast-rng"] }
serde = { version = "1.0.228", features = ["derive"] }
