local path = require("guanghechen.util.path")
print(path.is_absolute("/a/b/c"))
print(vim.inspect(path.split("/a/b/c")))
print(path.relative("/a/b/c", "/a/b/c/d/e.txt"))
print(path.relative("/a/b/c", "/a/b/c/e.txt"))
print(path.relative("/a/b/c", "/a/b/e.txt"))
print(path.relative("/a/b/c", "e.txt"))
print(path.relative("a/b/c", "/a/b/c/e.txt"))
print(path.normalize("a/b/c"))
print(path.normalize("a/b/..//c"))
print(path.normalize("/../a/../../../b/d/e/..//c"))
